"""
mask_collator_template.py
=========================
MaskCollator: DataLoader collate_fn that groups batch items by FPC (frames per
clip) and generates spatiotemporal masks per group.

References:
    - references/mask-collation.md
    - SKILL.md § MaskCollator, § Mask Collator Details

Done-when Gate 3 (Collator Grouping):
    MaskCollator correctly groups mixed-FPC batches.
    Each group has a consistent token sequence length.
    Returns [(collated_batch, masks_enc, masks_pred)] per FPC group.
"""

from __future__ import annotations

import random
from collections import defaultdict
from multiprocessing import Value
from typing import Any, Dict, List, Optional, Tuple

import torch
from torch import Tensor
from torch.utils.data.dataloader import default_collate

from mask_generator_template import MaskGenerator


# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------

# One element returned by the collator per FPC group.
# (collated_batch, list-of-enc-masks, list-of-pred-masks)
CollatorGroup = Tuple[Any, List[Tensor], List[Tensor]]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _group_by_fpc(
    batch: List[Any],
    fpc_key: str = "fpc",
) -> Dict[int, List[Any]]:
    """
    Partition batch items into groups keyed by frames-per-clip.

    Items are expected to be dicts with a `fpc_key` field.  If they do not,
    the collator falls back to treating all items as a single FPC group
    (single-FPC mode, FPC value taken from the first item).

    Preserves insertion order within each group.
    """
    groups: Dict[int, List[Any]] = defaultdict(list)
    for item in batch:
        if isinstance(item, dict) and fpc_key in item:
            fpc = int(item[fpc_key])
        elif isinstance(item, (list, tuple)) and len(item) >= 1:
            # Assume first element is the video tensor; derive FPC from T dim
            try:
                fpc = int(item[0].shape[-4])  # [..., T, H, W, C] or [C, T, H, W]
            except (AttributeError, IndexError):
                fpc = -1
        else:
            fpc = -1
        groups[fpc].append(item)
    return dict(groups)


# ---------------------------------------------------------------------------
# MaskCollator
# ---------------------------------------------------------------------------

class MaskCollator:
    """
    Custom DataLoader collate_fn for V-JEPA 2.

    Groups batch items by their FPC value, runs default_collate within each
    group, and attaches spatiotemporal masks generated by the appropriate
    MaskGenerator.

    Args:
        mask_generators:            Dict mapping FPC -> MaskGenerator, or a
                                    single MaskGenerator used for all FPCs.
        max_context_frames_ratio:   Passed to each MaskGenerator.
        max_keep:                   Passed to each MaskGenerator.
        fpc_key:                    Dict key used to read FPC from each item.

    Returns (per __call__):
        List[Tuple[collated_batch, List[Tensor], List[Tensor]]]
        One tuple per FPC group in the batch.
    """

    def __init__(
        self,
        mask_generators:            Any,   # MaskGenerator or Dict[int, MaskGenerator]
        max_context_frames_ratio:   float = 1.0,
        max_keep:                   Optional[int] = None,
        fpc_key:                    str = "fpc",
    ) -> None:
        # Normalise to dict form
        if isinstance(mask_generators, MaskGenerator):
            self._mg_dict:  Optional[Dict[int, MaskGenerator]] = None
            self._mg_default: MaskGenerator = mask_generators
        elif isinstance(mask_generators, dict):
            self._mg_dict    = mask_generators
            self._mg_default = None
        else:
            raise TypeError(
                "mask_generators must be a MaskGenerator or Dict[int, MaskGenerator], "
                f"got {type(mask_generators)}."
            )

        self.max_context_frames_ratio = max_context_frames_ratio
        self.max_keep                 = max_keep
        self.fpc_key                  = fpc_key

        # Shared integer counter for seed stepping across DataLoader workers.
        # Must be created BEFORE the DataLoader (before fork) so that the
        # underlying ctypes integer is shared across all workers.
        self._itr_counter: Value = Value("i", -1)

    # ------------------------------------------------------------------
    # Seed management
    # ------------------------------------------------------------------

    def _step(self) -> int:
        """
        Atomically increment and return the shared counter.

        This is safe to call from multiple DataLoader workers because
        multiprocessing.Value uses a reentrant lock.
        """
        with self._itr_counter.get_lock():
            self._itr_counter.value += 1
            return self._itr_counter.value

    def _get_mask_generator(self, fpc: int) -> MaskGenerator:
        """Return the MaskGenerator for the given FPC, or the default one."""
        if self._mg_dict is not None:
            if fpc in self._mg_dict:
                return self._mg_dict[fpc]
            # Fallback: use an arbitrary available generator
            return next(iter(self._mg_dict.values()))
        return self._mg_default

    # ------------------------------------------------------------------
    # Core collation logic
    # ------------------------------------------------------------------

    def __call__(self, batch: List[Any]) -> List[CollatorGroup]:
        """
        Collate a batch of dataset items into FPC groups with masks.

        Args:
            batch: List of items from the Dataset.__getitem__.

        Returns:
            List of (collated_batch, masks_enc, masks_pred) tuples, one per
            distinct FPC value found in the batch.
        """
        seed = self._step()

        groups = _group_by_fpc(batch, self.fpc_key)
        results: List[CollatorGroup] = []

        for fpc, items in groups.items():
            # Standard PyTorch collation within the FPC group
            collated = default_collate(items)
            B        = len(items)

            mg = self._get_mask_generator(fpc)
            masks_enc, masks_pred = mg(B, seed=seed)

            results.append((collated, masks_enc, masks_pred))

        return results

    def __repr__(self) -> str:
        if self._mg_dict is not None:
            mg_info = f"generators={list(self._mg_dict.keys())}"
        else:
            mg_info = f"generator={self._mg_default}"
        return (
            f"MaskCollator({mg_info}, "
            f"max_context_frames_ratio={self.max_context_frames_ratio}, "
            f"max_keep={self.max_keep})"
        )


# ---------------------------------------------------------------------------
# Convenience: build a MaskCollator from a VideoConfig + MaskConfig
# ---------------------------------------------------------------------------

def build_collator(
    grid_size:                Tuple[int, int, int] = (8, 14, 14),
    npred_small:              int = 8,
    npred_large:              int = 2,
    spatial_scale_small:      Tuple[float, float] = (0.15, 0.15),
    spatial_scale_large:      Tuple[float, float] = (0.70, 0.70),
    temporal_scale:           Tuple[float, float] = (1.0, 1.0),
    aspect_ratio:             Tuple[float, float] = (0.75, 1.5),
    max_context_frames_ratio: float = 1.0,
    max_keep:                 Optional[int] = None,
) -> Tuple["MaskCollator", MaskGenerator, MaskGenerator]:
    """
    Build a MaskCollator pre-configured with small + large generators.

    Returns:
        (collator, small_generator, large_generator)
    """
    mg_small = MaskGenerator(
        spatial_scale=spatial_scale_small,
        temporal_scale=temporal_scale,
        aspect_ratio=aspect_ratio,
        npred=npred_small,
        grid_size=grid_size,
        max_context_frames_ratio=max_context_frames_ratio,
        max_keep=max_keep,
    )
    mg_large = MaskGenerator(
        spatial_scale=spatial_scale_large,
        temporal_scale=temporal_scale,
        aspect_ratio=aspect_ratio,
        npred=npred_large,
        grid_size=grid_size,
        max_context_frames_ratio=max_context_frames_ratio,
        max_keep=max_keep,
    )
    # Use small generator as default for single-FPC batches
    collator = MaskCollator(mg_small, max_context_frames_ratio, max_keep)
    return collator, mg_small, mg_large


# ---------------------------------------------------------------------------
# Self-tests  (python mask_collator_template.py)
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys

    PASSED = 0
    FAILED = 0

    def check(name: str, condition: bool, msg: str = "") -> None:
        global PASSED, FAILED
        if condition:
            print(f"  PASS  {name}")
            PASSED += 1
        else:
            print(f"  FAIL  {name}  {msg}")
            FAILED += 1

    # Helper: make a fake batch item as a dict
    def make_item(fpc: int, T: int = None, H: int = 14, W: int = 14,
                  D: int = 1024) -> Dict[str, Any]:
        T = T or fpc // 2  # tubelet=2 convention
        return {
            "fpc":    fpc,
            "frames": torch.randn(fpc, H * 16, W * 16, 3),  # raw pixels
            "label":  torch.tensor(0),
        }

    GRID = (8, 14, 14)
    N    = 8 * 14 * 14  # 1568

    mg = MaskGenerator(
        spatial_scale=(0.15, 0.15),
        temporal_scale=(1.0, 1.0),
        aspect_ratio=(0.75, 1.5),
        npred=4,
        grid_size=GRID,
    )
    collator = MaskCollator(mg)

    # -------------------------------------------------------------------
    # Single-FPC batch
    # -------------------------------------------------------------------
    print("=" * 60)
    print("MaskCollator -- single-FPC batch")
    print("=" * 60)

    batch_single = [make_item(16) for _ in range(4)]
    result = collator(batch_single)

    check("Single-FPC: returns a list", isinstance(result, list))
    check("Single-FPC: exactly 1 group", len(result) == 1,
          f"got {len(result)} groups")

    collated_s, enc_s, pred_s = result[0]
    check("Single-FPC: collated batch is a dict", isinstance(collated_s, dict))
    check("Single-FPC: masks_enc is a list", isinstance(enc_s, list))
    check("Single-FPC: masks_pred is a list", isinstance(pred_s, list))
    check("Single-FPC: len(masks_enc) == 4", len(enc_s) == 4,
          f"got {len(enc_s)}")
    check("Single-FPC: mask shape == [N]",
          enc_s[0].shape == (N,), f"got {enc_s[0].shape}")
    check("Single-FPC: mask dtype bool",
          enc_s[0].dtype == torch.bool)

    # Coverage
    for i in range(4):
        check(f"Single-FPC[{i}] no gaps",
              (enc_s[i] | pred_s[i]).all().item())
        check(f"Single-FPC[{i}] no overlaps",
              not (enc_s[i] & pred_s[i]).any().item())

    # -------------------------------------------------------------------
    # Multi-FPC batch
    # -------------------------------------------------------------------
    print()
    print("=" * 60)
    print("MaskCollator -- multi-FPC batch")
    print("=" * 60)

    # 2 items FPC=16, 2 items FPC=8 -> 2 groups
    mg16 = MaskGenerator(
        spatial_scale=(0.15, 0.15), temporal_scale=(1.0, 1.0),
        aspect_ratio=(0.75, 1.5), npred=4, grid_size=(8, 14, 14),
    )
    mg8 = MaskGenerator(
        spatial_scale=(0.15, 0.15), temporal_scale=(1.0, 1.0),
        aspect_ratio=(0.75, 1.5), npred=4, grid_size=(4, 14, 14),
    )
    mg_dict = {16: mg16, 8: mg8}
    collator_multi = MaskCollator(mg_dict)

    batch_multi = [make_item(16), make_item(16), make_item(8), make_item(8)]
    result_multi = collator_multi(batch_multi)

    check("Multi-FPC: returns 2 groups",
          len(result_multi) == 2,
          f"got {len(result_multi)} groups")

    # Map groups by their mask length
    groups_by_n: Dict[int, Any] = {}
    for col, enc, pred in result_multi:
        n = enc[0].numel()
        groups_by_n[n] = (col, enc, pred)

    N16 = 8 * 14 * 14   # 1568
    N8  = 4 * 14 * 14   # 784

    check("Multi-FPC: group FPC=16 has N=1568 tokens",
          N16 in groups_by_n, f"groups found: {list(groups_by_n.keys())}")
    check("Multi-FPC: group FPC=8 has N=784 tokens",
          N8 in groups_by_n, f"groups found: {list(groups_by_n.keys())}")

    if N16 in groups_by_n:
        _, enc16, pred16 = groups_by_n[N16]
        check("Multi-FPC: FPC=16 group has 2 items", len(enc16) == 2,
              f"got {len(enc16)}")
        for i in range(len(enc16)):
            check(f"Multi-FPC FPC=16[{i}] no gaps",
                  (enc16[i] | pred16[i]).all().item())
            check(f"Multi-FPC FPC=16[{i}] no overlaps",
                  not (enc16[i] & pred16[i]).any().item())

    if N8 in groups_by_n:
        _, enc8, pred8 = groups_by_n[N8]
        check("Multi-FPC: FPC=8 group has 2 items", len(enc8) == 2,
              f"got {len(enc8)}")

    # -------------------------------------------------------------------
    # Seed determinism (counter increments)
    # -------------------------------------------------------------------
    print()
    print("=" * 60)
    print("MaskCollator -- counter / seed determinism")
    print("=" * 60)

    coll_det = MaskCollator(mg)
    # Reset counter manually for test
    with coll_det._itr_counter.get_lock():
        coll_det._itr_counter.value = -1

    r1 = coll_det([make_item(16) for _ in range(2)])
    r2 = coll_det([make_item(16) for _ in range(2)])

    # Seeds 0 and 1 should produce different masks
    _, enc1_list, _ = r1[0]
    _, enc2_list, _ = r2[0]
    seeds_differ = any(not torch.equal(e1, e2)
                       for e1, e2 in zip(enc1_list, enc2_list))
    check("Sequential calls use different seeds -> different masks",
          seeds_differ)

    # Same call with same seed should be identical
    coll_rep = MaskCollator(mg)
    with coll_rep._itr_counter.get_lock():
        coll_rep._itr_counter.value = 41  # next step = 42

    r_a = coll_rep([make_item(16) for _ in range(2)])

    with coll_rep._itr_counter.get_lock():
        coll_rep._itr_counter.value = 41  # reset to 41 again

    r_b = coll_rep([make_item(16) for _ in range(2)])

    _, enc_a_list, _ = r_a[0]
    _, enc_b_list, _ = r_b[0]
    same = all(torch.equal(a, b) for a, b in zip(enc_a_list, enc_b_list))
    check("Same counter value -> identical masks", same)

    print()
    print("=" * 60)
    print(f"Results: {PASSED} passed, {FAILED} failed")
    print("=" * 60)

    sys.exit(0 if FAILED == 0 else 1)
