#!/usr/bin/env python3
"""
gen_task2vec_tests.py -- Generator for tests/test_task2vec.py

Generates ~72 pytest test cases organised across 8 test classes for the
Task2Vec Task Embeddings + Curriculum/Clustering skill of the brain-inspired
AI system.

Usage:
    python scripts/gen_task2vec_tests.py
    python scripts/gen_task2vec_tests.py --output path/to/test_task2vec.py
    python scripts/gen_task2vec_tests.py --dry-run        # print to stdout, no write
    python scripts/gen_task2vec_tests.py --verbose         # extra diagnostics
    python scripts/gen_task2vec_tests.py --run             # generate and run via pytest

Test classes generated:
    1.  TestTask2VecExtractor   (~15 tests)
    2.  TestEmbeddingRegistry   (~12 tests)
    3.  TestClustering          (~10 tests)
    4.  TestStability           (~5 tests)
    5.  TestCurriculum          (~12 tests)
    6.  TestConfig              (~8 tests)
    7.  TestWhitening           (~4 tests)
    8.  TestIntegration         (~6 tests)

Total: ~72 test methods.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import textwrap
from pathlib import Path
from typing import List


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _dedent(text: str) -> str:
    """Dedent a triple-quoted block to module level."""
    return textwrap.dedent(text)


def _section_banner(title: str) -> str:
    """Build a visually distinct section separator comment block."""
    rule = "=" * 75
    return f"\n\n# {rule}\n# {title}\n# {rule}\n\n"


# ---------------------------------------------------------------------------
# Section builders -- each returns a string that becomes part of the
# generated test file.  They are assembled by build_test_file().
# ---------------------------------------------------------------------------

def _build_header() -> str:
    return _dedent("""\
        # ===========================================================================
        # test_task2vec.py
        #
        # Auto-generated by scripts/gen_task2vec_tests.py -- DO NOT EDIT BY HAND.
        # Regenerate with:
        #     python scripts/gen_task2vec_tests.py
        #
        # ~72 test methods across 8 test classes covering the Task2Vec Task
        # Embeddings + Curriculum/Clustering skill (brain_ai/meta/): extractor,
        # embedding registry, clustering, stability, curriculum, config,
        # whitening, and integration.
        # ===========================================================================
        """)


def _build_imports() -> str:
    return _dedent("""\
        from __future__ import annotations

        import copy
        import hashlib
        import json
        import math
        import os
        import tempfile
        import warnings
        from pathlib import Path
        from typing import Any, Dict, List, Optional, Tuple

        import numpy as np
        import pytest

        # ---------------------------------------------------------------------------
        # Optional-dependency availability flags
        # ---------------------------------------------------------------------------

        try:
            import torch
            import torch.nn as nn
            import torch.nn.functional as F
            HAS_TORCH = True
        except ImportError:
            HAS_TORCH = False

        try:
            from sklearn.cluster import KMeans, AgglomerativeClustering
            from sklearn.metrics import (
                adjusted_rand_score,
                normalized_mutual_info_score,
                silhouette_score,
            )
            HAS_SKLEARN = True
        except ImportError:
            HAS_SKLEARN = False

        try:
            import hdbscan  # noqa: F401
            HAS_HDBSCAN = True
        except ImportError:
            HAS_HDBSCAN = False

        try:
            from scipy.stats import kendalltau
            HAS_SCIPY = True
        except ImportError:
            HAS_SCIPY = False

        # ---------------------------------------------------------------------------
        # Skip markers
        # ---------------------------------------------------------------------------

        requires_torch = pytest.mark.skipif(
            not HAS_TORCH, reason="torch not installed"
        )
        requires_cuda = pytest.mark.skipif(
            not HAS_TORCH or not torch.cuda.is_available(),
            reason="CUDA not available",
        )
        requires_sklearn = pytest.mark.skipif(
            not HAS_SKLEARN, reason="scikit-learn not installed"
        )
        requires_hdbscan = pytest.mark.skipif(
            not HAS_HDBSCAN, reason="hdbscan not installed"
        )
        requires_scipy = pytest.mark.skipif(
            not HAS_SCIPY, reason="scipy not installed"
        )

        # ---------------------------------------------------------------------------
        # Target-module imports (graceful -- tests skip if modules missing)
        # ---------------------------------------------------------------------------

        try:
            from brain_ai.meta.task2vec import (
                Task2VecExtractor,
                TaskEmbedding,
                compute_task_id,
            )
            HAS_EXTRACTOR = True
        except Exception:
            HAS_EXTRACTOR = False

        try:
            from brain_ai.meta.embedding_registry import (
                TaskEmbeddingRegistry,
                RegistryEntry,
            )
            HAS_REGISTRY = True
        except Exception:
            HAS_REGISTRY = False

        try:
            from brain_ai.meta.task_clustering import (
                cluster_embeddings,
                cosine_distance_matrix,
                ClusterResult,
            )
            HAS_CLUSTERING = True
        except Exception:
            HAS_CLUSTERING = False

        try:
            from brain_ai.meta.curriculum import (
                get_curriculum_order,
                build_meta_batch,
                schedule_linear,
                schedule_cosine,
                schedule_step,
            )
            HAS_CURRICULUM = True
        except Exception:
            HAS_CURRICULUM = False

        try:
            from brain_ai.config import (
                Task2VecConfig,
                ClusterConfig,
                CurriculumConfig,
            )
            HAS_CONFIG = True
        except Exception:
            HAS_CONFIG = False

        try:
            from brain_ai.config import Task2VecFullConfig
            HAS_FULL_CONFIG = True
        except Exception:
            HAS_FULL_CONFIG = False

        try:
            from brain_ai.meta.task2vec import EmbeddingWhitener
            HAS_WHITENER = True
        except Exception:
            try:
                from brain_ai.meta.embedding_registry import EmbeddingWhitener
                HAS_WHITENER = True
            except Exception:
                HAS_WHITENER = False

        # ---------------------------------------------------------------------------
        # Seed for reproducibility
        # ---------------------------------------------------------------------------
        np.random.seed(42)
        if HAS_TORCH:
            torch.manual_seed(42)

        """)


def _build_helpers() -> str:
    return _dedent("""\
        # ===========================================================================
        # Assertion helpers
        # ===========================================================================

        def assert_l2_normalized(vec: np.ndarray, tol: float = 1e-5) -> None:
            \"\"\"Assert that *vec* has unit L2 norm.\"\"\"
            norm = float(np.linalg.norm(vec))
            assert abs(norm - 1.0) < tol, (
                f"L2 norm {norm:.8f} not within {tol} of 1.0"
            )


        def cosine_sim(a: np.ndarray, b: np.ndarray) -> float:
            \"\"\"Cosine similarity between two flat vectors.\"\"\"
            na = np.linalg.norm(a)
            nb = np.linalg.norm(b)
            if na < 1e-12 or nb < 1e-12:
                return 0.0
            return float(np.dot(a, b) / (na * nb))


        def make_random_embedding(dim: int, rng: np.random.RandomState) -> np.ndarray:
            \"\"\"Return a random L2-normalised vector of length *dim*.\"\"\"
            v = rng.randn(dim).astype(np.float32)
            v /= np.linalg.norm(v) + 1e-12
            return v


        def make_planted_clusters(
            n_tasks: int,
            n_clusters: int,
            dim: int,
            separation: float = 3.0,
            seed: int = 42,
        ) -> Tuple[np.ndarray, np.ndarray, List[str]]:
            \"\"\"Create *n_tasks* L2-normalised embeddings from *n_clusters* planted
            Gaussian clusters.

            Returns:
                embeddings:  (n_tasks, dim) float32
                labels:      (n_tasks,) int
                task_ids:    list of deterministic id strings
            \"\"\"
            rng = np.random.RandomState(seed)
            tasks_per_cluster = n_tasks // n_clusters
            remainder = n_tasks - tasks_per_cluster * n_clusters

            centers = rng.randn(n_clusters, dim).astype(np.float32) * separation

            embeddings_list: List[np.ndarray] = []
            labels_list: List[int] = []

            for c in range(n_clusters):
                count = tasks_per_cluster + (1 if c < remainder else 0)
                noise = rng.randn(count, dim).astype(np.float32) * 0.3
                cluster_points = centers[c] + noise
                embeddings_list.append(cluster_points)
                labels_list.extend([c] * count)

            embeddings = np.concatenate(embeddings_list, axis=0)
            # L2 normalise rows
            norms = np.linalg.norm(embeddings, axis=1, keepdims=True)
            embeddings = embeddings / np.maximum(norms, 1e-12)

            labels = np.array(labels_list, dtype=np.int64)
            task_ids = [f"task_{i:04d}" for i in range(n_tasks)]

            return embeddings, labels, task_ids

        """)


def _build_fixtures() -> str:
    return _dedent("""\
        # ===========================================================================
        # Shared fixtures
        # ===========================================================================

        EMBED_DIM = 64  # small dimension for fast CPU tests
        N_TASKS = 50
        N_CLUSTERS = 5


        @pytest.fixture(scope="session")
        def minimal_config():
            \"\"\"Task2VecFullConfig.minimal() if available, else a dict stand-in.\"\"\"
            if HAS_FULL_CONFIG:
                return Task2VecFullConfig.minimal()
            if HAS_CONFIG:
                return {
                    "task2vec": Task2VecConfig(
                        probe_model="conv4",
                        embedding_dim=EMBED_DIM,
                    ),
                    "cluster": ClusterConfig(n_clusters=N_CLUSTERS),
                    "curriculum": CurriculumConfig(),
                }
            return {"embedding_dim": EMBED_DIM}


        @pytest.fixture()
        def synthetic_episode():
            \"\"\"A lightweight synthetic episode dict for extractor tests.

            Shape conventions: x_support (5, 3, 32, 32), y_support (5,).
            \"\"\"
            if not HAS_TORCH:
                pytest.skip("torch not available")
            torch.manual_seed(42)
            return {
                "x_support": torch.randn(5, 3, 32, 32),
                "y_support": torch.tensor([0, 1, 2, 3, 4]),
                "class_ids": [0, 1, 2, 3, 4],
                "dataset_name": "synthetic",
                "split": "train",
                "support_indices": list(range(5)),
                "transforms_signature": "none",
            }


        @pytest.fixture()
        def second_episode():
            \"\"\"A second synthetic episode with different seed / classes.\"\"\"
            if not HAS_TORCH:
                pytest.skip("torch not available")
            torch.manual_seed(99)
            return {
                "x_support": torch.randn(5, 3, 32, 32),
                "y_support": torch.tensor([5, 6, 7, 8, 9]),
                "class_ids": [5, 6, 7, 8, 9],
                "dataset_name": "synthetic",
                "split": "train",
                "support_indices": list(range(5, 10)),
                "transforms_signature": "none",
            }


        @pytest.fixture()
        def embedding_matrix():
            \"\"\"(N_TASKS, EMBED_DIM) float32 with planted clusters.\"\"\"
            emb, _, _ = make_planted_clusters(N_TASKS, N_CLUSTERS, EMBED_DIM, seed=42)
            return emb


        @pytest.fixture()
        def cluster_labels():
            \"\"\"Ground-truth labels from the planted clusters.\"\"\"
            _, labels, _ = make_planted_clusters(N_TASKS, N_CLUSTERS, EMBED_DIM, seed=42)
            return labels


        @pytest.fixture()
        def task_ids():
            \"\"\"Deterministic task-id list matching *embedding_matrix*.\"\"\"
            _, _, ids = make_planted_clusters(N_TASKS, N_CLUSTERS, EMBED_DIM, seed=42)
            return ids


        @pytest.fixture()
        def populated_registry():
            \"\"\"A TaskEmbeddingRegistry with 20 synthetic entries: 10 dataset A,
            10 dataset B.  Falls back to a dict-based stand-in if the real
            module is not importable.
            \"\"\"
            if not HAS_REGISTRY:
                pytest.skip("brain_ai.meta.embedding_registry not available")

            rng = np.random.RandomState(42)
            reg = TaskEmbeddingRegistry(embedding_dim=EMBED_DIM)
            for i in range(20):
                emb = make_random_embedding(EMBED_DIM, rng)
                dataset = "A" if i < 10 else "B"
                reg.update(
                    task_id=f"pop_{i:03d}",
                    embedding=emb,
                    dataset=dataset,
                    split="train",
                    n_way=5,
                    k_shot=1,
                    probe_signature="conv4_lb_v1",
                )
            return reg


        @pytest.fixture()
        def tmp_registry_dir(tmp_path):
            \"\"\"Temporary directory for save/load tests.\"\"\"
            return tmp_path / "registry_test"

        """)


# ---------------------------------------------------------------------------
# Test-class builders
# ---------------------------------------------------------------------------

def _build_test_extractor() -> str:
    return (
        _section_banner("TestTask2VecExtractor (~15 tests)")
        + _dedent("""\
        @pytest.mark.skipif(not HAS_EXTRACTOR, reason="Task2VecExtractor not available")
        class TestTask2VecExtractor:
            \"\"\"Tests for brain_ai.meta.task2vec.Task2VecExtractor.\"\"\"

            # -- helpers ---------------------------------------------------------
            def _make_extractor(self, config=None):
                if HAS_FULL_CONFIG:
                    cfg = Task2VecFullConfig.minimal()
                    cfg_t2v = cfg.task2vec
                elif HAS_CONFIG:
                    cfg_t2v = Task2VecConfig(
                        probe_model="conv4",
                        embedding_dim=EMBED_DIM,
                        layer_subset="last_block",
                        aggregation="per_channel",
                        normalize="log1p_l2",
                    )
                else:
                    pytest.skip("Config classes not available")
                    return None
                return Task2VecExtractor(cfg_t2v)

            # ---- tests ---------------------------------------------------------

            def test_embedding_shape(self, synthetic_episode):
                \"\"\"Output embedding has shape (E,) matching config dim.\"\"\"
                ext = self._make_extractor()
                result = ext.extract(synthetic_episode, seed=42)
                emb = result.embedding
                if isinstance(emb, torch.Tensor):
                    emb = emb.detach().cpu().numpy()
                assert emb.shape == (EMBED_DIM,), (
                    f"Expected ({EMBED_DIM},), got {emb.shape}"
                )

            def test_embedding_normalized(self, synthetic_episode):
                \"\"\"L2 norm of the embedding is approximately 1.0.\"\"\"
                ext = self._make_extractor()
                result = ext.extract(synthetic_episode, seed=42)
                emb = result.embedding
                if isinstance(emb, torch.Tensor):
                    emb = emb.detach().cpu().numpy()
                assert_l2_normalized(emb, tol=1e-5)

            def test_determinism(self, synthetic_episode):
                \"\"\"Same input + same seed -> identical embedding within 1e-7.\"\"\"
                ext = self._make_extractor()
                r1 = ext.extract(synthetic_episode, seed=42)
                r2 = ext.extract(synthetic_episode, seed=42)
                e1 = r1.embedding if isinstance(r1.embedding, np.ndarray) else r1.embedding.detach().cpu().numpy()
                e2 = r2.embedding if isinstance(r2.embedding, np.ndarray) else r2.embedding.detach().cpu().numpy()
                np.testing.assert_allclose(e1, e2, atol=1e-7)

            def test_different_episodes_differ(self, synthetic_episode, second_episode):
                \"\"\"Different episodes should produce distinguishable embeddings.\"\"\"
                ext = self._make_extractor()
                e1 = ext.extract(synthetic_episode, seed=42).embedding
                e2 = ext.extract(second_episode, seed=42).embedding
                if isinstance(e1, torch.Tensor):
                    e1 = e1.detach().cpu().numpy()
                if isinstance(e2, torch.Tensor):
                    e2 = e2.detach().cpu().numpy()
                sim = cosine_sim(e1, e2)
                assert sim < 0.99, (
                    f"Cosine similarity {sim:.4f} -- embeddings not discriminative"
                )

            def test_probe_frozen(self, synthetic_episode):
                \"\"\"Probe params must not change during extraction.\"\"\"
                ext = self._make_extractor()
                probe = ext.probe if hasattr(ext, "probe") else None
                if probe is None:
                    pytest.skip("Extractor does not expose .probe attribute")
                snap = [p.clone() for p in probe.parameters()]
                ext.extract(synthetic_episode, seed=42)
                for p_before, p_after in zip(snap, probe.parameters()):
                    assert torch.equal(p_before, p_after), "Probe parameter changed"

            def test_probe_eval_mode(self, synthetic_episode):
                \"\"\"Probe must be in eval mode (training=False) during extraction.\"\"\"
                ext = self._make_extractor()
                probe = ext.probe if hasattr(ext, "probe") else None
                if probe is None:
                    pytest.skip("Extractor does not expose .probe attribute")
                # Extract once to trigger the pipeline
                ext.extract(synthetic_episode, seed=42)
                assert not probe.training, "Probe should be in eval mode"
                for name, m in probe.named_modules():
                    if isinstance(m, (nn.BatchNorm1d, nn.BatchNorm2d)):
                        assert not m.training, (
                            f"BN layer '{name}' is in training mode"
                        )

            def test_fisher_nonnegative(self, synthetic_episode):
                \"\"\"Raw Fisher diagonal values must be >= 0 (squared gradients).\"\"\"
                ext = self._make_extractor()
                result = ext.extract(synthetic_episode, seed=42)
                diag = result.diagnostics if isinstance(result.diagnostics, dict) else {}
                fisher_norm = diag.get("fisher_norm", None)
                if fisher_norm is not None:
                    assert fisher_norm >= 0, f"Fisher norm negative: {fisher_norm}"
                # If the extractor exposes raw fisher, check element-wise
                if hasattr(result, "raw_fisher"):
                    for name, f in result.raw_fisher.items():
                        arr = f.detach().cpu().numpy() if isinstance(f, torch.Tensor) else f
                        assert (arr >= -1e-12).all(), (
                            f"Negative Fisher values in '{name}'"
                        )

            def test_log1p_applied(self, synthetic_episode):
                \"\"\"After log1p, all embedding values should be >= 0.\"\"\"
                ext = self._make_extractor()
                result = ext.extract(synthetic_episode, seed=42)
                emb = result.embedding
                if isinstance(emb, torch.Tensor):
                    emb = emb.detach().cpu().numpy()
                assert (emb >= -1e-7).all(), (
                    f"Negative embedding values after log1p: min={emb.min():.2e}"
                )

            def test_layer_subset_last_block(self, synthetic_episode):
                \"\"\"With layer_subset='last_block', Fisher should cover only last block.\"\"\"
                if not HAS_CONFIG:
                    pytest.skip("Config not available")
                cfg = Task2VecConfig(
                    probe_model="conv4",
                    embedding_dim=EMBED_DIM,
                    layer_subset="last_block",
                )
                ext = Task2VecExtractor(cfg)
                result = ext.extract(synthetic_episode, seed=42)
                # Just verify it runs and produces the right dim
                emb = result.embedding
                if isinstance(emb, torch.Tensor):
                    emb = emb.detach().cpu().numpy()
                assert emb.shape == (EMBED_DIM,)

            def test_layer_subset_per_stage(self, synthetic_episode):
                \"\"\"With layer_subset='per_stage', Fisher should cover one layer per stage.\"\"\"
                if not HAS_CONFIG:
                    pytest.skip("Config not available")
                cfg = Task2VecConfig(
                    probe_model="conv4",
                    embedding_dim=EMBED_DIM,
                    layer_subset="per_stage",
                )
                ext = Task2VecExtractor(cfg)
                result = ext.extract(synthetic_episode, seed=42)
                emb = result.embedding
                if isinstance(emb, torch.Tensor):
                    emb = emb.detach().cpu().numpy()
                assert emb.shape == (EMBED_DIM,)

            def test_aggregation_per_channel(self, synthetic_episode):
                \"\"\"per_channel aggregation still produces correct embedding dim.\"\"\"
                if not HAS_CONFIG:
                    pytest.skip("Config not available")
                cfg = Task2VecConfig(
                    probe_model="conv4",
                    embedding_dim=EMBED_DIM,
                    aggregation="per_channel",
                )
                ext = Task2VecExtractor(cfg)
                result = ext.extract(synthetic_episode, seed=42)
                emb = result.embedding
                if isinstance(emb, torch.Tensor):
                    emb = emb.detach().cpu().numpy()
                assert emb.shape == (EMBED_DIM,)

            def test_aggregation_per_layer(self, synthetic_episode):
                \"\"\"per_layer aggregation still produces correct embedding dim.\"\"\"
                if not HAS_CONFIG:
                    pytest.skip("Config not available")
                cfg = Task2VecConfig(
                    probe_model="conv4",
                    embedding_dim=EMBED_DIM,
                    aggregation="per_layer",
                )
                ext = Task2VecExtractor(cfg)
                result = ext.extract(synthetic_episode, seed=42)
                emb = result.embedding
                if isinstance(emb, torch.Tensor):
                    emb = emb.detach().cpu().numpy()
                assert emb.shape == (EMBED_DIM,)

            def test_task_id_deterministic(self):
                \"\"\"Same canonical inputs -> same task_id hash.\"\"\"
                id1 = compute_task_id(
                    dataset_name="mnist",
                    split="train",
                    class_ids=[0, 1, 2],
                    support_indices=[10, 20, 30],
                    transforms_signature="none",
                )
                id2 = compute_task_id(
                    dataset_name="mnist",
                    split="train",
                    class_ids=[0, 1, 2],
                    support_indices=[10, 20, 30],
                    transforms_signature="none",
                )
                assert id1 == id2, "Task ID not deterministic"

                # Different input -> different hash
                id3 = compute_task_id(
                    dataset_name="mnist",
                    split="val",
                    class_ids=[0, 1, 2],
                    support_indices=[10, 20, 30],
                    transforms_signature="none",
                )
                assert id1 != id3, "Different splits should produce different IDs"

            def test_diagnostics_keys(self, synthetic_episode):
                \"\"\"Diagnostics dict must contain fisher_norm, sparsity, probe_loss.\"\"\"
                ext = self._make_extractor()
                result = ext.extract(synthetic_episode, seed=42)
                diag = result.diagnostics
                assert isinstance(diag, dict), f"diagnostics is {type(diag)}"
                required = {"fisher_norm", "sparsity", "probe_loss"}
                # Accept either exact or superset
                for key in required:
                    assert key in diag, f"Missing diagnostics key: {key}"
                    val = diag[key]
                    assert isinstance(val, (int, float)), (
                        f"diagnostics['{key}'] is {type(val)}, expected numeric"
                    )
                    assert np.isfinite(val), f"diagnostics['{key}'] is not finite"

            def test_fp32_enforcement(self, synthetic_episode):
                \"\"\"Embedding dtype must be float32 regardless of ambient precision.\"\"\"
                ext = self._make_extractor()
                result = ext.extract(synthetic_episode, seed=42)
                emb = result.embedding
                if isinstance(emb, torch.Tensor):
                    assert emb.dtype == torch.float32, (
                        f"Expected float32, got {emb.dtype}"
                    )
                elif isinstance(emb, np.ndarray):
                    assert emb.dtype == np.float32, (
                        f"Expected float32, got {emb.dtype}"
                    )

        """)
    )


def _build_test_registry() -> str:
    return (
        _section_banner("TestEmbeddingRegistry (~12 tests)")
        + _dedent("""\
        @pytest.mark.skipif(not HAS_REGISTRY, reason="embedding_registry not available")
        class TestEmbeddingRegistry:
            \"\"\"Tests for brain_ai.meta.embedding_registry.TaskEmbeddingRegistry.\"\"\"

            def test_add_and_retrieve(self):
                \"\"\"Single entry round-trip: add then get.\"\"\"
                rng = np.random.RandomState(0)
                reg = TaskEmbeddingRegistry(embedding_dim=EMBED_DIM)
                emb = make_random_embedding(EMBED_DIM, rng)
                reg.update("t1", emb, dataset="ds1", split="train")
                retrieved = reg.get_embedding("t1")
                np.testing.assert_allclose(retrieved, emb, atol=1e-7)

            def test_batch_retrieval(self):
                \"\"\"get_embeddings returns (N, E) for N task_ids.\"\"\"
                rng = np.random.RandomState(1)
                reg = TaskEmbeddingRegistry(embedding_dim=EMBED_DIM)
                for i in range(5):
                    reg.update(f"bt_{i}", make_random_embedding(EMBED_DIM, rng))
                ids = [f"bt_{i}" for i in range(5)]
                mat = reg.get_embeddings(ids)
                assert mat.shape == (5, EMBED_DIM), f"Shape {mat.shape}"

            def test_save_load_jsonl_npz(self, tmp_registry_dir):
                \"\"\"Save and load round-trip preserves data.\"\"\"
                rng = np.random.RandomState(2)
                reg = TaskEmbeddingRegistry(embedding_dim=EMBED_DIM)
                orig_embs = {}
                for i in range(8):
                    emb = make_random_embedding(EMBED_DIM, rng)
                    tid = f"sl_{i:03d}"
                    reg.update(tid, emb, dataset="ds", split="train",
                               probe_signature="probe_a")
                    orig_embs[tid] = emb

                reg.save(tmp_registry_dir)
                loaded = TaskEmbeddingRegistry.load(tmp_registry_dir)
                assert len(loaded) == 8
                for tid, orig in orig_embs.items():
                    np.testing.assert_allclose(
                        loaded.get_embedding(tid), orig, atol=1e-7
                    )

            def test_query_by_dataset(self, populated_registry):
                \"\"\"query(dataset='A') returns exactly the A entries.\"\"\"
                result = populated_registry.query(dataset="A")
                assert len(result) == 10
                for tid in result:
                    entry = populated_registry.get_entry(tid)
                    assert entry.dataset == "A"

            def test_query_by_split(self):
                \"\"\"query(split=...) filters correctly.\"\"\"
                rng = np.random.RandomState(3)
                reg = TaskEmbeddingRegistry(embedding_dim=EMBED_DIM)
                reg.update("s1", make_random_embedding(EMBED_DIM, rng), split="train")
                reg.update("s2", make_random_embedding(EMBED_DIM, rng), split="val")
                reg.update("s3", make_random_embedding(EMBED_DIM, rng), split="train")
                result = reg.query(split="val")
                assert result == ["s2"]

            def test_query_combined(self, populated_registry):
                \"\"\"Combined filters use AND semantics.\"\"\"
                result = populated_registry.query(dataset="A", split="train")
                assert len(result) == 10  # all A entries have split=train

            def test_overwrite_duplicate(self):
                \"\"\"Re-inserting same task_id overwrites; length unchanged.\"\"\"
                rng = np.random.RandomState(4)
                reg = TaskEmbeddingRegistry(embedding_dim=EMBED_DIM)
                emb1 = make_random_embedding(EMBED_DIM, rng)
                emb2 = make_random_embedding(EMBED_DIM, rng)
                reg.update("dup", emb1, dataset="old")
                reg.update("dup", emb2, dataset="new")
                assert len(reg) == 1
                np.testing.assert_allclose(
                    reg.get_embedding("dup"), emb2, atol=1e-7
                )

            def test_contains(self):
                \"\"\"__contains__ reports presence correctly.\"\"\"
                rng = np.random.RandomState(5)
                reg = TaskEmbeddingRegistry(embedding_dim=EMBED_DIM)
                reg.update("yes", make_random_embedding(EMBED_DIM, rng))
                assert "yes" in reg
                assert "no" not in reg

            def test_merge(self):
                \"\"\"merge() combines two registries, deduplicating by task_id.\"\"\"
                rng = np.random.RandomState(6)
                ra = TaskEmbeddingRegistry(embedding_dim=EMBED_DIM)
                rb = TaskEmbeddingRegistry(embedding_dim=EMBED_DIM)
                for i in range(10):
                    ra.update(f"a_{i}", make_random_embedding(EMBED_DIM, rng))
                for i in range(10):
                    tid = f"a_{i}" if i < 5 else f"b_{i}"
                    rb.update(tid, make_random_embedding(EMBED_DIM, rng))
                merged = ra.merge(rb)
                assert len(merged) == 15  # 10 + 10 - 5 overlap

            def test_diff(self):
                \"\"\"diff() detects added, removed, changed, unchanged.\"\"\"
                rng = np.random.RandomState(7)
                ra = TaskEmbeddingRegistry(embedding_dim=EMBED_DIM)
                rb = TaskEmbeddingRegistry(embedding_dim=EMBED_DIM)
                shared_emb = make_random_embedding(EMBED_DIM, rng)
                ra.update("only_a", make_random_embedding(EMBED_DIM, rng))
                ra.update("shared", shared_emb.copy())
                rb.update("shared", shared_emb.copy())
                rb.update("only_b", make_random_embedding(EMBED_DIM, rng))
                d = ra.diff(rb)
                assert "only_b" in d["added"]
                assert "only_a" in d["removed"]
                assert "shared" in d["unchanged"]

            def test_embedding_matrix_shape(self, populated_registry):
                \"\"\"embedding_matrix() returns (N, E).\"\"\"
                mat = populated_registry.embedding_matrix()
                assert mat.shape == (20, EMBED_DIM)

            def test_empty_registry(self, tmp_registry_dir):
                \"\"\"Empty registry save/load round-trip works.\"\"\"
                reg = TaskEmbeddingRegistry(embedding_dim=EMBED_DIM)
                reg.save(tmp_registry_dir)
                loaded = TaskEmbeddingRegistry.load(tmp_registry_dir)
                assert len(loaded) == 0
                assert loaded.embedding_dim == EMBED_DIM
                with pytest.raises(KeyError):
                    loaded.get_embedding("nonexistent")

        """)
    )


def _build_test_clustering() -> str:
    return (
        _section_banner("TestClustering (~10 tests)")
        + _dedent("""\
        @requires_sklearn
        class TestClustering:
            \"\"\"Tests for brain_ai.meta.task_clustering.\"\"\"

            # ---- kmeans --------------------------------------------------------

            def test_kmeans_k_clusters(self, embedding_matrix, task_ids):
                \"\"\"k-means with k=5 produces exactly 5 unique labels.\"\"\"
                km = KMeans(n_clusters=N_CLUSTERS, random_state=42, n_init=10)
                labels = km.fit_predict(embedding_matrix)
                assert len(set(labels)) == N_CLUSTERS
                assert len(labels) == N_TASKS

            def test_kmeans_deterministic(self, embedding_matrix):
                \"\"\"Same seed -> same labels.\"\"\"
                km1 = KMeans(n_clusters=N_CLUSTERS, random_state=42, n_init=10)
                km2 = KMeans(n_clusters=N_CLUSTERS, random_state=42, n_init=10)
                l1 = km1.fit_predict(embedding_matrix)
                l2 = km2.fit_predict(embedding_matrix)
                np.testing.assert_array_equal(l1, l2)

            # ---- cosine distance -----------------------------------------------

            def test_cosine_distance_symmetric(self, embedding_matrix):
                \"\"\"Cosine distance matrix is symmetric.\"\"\"
                sim = embedding_matrix @ embedding_matrix.T
                dist = 1.0 - sim
                np.fill_diagonal(dist, 0.0)
                np.testing.assert_allclose(dist, dist.T, atol=1e-6)

            def test_cosine_distance_diagonal_zero(self, embedding_matrix):
                \"\"\"Diagonal of cosine distance matrix is 0.\"\"\"
                sim = embedding_matrix @ embedding_matrix.T
                dist = 1.0 - sim
                np.fill_diagonal(dist, 0.0)
                assert np.max(np.abs(np.diag(dist))) < 1e-7

            # ---- silhouette ----------------------------------------------------

            def test_silhouette_range(self, embedding_matrix, cluster_labels):
                \"\"\"Silhouette score is in [-1, 1] and positive for planted data.\"\"\"
                km = KMeans(n_clusters=N_CLUSTERS, random_state=42, n_init=10)
                pred = km.fit_predict(embedding_matrix)
                sil = silhouette_score(embedding_matrix, pred, metric="cosine")
                assert -1.0 <= sil <= 1.0
                assert sil > 0, f"Expected positive silhouette, got {sil:.4f}"

            def test_cluster_sizes_sum(self, embedding_matrix):
                \"\"\"Sum of cluster sizes equals n_tasks.\"\"\"
                km = KMeans(n_clusters=N_CLUSTERS, random_state=42, n_init=10)
                labels = km.fit_predict(embedding_matrix)
                total = sum(int((labels == c).sum()) for c in range(N_CLUSTERS))
                assert total == N_TASKS

            def test_representative_tasks_valid(self, embedding_matrix, task_ids):
                \"\"\"Representative task index is within range for each cluster.\"\"\"
                km = KMeans(n_clusters=N_CLUSTERS, random_state=42, n_init=10)
                labels = km.fit_predict(embedding_matrix)
                centroids = km.cluster_centers_
                c_norms = np.linalg.norm(centroids, axis=1, keepdims=True)
                centroids = centroids / np.maximum(c_norms, 1e-8)

                for k in range(N_CLUSTERS):
                    mask = labels == k
                    cluster_embs = embedding_matrix[mask]
                    sims = cluster_embs @ centroids[k]
                    best = int(np.argmax(sims))
                    assert 0 <= best < cluster_embs.shape[0]

            def test_single_cluster(self, embedding_matrix):
                \"\"\"k-means with k=1 assigns all points to cluster 0.\"\"\"
                km = KMeans(n_clusters=1, random_state=42, n_init=10)
                labels = km.fit_predict(embedding_matrix)
                assert set(labels) == {0}

            # ---- agglomerative / hdbscan (optional) ----------------------------

            def test_agglomerative(self, embedding_matrix):
                \"\"\"Agglomerative clustering produces k clusters.\"\"\"
                agg = AgglomerativeClustering(n_clusters=N_CLUSTERS, linkage="ward")
                labels = agg.fit_predict(embedding_matrix)
                assert len(set(labels)) == N_CLUSTERS

            @requires_hdbscan
            def test_hdbscan(self, embedding_matrix):
                \"\"\"HDBSCAN runs and returns valid label array.\"\"\"
                clusterer = hdbscan.HDBSCAN(
                    min_cluster_size=3, metric="euclidean"
                )
                labels = clusterer.fit_predict(embedding_matrix)
                assert isinstance(labels, np.ndarray)
                assert labels.shape == (N_TASKS,)

        """)
    )


def _build_test_stability() -> str:
    return (
        _section_banner("TestStability (~5 tests)")
        + _dedent("""\
        @requires_sklearn
        class TestStability:
            \"\"\"Cluster stability metrics: ARI, NMI across seed pairs.\"\"\"

            def _cluster(self, embeddings, seed):
                km = KMeans(n_clusters=N_CLUSTERS, random_state=seed, n_init=10)
                return km.fit_predict(embeddings)

            def test_ari_well_separated(self, embedding_matrix):
                \"\"\"ARI >= 0.9 for well-separated planted clusters.\"\"\"
                l1 = self._cluster(embedding_matrix, 42)
                l2 = self._cluster(embedding_matrix, 123)
                ari = adjusted_rand_score(l1, l2)
                assert ari >= 0.9, f"ARI = {ari:.4f}, expected >= 0.9"

            def test_ari_overlapping(self):
                \"\"\"ARI is lower for overlapping/noisy clusters.\"\"\"
                rng = np.random.RandomState(99)
                noisy = rng.randn(50, EMBED_DIM).astype(np.float32)
                norms = np.linalg.norm(noisy, axis=1, keepdims=True)
                noisy /= np.maximum(norms, 1e-8)
                l1 = KMeans(n_clusters=5, random_state=0, n_init=10).fit_predict(noisy)
                l2 = KMeans(n_clusters=5, random_state=1, n_init=10).fit_predict(noisy)
                ari = adjusted_rand_score(l1, l2)
                # For pure noise, ARI should be low, but we just check it's bounded
                assert -1.0 <= ari <= 1.0

            def test_nmi_agreement(self, embedding_matrix):
                \"\"\"NMI direction agrees with ARI for planted clusters.\"\"\"
                l1 = self._cluster(embedding_matrix, 42)
                l2 = self._cluster(embedding_matrix, 123)
                ari = adjusted_rand_score(l1, l2)
                nmi = normalized_mutual_info_score(
                    l1, l2, average_method="arithmetic"
                )
                # Both should be high for well-separated data
                if ari >= 0.9:
                    assert nmi >= 0.8, f"NMI = {nmi:.4f} too low given ARI = {ari:.4f}"

            def test_stability_result_fields(self, embedding_matrix):
                \"\"\"Multi-trial stability returns all required fields.\"\"\"
                ari_list = []
                nmi_list = []
                for t in range(5):
                    l1 = self._cluster(embedding_matrix, t * 2)
                    l2 = self._cluster(embedding_matrix, t * 2 + 1)
                    ari_list.append(adjusted_rand_score(l1, l2))
                    nmi_list.append(normalized_mutual_info_score(
                        l1, l2, average_method="arithmetic"
                    ))
                ari_arr = np.array(ari_list)
                nmi_arr = np.array(nmi_list)
                assert ari_arr.shape == (5,)
                assert nmi_arr.shape == (5,)
                assert np.isfinite(ari_arr).all()
                assert np.isfinite(nmi_arr).all()

            def test_multiple_runs(self, embedding_matrix):
                \"\"\"Multiple clustering runs with same seed give identical labels.\"\"\"
                labels = [self._cluster(embedding_matrix, 42) for _ in range(3)]
                for i in range(1, len(labels)):
                    np.testing.assert_array_equal(labels[0], labels[i])

        """)
    )


def _build_test_curriculum() -> str:
    return (
        _section_banner("TestCurriculum (~12 tests)")
        + _dedent("""\
        class TestCurriculum:
            \"\"\"Tests for brain_ai.meta.curriculum ordering and schedule functions.\"\"\"

            # ---- helpers -------------------------------------------------------
            def _difficulty_from_embeddings(self, embeddings, task_ids):
                \"\"\"Simple centroid-distance difficulty proxy for testing.\"\"\"
                # Use first cluster centroid as the 'easy' reference
                centroid = embeddings.mean(axis=0)
                centroid /= np.linalg.norm(centroid) + 1e-12
                difficulty = {}
                for i, tid in enumerate(task_ids):
                    difficulty[tid] = float(1.0 - np.dot(embeddings[i], centroid))
                return difficulty

            # ---- ordering tests ------------------------------------------------

            def test_easy_to_hard_order(self, embedding_matrix, task_ids):
                \"\"\"Easy-to-hard ordering matches sorted difficulty.\"\"\"
                diff = self._difficulty_from_embeddings(embedding_matrix, task_ids)
                ordered = sorted(task_ids, key=lambda t: (diff[t], t))
                # Verify monotonicity
                for i in range(1, len(ordered)):
                    assert diff[ordered[i]] >= diff[ordered[i - 1]] - 1e-9

            def test_anti_curriculum_order(self, embedding_matrix, task_ids):
                \"\"\"Anti-curriculum reverses easy-to-hard ordering.\"\"\"
                diff = self._difficulty_from_embeddings(embedding_matrix, task_ids)
                easy = sorted(task_ids, key=lambda t: (diff[t], t))
                anti = list(reversed(easy))
                assert anti[0] != easy[0] or len(easy) == 1

            def test_none_preserves_all(self, task_ids):
                \"\"\"Strategy 'none' still returns all task_ids (no drops).\"\"\"
                rng = np.random.RandomState(42)
                shuffled = list(task_ids)
                rng.shuffle(shuffled)
                assert set(shuffled) == set(task_ids)
                assert len(shuffled) == len(task_ids)

            def test_deterministic_ordering(self, embedding_matrix, task_ids):
                \"\"\"Same seed -> identical curriculum ordering.\"\"\"
                diff = self._difficulty_from_embeddings(embedding_matrix, task_ids)
                o1 = sorted(task_ids, key=lambda t: (diff[t], t))
                o2 = sorted(task_ids, key=lambda t: (diff[t], t))
                assert o1 == o2

            def test_different_seeds_differ(self, task_ids):
                \"\"\"Different RNG seeds should produce different random orderings.\"\"\"
                rng42 = np.random.RandomState(42)
                rng99 = np.random.RandomState(99)
                s1 = list(task_ids)
                s2 = list(task_ids)
                rng42.shuffle(s1)
                rng99.shuffle(s2)
                assert s1 != s2, "Different seeds produced identical orderings"

            @requires_scipy
            def test_kendall_tau_significant(self, embedding_matrix, task_ids):
                \"\"\"Curriculum ordering is significantly different from random
                (Kendall tau p < 0.05).\"\"\"
                diff = self._difficulty_from_embeddings(embedding_matrix, task_ids)
                curriculum = sorted(task_ids, key=lambda t: (diff[t], t))
                rng = np.random.RandomState(99)
                random_order = list(task_ids)
                rng.shuffle(random_order)
                rank_c = {t: i for i, t in enumerate(curriculum)}
                rank_r = {t: i for i, t in enumerate(random_order)}
                all_ids = sorted(task_ids)
                rc = [rank_c[t] for t in all_ids]
                rr = [rank_r[t] for t in all_ids]
                tau, p = kendalltau(rc, rr)
                assert abs(tau) > 0.0, "Kendall tau is exactly 0"

            @requires_scipy
            def test_kendall_tau_identical(self):
                \"\"\"Identical orderings yield tau = 1.0.\"\"\"
                x = list(range(20))
                tau, _ = kendalltau(x, x)
                assert abs(tau - 1.0) < 1e-6

            def test_diversity_min_distance(self, embedding_matrix, task_ids):
                \"\"\"Diversity batch pairwise cosine distances >= threshold.\"\"\"
                threshold = 0.2
                rng = np.random.RandomState(42)
                candidates = list(range(len(task_ids)))
                rng.shuffle(candidates)

                selected_idx = [candidates[0]]
                for ci in candidates[1:]:
                    emb = embedding_matrix[ci]
                    dists = [
                        1.0 - np.dot(emb, embedding_matrix[si])
                        for si in selected_idx
                    ]
                    if min(dists) >= threshold:
                        selected_idx.append(ci)
                    if len(selected_idx) >= 10:
                        break

                # Verify pairwise distances
                for i in range(len(selected_idx)):
                    for j in range(i + 1, len(selected_idx)):
                        d = 1.0 - np.dot(
                            embedding_matrix[selected_idx[i]],
                            embedding_matrix[selected_idx[j]],
                        )
                        assert d >= threshold - 1e-6, (
                            f"Pair ({i},{j}) distance {d:.4f} < {threshold}"
                        )

            def test_batch_size_enforced(self, task_ids):
                \"\"\"Meta-batch always returns exactly the requested count.\"\"\"
                rng = np.random.RandomState(42)
                pool = list(task_ids)
                for size in [1, 8, len(task_ids)]:
                    rng.shuffle(pool)
                    batch = pool[:size]
                    assert len(batch) == size

            # ---- schedule functions --------------------------------------------

            def test_schedule_linear(self):
                \"\"\"Linear schedule: p(0)=0, p(max)=1, linearly.\"\"\"
                max_e = 100
                for e in range(0, max_e + 1, 10):
                    p = min(e / max_e, 1.0)
                    expected = e / max_e
                    assert abs(p - expected) < 0.02, (
                        f"Epoch {e}: p={p:.4f}, expected={expected:.4f}"
                    )

            def test_schedule_cosine(self):
                \"\"\"Cosine schedule: monotonic from 0 to 1.\"\"\"
                max_e = 100
                prev = -1.0
                for e in range(0, max_e + 1):
                    progress = min(e / max_e, 1.0)
                    p = 0.5 * (1.0 - math.cos(math.pi * progress))
                    assert p >= prev - 1e-9, (
                        f"Non-monotonic at epoch {e}: {prev:.4f} -> {p:.4f}"
                    )
                    prev = p
                # Boundary values
                p0 = 0.5 * (1.0 - math.cos(0.0))
                p_max = 0.5 * (1.0 - math.cos(math.pi))
                assert abs(p0) < 0.01
                assert abs(p_max - 1.0) < 0.01

            def test_epoch_log_fields(self, embedding_matrix, task_ids):
                \"\"\"Epoch log entry contains required fields.\"\"\"
                diff = self._difficulty_from_embeddings(embedding_matrix, task_ids)
                ordered = sorted(task_ids, key=lambda t: (diff[t], t))
                order_str = ",".join(ordered)
                order_hash = hashlib.sha256(order_str.encode()).hexdigest()

                log_entry = {
                    "epoch": 0,
                    "strategy": "easy_to_hard",
                    "task_order_hash": order_hash,
                    "num_tasks": len(ordered),
                }
                for key in ("epoch", "strategy", "task_order_hash", "num_tasks"):
                    assert key in log_entry, f"Missing log field: {key}"

        """)
    )


def _build_test_config() -> str:
    return (
        _section_banner("TestConfig (~8 tests)")
        + _dedent("""\
        class TestConfig:
            \"\"\"Tests for Task2Vec-related configuration dataclasses.\"\"\"

            @pytest.mark.skipif(not HAS_CONFIG, reason="Config classes not available")
            def test_defaults(self):
                \"\"\"Default instantiation of all config classes succeeds.\"\"\"
                t2v = Task2VecConfig()
                assert t2v.embedding_dim == 512
                assert t2v.probe_model == "conv4"
                cc = ClusterConfig()
                assert cc.n_clusters == 8
                cur = CurriculumConfig()
                assert cur.strategy == "none"

            @pytest.mark.skipif(not HAS_FULL_CONFIG, reason="Task2VecFullConfig not available")
            def test_presets(self):
                \"\"\"Presets minimal / dev / production instantiate without error.\"\"\"
                m = Task2VecFullConfig.minimal()
                assert m.task2vec.embedding_dim <= 256
                d = Task2VecFullConfig.dev()
                assert d.task2vec.embedding_dim >= 256
                p = Task2VecFullConfig.production()
                assert p.task2vec.embedding_dim >= 512

            @pytest.mark.skipif(not HAS_CONFIG, reason="Config classes not available")
            def test_serialization(self):
                \"\"\"to_dict -> from_dict round-trip for Task2VecConfig.\"\"\"
                original = Task2VecConfig(
                    probe_model="conv4", embedding_dim=256
                )
                if hasattr(original, "to_dict") and hasattr(Task2VecConfig, "from_dict"):
                    d = original.to_dict()
                    restored = Task2VecConfig.from_dict(d)
                    assert restored.probe_model == original.probe_model
                    assert restored.embedding_dim == original.embedding_dim
                else:
                    pytest.skip("to_dict/from_dict not implemented")

            @pytest.mark.skipif(not HAS_CONFIG, reason="Config classes not available")
            def test_invalid_probe_model(self):
                \"\"\"Invalid probe model raises ValueError during validation.\"\"\"
                cfg = Task2VecConfig(probe_model="nonexistent_model")
                if hasattr(cfg, "validate"):
                    with pytest.raises(ValueError):
                        cfg.validate()
                else:
                    # If no explicit validate, the extractor should reject it
                    if HAS_EXTRACTOR:
                        with pytest.raises((ValueError, KeyError, RuntimeError)):
                            Task2VecExtractor(cfg)
                    else:
                        pytest.skip("No validation path available")

            @pytest.mark.skipif(not HAS_CONFIG, reason="Config classes not available")
            def test_invalid_embedding_dim(self):
                \"\"\"Embedding dim <= 0 raises ValueError.\"\"\"
                try:
                    cfg = Task2VecConfig(embedding_dim=0)
                    if hasattr(cfg, "validate"):
                        with pytest.raises(ValueError):
                            cfg.validate()
                    elif hasattr(cfg, "__post_init__"):
                        # __post_init__ should have raised
                        pass
                    else:
                        pytest.skip("No validation on embedding_dim")
                except (ValueError, TypeError):
                    pass  # Raised during construction -- correct

            @pytest.mark.skipif(not HAS_CONFIG, reason="Config classes not available")
            def test_invalid_strategy(self):
                \"\"\"Invalid curriculum strategy raises ValueError.\"\"\"
                try:
                    cfg = CurriculumConfig(strategy="nonexistent")
                    if hasattr(cfg, "validate"):
                        with pytest.raises(ValueError):
                            cfg.validate()
                    else:
                        pytest.skip("No validate method")
                except (ValueError, TypeError):
                    pass

            @pytest.mark.skipif(not HAS_FULL_CONFIG, reason="Full config not available")
            def test_minimal_smaller(self):
                \"\"\"Minimal preset has smaller dims than production.\"\"\"
                m = Task2VecFullConfig.minimal()
                p = Task2VecFullConfig.production()
                assert m.task2vec.embedding_dim < p.task2vec.embedding_dim

            @pytest.mark.skipif(not HAS_CONFIG, reason="Config classes not available")
            def test_feature_flag(self):
                \"\"\"Default use_task2vec flag behaviour (if it exists on parent config).\"\"\"
                try:
                    from brain_ai.config import BrainAIConfig
                    cfg = BrainAIConfig()
                    if hasattr(cfg, "use_task2vec"):
                        # Just check it is a bool
                        assert isinstance(cfg.use_task2vec, bool)
                    else:
                        pytest.skip("use_task2vec flag not present")
                except Exception:
                    pytest.skip("BrainAIConfig not importable")

        """)
    )


def _build_test_whitening() -> str:
    return (
        _section_banner("TestWhitening (~4 tests)")
        + _dedent("""\
        class TestWhitening:
            \"\"\"Tests for EmbeddingWhitener (optional whitening transform).\"\"\"

            def _make_whitener(self, dim=EMBED_DIM):
                if HAS_WHITENER:
                    return EmbeddingWhitener(embedding_dim=dim)
                pytest.skip("EmbeddingWhitener not available")

            @requires_torch
            def test_fit_transform(self):
                \"\"\"Fit on reference, transform produces approx zero mean and
                unit variance.\"\"\"
                whitener = self._make_whitener()
                # Need n_ref >= dim for full rank
                n_ref = EMBED_DIM + 20
                rng = np.random.RandomState(42)
                ref = rng.randn(n_ref, EMBED_DIM).astype(np.float32)
                # L2-normalise rows
                ref /= np.linalg.norm(ref, axis=1, keepdims=True) + 1e-12
                ref_t = torch.from_numpy(ref)
                whitener.fit(ref_t)
                assert whitener.fitted

                # Transform a batch
                test_batch = torch.from_numpy(
                    rng.randn(20, EMBED_DIM).astype(np.float32)
                )
                test_batch /= test_batch.norm(dim=1, keepdim=True).clamp(min=1e-12)
                out = whitener.transform(test_batch)
                assert out.shape == (20, EMBED_DIM)
                # After whitening + re-normalisation, norms should be ~ 1
                norms = out.norm(dim=1)
                np.testing.assert_allclose(
                    norms.numpy(), np.ones(20), atol=0.1
                )

            @requires_torch
            def test_identity_without_fit(self):
                \"\"\"transform() before fit() raises RuntimeError.\"\"\"
                whitener = self._make_whitener()
                x = torch.randn(5, EMBED_DIM)
                with pytest.raises(RuntimeError):
                    whitener.transform(x)

            @requires_torch
            def test_regularization(self):
                \"\"\"Whitener handles near-singular covariance via regularization.\"\"\"
                whitener = self._make_whitener(dim=8)
                # Create near-rank-deficient data: repeat a vector with tiny noise
                base = torch.randn(1, 8)
                ref = base.expand(20, -1) + torch.randn(20, 8) * 1e-6
                ref /= ref.norm(dim=1, keepdim=True).clamp(min=1e-12)
                # Should not raise, due to regularization
                whitener.fit(ref)
                assert whitener.fitted

            @requires_torch
            def test_deterministic(self):
                \"\"\"Same input -> same output.\"\"\"
                whitener = self._make_whitener()
                rng = np.random.RandomState(0)
                n_ref = EMBED_DIM + 10
                ref = rng.randn(n_ref, EMBED_DIM).astype(np.float32)
                ref /= np.linalg.norm(ref, axis=1, keepdims=True) + 1e-12
                ref_t = torch.from_numpy(ref)
                whitener.fit(ref_t)

                x = torch.from_numpy(
                    rng.randn(5, EMBED_DIM).astype(np.float32)
                )
                x /= x.norm(dim=1, keepdim=True).clamp(min=1e-12)
                out1 = whitener.transform(x.clone())
                out2 = whitener.transform(x.clone())
                np.testing.assert_allclose(
                    out1.numpy(), out2.numpy(), atol=1e-7
                )

        """)
    )


def _build_test_integration() -> str:
    return (
        _section_banner("TestIntegration (~6 tests)")
        + _dedent("""\
        class TestIntegration:
            \"\"\"End-to-end pipeline tests: extract -> register -> cluster -> curriculum.\"\"\"

            @requires_sklearn
            def test_end_to_end_pipeline(self, embedding_matrix, task_ids):
                \"\"\"Full pipeline: make embeddings, cluster, order by difficulty.\"\"\"
                # 1. Create registry (stand-in)
                if HAS_REGISTRY:
                    reg = TaskEmbeddingRegistry(embedding_dim=EMBED_DIM)
                    for i, tid in enumerate(task_ids):
                        reg.update(tid, embedding_matrix[i],
                                   dataset="synth", split="train")
                    assert len(reg) == N_TASKS

                # 2. Cluster
                km = KMeans(n_clusters=N_CLUSTERS, random_state=42, n_init=10)
                labels = km.fit_predict(embedding_matrix)
                assert len(set(labels)) >= 1

                # 3. Difficulty proxy: distance to global centroid
                centroid = embedding_matrix.mean(axis=0)
                centroid /= np.linalg.norm(centroid) + 1e-12
                diff = {
                    tid: float(1.0 - np.dot(embedding_matrix[i], centroid))
                    for i, tid in enumerate(task_ids)
                }

                # 4. Curriculum order
                ordered = sorted(task_ids, key=lambda t: (diff[t], t))
                assert set(ordered) == set(task_ids)
                assert len(ordered) == N_TASKS

            @pytest.mark.skipif(not HAS_REGISTRY, reason="Registry not available")
            def test_registry_checkpoint(self, tmp_registry_dir):
                \"\"\"Registry survives save/load round-trip (simulated checkpoint).\"\"\"
                rng = np.random.RandomState(10)
                reg = TaskEmbeddingRegistry(embedding_dim=EMBED_DIM)
                orig = {}
                for i in range(10):
                    emb = make_random_embedding(EMBED_DIM, rng)
                    tid = f"ckpt_{i:03d}"
                    reg.update(tid, emb, dataset="ds", split="train")
                    orig[tid] = emb

                reg.save(tmp_registry_dir)
                loaded = TaskEmbeddingRegistry.load(tmp_registry_dir)
                assert len(loaded) == 10
                for tid, emb in orig.items():
                    np.testing.assert_allclose(
                        loaded.get_embedding(tid), emb, atol=1e-7
                    )

            def test_curriculum_changes_per_epoch(self, embedding_matrix, task_ids):
                \"\"\"Mixed schedule should produce different orderings at different
                epochs (p_hard varies).\"\"\"
                centroid = embedding_matrix.mean(axis=0)
                centroid /= np.linalg.norm(centroid) + 1e-12
                diff = {
                    tid: float(1.0 - np.dot(embedding_matrix[i], centroid))
                    for i, tid in enumerate(task_ids)
                }
                median_d = np.median(list(diff.values()))

                # Epoch 0: p_hard ~ 0 -> mostly easy tasks
                rng0 = np.random.RandomState(0)
                weights_0 = np.array([
                    0.0 if diff[t] > median_d else 1.0
                    for t in task_ids
                ])
                weights_0 /= weights_0.sum() + 1e-12
                idx_0 = rng0.choice(len(task_ids), size=len(task_ids),
                                     replace=True, p=weights_0)
                order_0 = [task_ids[i] for i in idx_0]

                # Epoch 50: p_hard ~ 0.5 -> mixed
                rng50 = np.random.RandomState(50)
                weights_50 = np.array([
                    0.5 if diff[t] > median_d else 0.5
                    for t in task_ids
                ])
                weights_50 /= weights_50.sum() + 1e-12
                idx_50 = rng50.choice(len(task_ids), size=len(task_ids),
                                       replace=True, p=weights_50)
                order_50 = [task_ids[i] for i in idx_50]

                assert order_0 != order_50, (
                    "Epoch 0 and 50 produced identical orderings"
                )

            @requires_sklearn
            def test_diversity_affects_batch(self, embedding_matrix, task_ids):
                \"\"\"Diversity constraint changes batch composition.\"\"\"
                rng = np.random.RandomState(42)
                # Unconstrained: random
                pool = list(range(len(task_ids)))
                rng.shuffle(pool)
                unconstrained = pool[:10]

                # Constrained: greedy with min_distance
                rng2 = np.random.RandomState(42)
                pool2 = list(range(len(task_ids)))
                rng2.shuffle(pool2)
                constrained = [pool2[0]]
                for ci in pool2[1:]:
                    emb = embedding_matrix[ci]
                    dists = [
                        1.0 - np.dot(emb, embedding_matrix[si])
                        for si in constrained
                    ]
                    if min(dists) >= 0.2:
                        constrained.append(ci)
                    if len(constrained) >= 10:
                        break

                # Compute mean pairwise distances
                def mean_pairwise(idxs):
                    dists = []
                    for i in range(len(idxs)):
                        for j in range(i + 1, len(idxs)):
                            d = 1.0 - np.dot(
                                embedding_matrix[idxs[i]],
                                embedding_matrix[idxs[j]],
                            )
                            dists.append(d)
                    return np.mean(dists) if dists else 0.0

                md_unc = mean_pairwise(unconstrained)
                md_con = mean_pairwise(constrained)
                assert md_con >= md_unc - 0.05, (
                    f"Constrained mean dist {md_con:.4f} < unconstrained {md_unc:.4f}"
                )

            @pytest.mark.skipif(not HAS_FULL_CONFIG, reason="Full config not available")
            @pytest.mark.skipif(not HAS_EXTRACTOR, reason="Extractor not available")
            def test_preset_pipelines(self, synthetic_episode):
                \"\"\"All presets produce working extraction pipelines.\"\"\"
                for preset_name in ("minimal", "dev", "production"):
                    cfg = getattr(Task2VecFullConfig, preset_name)()
                    # Only attempt extraction on minimal to save time
                    if preset_name == "minimal":
                        ext = Task2VecExtractor(cfg.task2vec)
                        result = ext.extract(synthetic_episode, seed=42)
                        emb = result.embedding
                        if isinstance(emb, torch.Tensor):
                            emb = emb.detach().cpu().numpy()
                        assert emb.ndim == 1
                        assert emb.shape[0] > 0

            @pytest.mark.skipif(not HAS_REGISTRY, reason="Registry not available")
            def test_multiple_episodes(self):
                \"\"\"Registry grows correctly as episodes are added.\"\"\"
                rng = np.random.RandomState(77)
                reg = TaskEmbeddingRegistry(embedding_dim=EMBED_DIM)
                for i in range(20):
                    emb = make_random_embedding(EMBED_DIM, rng)
                    reg.update(
                        f"ep_{i:03d}", emb,
                        dataset="multi", split="train",
                    )
                assert len(reg) == 20
                ids = reg.all_task_ids()
                assert len(set(ids)) == 20
                # Check all normalised
                for tid in ids:
                    e = reg.get_embedding(tid)
                    assert abs(np.linalg.norm(e) - 1.0) < 1e-4

        """)
    )


# ---------------------------------------------------------------------------
# Assembly
# ---------------------------------------------------------------------------

def build_test_file() -> str:
    """Assemble all sections into the final test file content."""
    parts: List[str] = [
        _build_header(),
        _build_imports(),
        _build_helpers(),
        _build_fixtures(),
        _build_test_extractor(),
        _build_test_registry(),
        _build_test_clustering(),
        _build_test_stability(),
        _build_test_curriculum(),
        _build_test_config(),
        _build_test_whitening(),
        _build_test_integration(),
    ]
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _default_output() -> str:
    """Resolve the default output path relative to the project root."""
    # Try to find the project root (contains brain_ai/ or scripts/)
    here = Path(__file__).resolve().parent  # scripts/
    skill_root = here.parent               # task2vec-curriculum/
    # Go up to the repo root
    repo_root = skill_root.parent.parent   # human-brain/
    target = repo_root / "tests" / "test_task2vec.py"
    return str(target)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate tests/test_task2vec.py for the Task2Vec skill.",
    )
    parser.add_argument(
        "--output", "-o",
        default=_default_output(),
        help="Path to write the generated test file "
             "(default: tests/test_task2vec.py relative to repo root).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated file to stdout instead of writing to disk.",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Print extra diagnostics about what the generator is doing.",
    )
    parser.add_argument(
        "--run",
        action="store_true",
        help="Generate the test file and immediately run it with pytest.",
    )
    args = parser.parse_args()

    content = build_test_file()

    # Count test methods
    test_count = content.count("\n    def test_")
    class_count = content.count("\nclass Test")

    if args.verbose:
        print(f"[gen_task2vec_tests] Generated {test_count} test methods "
              f"across {class_count} test classes.")
        print(f"[gen_task2vec_tests] Total lines: {content.count(chr(10)) + 1}")

    if args.dry_run:
        print(content)
        print(f"\n# --- DRY RUN --- {test_count} tests, {class_count} classes ---")
        return

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"[gen_task2vec_tests] Wrote {output_path} "
          f"({test_count} tests, {class_count} classes)")

    if args.run:
        print(f"[gen_task2vec_tests] Running pytest on {output_path} ...")
        result = subprocess.run(
            [sys.executable, "-m", "pytest", str(output_path), "-v", "--tb=short"],
            cwd=str(output_path.parent.parent),
        )
        sys.exit(result.returncode)


if __name__ == "__main__":
    main()
