#!/usr/bin/env python3
"""
gen_masking_tests.py
====================
Generates 100+ pytest test cases for V-JEPA 2 Video & Masking.

Generates tests/test_vjepa2_masking.py in the same directory as this script
(or the path specified by --output).

Generated test categories:
    - PatchEmbed (2-D) shapes                       [~10 tests]
    - PatchEmbed3D shapes                           [~15 tests]
    - PatchEmbed3D grid properties                  [~10 tests]
    - PatchEmbed3D error cases                      [~5 tests]
    - MaskGenerator shapes                          [~8 tests]
    - MaskGenerator coverage invariants             [~12 tests]
    - MaskGenerator block config variants           [~10 tests]
    - MaskGenerator max_context_frames_ratio        [~6 tests]
    - MaskGenerator max_keep                        [~6 tests]
    - MaskGenerator seed determinism                [~5 tests]
    - MaskGenerator edge cases                      [~6 tests]
    - apply_masks correctness                       [~8 tests]
    - apply_masks_fast equivalence                  [~4 tests]
    - scatter_masks roundtrip                       [~4 tests]
    - MaskCollator single-FPC grouping              [~8 tests]
    - MaskCollator multi-FPC grouping               [~10 tests]
    - MaskCollator coverage in collated groups      [~6 tests]
    - MaskCollator counter / seed                   [~5 tests]
    - MultiSequenceEncoder                          [~6 tests]
    - MultiSequencePredictor                        [~4 tests]
    - MaskConfig validation                         [~8 tests]
    - VideoConfig validation                        [~6 tests]
    - make_mask_generators factory                  [~5 tests]

Usage:
    python gen_masking_tests.py                     # write tests/test_vjepa2_masking.py
    python gen_masking_tests.py --output /tmp/t.py  # custom output path
    python gen_masking_tests.py --run               # generate and immediately run pytest
"""

from __future__ import annotations

import argparse
import os
import sys
import textwrap


TEST_FILE_HEADER = '''"""
test_vjepa2_masking.py
======================
Auto-generated pytest test suite for V-JEPA 2 Video & Masking.
Generated by scripts/gen_masking_tests.py.

Run:
    cd /path/to/vjepa2-video-masking/assets
    pytest ../tests/test_vjepa2_masking.py -v
"""
from __future__ import annotations
import sys, os
import math

import pytest
import torch
import torch.nn as nn
from torch import Tensor

# Allow imports from assets/ when running from tests/
_HERE   = os.path.dirname(os.path.abspath(__file__))
_ASSETS = os.path.join(_HERE, "..", "assets")
if _ASSETS not in sys.path:
    sys.path.insert(0, os.path.abspath(_ASSETS))

from patch_embed_template import PatchEmbed, PatchEmbed3D, make_patch_embed, make_patch_embed_3d
from mask_generator_template import (
    MaskGenerator, make_small_mask_generator, make_large_mask_generator,
    _sample_block_size, _place_block, _cap_keep,
)
from mask_collator_template import MaskCollator, _group_by_fpc, build_collator
from multi_sequence_template import (
    apply_masks, apply_masks_fast, scatter_masks,
    MultiSequenceEncoder, MultiSequencePredictor,
    _StubEncoder, _StubPredictor,
)
from masking_config_template import (
    MaskConfig, VideoConfig, apply_masks as cfg_apply_masks, make_mask_generators
)

import random


# ===========================================================================
# Fixtures
# ===========================================================================

@pytest.fixture
def grid_8_14_14():
    return (8, 14, 14)

@pytest.fixture
def grid_4_14_14():
    return (4, 14, 14)

@pytest.fixture
def grid_8_16_16():
    return (8, 16, 16)

@pytest.fixture
def mg_small(grid_8_14_14):
    return make_small_mask_generator(grid_size=grid_8_14_14, npred=8)

@pytest.fixture
def mg_large(grid_8_14_14):
    return make_large_mask_generator(grid_size=grid_8_14_14, npred=2)


def make_item(fpc: int) -> dict:
    return {
        "fpc":    fpc,
        "frames": torch.randn(fpc, 3, 14, 14),
        "label":  torch.tensor(0),
    }


# ===========================================================================
# PatchEmbed (2-D) -- shape tests
# ===========================================================================

class TestPatchEmbed2D:

    def test_shape_224_patch16_dim768_batch1(self):
        pe = PatchEmbed(img_size=224, patch_size=16, embed_dim=768)
        out = pe(torch.randn(1, 3, 224, 224))
        assert out.shape == (1, 196, 768)

    def test_shape_224_patch16_dim768_batch4(self):
        pe = PatchEmbed(img_size=224, patch_size=16, embed_dim=768)
        out = pe(torch.randn(4, 3, 224, 224))
        assert out.shape == (4, 196, 768)

    def test_shape_384_patch16_dim768(self):
        pe = PatchEmbed(img_size=384, patch_size=16, embed_dim=768)
        out = pe(torch.randn(2, 3, 384, 384))
        assert out.shape == (2, 576, 768)

    def test_shape_224_patch32_dim1024(self):
        pe = PatchEmbed(img_size=224, patch_size=32, embed_dim=1024)
        out = pe(torch.randn(1, 3, 224, 224))
        assert out.shape == (1, 49, 1024)

    def test_num_patches_196(self):
        pe = PatchEmbed(img_size=224, patch_size=16)
        assert pe.num_patches == 196

    def test_num_patches_576(self):
        pe = PatchEmbed(img_size=384, patch_size=16)
        assert pe.num_patches == 576

    def test_grid_size_14x14(self):
        pe = PatchEmbed(img_size=224, patch_size=16)
        assert pe.grid_size == (14, 14)

    def test_grid_size_7x7(self):
        pe = PatchEmbed(img_size=224, patch_size=32)
        assert pe.grid_size == (7, 7)

    def test_raises_indivisible_img(self):
        with pytest.raises(ValueError):
            PatchEmbed(img_size=225, patch_size=16)

    def test_output_dtype_matches_input(self):
        pe = PatchEmbed(img_size=224, patch_size=16, embed_dim=768)
        x  = torch.randn(2, 3, 224, 224).to(torch.float16)
        out = pe(x.float())  # cast back to float32 for conv
        assert out.dtype == torch.float32


# ===========================================================================
# PatchEmbed3D -- shape tests
# ===========================================================================

class TestPatchEmbed3D:

    @pytest.mark.parametrize("img_size,frames,patch,tubelet,embed,B,expected", [
        (224, 16, 16, 2, 1024, 1, (1, 1568, 1024)),
        (224, 16, 16, 2, 1024, 2, (2, 1568, 1024)),
        (256, 16, 16, 2, 1024, 1, (1, 2048, 1024)),
        (224,  8, 16, 2,  768, 4, (4,  784,  768)),
        (224, 16, 16, 4, 1024, 1, (1,  784, 1024)),
        (224, 16, 32, 2,  512, 1, (1,  392,  512)),
        (384, 16, 16, 2, 1024, 1, (1, 4608, 1024)),
    ])
    def test_output_shape(
        self, img_size, frames, patch, tubelet, embed, B, expected
    ):
        pe  = PatchEmbed3D(img_size=img_size, frames=frames,
                           patch_size=patch, tubelet_size=tubelet,
                           embed_dim=embed)
        out = pe(torch.randn(B, 3, frames, img_size, img_size))
        assert out.shape == expected, f"got {out.shape}"

    def test_num_patches_1568(self):
        pe = PatchEmbed3D(img_size=224, frames=16, patch_size=16,
                          tubelet_size=2, embed_dim=1024)
        assert pe.num_patches == 1568

    def test_num_patches_2048(self):
        pe = PatchEmbed3D(img_size=256, frames=16, patch_size=16,
                          tubelet_size=2, embed_dim=1024)
        assert pe.num_patches == 2048

    def test_num_patches_matches_output(self):
        pe  = PatchEmbed3D(img_size=224, frames=16, patch_size=16,
                           tubelet_size=2, embed_dim=1024)
        out = pe(torch.randn(1, 3, 16, 224, 224))
        assert out.shape[1] == pe.num_patches

    def test_grid_size_8_14_14(self):
        pe = PatchEmbed3D(img_size=224, frames=16, patch_size=16,
                          tubelet_size=2, embed_dim=1024)
        assert pe.grid_size == (8, 14, 14)

    def test_grid_size_4_14_14(self):
        pe = PatchEmbed3D(img_size=224, frames=8, patch_size=16,
                          tubelet_size=2, embed_dim=768)
        assert pe.grid_size == (4, 14, 14)

    def test_token_count_formula(self):
        """Verify N = (T/t)*(H/P)*(W/P) for multiple configs."""
        configs = [
            dict(img_size=224, frames=16, patch_size=16, tubelet_size=2),
            dict(img_size=256, frames=16, patch_size=16, tubelet_size=2),
            dict(img_size=224, frames=8,  patch_size=16, tubelet_size=2),
        ]
        for c in configs:
            pe = PatchEmbed3D(**c, embed_dim=64)
            T  = c["frames"] // c["tubelet_size"]
            H  = c["img_size"] // c["patch_size"]
            W  = H
            assert pe.num_patches == T * H * W

    def test_raises_frames_not_divisible(self):
        with pytest.raises(ValueError):
            PatchEmbed3D(frames=15, tubelet_size=2)

    def test_raises_img_not_divisible(self):
        with pytest.raises(ValueError):
            PatchEmbed3D(img_size=225, patch_size=16)

    def test_raises_wrong_frame_count_at_forward(self):
        pe = PatchEmbed3D(img_size=224, frames=16, patch_size=16,
                          tubelet_size=2, embed_dim=64)
        with pytest.raises(ValueError):
            pe(torch.randn(1, 3, 8, 224, 224))

    def test_raises_wrong_spatial_at_forward(self):
        pe = PatchEmbed3D(img_size=224, frames=16, patch_size=16,
                          tubelet_size=2, embed_dim=64)
        with pytest.raises(ValueError):
            pe(torch.randn(1, 3, 16, 256, 256))

    def test_make_factory(self):
        pe = make_patch_embed_3d(img_size=224, frames=16, patch_size=16,
                                 tubelet_size=2, embed_dim=64)
        assert isinstance(pe, PatchEmbed3D)
        out = pe(torch.randn(1, 3, 16, 224, 224))
        assert out.shape == (1, 1568, 64)


# ===========================================================================
# MaskGenerator -- shapes
# ===========================================================================

class TestMaskGeneratorShapes:

    def test_output_type(self, mg_small):
        enc, pred = mg_small(4, seed=0)
        assert isinstance(enc, list)
        assert isinstance(pred, list)

    def test_list_length_equals_batch(self, mg_small):
        for B in [1, 2, 4, 8]:
            enc, _ = mg_small(B, seed=0)
            assert len(enc) == B

    def test_mask_shape_1568(self, mg_small):
        enc, pred = mg_small(4, seed=0)
        N = 8 * 14 * 14
        for e, p in zip(enc, pred):
            assert e.shape == (N,)
            assert p.shape == (N,)

    def test_mask_dtype_bool(self, mg_small):
        enc, pred = mg_small(4, seed=0)
        for e, p in zip(enc, pred):
            assert e.dtype == torch.bool
            assert p.dtype == torch.bool

    def test_shape_different_grids(self):
        for grid in [(8, 14, 14), (4, 14, 14), (8, 16, 16), (2, 7, 7)]:
            N  = grid[0] * grid[1] * grid[2]
            mg = MaskGenerator(npred=2, grid_size=grid)
            enc, pred = mg(2, seed=0)
            assert enc[0].shape == (N,)
            assert pred[0].shape == (N,)


# ===========================================================================
# MaskGenerator -- coverage invariants
# ===========================================================================

class TestMaskGeneratorCoverage:

    GRIDS = [(8, 14, 14), (4, 14, 14), (8, 16, 16)]

    @pytest.mark.parametrize("grid", GRIDS)
    @pytest.mark.parametrize("seed", [0, 42, 99])
    def test_no_gaps(self, grid, seed):
        mg = MaskGenerator(spatial_scale=(0.15, 0.15), temporal_scale=(1.0, 1.0),
                           aspect_ratio=(0.75, 1.5), npred=4, grid_size=grid)
        enc, pred = mg(4, seed=seed)
        for e, p in zip(enc, pred):
            assert (e | p).all().item(), "Gap detected: some tokens uncovered"

    @pytest.mark.parametrize("grid", GRIDS)
    @pytest.mark.parametrize("seed", [0, 42, 99])
    def test_no_overlaps(self, grid, seed):
        mg = MaskGenerator(spatial_scale=(0.15, 0.15), temporal_scale=(1.0, 1.0),
                           aspect_ratio=(0.75, 1.5), npred=4, grid_size=grid)
        enc, pred = mg(4, seed=seed)
        for e, p in zip(enc, pred):
            assert not (e & p).any().item(), "Overlap: enc and pred share a token"

    @pytest.mark.parametrize("grid", GRIDS)
    def test_exact_complement(self, grid):
        mg = MaskGenerator(npred=4, grid_size=grid)
        enc, pred = mg(2, seed=7)
        for e, p in zip(enc, pred):
            assert torch.equal(e, ~p), "enc is not exact complement of pred"

    @pytest.mark.parametrize("grid", GRIDS)
    def test_sum_equals_N(self, grid):
        N  = grid[0] * grid[1] * grid[2]
        mg = MaskGenerator(npred=4, grid_size=grid)
        enc, pred = mg(4, seed=1)
        for e, p in zip(enc, pred):
            assert e.long().sum() + p.long().sum() == N

    def test_large_blocks_cover_majority(self, grid_8_14_14):
        mg = make_large_mask_generator(grid_size=grid_8_14_14, npred=2)
        enc, pred = mg(8, seed=0)
        mean_pred = sum(p.float().mean().item() for p in pred) / 8
        assert mean_pred >= 0.5, f"Large blocks only covered {mean_pred:.2%} on average"

    def test_small_blocks_non_trivial(self, grid_8_14_14):
        mg = make_small_mask_generator(grid_size=grid_8_14_14, npred=8)
        enc, pred = mg(4, seed=0)
        for p in pred:
            assert p.any().item(), "Small block pred mask is all False"

    def test_npred_zero_enc_all_true(self):
        mg = MaskGenerator(npred=0, grid_size=(4, 4, 4))
        enc, pred = mg(2, seed=0)
        for e in enc:
            assert e.all().item()
        for p in pred:
            assert not p.any().item()

    def test_coverage_with_temporal_half(self):
        grid = (8, 7, 7)
        mg = MaskGenerator(
            spatial_scale=(0.15, 0.15),
            temporal_scale=(0.5, 0.5),
            aspect_ratio=(1.0, 1.0),
            npred=1,
            grid_size=grid,
        )
        enc, pred = mg(4, seed=0)
        for e, p in zip(enc, pred):
            assert (e | p).all(), "No gaps despite temporal_scale=0.5"
            assert not (e & p).any(), "No overlaps"


# ===========================================================================
# MaskGenerator -- block config variants
# ===========================================================================

class TestMaskGeneratorBlockConfig:

    def test_full_temporal_scale(self):
        """temporal_scale=(1,1) => each pred block spans all T frames."""
        T, H, W = 8, 7, 7
        mg = MaskGenerator(
            spatial_scale=(0.1, 0.1),
            temporal_scale=(1.0, 1.0),
            aspect_ratio=(1.0, 1.0),
            npred=1,
            grid_size=(T, H, W),
        )
        enc, pred = mg(4, seed=0)
        for p in pred:
            p3d = p.view(T, H, W)
            # Every temporal frame that has any pred token must cover entire
            # block height/width (since temporal_scale=1 means tl==T)
            assert p.any(), "pred must have some tokens"

    def test_square_aspect_ratio(self):
        """aspect_ratio=(1,1) => block_h == block_w always."""
        import random as _random
        rng = _random.Random(0)
        T, H, W = 4, 8, 8
        for _ in range(50):
            tl, bh, bw = _sample_block_size(
                T, H, W,
                spatial_scale=(0.2, 0.5),
                temporal_scale=(1.0, 1.0),
                aspect_ratio=(1.0, 1.0),
                rng=rng,
            )
            assert bh == bw, f"Expected square block, got bh={bh}, bw={bw}"

    def test_large_spatial_scale(self):
        grid = (8, 14, 14)
        N    = 8 * 14 * 14
        mg = MaskGenerator(
            spatial_scale=(0.7, 0.7),
            temporal_scale=(1.0, 1.0),
            aspect_ratio=(1.0, 1.0),
            npred=1,
            grid_size=grid,
        )
        enc, pred = mg(4, seed=0)
        for p in pred:
            ratio = p.float().mean().item()
            assert ratio > 0.3, f"Large scale should cover >30%, got {ratio:.2%}"

    def test_aspect_ratio_bounds(self):
        """block dimensions always stay within grid bounds."""
        import random as _random
        rng = _random.Random(42)
        T, H, W = 4, 6, 6
        for _ in range(200):
            tl, bh, bw = _sample_block_size(
                T, H, W,
                spatial_scale=(0.1, 0.9),
                temporal_scale=(0.5, 1.0),
                aspect_ratio=(0.1, 10.0),
                rng=rng,
            )
            assert 1 <= tl <= T
            assert 1 <= bh <= H
            assert 1 <= bw <= W


# ===========================================================================
# MaskGenerator -- max_context_frames_ratio
# ===========================================================================

class TestMaxContextFramesRatio:

    def test_ratio_1_no_cap(self):
        """ratio=1.0 means no temporal cap."""
        T, H, W = 8, 7, 7
        mg = MaskGenerator(npred=0, grid_size=(T, H, W),
                           max_context_frames_ratio=1.0)
        enc, _ = mg(4, seed=0)
        N = T * H * W
        for e in enc:
            assert e.long().sum().item() == N, "npred=0 should leave all tokens visible"

    def test_ratio_half_limits_frames(self):
        T, H, W = 8, 7, 7
        mg = MaskGenerator(npred=0, grid_size=(T, H, W),
                           max_context_frames_ratio=0.5)
        enc, _ = mg(1, seed=0)
        enc3d = enc[0].view(T, H, W)
        visible_frames = enc3d.any(dim=(1, 2)).nonzero(as_tuple=False)
        if visible_frames.numel() > 0:
            last = visible_frames[-1, 0].item()
            assert last < T, f"Expected frame capped, last visible={last}, T={T}"

    def test_ratio_quarter_limits_frames(self):
        T, H, W = 8, 7, 7
        mg = MaskGenerator(npred=0, grid_size=(T, H, W),
                           max_context_frames_ratio=0.25)
        enc, _ = mg(1, seed=0)
        enc3d = enc[0].view(T, H, W)
        # Frames beyond first 25% should be invisible
        beyond = enc3d[round(T * 0.25):, :, :]
        assert not beyond.any(), "Frames beyond ratio should be masked"

    def test_invalid_ratio_zero(self):
        with pytest.raises(ValueError):
            MaskGenerator(grid_size=(4, 4, 4), max_context_frames_ratio=0.0)

    def test_invalid_ratio_negative(self):
        with pytest.raises(ValueError):
            MaskGenerator(grid_size=(4, 4, 4), max_context_frames_ratio=-0.5)

    def test_invalid_ratio_above_1(self):
        with pytest.raises(ValueError):
            MaskGenerator(grid_size=(4, 4, 4), max_context_frames_ratio=1.5)


# ===========================================================================
# MaskGenerator -- max_keep
# ===========================================================================

class TestMaxKeep:

    def test_max_keep_caps_enc(self):
        MAX_KEEP = 200
        mg = MaskGenerator(npred=1, grid_size=(8, 14, 14), max_keep=MAX_KEEP)
        enc, _ = mg(8, seed=0)
        for e in enc:
            assert e.long().sum().item() <= MAX_KEEP

    def test_max_keep_none_no_cap(self):
        mg = MaskGenerator(npred=1, grid_size=(8, 14, 14), max_keep=None)
        enc, pred = mg(4, seed=0)
        # Without cap, the mask invariant still holds
        for e, p in zip(enc, pred):
            assert (e | p).all()

    def test_max_keep_large_no_effect(self):
        """max_keep larger than N should not change enc mask."""
        N = 8 * 14 * 14
        mg_ref = MaskGenerator(npred=2, grid_size=(8, 14, 14), max_keep=None)
        mg_big = MaskGenerator(npred=2, grid_size=(8, 14, 14), max_keep=N + 1000)
        enc_ref, _ = mg_ref(2, seed=11)
        enc_big, _ = mg_big(2, seed=11)
        for e_r, e_b in zip(enc_ref, enc_big):
            assert torch.equal(e_r, e_b)

    def test_max_keep_zero_enc_empty(self):
        mg = MaskGenerator(npred=0, grid_size=(4, 4, 4), max_keep=0)
        enc, _ = mg(2, seed=0)
        for e in enc:
            assert e.long().sum().item() == 0

    def test_cap_keep_helper(self):
        N = 100
        mask = torch.ones(N, dtype=torch.bool)
        rng  = random.Random(0)
        capped = _cap_keep(mask, max_keep=30, rng=rng)
        assert capped.long().sum().item() == 30

    def test_cap_keep_no_op_when_small(self):
        N = 10
        mask = torch.ones(N, dtype=torch.bool)
        rng  = random.Random(0)
        capped = _cap_keep(mask, max_keep=100, rng=rng)
        assert capped.long().sum().item() == N


# ===========================================================================
# MaskGenerator -- seed determinism
# ===========================================================================

class TestSeedDeterminism:

    def test_same_seed_identical(self, mg_small):
        e_a, _ = mg_small(4, seed=42)
        e_b, _ = mg_small(4, seed=42)
        for a, b in zip(e_a, e_b):
            assert torch.equal(a, b)

    def test_different_seed_different(self, mg_small):
        e_a, _ = mg_small(4, seed=1)
        e_b, _ = mg_small(4, seed=2)
        assert any(not torch.equal(a, b) for a, b in zip(e_a, e_b))

    def test_none_seed_random(self, mg_small):
        """Without seed, two calls should almost certainly differ."""
        e_a, _ = mg_small(4, seed=None)
        e_b, _ = mg_small(4, seed=None)
        # This can theoretically fail with astronomically small probability
        assert any(not torch.equal(a, b) for a, b in zip(e_a, e_b))

    def test_seed_independent_of_batch_size(self):
        """First sample from seed=X should be the same regardless of batch size."""
        mg = make_small_mask_generator(grid_size=(4, 7, 7), npred=3)
        e_b1, _ = mg(1, seed=77)
        e_b4, _ = mg(4, seed=77)
        assert torch.equal(e_b1[0], e_b4[0])


# ===========================================================================
# MaskGenerator -- edge cases
# ===========================================================================

class TestMaskGeneratorEdgeCases:

    def test_single_token_grid(self):
        mg = MaskGenerator(npred=1, grid_size=(1, 1, 1))
        enc, pred = mg(2, seed=0)
        for e, p in zip(enc, pred):
            assert e.numel() == 1
            assert p.numel() == 1
            assert (e | p).all()
            assert not (e & p).any()

    def test_npred_0(self):
        mg = MaskGenerator(npred=0, grid_size=(4, 4, 4))
        enc, pred = mg(2, seed=0)
        for e in enc:
            assert e.all()
        for p in pred:
            assert not p.any()

    def test_invalid_grid_zero(self):
        with pytest.raises(ValueError):
            MaskGenerator(grid_size=(0, 14, 14))

    def test_invalid_npred_negative(self):
        with pytest.raises(ValueError):
            MaskGenerator(npred=-1, grid_size=(4, 4, 4))

    def test_batch_size_1(self):
        mg = make_small_mask_generator(grid_size=(4, 7, 7))
        enc, pred = mg(1, seed=0)
        assert len(enc) == 1
        assert (enc[0] | pred[0]).all()

    def test_large_npred_coverage(self):
        """Many blocks may saturate the grid; coverage invariant must still hold."""
        mg = MaskGenerator(
            spatial_scale=(0.5, 0.5), temporal_scale=(1.0, 1.0),
            aspect_ratio=(1.0, 1.0), npred=100, grid_size=(4, 4, 4),
        )
        enc, pred = mg(2, seed=0)
        for e, p in zip(enc, pred):
            assert (e | p).all()
            assert not (e & p).any()


# ===========================================================================
# apply_masks
# ===========================================================================

class TestApplyMasks:

    @pytest.mark.parametrize("B,N,D,n_vis", [
        (2, 10, 32, 5),
        (4, 100, 64, 75),
        (1, 1568, 128, 392),
    ])
    def test_shape(self, B, N, D, n_vis):
        x  = torch.randn(B, N, D)
        ms = [torch.zeros(N, dtype=torch.bool) for _ in range(B)]
        for m in ms:
            m[:n_vis] = True
        out = apply_masks(x, ms)
        assert out.shape == (B, n_vis, D)

    def test_token_values_correct(self):
        B, N, D = 3, 20, 16
        x  = torch.randn(B, N, D)
        ms = [torch.zeros(N, dtype=torch.bool) for _ in range(B)]
        for m in ms:
            m[::2] = True  # 10 visible
        out = apply_masks(x, ms)
        for i, m in enumerate(ms):
            assert torch.allclose(out[i], x[i][m])

    def test_all_true_identity(self):
        B, N, D = 2, 50, 32
        x  = torch.randn(B, N, D)
        ms = [torch.ones(N, dtype=torch.bool) for _ in range(B)]
        out = apply_masks(x, ms)
        assert torch.allclose(out, x)

    def test_naive_equals_fast(self):
        B, N, D = 4, 100, 64
        x  = torch.randn(B, N, D)
        ms = [torch.zeros(N, dtype=torch.bool) for _ in range(B)]
        for m in ms:
            m[:50] = True
        out_naive = apply_masks(x, ms)
        out_fast  = apply_masks_fast(x, ms)
        assert torch.allclose(out_naive, out_fast)

    def test_raises_wrong_mask_count(self):
        x  = torch.randn(4, 10, 8)
        ms = [torch.ones(10, dtype=torch.bool) for _ in range(2)]
        with pytest.raises(ValueError):
            apply_masks(x, ms)

    def test_raises_inconsistent_n_vis(self):
        B, N, D = 3, 10, 8
        x  = torch.randn(B, N, D)
        ms = [torch.zeros(N, dtype=torch.bool) for _ in range(B)]
        ms[0][:5] = True
        ms[1][:3] = True  # different N_vis
        ms[2][:5] = True
        with pytest.raises(ValueError):
            apply_masks(x, ms)


# ===========================================================================
# scatter_masks (roundtrip)
# ===========================================================================

class TestScatterMasks:

    def test_visible_positions_correct(self):
        B, N, D = 2, 20, 8
        x  = torch.randn(B, N, D)
        ms = [torch.zeros(N, dtype=torch.bool) for _ in range(B)]
        for m in ms:
            m[:10] = True
        x_vis = apply_masks(x, ms)
        x_rec = scatter_masks(x_vis, ms, N)
        for i, m in enumerate(ms):
            assert torch.allclose(x_rec[i][m], x[i][m])

    def test_masked_positions_zero(self):
        B, N, D = 2, 20, 8
        x  = torch.randn(B, N, D)
        ms = [torch.zeros(N, dtype=torch.bool) for _ in range(B)]
        for m in ms:
            m[:10] = True
        x_vis = apply_masks(x, ms)
        x_rec = scatter_masks(x_vis, ms, N)
        for i, m in enumerate(ms):
            assert (x_rec[i][~m] == 0.0).all()

    def test_all_true_roundtrip(self):
        B, N, D = 2, 10, 8
        x  = torch.randn(B, N, D)
        ms = [torch.ones(N, dtype=torch.bool) for _ in range(B)]
        x_vis = apply_masks(x, ms)
        x_rec = scatter_masks(x_vis, ms, N)
        assert torch.allclose(x_rec, x)


# ===========================================================================
# MaskCollator -- single-FPC
# ===========================================================================

class TestMaskCollatorSingleFPC:

    @pytest.fixture
    def collator(self):
        mg = MaskGenerator(spatial_scale=(0.15, 0.15), temporal_scale=(1.0, 1.0),
                           aspect_ratio=(0.75, 1.5), npred=4, grid_size=(8, 14, 14))
        return MaskCollator(mg)

    def test_returns_list(self, collator):
        result = collator([make_item(16) for _ in range(4)])
        assert isinstance(result, list)

    def test_one_group(self, collator):
        result = collator([make_item(16) for _ in range(4)])
        assert len(result) == 1

    def test_mask_list_length(self, collator):
        result = collator([make_item(16) for _ in range(4)])
        _, enc, pred = result[0]
        assert len(enc) == 4
        assert len(pred) == 4

    def test_mask_shape(self, collator):
        result = collator([make_item(16) for _ in range(4)])
        _, enc, pred = result[0]
        N = 8 * 14 * 14
        assert enc[0].shape == (N,)
        assert pred[0].shape == (N,)

    def test_mask_dtype_bool(self, collator):
        result = collator([make_item(16) for _ in range(4)])
        _, enc, pred = result[0]
        assert enc[0].dtype == torch.bool
        assert pred[0].dtype == torch.bool

    def test_coverage_in_single_fpc_group(self, collator):
        result = collator([make_item(16) for _ in range(4)])
        _, enc, pred = result[0]
        for e, p in zip(enc, pred):
            assert (e | p).all()
            assert not (e & p).any()

    def test_collated_batch_is_dict(self, collator):
        result = collator([make_item(16) for _ in range(2)])
        collated, _, _ = result[0]
        assert isinstance(collated, dict)

    def test_collated_fpc_field(self, collator):
        result = collator([make_item(16) for _ in range(2)])
        collated, _, _ = result[0]
        assert "fpc" in collated


# ===========================================================================
# MaskCollator -- multi-FPC
# ===========================================================================

class TestMaskCollatorMultiFPC:

    @pytest.fixture
    def collator(self):
        mg16 = MaskGenerator(npred=4, grid_size=(8, 14, 14))
        mg8  = MaskGenerator(npred=4, grid_size=(4, 14, 14))
        mg4  = MaskGenerator(npred=4, grid_size=(2, 14, 14))
        return MaskCollator({16: mg16, 8: mg8, 4: mg4})

    def test_two_fpc_groups(self, collator):
        batch = [make_item(16), make_item(16), make_item(8), make_item(8)]
        result = collator(batch)
        assert len(result) == 2

    def test_three_fpc_groups(self, collator):
        batch = [make_item(16), make_item(8), make_item(4)] * 2
        result = collator(batch)
        assert len(result) == 3

    def test_group_sizes_correct(self, collator):
        batch = [make_item(16)] * 3 + [make_item(8)] * 2
        result = collator(batch)
        sizes = {r[1][0].shape[0]: len(r[1]) for r in result}
        N16, N8 = 8 * 14 * 14, 4 * 14 * 14
        assert sizes.get(N16) == 3
        assert sizes.get(N8)  == 2

    def test_coverage_multi_fpc(self, collator):
        batch = [make_item(16), make_item(8), make_item(16), make_item(8)]
        result = collator(batch)
        for _, enc, pred in result:
            for e, p in zip(enc, pred):
                assert (e | p).all()
                assert not (e & p).any()

    def test_different_mask_lengths_per_group(self, collator):
        batch = [make_item(16), make_item(8)]
        result = collator(batch)
        N_list = sorted(r[1][0].shape[0] for r in result)
        assert N_list == sorted([8 * 14 * 14, 4 * 14 * 14])

    def test_fallback_to_first_generator(self):
        """Unknown FPC falls back to first available generator."""
        mg  = MaskGenerator(npred=2, grid_size=(8, 14, 14))
        col = MaskCollator({16: mg})
        # FPC=99 unknown, should use fallback
        batch = [make_item(16), make_item(16)]  # both FPC=16
        result = col(batch)
        assert len(result) == 1  # one group


# ===========================================================================
# MaskCollator -- counter / seed
# ===========================================================================

class TestMaskCollatorSeed:

    def test_counter_increments(self):
        mg  = MaskGenerator(npred=2, grid_size=(4, 7, 7))
        col = MaskCollator(mg)
        with col._itr_counter.get_lock():
            col._itr_counter.value = -1

        step0 = col._step()
        step1 = col._step()
        assert step0 == 0
        assert step1 == 1

    def test_different_calls_different_masks(self):
        mg  = MaskGenerator(npred=4, grid_size=(8, 14, 14))
        col = MaskCollator(mg)
        with col._itr_counter.get_lock():
            col._itr_counter.value = -1

        r1 = col([make_item(16)] * 2)
        r2 = col([make_item(16)] * 2)
        _, e1, _ = r1[0]
        _, e2, _ = r2[0]
        assert any(not torch.equal(a, b) for a, b in zip(e1, e2))

    def test_same_step_same_masks(self):
        mg  = MaskGenerator(npred=4, grid_size=(8, 14, 14))
        col = MaskCollator(mg)

        with col._itr_counter.get_lock():
            col._itr_counter.value = 41  # next = 42

        r_a = col([make_item(16)] * 2)

        with col._itr_counter.get_lock():
            col._itr_counter.value = 41  # reset

        r_b = col([make_item(16)] * 2)
        _, ea, _ = r_a[0]
        _, eb, _ = r_b[0]
        assert all(torch.equal(a, b) for a, b in zip(ea, eb))


# ===========================================================================
# MultiSequenceEncoder
# ===========================================================================

class TestMultiSequenceEncoder:

    @pytest.fixture
    def encoder(self):
        return _StubEncoder(embed_dim=64, num_heads=4, num_layers=1)

    def test_single_group_shape(self, encoder):
        enc_wrap = MultiSequenceEncoder(encoder)
        N, D, B = 100, 64, 2
        x = torch.randn(B, N, D)
        ms = [torch.zeros(N, dtype=torch.bool) for _ in range(B)]
        for m in ms:
            m[:50] = True
        with torch.no_grad():
            out = enc_wrap([x], [ms])
        assert len(out) == 1
        assert out[0].shape == (B, 50, D)

    def test_multi_group_shapes(self, encoder):
        enc_wrap = MultiSequenceEncoder(encoder)
        D = 64
        x0 = torch.randn(2, 100, D)
        x1 = torch.randn(3, 80,  D)
        ms0 = [torch.zeros(100, dtype=torch.bool) for _ in range(2)]
        ms1 = [torch.zeros(80,  dtype=torch.bool) for _ in range(3)]
        for m in ms0:
            m[:40] = True
        for m in ms1:
            m[:20] = True
        with torch.no_grad():
            out = enc_wrap([x0, x1], [ms0, ms1])
        assert len(out) == 2
        assert out[0].shape == (2, 40, D)
        assert out[1].shape == (3, 20, D)

    def test_fast_and_naive_modes(self, encoder):
        """fast=True and fast=False gather the same input tokens (apply_masks variants agree)."""
        D, N, B = 64, 50, 2
        x  = torch.randn(B, N, D)
        ms = [torch.zeros(N, dtype=torch.bool) for _ in range(B)]
        for m in ms:
            m[:25] = True

        # Verify that both gather implementations select identical visible tokens
        # (the encoder forward will differ if it has stochastic layers, but the
        # token gathering step must be identical)
        vis_naive = apply_masks(x, ms)
        vis_fast  = apply_masks_fast(x, ms)
        assert torch.allclose(vis_naive, vis_fast), "apply_masks and apply_masks_fast disagree"

        # Both wrappers should produce the same shape output
        enc_fast  = MultiSequenceEncoder(encoder, fast=True)
        enc_naive = MultiSequenceEncoder(encoder, fast=False)
        with torch.no_grad():
            out_f = enc_fast([x], [ms])
            out_n = enc_naive([x], [ms])
        assert out_f[0].shape == out_n[0].shape

    def test_raises_mismatched_groups(self, encoder):
        enc_wrap = MultiSequenceEncoder(encoder)
        with pytest.raises(ValueError):
            enc_wrap([torch.randn(2, 10, 64)], [])


# ===========================================================================
# MaskConfig and VideoConfig
# ===========================================================================

class TestMaskConfig:

    def test_defaults(self):
        mc = MaskConfig()
        assert mc.npred_small == 8
        assert mc.npred_large == 2
        assert mc.max_context_frames_ratio == 1.0
        assert mc.max_keep is None

    def test_causal_preset(self):
        mc = MaskConfig.causal(0.5)
        assert mc.max_context_frames_ratio == 0.5

    def test_invalid_spatial_scale(self):
        with pytest.raises(ValueError):
            MaskConfig(spatial_scale_small=(0.8, 0.2))

    def test_invalid_temporal_scale(self):
        with pytest.raises(ValueError):
            MaskConfig(temporal_scale=(0.9, 0.1))

    def test_invalid_ratio_zero(self):
        with pytest.raises(ValueError):
            MaskConfig(max_context_frames_ratio=0.0)

    def test_invalid_npred_negative(self):
        with pytest.raises(ValueError):
            MaskConfig(npred_small=-1)


class TestVideoConfig:

    def test_vjepa2_base(self):
        vc = VideoConfig.vjepa2_base()
        assert vc.grid_size == (8, 14, 14)
        assert vc.num_patches == 1568

    def test_vjepa2_256(self):
        vc = VideoConfig.vjepa2_256()
        assert vc.num_patches == 2048

    def test_invalid_divisibility_temporal(self):
        with pytest.raises(ValueError):
            VideoConfig(frames_per_clip=15, tubelet_size=2)

    def test_invalid_divisibility_spatial(self):
        with pytest.raises(ValueError):
            VideoConfig(img_size=225, patch_size=16)

    def test_grid_size_matches_formula(self):
        vc = VideoConfig(frames_per_clip=8, patch_size=16, tubelet_size=2,
                         img_size=224)
        assert vc.grid_size == (4, 14, 14)
        assert vc.num_patches == 4 * 14 * 14


class TestMakeMaskGenerators:

    def test_returns_two_generators(self):
        mc, vc = MaskConfig(), VideoConfig.vjepa2_base()
        mg_s, mg_l = make_mask_generators(mc, vc)
        assert mg_s is not None
        assert mg_l is not None

    def test_grid_matches_video_config(self):
        mc, vc = MaskConfig(), VideoConfig.vjepa2_base()
        mg_s, mg_l = make_mask_generators(mc, vc)
        assert mg_s.grid_size == vc.grid_size
        assert mg_l.grid_size == vc.grid_size

    def test_npred_matches_mask_config(self):
        mc, vc = MaskConfig(), VideoConfig.vjepa2_base()
        mg_s, mg_l = make_mask_generators(mc, vc)
        assert mg_s.npred == mc.npred_small
        assert mg_l.npred == mc.npred_large

    def test_coverage_from_factory(self):
        mc, vc = MaskConfig(), VideoConfig.vjepa2_base()
        mg_s, mg_l = make_mask_generators(mc, vc)
        for mg in [mg_s, mg_l]:
            enc, pred = mg(2, seed=0)
            for e, p in zip(enc, pred):
                assert (e | p).all()
                assert not (e & p).any()
'''

MAIN_CODE = '''

if __name__ == "__main__":
    import pytest
    sys.exit(pytest.main([__file__, "-v"]))
'''


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate V-JEPA 2 masking pytest suite.")
    p.add_argument(
        "--output", "-o",
        default=None,
        help="Output file path. Default: <skill_root>/tests/test_vjepa2_masking.py",
    )
    p.add_argument(
        "--run", action="store_true",
        help="Run pytest immediately after generating the file.",
    )
    return p.parse_args()


def main() -> int:
    args = parse_args()

    # Determine output path
    if args.output:
        out_path = os.path.abspath(args.output)
    else:
        skill_root = os.path.abspath(os.path.join(_SCRIPT_DIR, ".."))
        tests_dir  = os.path.join(skill_root, "tests")
        os.makedirs(tests_dir, exist_ok=True)
        out_path = os.path.join(tests_dir, "test_vjepa2_masking.py")

    content = TEST_FILE_HEADER + MAIN_CODE

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Generated: {out_path}")

    # Count test functions
    test_count = content.count("    def test_")
    print(f"Test functions: {test_count}")

    if args.run:
        import subprocess
        assets_dir = os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "assets"))
        result = subprocess.run(
            [sys.executable, "-m", "pytest", out_path, "-v"],
            cwd=assets_dir,
        )
        return result.returncode

    return 0


if __name__ == "__main__":
    _SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
    sys.exit(main())
