#!/usr/bin/env python3
"""
gen_distributed_tests.py
--------------------------
Generates a pytest test file with 100+ test functions covering all components
of the distributed-memory-scaling skill.

Test categories:
  - Config validation (strategy, FSDP, DeepSpeed, cross-field)
  - Strategy router (wrapping order, DDP/FSDP/DS paths, optimizer creation)
  - FSDP wrapper (policies, mixed precision, activation checkpointing, checkpoints)
  - DeepSpeed wrapper (JSON generation for all stage/offload combos)
  - Checkpoint portability (round-trips, cross-strategy load)
  - Scaling benchmark (efficiency computation, edge cases, schema)

Usage
-----
    python scripts/gen_distributed_tests.py                    # prints to stdout
    python scripts/gen_distributed_tests.py -o tests/test_distributed.py
    pytest tests/test_distributed.py -v
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import List


# ---------------------------------------------------------------------------
# Test file content builder
# ---------------------------------------------------------------------------

def generate_test_file() -> str:
    sections: List[str] = []

    sections.append(_header())
    sections.append(_imports_and_fixtures())
    sections.append(_config_tests())
    sections.append(_router_tests())
    sections.append(_fsdp_wrapper_tests())
    sections.append(_deepspeed_wrapper_tests())
    sections.append(_checkpoint_portability_tests())
    sections.append(_scaling_benchmark_tests())
    sections.append(_edge_case_tests())

    return "\n\n".join(sections)


# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------

def _header() -> str:
    return '''\
"""
test_distributed_generated.py
------------------------------
Auto-generated by gen_distributed_tests.py
Do not edit manually — regenerate via:
    python scripts/gen_distributed_tests.py -o tests/test_distributed.py
"""'''


# ---------------------------------------------------------------------------
# Imports and fixtures
# ---------------------------------------------------------------------------

def _imports_and_fixtures() -> str:
    return '''\
import json
import os
import sys
import tempfile
from dataclasses import dataclass
from typing import Any, Optional
from unittest.mock import MagicMock, patch

import pytest
import torch
import torch.nn as nn

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------

SKILL_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS_DIR = os.path.join(SKILL_DIR, "assets")
if ASSETS_DIR not in sys.path:
    sys.path.insert(0, ASSETS_DIR)

# ---------------------------------------------------------------------------
# Minimal config stubs (avoid circular imports between asset files)
# ---------------------------------------------------------------------------


@dataclass
class DistCfg:
    strategy: str = "ddp"
    world_size: int = 1
    backend: str = "gloo"
    grad_accum: int = 1

    def validate(self):
        valid = {"ddp", "fsdp", "deepspeed_zero2", "deepspeed_zero3"}
        if self.strategy not in valid:
            raise ValueError(f"Invalid strategy: {self.strategy!r}")
        if self.strategy == "" or self.strategy is None:
            raise ValueError("strategy must be non-empty")
        if self.backend not in {"nccl", "gloo", "mpi"}:
            raise ValueError(f"Invalid backend: {self.backend!r}")
        if self.grad_accum < 1:
            raise ValueError("grad_accum must be >= 1")

    def to_dict(self):
        import dataclasses
        return dataclasses.asdict(self)

    @classmethod
    def from_dict(cls, d):
        obj = cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})
        obj.validate()
        return obj


@dataclass
class FSDPCfg:
    sharding_strategy: str = "FULL_SHARD"
    wrap_policy: str = "transformer_block"
    wrap_module_classes: list = None
    mixed_precision: str = "bf16"
    activation_checkpointing: str = "off"
    state_dict_type: str = "full"
    sync_module_states: bool = True
    cpu_offload: bool = False
    min_num_params: int = 100_000_000

    def __post_init__(self):
        if self.wrap_module_classes is None:
            self.wrap_module_classes = []

    def validate(self):
        valid_sharding = {"FULL_SHARD", "SHARD_GRAD_OP", "NO_SHARD", "HYBRID_SHARD"}
        if self.sharding_strategy not in valid_sharding:
            raise ValueError(f"Invalid sharding_strategy: {self.sharding_strategy!r}")
        valid_policy = {"transformer_block", "size_based"}
        if self.wrap_policy not in valid_policy:
            raise ValueError(f"Invalid wrap_policy: {self.wrap_policy!r}")
        if self.wrap_policy == "transformer_block" and not self.wrap_module_classes:
            raise ValueError("wrap_module_classes required for transformer_block policy")
        valid_precision = {"bf16", "fp16", "none"}
        if self.mixed_precision not in valid_precision:
            raise ValueError(f"Invalid mixed_precision: {self.mixed_precision!r}")
        valid_ckpt = {"off", "transformer_block"}
        if self.activation_checkpointing not in valid_ckpt:
            raise ValueError(f"Invalid activation_checkpointing: {self.activation_checkpointing!r}")

    def to_dict(self):
        import dataclasses
        return dataclasses.asdict(self)

    @classmethod
    def from_dict(cls, d):
        obj = cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})
        obj.validate()
        return obj


@dataclass
class DSCfg:
    zero_stage: int = 3
    offload_optimizer: str = "none"
    offload_param: str = "none"
    reduce_bucket_size: int = 500_000_000
    allgather_bucket_size: int = 500_000_000
    stage3_prefetch_bucket_size: int = 50_000_000
    stage3_param_persistence_threshold: int = 100_000
    stage3_max_live_parameters: int = 1_000_000_000
    stage3_max_reuse_distance: int = 1_000_000_000
    overlap_comm: bool = True
    contiguous_gradients: bool = True
    nvme_path: Any = None
    fp16: bool = False
    bf16: bool = False
    gradient_clipping: float = 1.0

    def validate(self):
        if self.zero_stage not in {2, 3}:
            raise ValueError(f"Invalid zero_stage: {self.zero_stage}")
        if self.offload_param != "none" and self.zero_stage != 3:
            raise ValueError("offload_param requires zero_stage=3")
        if self.fp16 and self.bf16:
            raise ValueError("Cannot enable both fp16 and bf16")
        if self.reduce_bucket_size <= 0:
            raise ValueError("reduce_bucket_size must be > 0")
        if self.offload_param == "nvme" and not self.nvme_path:
            raise ValueError("nvme_path required for NVMe offload")

    def to_dict(self):
        import dataclasses
        return dataclasses.asdict(self)

    @classmethod
    def from_dict(cls, d):
        obj = cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})
        obj.validate()
        return obj


@dataclass
class OptCfg:
    optimizer_type: str = "AdamW"
    lr: float = 1e-4
    weight_decay: float = 0.01
    betas: tuple = (0.9, 0.95)
    eps: float = 1e-8
    momentum: float = 0.9
    grad_clip: float = 1.0

    def validate(self):
        valid_types = {"AdamW", "Adam", "SGD"}
        if self.optimizer_type not in valid_types:
            raise ValueError(f"Invalid optimizer_type: {self.optimizer_type!r}")
        if self.lr <= 0:
            raise ValueError("lr must be > 0")


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def small_model():
    return nn.Sequential(nn.Linear(8, 8), nn.ReLU(), nn.Linear(8, 4))


@pytest.fixture
def tmp_dir():
    with tempfile.TemporaryDirectory() as d:
        yield d'''


# ---------------------------------------------------------------------------
# Config tests
# ---------------------------------------------------------------------------

def _config_tests() -> str:
    return '''\
# ===========================================================================
# Phase 1: Config Validation Tests
# ===========================================================================


class TestDistributedConfig:
    """Tests for DistributedConfig-like dataclass validation."""

    @pytest.mark.parametrize("strategy", ["ddp", "fsdp", "deepspeed_zero2", "deepspeed_zero3"])
    def test_valid_strategy(self, strategy):
        cfg = DistCfg(strategy=strategy)
        cfg.validate()  # should not raise

    @pytest.mark.parametrize("strategy", ["unknown", "deepspeed", "FSDP", "zero3", ""])
    def test_invalid_strategy_raises(self, strategy):
        with pytest.raises(ValueError):
            DistCfg(strategy=strategy).validate()

    @pytest.mark.parametrize("backend", ["nccl", "gloo", "mpi"])
    def test_valid_backend(self, backend):
        DistCfg(backend=backend).validate()

    def test_invalid_backend_raises(self):
        with pytest.raises(ValueError):
            DistCfg(backend="invalid_backend").validate()

    def test_grad_accum_zero_raises(self):
        with pytest.raises(ValueError):
            DistCfg(grad_accum=0).validate()

    def test_grad_accum_negative_raises(self):
        with pytest.raises(ValueError):
            DistCfg(grad_accum=-1).validate()

    def test_serialization_roundtrip(self):
        cfg = DistCfg(strategy="fsdp", world_size=8, grad_accum=4)
        restored = DistCfg.from_dict(cfg.to_dict())
        assert restored == cfg

    def test_serialization_preserves_all_fields(self):
        cfg = DistCfg(strategy="deepspeed_zero3", world_size=16, backend="nccl")
        d = cfg.to_dict()
        assert d["strategy"] == "deepspeed_zero3"
        assert d["world_size"] == 16
        assert d["backend"] == "nccl"


class TestFSDPConfig:
    """Tests for FSDPConfig-like dataclass validation."""

    @pytest.mark.parametrize(
        "ss", ["FULL_SHARD", "SHARD_GRAD_OP", "NO_SHARD", "HYBRID_SHARD"]
    )
    def test_valid_sharding_strategy(self, ss):
        FSDPCfg(sharding_strategy=ss, wrap_module_classes=["Linear"]).validate()

    def test_invalid_sharding_strategy_raises(self):
        with pytest.raises(ValueError):
            FSDPCfg(
                sharding_strategy="FULL_SHARED",
                wrap_module_classes=["Linear"],
            ).validate()

    @pytest.mark.parametrize("policy", ["transformer_block", "size_based"])
    def test_valid_wrap_policy(self, policy):
        classes = ["Linear"] if policy == "transformer_block" else []
        FSDPCfg(wrap_policy=policy, wrap_module_classes=classes).validate()

    def test_invalid_wrap_policy_raises(self):
        with pytest.raises(ValueError):
            FSDPCfg(wrap_policy="invalid_policy", wrap_module_classes=[]).validate()

    def test_transformer_block_requires_module_classes(self):
        with pytest.raises(ValueError):
            FSDPCfg(
                wrap_policy="transformer_block",
                wrap_module_classes=[],
            ).validate()

    def test_size_based_without_classes_ok(self):
        FSDPCfg(wrap_policy="size_based", wrap_module_classes=[]).validate()

    @pytest.mark.parametrize("mp", ["bf16", "fp16", "none"])
    def test_valid_mixed_precision(self, mp):
        FSDPCfg(
            mixed_precision=mp,
            wrap_module_classes=["Linear"],
        ).validate()

    def test_invalid_mixed_precision_raises(self):
        with pytest.raises(ValueError):
            FSDPCfg(
                mixed_precision="fp8",
                wrap_module_classes=["Linear"],
            ).validate()

    @pytest.mark.parametrize("ac", ["off", "transformer_block"])
    def test_valid_activation_checkpointing(self, ac):
        FSDPCfg(
            activation_checkpointing=ac,
            wrap_module_classes=["Linear"],
        ).validate()

    def test_serialization_roundtrip(self):
        cfg = FSDPCfg(
            sharding_strategy="HYBRID_SHARD",
            wrap_module_classes=["TransformerBlock"],
            mixed_precision="fp16",
        )
        restored = FSDPCfg.from_dict(cfg.to_dict())
        assert restored == cfg


class TestDeepSpeedConfig:
    """Tests for DeepSpeedConfig-like dataclass validation."""

    @pytest.mark.parametrize("stage", [2, 3])
    def test_valid_zero_stage(self, stage):
        DSCfg(zero_stage=stage).validate()

    @pytest.mark.parametrize("stage", [0, 1, 4, -1])
    def test_invalid_zero_stage_raises(self, stage):
        with pytest.raises(ValueError):
            DSCfg(zero_stage=stage).validate()

    def test_offload_param_stage3_valid(self):
        DSCfg(zero_stage=3, offload_param="cpu").validate()

    def test_offload_param_stage2_raises(self):
        with pytest.raises(ValueError):
            DSCfg(zero_stage=2, offload_param="cpu").validate()

    def test_offload_param_nvme_stage2_raises(self):
        with pytest.raises(ValueError):
            DSCfg(zero_stage=2, offload_param="nvme").validate()

    def test_offload_optimizer_stage2_valid(self):
        DSCfg(zero_stage=2, offload_optimizer="cpu").validate()

    def test_offload_optimizer_stage3_valid(self):
        DSCfg(zero_stage=3, offload_optimizer="cpu").validate()

    def test_fp16_bf16_mutual_exclusion(self):
        with pytest.raises(ValueError):
            DSCfg(fp16=True, bf16=True).validate()

    def test_nvme_no_path_raises(self):
        with pytest.raises(ValueError):
            DSCfg(zero_stage=3, offload_param="nvme", nvme_path=None).validate()

    def test_nvme_with_path_valid(self):
        DSCfg(zero_stage=3, offload_param="nvme", nvme_path="/nvme0").validate()

    def test_negative_reduce_bucket_raises(self):
        with pytest.raises(ValueError):
            DSCfg(reduce_bucket_size=-1).validate()

    def test_serialization_roundtrip_stage2(self):
        cfg = DSCfg(zero_stage=2, offload_optimizer="cpu")
        restored = DSCfg.from_dict(cfg.to_dict())
        assert restored == cfg

    def test_serialization_roundtrip_stage3(self):
        cfg = DSCfg(
            zero_stage=3,
            offload_optimizer="cpu",
            offload_param="cpu",
            bf16=True,
        )
        restored = DSCfg.from_dict(cfg.to_dict())
        assert restored == cfg'''


# ---------------------------------------------------------------------------
# Router tests
# ---------------------------------------------------------------------------

def _router_tests() -> str:
    return '''\
# ===========================================================================
# Phase 2: Strategy Router Tests
# ===========================================================================


class TestStrategyRouter:
    """Tests for StrategyRouter wrapping order and dispatch."""

    @pytest.fixture
    def router_ddp(self):
        from strategy_router_template import RouterState, StrategyContext, StrategyRouter
        r = StrategyRouter(DistCfg(strategy="ddp"))
        r._state = RouterState.DISTRIBUTED_READY
        r._context = StrategyContext(
            strategy="ddp", rank=0, world_size=1,
            local_rank=0, device="cpu", is_distributed=False,
        )
        return r

    def test_wrap_before_setup_raises(self, small_model):
        from strategy_router_template import StrategyRouter
        r = StrategyRouter(DistCfg(strategy="ddp"))
        with pytest.raises(RuntimeError, match="setup_distributed"):
            r.wrap_model(small_model)

    def test_build_optimizer_before_wrap_raises(self, small_model):
        from strategy_router_template import RouterState, StrategyContext, StrategyRouter
        r = StrategyRouter(DistCfg(strategy="ddp"))
        r._state = RouterState.DISTRIBUTED_READY
        r._context = StrategyContext(strategy="ddp", world_size=1)
        with pytest.raises(RuntimeError, match="wrap_model"):
            r.build_optimizer(small_model, OptCfg())

    def test_load_before_wrap_raises(self, small_model):
        from strategy_router_template import RouterState, StrategyContext, StrategyRouter
        r = StrategyRouter(DistCfg(strategy="ddp"))
        r._state = RouterState.DISTRIBUTED_READY
        r._context = StrategyContext(strategy="ddp", world_size=1)
        with pytest.raises(RuntimeError):
            r.load_checkpoint(small_model, None, "/nonexistent")

    def test_ddp_path_context_strategy(self, router_ddp, small_model):
        with patch("torch.distributed.is_initialized", return_value=False):
            _, ctx = router_ddp.wrap_model(nn.Linear(4, 4))
        assert ctx.strategy == "ddp"

    def test_ddp_path_optimizer_type_adamw(self, router_ddp, small_model):
        with patch("torch.distributed.is_initialized", return_value=False):
            from strategy_router_template import RouterState
            wrapped, _ = router_ddp.wrap_model(nn.Linear(4, 4))
        opt = router_ddp.build_optimizer(wrapped, OptCfg(optimizer_type="AdamW"))
        assert isinstance(opt, torch.optim.AdamW)

    def test_ddp_path_optimizer_type_adam(self, router_ddp, small_model):
        with patch("torch.distributed.is_initialized", return_value=False):
            wrapped, _ = router_ddp.wrap_model(nn.Linear(4, 4))
        opt = router_ddp.build_optimizer(wrapped, OptCfg(optimizer_type="Adam"))
        assert isinstance(opt, torch.optim.Adam)

    def test_ddp_path_optimizer_type_sgd(self, router_ddp, small_model):
        with patch("torch.distributed.is_initialized", return_value=False):
            wrapped, _ = router_ddp.wrap_model(nn.Linear(4, 4))
        opt = router_ddp.build_optimizer(wrapped, OptCfg(optimizer_type="SGD"))
        assert isinstance(opt, torch.optim.SGD)

    def test_ddp_path_invalid_optimizer_raises(self, router_ddp):
        with patch("torch.distributed.is_initialized", return_value=False):
            wrapped, _ = router_ddp.wrap_model(nn.Linear(4, 4))
        with pytest.raises(ValueError):
            router_ddp.build_optimizer(wrapped, OptCfg(optimizer_type="RMSprop"))

    def test_fsdp_dispatch_calls_wrap_fsdp(self):
        from strategy_router_template import RouterState, StrategyContext, StrategyRouter
        r = StrategyRouter(DistCfg(strategy="fsdp"), fsdp_cfg=FSDPCfg(wrap_module_classes=["Linear"]))
        r._state = RouterState.DISTRIBUTED_READY
        r._context = StrategyContext(strategy="fsdp", world_size=4)
        with patch.object(r, "_wrap_fsdp", return_value=nn.Linear(4, 4)) as mock_wrap:
            r.wrap_model(nn.Linear(4, 4))
        mock_wrap.assert_called_once()

    def test_fsdp_requires_fsdp_cfg(self):
        from strategy_router_template import StrategyRouter
        with pytest.raises(ValueError):
            StrategyRouter(DistCfg(strategy="fsdp"))

    def test_deepspeed_zero2_requires_ds_cfg(self):
        from strategy_router_template import StrategyRouter
        with pytest.raises(ValueError):
            StrategyRouter(DistCfg(strategy="deepspeed_zero2"))

    def test_deepspeed_zero3_requires_ds_cfg(self):
        from strategy_router_template import StrategyRouter
        with pytest.raises(ValueError):
            StrategyRouter(DistCfg(strategy="deepspeed_zero3"))

    def test_deepspeed_dispatch_calls_wrap_deepspeed(self):
        from strategy_router_template import RouterState, StrategyContext, StrategyRouter
        r = StrategyRouter(
            DistCfg(strategy="deepspeed_zero3"),
            ds_cfg=DSCfg(zero_stage=3),
        )
        r._state = RouterState.DISTRIBUTED_READY
        r._context = StrategyContext(strategy="deepspeed_zero3", world_size=4)
        model = nn.Linear(4, 4)
        _, _ = r.wrap_model(model)
        with patch.object(r, "_wrap_deepspeed", return_value=(MagicMock(), MagicMock())) as mock_ds:
            r.build_optimizer(model, OptCfg())
        mock_ds.assert_called_once()

    def test_ddp_no_fsdp_cfg_required(self):
        from strategy_router_template import StrategyRouter
        r = StrategyRouter(DistCfg(strategy="ddp"))
        assert r is not None

    def test_optimizer_lr_propagated(self, router_ddp):
        with patch("torch.distributed.is_initialized", return_value=False):
            wrapped, _ = router_ddp.wrap_model(nn.Linear(4, 4))
        opt = router_ddp.build_optimizer(wrapped, OptCfg(lr=3e-5))
        assert opt.param_groups[0]["lr"] == pytest.approx(3e-5)

    def test_optimizer_weight_decay_propagated(self, router_ddp):
        with patch("torch.distributed.is_initialized", return_value=False):
            wrapped, _ = router_ddp.wrap_model(nn.Linear(4, 4))
        opt = router_ddp.build_optimizer(wrapped, OptCfg(weight_decay=0.05))
        assert opt.param_groups[0]["weight_decay"] == pytest.approx(0.05)'''


# ---------------------------------------------------------------------------
# FSDP wrapper tests
# ---------------------------------------------------------------------------

def _fsdp_wrapper_tests() -> str:
    return '''\
# ===========================================================================
# Phase 3: FSDP Wrapper Tests
# ===========================================================================


class TestFSDPWrapper:
    """Tests for FSDPWrapper configuration building."""

    @pytest.fixture
    def wrapper(self):
        from fsdp_wrapper_template import FSDPWrapper
        return FSDPWrapper()

    @pytest.fixture
    def fsdp_available(self):
        try:
            from torch.distributed.fsdp import FullyShardedDataParallel
            return True
        except ImportError:
            return False

    def test_bf16_mixed_precision(self, wrapper, fsdp_available):
        if not fsdp_available:
            pytest.skip("FSDP not available")
        from torch.distributed.fsdp import MixedPrecision
        policy = FSDPWrapper._build_mixed_precision("bf16", MixedPrecision)
        assert policy.param_dtype == torch.bfloat16
        assert policy.reduce_dtype == torch.bfloat16
        assert policy.buffer_dtype == torch.bfloat16

    def test_fp16_mixed_precision(self, wrapper, fsdp_available):
        if not fsdp_available:
            pytest.skip("FSDP not available")
        from torch.distributed.fsdp import MixedPrecision
        policy = FSDPWrapper._build_mixed_precision("fp16", MixedPrecision)
        assert policy.param_dtype == torch.float16

    def test_none_mixed_precision(self, wrapper, fsdp_available):
        if not fsdp_available:
            pytest.skip("FSDP not available")
        from torch.distributed.fsdp import MixedPrecision
        policy = FSDPWrapper._build_mixed_precision("none", MixedPrecision)
        assert policy is None

    def test_invalid_mixed_precision_raises(self, wrapper, fsdp_available):
        if not fsdp_available:
            pytest.skip("FSDP not available")
        from torch.distributed.fsdp import MixedPrecision
        with pytest.raises(ValueError):
            FSDPWrapper._build_mixed_precision("fp8", MixedPrecision)

    @pytest.mark.parametrize("ss_name", ["FULL_SHARD", "SHARD_GRAD_OP", "NO_SHARD", "HYBRID_SHARD"])
    def test_sharding_strategy_resolution(self, wrapper, fsdp_available, ss_name):
        if not fsdp_available:
            pytest.skip("FSDP not available")
        from torch.distributed.fsdp import ShardingStrategy
        resolved = FSDPWrapper._resolve_sharding_strategy(ss_name, ShardingStrategy)
        assert resolved is not None

    def test_invalid_sharding_strategy_raises(self, wrapper, fsdp_available):
        if not fsdp_available:
            pytest.skip("FSDP not available")
        from torch.distributed.fsdp import ShardingStrategy
        with pytest.raises(ValueError):
            FSDPWrapper._resolve_sharding_strategy("BAD_SHARD", ShardingStrategy)

    def test_class_resolution_by_simple_name(self, wrapper):
        from fsdp_wrapper_template import FSDPWrapper
        classes = wrapper._resolve_module_classes(["Linear"])
        assert nn.Linear in classes

    def test_class_resolution_by_dotted_name(self, wrapper):
        classes = wrapper._resolve_module_classes(["torch.nn.Linear"])
        assert nn.Linear in classes

    def test_class_resolution_nonexistent_raises(self, wrapper):
        with pytest.raises(ValueError):
            wrapper._resolve_module_classes(["NonExistentClass_XYZ_99"])

    def test_transformer_block_policy_requires_classes(self, wrapper, fsdp_available):
        if not fsdp_available:
            pytest.skip("FSDP not available")
        from torch.distributed.fsdp.wrap import ModuleWrapPolicy, size_based_auto_wrap_policy

        @dataclass
        class MockCfg:
            wrap_policy: str = "transformer_block"
            wrap_module_classes: list = None
            min_num_params: int = 100_000_000
            def __post_init__(self):
                if self.wrap_module_classes is None:
                    self.wrap_module_classes = []

        with pytest.raises(ValueError):
            wrapper._build_wrap_policy(
                MockCfg(wrap_policy="transformer_block", wrap_module_classes=[]),
                ModuleWrapPolicy, size_based_auto_wrap_policy,
            )

    def test_transformer_block_policy_with_classes(self, wrapper, fsdp_available):
        if not fsdp_available:
            pytest.skip("FSDP not available")
        from torch.distributed.fsdp.wrap import ModuleWrapPolicy, size_based_auto_wrap_policy

        @dataclass
        class MockCfg:
            wrap_policy: str = "transformer_block"
            wrap_module_classes: list = None
            min_num_params: int = 100_000_000
            def __post_init__(self):
                if self.wrap_module_classes is None:
                    self.wrap_module_classes = []

        policy = wrapper._build_wrap_policy(
            MockCfg(wrap_policy="transformer_block", wrap_module_classes=["Linear"]),
            ModuleWrapPolicy, size_based_auto_wrap_policy,
        )
        assert isinstance(policy, ModuleWrapPolicy)

    def test_size_based_policy_callable(self, wrapper, fsdp_available):
        if not fsdp_available:
            pytest.skip("FSDP not available")
        from torch.distributed.fsdp.wrap import ModuleWrapPolicy, size_based_auto_wrap_policy

        @dataclass
        class MockCfg:
            wrap_policy: str = "size_based"
            wrap_module_classes: list = None
            min_num_params: int = 100_000_000
            def __post_init__(self):
                if self.wrap_module_classes is None:
                    self.wrap_module_classes = []

        policy = wrapper._build_wrap_policy(
            MockCfg(wrap_policy="size_based"),
            ModuleWrapPolicy, size_based_auto_wrap_policy,
        )
        assert callable(policy)

    def test_full_state_dict_config_offload_to_cpu(self, fsdp_available):
        if not fsdp_available:
            pytest.skip("FSDP not available")
        from torch.distributed.fsdp import FullStateDictConfig
        cfg = FullStateDictConfig(offload_to_cpu=True, rank0_only=True)
        assert cfg.offload_to_cpu is True

    def test_full_state_dict_config_rank0_only(self, fsdp_available):
        if not fsdp_available:
            pytest.skip("FSDP not available")
        from torch.distributed.fsdp import FullStateDictConfig
        cfg = FullStateDictConfig(offload_to_cpu=True, rank0_only=True)
        assert cfg.rank0_only is True

    def test_save_full_state_dict_uses_correct_config(self):
        import inspect
        from fsdp_wrapper_template import FSDPWrapper
        src = inspect.getsource(FSDPWrapper.save_full_state_dict)
        assert "offload_to_cpu=True" in src
        assert "rank0_only=True" in src
        assert "FULL_STATE_DICT" in src

    def test_activation_checkpointing_applied_after_wrap(self):
        import inspect
        from fsdp_wrapper_template import FSDPWrapper
        src = inspect.getsource(FSDPWrapper.wrap)
        # activation checkpointing should be called AFTER FSDP construction
        fsdp_idx = src.find("FSDP(")
        ac_idx = src.find("apply_activation_checkpointing")
        assert fsdp_idx < ac_idx, (
            "apply_activation_checkpointing must be called after FSDP wrapping"
        )'''


# ---------------------------------------------------------------------------
# DeepSpeed wrapper tests
# ---------------------------------------------------------------------------

def _deepspeed_wrapper_tests() -> str:
    return '''\
# ===========================================================================
# Phase 4: DeepSpeed Wrapper Tests
# ===========================================================================


class TestDeepSpeedWrapper:
    """Tests for DeepSpeedWrapper JSON generation and field validation."""

    @pytest.fixture
    def wrapper(self):
        from deepspeed_wrapper_template import DeepSpeedWrapper
        return DeepSpeedWrapper()

    def test_stage2_json_stage_field(self, wrapper):
        cfg = DSCfg(zero_stage=2)
        d = wrapper.generate_config_json(cfg)
        assert d["zero_optimization"]["stage"] == 2

    def test_stage2_no_stage3_fields(self, wrapper):
        cfg = DSCfg(zero_stage=2)
        d = wrapper.generate_config_json(cfg)
        zo = d["zero_optimization"]
        assert "stage3_prefetch_bucket_size" not in zo
        assert "stage3_param_persistence_threshold" not in zo

    def test_stage2_no_offload_param(self, wrapper):
        cfg = DSCfg(zero_stage=2)
        d = wrapper.generate_config_json(cfg)
        assert "offload_param" not in d["zero_optimization"]

    def test_stage2_overlap_comm(self, wrapper):
        cfg = DSCfg(zero_stage=2, overlap_comm=True)
        d = wrapper.generate_config_json(cfg)
        assert d["zero_optimization"]["overlap_comm"] is True

    def test_stage2_contiguous_gradients(self, wrapper):
        cfg = DSCfg(zero_stage=2, contiguous_gradients=True)
        d = wrapper.generate_config_json(cfg)
        assert d["zero_optimization"]["contiguous_gradients"] is True

    def test_stage2_reduce_bucket_size(self, wrapper):
        cfg = DSCfg(zero_stage=2, reduce_bucket_size=200_000_000)
        d = wrapper.generate_config_json(cfg)
        assert d["zero_optimization"]["reduce_bucket_size"] == 200_000_000

    def test_stage2_allgather_bucket_size(self, wrapper):
        cfg = DSCfg(zero_stage=2, allgather_bucket_size=300_000_000)
        d = wrapper.generate_config_json(cfg)
        assert d["zero_optimization"]["allgather_bucket_size"] == 300_000_000

    def test_stage2_offload_optimizer_cpu(self, wrapper):
        cfg = DSCfg(zero_stage=2, offload_optimizer="cpu")
        d = wrapper.generate_config_json(cfg)
        assert d["zero_optimization"]["offload_optimizer"]["device"] == "cpu"
        assert d["zero_optimization"]["offload_optimizer"]["pin_memory"] is True

    def test_stage3_json_stage_field(self, wrapper):
        cfg = DSCfg(zero_stage=3)
        d = wrapper.generate_config_json(cfg)
        assert d["zero_optimization"]["stage"] == 3

    def test_stage3_has_prefetch_bucket(self, wrapper):
        cfg = DSCfg(zero_stage=3)
        d = wrapper.generate_config_json(cfg)
        assert "stage3_prefetch_bucket_size" in d["zero_optimization"]

    def test_stage3_has_persistence_threshold(self, wrapper):
        cfg = DSCfg(zero_stage=3)
        d = wrapper.generate_config_json(cfg)
        assert "stage3_param_persistence_threshold" in d["zero_optimization"]

    def test_stage3_gather_weights_on_save(self, wrapper):
        cfg = DSCfg(zero_stage=3)
        d = wrapper.generate_config_json(cfg)
        assert d["zero_optimization"]["stage3_gather_16bit_weights_on_model_save"] is True

    def test_stage3_offload_optimizer_cpu(self, wrapper):
        cfg = DSCfg(zero_stage=3, offload_optimizer="cpu")
        d = wrapper.generate_config_json(cfg)
        assert d["zero_optimization"]["offload_optimizer"]["device"] == "cpu"

    def test_stage3_offload_param_cpu(self, wrapper):
        cfg = DSCfg(zero_stage=3, offload_param="cpu")
        d = wrapper.generate_config_json(cfg)
        assert d["zero_optimization"]["offload_param"]["device"] == "cpu"

    def test_stage3_offload_param_nvme(self, wrapper):
        cfg = DSCfg(zero_stage=3, offload_param="nvme", nvme_path="/nvme0")
        d = wrapper.generate_config_json(cfg)
        zo = d["zero_optimization"]
        assert zo["offload_param"]["device"] == "nvme"
        assert zo["offload_param"]["nvme_path"] == "/nvme0"

    def test_offload_param_stage2_raises(self, wrapper):
        cfg = DSCfg(zero_stage=2, offload_param="cpu")
        with pytest.raises(ValueError):
            wrapper.generate_config_json(cfg)

    def test_fp16_bf16_conflict_raises(self, wrapper):
        cfg = DSCfg(fp16=True, bf16=True)
        with pytest.raises(ValueError):
            wrapper.generate_config_json(cfg)

    def test_bf16_config(self, wrapper):
        cfg = DSCfg(zero_stage=3, bf16=True)
        d = wrapper.generate_config_json(cfg)
        assert d.get("bf16", {}).get("enabled") is True
        assert "fp16" not in d

    def test_fp16_config(self, wrapper):
        cfg = DSCfg(zero_stage=3, fp16=True)
        d = wrapper.generate_config_json(cfg)
        assert d.get("fp16", {}).get("enabled") is True
        assert "bf16" not in d

    def test_gradient_clipping_propagated(self, wrapper):
        cfg = DSCfg(zero_stage=2, gradient_clipping=0.5)
        d = wrapper.generate_config_json(cfg)
        assert d["gradient_clipping"] == pytest.approx(0.5)

    def test_config_is_json_serializable(self, wrapper):
        cfg = DSCfg(zero_stage=3, bf16=True)
        d = wrapper.generate_config_json(cfg)
        json_str = json.dumps(d)
        reparsed = json.loads(json_str)
        assert reparsed["zero_optimization"]["stage"] == 3

    @pytest.mark.parametrize("stage", [2, 3])
    def test_reduce_scatter_always_true(self, wrapper, stage):
        cfg = DSCfg(zero_stage=stage)
        d = wrapper.generate_config_json(cfg)
        assert d["zero_optimization"]["reduce_scatter"] is True

    def test_validate_stage_fields_negative_bucket(self, wrapper):
        from deepspeed_wrapper_template import DeepSpeedWrapper
        cfg = DSCfg(zero_stage=2, reduce_bucket_size=-1)
        with pytest.raises(ValueError):
            DeepSpeedWrapper.validate_stage_fields(cfg)

    def test_nvme_offload_without_path_raises(self, wrapper):
        cfg = DSCfg(zero_stage=3, offload_param="nvme", nvme_path=None)
        with pytest.raises(ValueError):
            wrapper.generate_config_json(cfg)'''


# ---------------------------------------------------------------------------
# Checkpoint portability tests
# ---------------------------------------------------------------------------

def _checkpoint_portability_tests() -> str:
    return '''\
# ===========================================================================
# Phase 5: Checkpoint Portability Tests
# ===========================================================================


class TestCheckpointPortability:
    """Tests for checkpoint save/load and cross-strategy compatibility."""

    def test_fsdp_full_state_dict_source_uses_full_state_dict_type(self):
        import inspect
        from fsdp_wrapper_template import FSDPWrapper
        src = inspect.getsource(FSDPWrapper.save_full_state_dict)
        assert "StateDictType.FULL_STATE_DICT" in src

    def test_fsdp_load_full_state_dict_uses_full_state_dict_type(self):
        import inspect
        from fsdp_wrapper_template import FSDPWrapper
        src = inspect.getsource(FSDPWrapper.load_full_state_dict)
        assert "FULL_STATE_DICT" in src

    def test_fsdp_sharded_checkpoint_uses_dcp(self):
        import inspect
        from fsdp_wrapper_template import FSDPWrapper
        src = inspect.getsource(FSDPWrapper.save_sharded_checkpoint)
        assert "dist_cp" in src or "distributed.checkpoint" in src or "FileSystemWriter" in src

    def test_ds_export_calls_zero_to_fp32(self):
        import inspect
        from deepspeed_wrapper_template import DeepSpeedWrapper
        src = inspect.getsource(DeepSpeedWrapper.export_fp32_weights)
        assert "zero_to_fp32" in src

    def test_ds_export_subprocess_called(self, tmp_dir):
        from deepspeed_wrapper_template import DeepSpeedWrapper
        wrapper = DeepSpeedWrapper()
        fake_script = os.path.join(tmp_dir, "zero_to_fp32.py")
        # Create a dummy script
        with open(fake_script, "w") as f:
            f.write("import sys\\nprint('ok')\\n")

        ckpt_dir = tmp_dir
        out_path = os.path.join(tmp_dir, "fp32.pt")

        import subprocess
        with patch("subprocess.run") as mock_run:
            mock_run.return_value = MagicMock(returncode=0)
            wrapper.export_fp32_weights(ckpt_dir, out_path, zero_to_fp32_script=fake_script)
        mock_run.assert_called_once()
        call_args = mock_run.call_args[0][0]
        assert "zero_to_fp32.py" in call_args[-3] or fake_script in call_args

    def test_ddp_checkpoint_round_trip(self, tmp_dir):
        """DDP checkpoint save and reload preserves weights."""
        model = nn.Linear(8, 4)
        orig_weight = model.weight.data.clone()
        ckpt_path = os.path.join(tmp_dir, "ddp_ckpt.pt")

        torch.save({"model": model.state_dict(), "step": 42}, ckpt_path)

        model2 = nn.Linear(8, 4)
        ckpt = torch.load(ckpt_path, map_location="cpu")
        model2.load_state_dict(ckpt["model"])
        assert torch.allclose(model2.weight.data, orig_weight)
        assert ckpt["step"] == 42

    def test_full_state_dict_portable_across_non_fsdp_models(self, tmp_dir):
        """Simulate FSDP full state dict being loaded into unwrapped model."""
        model = nn.Linear(8, 4)
        orig_weight = model.weight.data.clone()
        ckpt_path = os.path.join(tmp_dir, "portable.pt")
        torch.save(model.state_dict(), ckpt_path)

        model2 = nn.Linear(8, 4)
        sd = torch.load(ckpt_path, map_location="cpu")
        model2.load_state_dict(sd)
        assert torch.allclose(model2.weight.data, orig_weight)

    def test_optimizer_state_not_in_portable_weights(self, tmp_dir):
        """Portable weights should not embed optimizer state."""
        model = nn.Linear(4, 4)
        ckpt_path = os.path.join(tmp_dir, "weights.pt")
        torch.save(model.state_dict(), ckpt_path)
        sd = torch.load(ckpt_path, map_location="cpu")
        # State dict should only have weight/bias, not optimizer keys
        assert all("weight" in k or "bias" in k for k in sd.keys())

    def test_checkpoint_missing_file_no_crash(self, tmp_dir):
        """Loading from a non-existent path should log and return None."""
        from strategy_router_template import RouterState, StrategyContext, StrategyRouter
        r = StrategyRouter(DistCfg(strategy="ddp"))
        r._state = RouterState.OPTIMIZER_BUILT
        r._context = StrategyContext(strategy="ddp", rank=0, world_size=1)
        model = nn.Linear(4, 4)
        step = r._load_ddp_checkpoint(
            model, None, os.path.join(tmp_dir, "nonexistent.pt")
        )
        assert step is None'''


# ---------------------------------------------------------------------------
# Scaling benchmark tests
# ---------------------------------------------------------------------------

def _scaling_benchmark_tests() -> str:
    return '''\
# ===========================================================================
# Phase 6: Scaling Benchmark Tests
# ===========================================================================


class TestScalingBenchmark:
    """Tests for ScalingBenchmark efficiency computation and metrics."""

    @pytest.fixture
    def bench(self):
        from scaling_benchmark_template import ScalingBenchmark
        return ScalingBenchmark()

    @pytest.fixture
    def make_result(self):
        from scaling_benchmark_template import BenchResult

        def _make(world_size, throughput, strategy="fsdp"):
            return BenchResult(
                strategy=strategy,
                world_size=world_size,
                throughput_p50=throughput,
                throughput_p90=throughput * 0.95,
                step_time_p50_ms=100.0,
                step_time_p90_ms=110.0,
                memory_peak_gb=20.0,
                measured_steps=50,
                warmup_steps=10,
                per_gpu_batch_size=4,
                seq_len=2048,
            )

        return _make

    def test_perfect_scaling_efficiency(self, bench, make_result):
        single = make_result(1, 10000.0)
        multi = make_result(4, 40000.0)
        report = bench.compute_efficiency(single, multi)
        assert report.scaling_efficiency == pytest.approx(1.0)

    def test_90pct_scaling_efficiency(self, bench, make_result):
        single = make_result(1, 10000.0)
        multi = make_result(4, 36000.0)
        report = bench.compute_efficiency(single, multi)
        assert report.scaling_efficiency == pytest.approx(0.9)

    def test_50pct_scaling_efficiency(self, bench, make_result):
        single = make_result(1, 10000.0)
        multi = make_result(4, 20000.0)
        report = bench.compute_efficiency(single, multi)
        assert report.scaling_efficiency == pytest.approx(0.5)

    def test_superlinear_scaling(self, bench, make_result):
        single = make_result(1, 10000.0)
        multi = make_result(4, 42000.0)
        report = bench.compute_efficiency(single, multi)
        assert report.scaling_efficiency > 1.0

    def test_world_size_1_efficiency(self, bench, make_result):
        single = make_result(1, 8000.0)
        multi = make_result(1, 8000.0)
        report = bench.compute_efficiency(single, multi)
        assert report.scaling_efficiency == pytest.approx(1.0)

    def test_zero_throughput_raises(self, bench, make_result):
        single = make_result(1, 0.0)
        multi = make_result(4, 30000.0)
        with pytest.raises((ValueError, ZeroDivisionError)):
            bench.compute_efficiency(single, multi)

    def test_world_size_8_efficiency(self, bench, make_result):
        single = make_result(1, 5000.0)
        multi = make_result(8, 38000.0)
        report = bench.compute_efficiency(single, multi)
        expected = 38000.0 / (8 * 5000.0)
        assert report.scaling_efficiency == pytest.approx(expected)

    @pytest.mark.parametrize("world_size,throughput_n,expected_eff", [
        (2, 18000.0, 0.9),
        (4, 32000.0, 0.8),
        (8, 60000.0, 0.75),
        (16, 120000.0, 0.75),
    ])
    def test_various_world_sizes(self, bench, make_result, world_size, throughput_n, expected_eff):
        single = make_result(1, 10000.0)
        multi = make_result(world_size, throughput_n)
        report = bench.compute_efficiency(single, multi)
        assert report.scaling_efficiency == pytest.approx(expected_eff)

    def test_report_strategy_preserved(self, bench, make_result):
        single = make_result(1, 10000.0, strategy="deepspeed_zero3")
        multi = make_result(4, 38000.0, strategy="deepspeed_zero3")
        report = bench.compute_efficiency(single, multi)
        assert report.strategy == "deepspeed_zero3"

    def test_report_world_size_preserved(self, bench, make_result):
        single = make_result(1, 10000.0)
        multi = make_result(8, 75000.0)
        report = bench.compute_efficiency(single, multi)
        assert report.world_size == 8

    def test_metrics_schema_all_required_fields(self, bench, make_result):
        from scaling_benchmark_template import REQUIRED_METRICS_FIELDS, validate_metrics_schema
        single = make_result(1, 10000.0)
        multi = make_result(4, 38000.0)
        report = bench.compute_efficiency(single, multi)
        data = report.to_dict()
        missing = validate_metrics_schema(data)
        assert len(missing) == 0, f"Missing fields: {missing}"

    def test_metrics_strategy_is_str(self, bench, make_result):
        single = make_result(1, 10000.0)
        multi = make_result(4, 38000.0)
        report = bench.compute_efficiency(single, multi)
        assert isinstance(report.to_dict()["strategy"], str)

    def test_metrics_world_size_is_int(self, bench, make_result):
        single = make_result(1, 10000.0)
        multi = make_result(4, 38000.0)
        report = bench.compute_efficiency(single, multi)
        assert isinstance(report.to_dict()["world_size"], int)

    def test_metrics_json_serializable(self, bench, make_result, tmp_dir):
        single = make_result(1, 10000.0)
        multi = make_result(4, 38000.0)
        report = bench.compute_efficiency(single, multi)
        path = os.path.join(tmp_dir, "metrics.json")
        bench.save_metrics(report, path)
        with open(path) as f:
            loaded = json.load(f)
        assert loaded["strategy"] == "fsdp"

    def test_synthetic_bench_returns_positive_throughput(self, bench):
        from scaling_benchmark_template import BenchConfig
        cfg = BenchConfig(
            strategy="ddp",
            world_size=1,
            per_gpu_batch_size=2,
            seq_len=32,
            warmup_steps=2,
            measured_steps=3,
        )
        result = bench.run_single(cfg)
        assert result.throughput_p50 > 0

    def test_synthetic_bench_measured_steps(self, bench):
        from scaling_benchmark_template import BenchConfig
        cfg = BenchConfig(
            strategy="ddp",
            world_size=1,
            per_gpu_batch_size=1,
            seq_len=16,
            warmup_steps=1,
            measured_steps=5,
        )
        result = bench.run_single(cfg)
        assert result.measured_steps == 5

    def test_format_report_contains_strategy(self, bench, make_result):
        single = make_result(1, 10000.0)
        multi = make_result(4, 38000.0)
        report = bench.compute_efficiency(single, multi)
        formatted = bench.format_report(report)
        assert "fsdp" in formatted

    def test_format_report_contains_percentage(self, bench, make_result):
        single = make_result(1, 10000.0)
        multi = make_result(4, 38000.0)
        report = bench.compute_efficiency(single, multi)
        formatted = bench.format_report(report)
        assert "%" in formatted

    def test_report_roundtrip(self, bench, make_result, tmp_dir):
        single = make_result(1, 10000.0)
        multi = make_result(4, 38000.0)
        report = bench.compute_efficiency(single, multi)
        path = os.path.join(tmp_dir, "metrics.json")
        bench.save_metrics(report, path)
        loaded_report = bench.load_metrics(path)
        assert loaded_report.strategy == report.strategy
        assert loaded_report.world_size == report.world_size
        assert loaded_report.scaling_efficiency == pytest.approx(report.scaling_efficiency)'''


# ---------------------------------------------------------------------------
# Edge case tests
# ---------------------------------------------------------------------------

def _edge_case_tests() -> str:
    return '''\
# ===========================================================================
# Edge Cases
# ===========================================================================


class TestEdgeCases:
    """Edge cases and boundary conditions."""

    def test_dist_config_world_size_negative_one_valid(self):
        cfg = DistCfg(world_size=-1)
        cfg.validate()

    def test_fsdp_min_num_params_zero_raises(self):
        cfg = FSDPCfg(
            wrap_policy="size_based",
            wrap_module_classes=[],
            min_num_params=0,
        )
        with pytest.raises(ValueError):
            cfg.validate()

    def test_ds_gradient_clipping_zero_raises(self):
        from deepspeed_wrapper_template import DeepSpeedWrapper
        cfg = DSCfg(gradient_clipping=-0.5)
        with pytest.raises(ValueError):
            cfg.validate()

    def test_bench_config_zero_measured_steps_raises(self):
        from scaling_benchmark_template import BenchConfig
        cfg = BenchConfig(measured_steps=0)
        with pytest.raises(ValueError):
            cfg.validate()

    def test_bench_config_negative_warmup_raises(self):
        from scaling_benchmark_template import BenchConfig
        cfg = BenchConfig(warmup_steps=-1)
        with pytest.raises(ValueError):
            cfg.validate()

    def test_bench_config_zero_seq_len_raises(self):
        from scaling_benchmark_template import BenchConfig
        cfg = BenchConfig(seq_len=0)
        with pytest.raises(ValueError):
            cfg.validate()

    def test_ds_stage3_max_live_params_field_present(self):
        from deepspeed_wrapper_template import DeepSpeedWrapper
        wrapper = DeepSpeedWrapper()
        cfg = DSCfg(zero_stage=3)
        d = wrapper.generate_config_json(cfg)
        assert "stage3_max_live_parameters" in d["zero_optimization"]

    def test_ds_stage3_max_reuse_distance_field_present(self):
        from deepspeed_wrapper_template import DeepSpeedWrapper
        wrapper = DeepSpeedWrapper()
        cfg = DSCfg(zero_stage=3)
        d = wrapper.generate_config_json(cfg)
        assert "stage3_max_reuse_distance" in d["zero_optimization"]

    def test_scaling_efficiency_formula_correctness(self):
        """Direct formula check: efficiency = throughput_n / (N * throughput_1)."""
        from scaling_benchmark_template import BenchResult, ScalingBenchmark
        bench = ScalingBenchmark()

        def make(ws, tp):
            return BenchResult(
                strategy="fsdp", world_size=ws,
                throughput_p50=tp, throughput_p90=tp * 0.95,
                step_time_p50_ms=100.0, step_time_p90_ms=110.0,
                memory_peak_gb=10.0, measured_steps=50, warmup_steps=10,
                per_gpu_batch_size=4, seq_len=512,
            )

        for N in [1, 2, 4, 8]:
            for tp_n in [9000.0, 10000.0, 11000.0]:
                tp_1 = 1000.0
                single = make(1, tp_1)
                multi = make(N, tp_n)
                report = bench.compute_efficiency(single, multi)
                expected = tp_n / (N * tp_1)
                assert report.scaling_efficiency == pytest.approx(expected), (
                    f"N={N}, tp_n={tp_n}: expected {expected}, got {report.scaling_efficiency}"
                )

    def test_validate_metrics_schema_detects_missing_fields(self):
        from scaling_benchmark_template import validate_metrics_schema
        # Missing all required fields
        missing = validate_metrics_schema({})
        assert len(missing) > 0

    def test_validate_metrics_schema_with_all_fields(self):
        from scaling_benchmark_template import validate_metrics_schema
        complete = {
            "strategy": "fsdp",
            "world_size": 4,
            "scaling_efficiency": 0.9,
            "memory_peak_gb": 20.0,
            "throughput_p50": 38000.0,
            "step_time_p50_ms": 100.0,
        }
        missing = validate_metrics_schema(complete)
        assert len(missing) == 0

    def test_router_state_initial(self):
        from strategy_router_template import RouterState, StrategyRouter
        r = StrategyRouter(DistCfg(strategy="ddp"))
        assert r.state == RouterState.INITIAL

    def test_router_context_none_before_setup(self):
        from strategy_router_template import StrategyRouter
        r = StrategyRouter(DistCfg(strategy="ddp"))
        assert r.context is None

    def test_fsdp_wrapper_find_class_none_for_unknown(self):
        from fsdp_wrapper_template import FSDPWrapper
        result = FSDPWrapper._find_class_by_name("__totally_nonexistent_class_xyz__")
        assert result is None'''


# ---------------------------------------------------------------------------
# Main CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate pytest test file for distributed-memory-scaling skill."
    )
    parser.add_argument(
        "-o", "--output",
        default=None,
        help="Output file path. If not specified, prints to stdout.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Count approximate test functions without writing.",
    )
    args = parser.parse_args()

    content = generate_test_file()

    if args.dry_run:
        count = content.count("def test_")
        print(f"Generated {count} test functions.")
        return

    if args.output:
        output_path = args.output
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
            f.write("\n")
        count = content.count("def test_")
        print(f"Generated {count} test functions -> {output_path}")
    else:
        print(content)


if __name__ == "__main__":
    main()
