#!/usr/bin/env python3
"""
gen_codec_tests.py -- Generate comprehensive pytest suite for spike codec & losses.

Generates tests/test_codec_losses.py with exhaustive coverage of:
  - Spike encoding round-trips (rate, latency/TTFS, population, delta)
  - SpikeBatch contract validation
  - Axis convention enforcement
  - Spike decoding (rate, first-spike, population)
  - ProbSpikes loss and regularization terms
  - ISI regularization (conv1d vectorized)
  - Loss composition via SNNLossComposer
  - AMP hardening for all components
  - End-to-end gradient flow
  - Integration pipelines

Usage:
    python gen_codec_tests.py                        # Generate to default path
    python gen_codec_tests.py --output path/to.py    # Custom output
    python gen_codec_tests.py --dry-run               # Print to stdout

Generated test structure:
    TestRateCodingRoundTrip      -- rate encoding invariants & statistics
    TestLatencyTTFSRoundTrip     -- TTFS monotonicity and jitter
    TestPopulationCodingRoundTrip-- population encode/decode fidelity
    TestDeltaModulation          -- change detection, ON/OFF channels
    TestSpikeBatchContract       -- SpikeBatch dataclass invariants
    TestAxisConvention           -- (B, T, ...) enforcement
    TestRateDecoder              -- rate/spike-count decoding
    TestFirstSpikeDecoder        -- first-spike (latency) decoding
    TestPopulationDecoder        -- population classification & regression
    TestProbSpikesLoss           -- spike-count cross-entropy
    TestSpikeRateRegularization  -- target-rate & range penalties
    TestTemporalConsistency      -- flicker / smoothness penalties
    TestISIRegularization        -- conv1d refractory penalty
    TestLossComposer             -- SNNLossComposer composition
    TestAMPHardening             -- mixed-precision safety
    TestGradientFlow             -- end-to-end gradient presence
    TestIntegration              -- multi-step training pipelines
"""

from __future__ import annotations

import argparse
import ast
import os
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from typing import Tuple


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate comprehensive pytest suite for spike codec and losses."
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help=(
            "Destination file path for the generated test file. "
            "Defaults to <repo_root>/tests/test_codec_losses.py"
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated file to stdout instead of writing.",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _default_output_path() -> Path:
    """Return <repo_root>/tests/test_codec_losses.py relative to this script."""
    # scripts/ -> spike-codec-losses/ -> skills/ -> brain-ai-dev/ -> human-brain/
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent.parent.parent.parent
    tests_dir = repo_root / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    return tests_dir / "test_codec_losses.py"


# ---------------------------------------------------------------------------
# Template sections -- each returns a string fragment of the generated file
# ---------------------------------------------------------------------------

def _section_header() -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return f'''\
# ============================================================================
# test_codec_losses.py
# AUTO-GENERATED by gen_codec_tests.py -- do not edit by hand.
# Re-generate with:
#     python brain-ai-dev/skills/spike-codec-losses/scripts/gen_codec_tests.py
#
# Generated: {ts}
# ============================================================================
"""
Comprehensive pytest suite for the spike encoding, decoding, and loss pack.

Coverage:
  - Spike encoders: rate, latency/TTFS, population, delta
  - SpikeBatch contract and axis conventions
  - Spike decoders: rate, first-spike, population
  - Loss terms: ProbSpikes, spike-rate, temporal consistency, ISI
  - Loss composition via SNNLossComposer
  - AMP hardening for all components
  - End-to-end gradient flow and integration pipelines

Run:
    pytest tests/test_codec_losses.py -v --tb=short
    pytest tests/test_codec_losses.py -v -k "not AMP"   # skip CUDA tests
"""
'''


def _section_imports() -> str:
    return '''\
from __future__ import annotations

import math
import warnings
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Tuple

import pytest
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

HAS_CUDA = torch.cuda.is_available()
DEFAULT_B = 8       # batch size
DEFAULT_T = 25      # timesteps
DEFAULT_N = 10      # neurons / classes
DEFAULT_SEED = 42

# ---------------------------------------------------------------------------
# Attempt to import the target API (new codec modules).
# If they do not exist yet (pre-implementation CI), fall back to stubs that
# replicate the minimal contract so tests can be collected without ImportError.
# ---------------------------------------------------------------------------

_USING_STUBS = False

try:
    from brain_ai.core.encoding import (
        RateEncoder,
        TemporalEncoder,
        LatencyEncoder,
        PopulationEncoder,
        DeltaEncoder,
        SpikeDecoder,
    )
    from brain_ai.core.losses import (
        prob_spikes_loss,
        spike_rate_regularization,
        spike_rate_range_regularization,
        temporal_consistency_loss,
        inter_spike_interval_loss,
        membrane_potential_regularization,
        SNNLoss,
    )
    from brain_ai.core.neurons import LIFNeuron, get_surrogate
except ImportError:
    _USING_STUBS = True


# ---------------------------------------------------------------------------
# New-API imports -- these are the target modules this test suite validates.
# If they are not yet implemented, we define lightweight stubs below so the
# test file is always parseable and collectable by pytest.
# ---------------------------------------------------------------------------

# -- SpikeBatch ---------------------------------------------------------

try:
    from brain_ai.core.spike_batch import SpikeBatch
except ImportError:
    @dataclass
    class SpikeBatch:
        """Stub SpikeBatch for CI before module exists."""
        spikes: Tensor          # (B, T, N) binary
        mask: Optional[Tensor] = None  # (B, T)

        @staticmethod
        def from_dense(spikes: Tensor, mask: Optional[Tensor] = None) -> "SpikeBatch":
            return SpikeBatch(spikes=spikes, mask=mask)

        def is_binary(self) -> bool:
            unique = self.spikes.unique()
            return all(v in (0.0, 1.0) for v in unique.tolist())

        @property
        def time_steps(self) -> int:
            return self.spikes.shape[1]

        def to(self, device):
            s = self.spikes.to(device)
            m = self.mask.to(device) if self.mask is not None else None
            return SpikeBatch(spikes=s, mask=m)

        def __getitem__(self, idx):
            s = self.spikes[idx]
            m = self.mask[idx] if self.mask is not None else None
            if s.dim() == 2:
                s = s.unsqueeze(0)
                if m is not None:
                    m = m.unsqueeze(0)
            return SpikeBatch(spikes=s, mask=m)


# -- DecoderOutput -------------------------------------------------------

try:
    from brain_ai.core.decoders import DecoderOutput
except ImportError:
    @dataclass
    class DecoderOutput:
        """Stub DecoderOutput for CI before module exists."""
        logits_proxy: Tensor       # (B, N) or (B, G)
        prediction: Tensor         # (B,) int64
        confidence: Tensor         # (B,) float
        aux: Dict[str, Any] = field(default_factory=dict)


# -- Decoders ------------------------------------------------------------

try:
    from brain_ai.core.decoders import (
        rate_decode,
        first_spike_decode,
        population_decode_classify,
        population_decode_regression,
    )
except ImportError:
    def rate_decode(
        spikes: Tensor,
        temperature: float = 1.0,
        eps: float = 1e-7,
        normalize_by_T: bool = False,
    ) -> DecoderOutput:
        B, T, N = spikes.shape
        counts = spikes.float().sum(dim=1)
        if normalize_by_T:
            rate = counts / T
            logits_proxy = rate / temperature
        else:
            logits_proxy = counts / temperature
        prediction = counts.argmax(dim=-1)
        probs = torch.softmax(logits_proxy.float(), dim=-1)
        top2 = probs.topk(min(2, N), dim=-1).values
        margin = (top2[:, 0] - top2[:, 1]).clamp(min=0.0) if N >= 2 else top2[:, 0]
        confidence = margin
        return DecoderOutput(
            logits_proxy=logits_proxy,
            prediction=prediction,
            confidence=confidence,
            aux={"raw_counts": counts.detach(), "margin": margin.detach()},
        )

    def first_spike_decode(
        spikes: Tensor,
        temperature: float = 1.0,
        eps: float = 1e-7,
    ) -> DecoderOutput:
        B, T, N = spikes.shape
        cumsum = spikes.cumsum(dim=1)
        has_spiked = (cumsum >= 1.0)
        t_first = has_spiked.float().argmax(dim=1)
        ever_spiked = (cumsum[:, -1, :] > 0)
        t_first = torch.where(ever_spiked, t_first, torch.full_like(t_first, T))
        logits_proxy = (-t_first.float() / T) / temperature
        prediction = t_first.argmin(dim=-1)
        sorted_times = t_first.sort(dim=-1).values
        if N >= 2:
            time_margin = (sorted_times[:, 1] - sorted_times[:, 0]).float() / T
        else:
            time_margin = torch.zeros(B, device=spikes.device)
        confidence = time_margin.clamp(min=0.0, max=1.0)
        return DecoderOutput(
            logits_proxy=logits_proxy,
            prediction=prediction,
            confidence=confidence,
            aux={
                "first_spike_times": t_first.detach(),
                "ever_spiked": ever_spiked.detach(),
            },
        )

    def population_decode_classify(
        spikes: Tensor,
        population_map: Dict[int, List[int]],
        temperature: float = 1.0,
        eps: float = 1e-7,
    ) -> DecoderOutput:
        B, T, N = spikes.shape
        num_groups = len(population_map)
        counts = spikes.float().sum(dim=1)
        group_counts = torch.zeros(
            B, num_groups, device=spikes.device, dtype=torch.float32,
        )
        for g, indices in population_map.items():
            group_counts[:, g] = counts[:, indices].sum(dim=-1)
        logits_proxy = group_counts / temperature
        prediction = group_counts.argmax(dim=-1)
        probs = torch.softmax(logits_proxy, dim=-1)
        top2 = probs.topk(min(2, num_groups), dim=-1).values
        if num_groups >= 2:
            margin = (top2[:, 0] - top2[:, 1]).clamp(min=0.0)
        else:
            margin = top2[:, 0]
        confidence = margin
        return DecoderOutput(
            logits_proxy=logits_proxy,
            prediction=prediction,
            confidence=confidence,
            aux={"raw_counts": counts.detach()},
        )

    def population_decode_regression(
        spikes: Tensor,
        population_map: Dict[int, List[int]],
        centers: Tensor,
        temperature: float = 1.0,
        eps: float = 1e-7,
    ) -> DecoderOutput:
        B, T, N = spikes.shape
        num_groups = len(population_map)
        counts = spikes.float().sum(dim=1)
        group_counts = torch.zeros(
            B, num_groups, device=spikes.device, dtype=torch.float32,
        )
        for g, indices in population_map.items():
            group_counts[:, g] = counts[:, indices].sum(dim=-1)
        weights = torch.softmax(group_counts / temperature, dim=-1)
        predicted_value = (weights * centers.unsqueeze(0)).sum(dim=-1)
        logits_proxy = group_counts / temperature
        prediction = group_counts.argmax(dim=-1)
        confidence = weights.max(dim=-1).values
        return DecoderOutput(
            logits_proxy=logits_proxy,
            prediction=prediction,
            confidence=confidence,
            aux={
                "predicted_value": predicted_value.detach(),
                "group_weights": weights.detach(),
            },
        )


# -- New loss terms (LossTerm-based) ------------------------------------

try:
    from brain_ai.core.losses import (
        LossTerm,
        ProbSpikesLoss,
        SpikeRateRegularization,
        TemporalConsistencyLoss,
        ISIRegularization,
        MembraneRegularization,
        SNNLossComposer,
    )
except ImportError:
    class LossTerm(nn.Module):
        """Stub base class."""
        def forward(self, spikes, membrane, targets, **kwargs):
            raise NotImplementedError

    class ProbSpikesLoss(LossTerm):
        def __init__(self, temperature=1.0, eps=1e-7, mode="softmax"):
            super().__init__()
            self.temperature = temperature
            self.eps = eps
            self.mode = mode

        def forward(self, spikes, membrane, targets, **kwargs):
            counts = spikes.float().sum(dim=1)
            if self.mode == "softmax":
                scaled = counts / self.temperature
                log_probs = F.log_softmax(scaled, dim=-1)
                loss = F.nll_loss(log_probs, targets)
            elif self.mode == "normalize":
                total = counts.sum(dim=-1, keepdim=True)
                probs = counts / (total + self.eps)
                probs = probs.clamp(min=self.eps)
                log_probs = probs.log()
                loss = F.nll_loss(log_probs, targets)
            else:
                loss = torch.tensor(0.0, device=spikes.device)
            with torch.no_grad():
                diag = {
                    "mean_count": counts.mean().item(),
                    "max_count": counts.max().item(),
                    "accuracy": (
                        (counts.argmax(dim=-1) == targets).float().mean().item()
                    ),
                }
            return loss, diag

    class SpikeRateRegularization(LossTerm):
        def __init__(
            self,
            target_rate=0.1,
            min_rate=0.01,
            max_rate=0.3,
            rate_type="l2",
            use_range_penalty=True,
        ):
            super().__init__()
            self.target_rate = target_rate
            self.min_rate = min_rate
            self.max_rate = max_rate
            self.rate_type = rate_type
            self.use_range_penalty = use_range_penalty

        def forward(self, spikes, membrane, targets, **kwargs):
            rates = spikes.float().mean(dim=1)
            if self.rate_type == "l2":
                target_loss = ((rates - self.target_rate) ** 2).mean()
            elif self.rate_type == "l1":
                target_loss = (rates - self.target_rate).abs().mean()
            else:
                target_loss = torch.tensor(0.0, device=spikes.device)
            loss = target_loss
            if self.use_range_penalty:
                below = F.relu(self.min_rate - rates)
                above = F.relu(rates - self.max_rate)
                range_loss = (below + above).mean()
                loss = loss + range_loss
            with torch.no_grad():
                diag = {
                    "mean_rate": rates.mean().item(),
                    "max_rate": rates.max().item(),
                    "min_rate": rates.min().item(),
                }
            return loss, diag

    class TemporalConsistencyLoss(LossTerm):
        def __init__(self, window_size=5, penalty_type="l2"):
            super().__init__()
            self.window_size = window_size
            self.penalty_type = penalty_type

        def forward(self, spikes, membrane, targets, **kwargs):
            B, T, N = spikes.shape
            if self.penalty_type in ("l1", "l2"):
                rates = spikes.float()
                diffs = rates[:, 1:, :] - rates[:, :-1, :]
                if self.penalty_type == "l1":
                    loss = diffs.abs().mean()
                else:
                    loss = (diffs ** 2).mean()
            elif self.penalty_type == "variance":
                if T < self.window_size * 2:
                    zero = torch.tensor(0.0, device=spikes.device)
                    return zero, {"skipped": 1.0}
                n_windows = T // self.window_size
                trimmed = spikes[:, :n_windows * self.window_size, :].float()
                windowed = trimmed.view(B, n_windows, self.window_size, N)
                window_means = windowed.mean(dim=2)
                loss = window_means.var(dim=1).mean()
            else:
                loss = torch.tensor(0.0, device=spikes.device)
            with torch.no_grad():
                rates_f = spikes.float()
                rate_diffs = rates_f[:, 1:, :] - rates_f[:, :-1, :]
                diag = {
                    "mean_temporal_variance": rate_diffs.var().item(),
                }
            return loss, diag

    class ISIRegularization(LossTerm):
        def __init__(
            self,
            refractory_window=5,
            kernel_type="exponential",
            penalty_weight=1.0,
        ):
            super().__init__()
            self.refractory_window = refractory_window
            self.kernel_type = kernel_type
            self.penalty_weight = penalty_weight
            k = torch.arange(
                1, refractory_window + 1, dtype=torch.float32,
            )
            if kernel_type == "exponential":
                tau = refractory_window / 3.0
                kernel = torch.exp(-k / tau)
            elif kernel_type == "rectangular":
                kernel = torch.ones_like(k)
            else:
                kernel = torch.ones_like(k)
            self.register_buffer(
                "kernel", kernel.flip(0).unsqueeze(0).unsqueeze(0),
            )

        def forward(self, spikes, membrane, targets, **kwargs):
            B, T, N = spikes.shape
            s = spikes.float().permute(0, 2, 1).reshape(B * N, 1, T)
            kernel_fp32 = self.kernel
            padded = F.pad(s, (self.refractory_window, 0))
            refractory_signal = F.conv1d(padded, kernel_fp32)
            penalty = (s * refractory_signal).mean()
            loss = self.penalty_weight * penalty
            with torch.no_grad():
                diag = {"mean_refractory_penalty": penalty.item()}
            return loss, diag

    class MembraneRegularization(LossTerm):
        def __init__(self, max_membrane=1.5):
            super().__init__()
            self.max_membrane = max_membrane

        def forward(self, spikes, membrane, targets, **kwargs):
            if membrane is None:
                zero = torch.tensor(0.0, device=spikes.device)
                return zero, {"skipped": 1.0}
            excess = F.relu(membrane.float().abs() - self.max_membrane)
            loss = (excess ** 2).mean()
            with torch.no_grad():
                diag = {
                    "mean_membrane": membrane.float().mean().item(),
                    "max_membrane": membrane.float().abs().max().item(),
                }
            return loss, diag

    class SNNLossComposer(nn.Module):
        def __init__(self, terms: dict):
            super().__init__()
            self.terms = nn.ModuleDict(
                {k: v[0] for k, v in terms.items()},
            )
            self.weights = {k: v[1] for k, v in terms.items()}

        def forward(self, spikes, membrane, targets, **kwargs):
            total = torch.tensor(
                0.0, device=spikes.device, dtype=torch.float32,
            )
            components = {}
            diagnostics = {}
            for name, term in self.terms.items():
                w = self.weights[name]
                if w == 0.0:
                    continue
                raw_loss, diag = term(spikes, membrane, targets, **kwargs)
                weighted = w * raw_loss
                total = total + weighted
                components[f"loss/{name}_raw"] = raw_loss.item()
                components[f"loss/{name}_weighted"] = weighted.item()
                diagnostics.update(
                    {f"diag/{name}/{k}": v for k, v in diag.items()},
                )
            components["loss/total"] = total.item()
            return total, {**components, **diagnostics}


# -- Axis helpers --------------------------------------------------------

try:
    from brain_ai.core.spike_batch import (
        TIME_DIM,
        BATCH_DIM,
        batch_to_time_first,
        time_to_batch_first,
    )
except ImportError:
    TIME_DIM = 1
    BATCH_DIM = 0

    def batch_to_time_first(x: Tensor) -> Tensor:
        """(B, T, ...) -> (T, B, ...)"""
        return x.permute(1, 0, *range(2, x.dim()))

    def time_to_batch_first(x: Tensor) -> Tensor:
        """(T, B, ...) -> (B, T, ...)"""
        return x.permute(1, 0, *range(2, x.dim()))
'''


def _section_fixtures() -> str:
    return '''\
# ============================================================================
# Fixtures
# ============================================================================

@pytest.fixture
def sample_input():
    """Random input tensor in [0, 1], shape (B, N)."""
    torch.manual_seed(DEFAULT_SEED)
    return torch.rand(DEFAULT_B, DEFAULT_N)


@pytest.fixture
def sample_spikes():
    """Random binary spikes, shape (B, T, N)."""
    torch.manual_seed(DEFAULT_SEED)
    return (torch.rand(DEFAULT_B, DEFAULT_T, DEFAULT_N) > 0.7).float()


@pytest.fixture
def sample_membrane():
    """Random membrane potentials, shape (B, T, N)."""
    torch.manual_seed(DEFAULT_SEED)
    return torch.randn(DEFAULT_B, DEFAULT_T, DEFAULT_N) * 0.5


@pytest.fixture
def snn_layer():
    """
    Simple LIF-based SNN layer for gradient tests.
    Returns a (nn.Linear, neuron) pair.
    """
    if _USING_STUBS:
        linear = nn.Linear(DEFAULT_N, DEFAULT_N)

        class _StubLIF(nn.Module):
            def __init__(self):
                super().__init__()
                self.threshold = 1.0
                self.beta = 0.9
                self.mem = None

            def reset_mem(self):
                self.mem = None

            def forward(self, x):
                if self.mem is None:
                    self.mem = torch.zeros_like(x)
                self.mem = self.beta * self.mem + x
                spk = ((self.mem - self.threshold) > 0).float()
                # Straight-through estimator for gradient flow
                spk = spk + (self.mem - self.mem.detach())
                self.mem = self.mem * (1.0 - spk.detach())
                return spk, self.mem

        return linear, _StubLIF()
    else:
        linear = nn.Linear(DEFAULT_N, DEFAULT_N)
        neuron = LIFNeuron(
            beta=0.9, threshold=1.0, surrogate="atan",
        )
        return linear, neuron


@pytest.fixture
def loss_config():
    """Default loss configuration dict."""
    return {
        "prob_spikes": {"temperature": 1.0, "mode": "softmax"},
        "spike_rate": {
            "target_rate": 0.1, "min_rate": 0.01, "max_rate": 0.3,
        },
        "temporal": {"window_size": 5, "penalty_type": "l2"},
        "isi": {"refractory_window": 5, "kernel_type": "exponential"},
    }
'''


def _section_test_rate_coding() -> str:
    return '''\
# ============================================================================
# TestRateCodingRoundTrip
# ============================================================================

class TestRateCodingRoundTrip:
    """
    Rate coding: higher input values produce more spikes.
    Tests ordering, determinism, reproducibility, and statistical distribution.
    """

    @pytest.mark.parametrize("T", [10, 25, 50, 100])
    def test_spike_count_ordering(self, T: int):
        """
        x=[0.1, 0.3, 0.9] encoded with rate coding for T steps:
        count(0.1) < count(0.3) < count(0.9) on average.
        """
        N_TRIALS = 20
        values = torch.tensor([0.1, 0.3, 0.9])
        accum = torch.zeros(3)

        for trial in range(N_TRIALS):
            torch.manual_seed(trial)
            encoder = RateEncoder(
                num_steps=T, method="bernoulli", gain=1.0,
            )
            x = values.unsqueeze(0)  # (1, 3)
            spikes = encoder(x)      # (T, 1, 3)
            counts = spikes.sum(dim=0).squeeze(0)  # (3,)
            accum += counts

        avg_counts = accum / N_TRIALS
        assert avg_counts[0] < avg_counts[1], (
            f"T={T}: count(0.1)={avg_counts[0]:.1f} >= "
            f"count(0.3)={avg_counts[1]:.1f}"
        )
        assert avg_counts[1] < avg_counts[2], (
            f"T={T}: count(0.3)={avg_counts[1]:.1f} >= "
            f"count(0.9)={avg_counts[2]:.1f}"
        )

    def test_deterministic_eval(self):
        """
        Deterministic encoder in eval mode: same input produces
        identical spikes.
        """
        encoder = RateEncoder(
            num_steps=25, method="deterministic", gain=1.0,
        )
        encoder.eval()
        x = torch.tensor([[0.3, 0.6, 0.9]])

        spikes_a = encoder(x)
        spikes_b = encoder(x)

        assert torch.equal(spikes_a, spikes_b), (
            "Deterministic encoder produced different outputs "
            "for same input in eval mode"
        )

    @pytest.mark.parametrize("T", [10, 25, 50, 100])
    def test_generator_reproducibility(self, T: int):
        """Same seed produces identical spike trains."""
        encoder = RateEncoder(
            num_steps=T, method="bernoulli", gain=1.0,
        )
        x = torch.rand(2, 5)

        torch.manual_seed(123)
        spikes_a = encoder(x)

        torch.manual_seed(123)
        spikes_b = encoder(x)

        assert torch.equal(spikes_a, spikes_b), (
            f"T={T}: same seed produced different spike trains"
        )

    @pytest.mark.parametrize("T", [10, 25, 50, 100])
    @pytest.mark.parametrize(
        "normalization", ["none", "minmax", "sigmoid"],
    )
    def test_statistical_distribution(
        self, T: int, normalization: str,
    ):
        """
        Spike counts approximate Binomial(T, p):
        mean count should be within 25% of T*p for p=0.5.
        """
        p = 0.5
        N_TRIALS = 50
        counts = []

        for trial in range(N_TRIALS):
            torch.manual_seed(trial)
            if normalization == "sigmoid":
                x = torch.sigmoid(torch.tensor([[0.0]]))
            else:
                x = torch.tensor([[p]])

            encoder = RateEncoder(
                num_steps=T, method="bernoulli", gain=1.0,
            )
            spikes = encoder(x)
            counts.append(spikes.sum().item())

        mean_count = sum(counts) / len(counts)
        expected = T * p
        tolerance = 0.25 * expected + 1.0
        assert abs(mean_count - expected) < tolerance, (
            f"T={T}, norm={normalization}: "
            f"mean_count={mean_count:.1f}, "
            f"expected={expected:.1f}, "
            f"tolerance={tolerance:.1f}"
        )

    def test_spikes_are_binary(self):
        """All values in rate-coded spike trains must be 0.0 or 1.0."""
        torch.manual_seed(0)
        encoder = RateEncoder(
            num_steps=25, method="bernoulli", gain=1.0,
        )
        x = torch.rand(4, 10)
        spikes = encoder(x)

        unique_vals = spikes.unique().tolist()
        non_binary = [
            v for v in unique_vals
            if abs(v) > 1e-6 and abs(v - 1.0) > 1e-6
        ]
        assert len(non_binary) == 0, (
            f"Non-binary spike values: {non_binary}"
        )

    def test_output_shape(self):
        """Rate encoder output shape must be (T, B, *features)."""
        encoder = RateEncoder(
            num_steps=25, method="bernoulli", gain=1.0,
        )
        x = torch.rand(4, 10)
        spikes = encoder(x)
        assert spikes.shape == (25, 4, 10), (
            f"Expected (25, 4, 10), got {spikes.shape}"
        )
'''


def _section_test_latency_ttfs() -> str:
    return '''\
# ============================================================================
# TestLatencyTTFSRoundTrip
# ============================================================================

class TestLatencyTTFSRoundTrip:
    """
    TTFS (Time-to-First-Spike) coding: larger x fires earlier.
    Tests monotonicity, single-spike constraint, no-spike handling,
    and jitter.
    """

    @pytest.mark.parametrize(
        "mapping", ["linear", "exponential", "log"],
    )
    def test_monotonic_spike_times(self, mapping: str):
        """
        For x_low < x_high, the first spike time of x_high
        must be <= x_low.
        """
        if mapping == "linear":
            encoder = LatencyEncoder(num_steps=50, normalize=False)
        elif mapping == "exponential":
            encoder = TemporalEncoder(num_steps=50, tau=5.0)
        elif mapping == "log":
            encoder = TemporalEncoder(num_steps=50, tau=3.0)
        else:
            encoder = LatencyEncoder(num_steps=50, normalize=False)

        x_low = torch.tensor([[0.2]])
        x_high = torch.tensor([[0.8]])

        spikes_low = encoder(x_low)    # (T, 1, 1)
        spikes_high = encoder(x_high)

        def first_spike_time(spikes_t):
            """Find first nonzero timestep."""
            for t in range(spikes_t.shape[0]):
                if spikes_t[t, 0, 0].item() > 0:
                    return t
            return spikes_t.shape[0]

        t_low = first_spike_time(spikes_low)
        t_high = first_spike_time(spikes_high)

        assert t_high <= t_low, (
            f"mapping={mapping}: x_high=0.8 spiked at t={t_high}, "
            f"x_low=0.2 spiked at t={t_low}. "
            f"Expected t_high <= t_low."
        )

    @pytest.mark.parametrize(
        "mapping", ["linear", "exponential", "log"],
    )
    def test_ttfs_single_spike(self, mapping: str):
        """
        TTFS encoder should produce at most 1 spike per neuron.
        """
        if mapping == "linear":
            encoder = LatencyEncoder(num_steps=50, normalize=False)
        else:
            encoder = TemporalEncoder(num_steps=50, tau=5.0)

        x = torch.tensor([[0.5]])
        spikes = encoder(x)  # (T, 1, 1)

        spike_count = spikes.sum(dim=0).squeeze()
        assert spike_count.item() <= 1.0, (
            f"mapping={mapping}: expected at most 1 spike, "
            f"got {spike_count.item()}"
        )

    def test_no_spike_allowed(self):
        """
        Very small x (below effective threshold) should produce
        no spike or spike at the latest timestep.
        """
        encoder = LatencyEncoder(num_steps=25, normalize=False)
        x = torch.tensor([[0.001]])
        spikes = encoder(x)

        total = spikes.sum().item()
        assert total <= 1.0, (
            f"Expected 0 or 1 spike for tiny input, got {total}"
        )

    def test_jitter_training_only(self):
        """
        Eval mode should be deterministic (no jitter).
        """
        encoder = LatencyEncoder(num_steps=25, normalize=False)
        x = torch.tensor([[0.5]])

        encoder.eval()
        spikes_eval_a = encoder(x)
        spikes_eval_b = encoder(x)
        assert torch.equal(spikes_eval_a, spikes_eval_b), (
            "Eval mode should produce deterministic spikes"
        )

    def test_output_shape(self):
        """Temporal encoder output must be (T, B, features)."""
        encoder = TemporalEncoder(num_steps=30, tau=5.0)
        x = torch.rand(4, 10).clamp(0.01, 1.0)
        spikes = encoder(x)
        assert spikes.shape == (30, 4, 10), (
            f"Expected (30, 4, 10), got {spikes.shape}"
        )

    def test_spikes_are_binary(self):
        """All values must be 0 or 1."""
        encoder = LatencyEncoder(num_steps=25, normalize=False)
        x = torch.rand(4, 10)
        spikes = encoder(x)
        unique = spikes.unique().tolist()
        non_binary = [
            v for v in unique
            if abs(v) > 1e-6 and abs(v - 1.0) > 1e-6
        ]
        assert len(non_binary) == 0, (
            f"Non-binary values: {non_binary}"
        )
'''


def _section_test_population_coding() -> str:
    return '''\
# ============================================================================
# TestPopulationCodingRoundTrip
# ============================================================================

class TestPopulationCodingRoundTrip:
    """
    Population coding: scalar values activate multiple neurons via
    Gaussian tuning curves.
    """

    @pytest.mark.parametrize("P", [4, 8, 16])
    def test_value_reconstruction(self, P: int):
        """
        Encode scalar -> decode via population centers ->
        within +/- 0.15.
        """
        torch.manual_seed(42)
        input_dim = 1
        encoder = PopulationEncoder(
            input_dim=input_dim,
            num_neurons_per_dim=P,
            num_steps=100,
            sigma=0.2,
        )

        x = torch.tensor([[0.5]])
        spikes = encoder(x)  # (T, 1, P)

        counts = spikes.sum(dim=0).squeeze(0)  # (P,)
        centers = torch.linspace(0, 1, P)
        if counts.sum() > 0:
            decoded = (counts * centers).sum() / counts.sum()
        else:
            decoded = torch.tensor(0.5)

        error = abs(decoded.item() - 0.5)
        assert error < 0.15, (
            f"P={P}: decoded={decoded.item():.3f}, "
            f"expected=0.5, error={error:.3f}"
        )

    @pytest.mark.parametrize("P", [4, 8, 16])
    def test_feature_expansion(self, P: int):
        """Output dim must equal input_dim * population_size."""
        input_dim = 5
        encoder = PopulationEncoder(
            input_dim=input_dim,
            num_neurons_per_dim=P,
            num_steps=10,
        )
        x = torch.rand(2, input_dim)
        spikes = encoder(x)  # (T, B, input_dim * P)

        expected_features = input_dim * P
        assert spikes.shape[-1] == expected_features, (
            f"P={P}: expected {expected_features} features, "
            f"got {spikes.shape[-1]}"
        )

    def test_population_map_present(self):
        """
        The population encoder should provide tuning curve centers.
        """
        P = 8
        input_dim = 3
        encoder = PopulationEncoder(
            input_dim=input_dim,
            num_neurons_per_dim=P,
            num_steps=10,
        )

        assert hasattr(encoder, "centers"), (
            "PopulationEncoder must have 'centers' attribute"
        )
        assert encoder.centers.shape[0] == P, (
            f"Expected {P} centers, got {encoder.centers.shape[0]}"
        )

    def test_activations_gaussian_profile(self):
        """
        The neuron closest to the input value should have the
        highest activation.
        """
        torch.manual_seed(42)
        P = 10
        input_dim = 1
        encoder = PopulationEncoder(
            input_dim=input_dim,
            num_neurons_per_dim=P,
            num_steps=200,
            sigma=0.15,
        )

        x = torch.tensor([[0.3]])
        spikes = encoder(x)
        counts = spikes.sum(dim=0).squeeze(0)  # (P,)

        centers = torch.linspace(0, 1, P)
        closest_idx = (centers - 0.3).abs().argmin().item()
        peak_idx = counts.argmax().item()

        assert peak_idx == closest_idx, (
            f"Peak neuron at idx {peak_idx} "
            f"(center={centers[peak_idx]:.2f}), "
            f"expected idx {closest_idx} "
            f"(center={centers[closest_idx]:.2f}) "
            f"for input 0.3"
        )
'''


def _section_test_delta_modulation() -> str:
    return '''\
# ============================================================================
# TestDeltaModulation
# ============================================================================

class TestDeltaModulation:
    """
    Delta modulation: spikes generated on signal changes.
    """

    def test_change_detection(self):
        """Known signal changes produce spikes at change points."""
        encoder = DeltaEncoder(threshold=0.05, num_steps=5)
        encoder.reset()

        x_before = torch.tensor([[0.0, 0.0, 0.0]])
        encoder(x_before)

        x_after = torch.tensor([[0.5, -0.5, 0.0]])
        spikes = encoder(x_after)

        # spikes: (num_steps, 1, 6) -- 3 ON + 3 OFF
        spike_sum = spikes.sum(dim=0).squeeze(0)  # (6,)

        assert spike_sum[0].item() > 0, (
            "Expected ON spike for positive change (dim 0)"
        )
        assert spike_sum[4].item() > 0, (
            "Expected OFF spike for negative change (dim 1)"
        )
        assert spike_sum[2].item() == 0, (
            "Expected no ON spike for zero change (dim 2)"
        )
        assert spike_sum[5].item() == 0, (
            "Expected no OFF spike for zero change (dim 2)"
        )

    def test_on_off_channels(self):
        """Positive -> ON channel; negative -> OFF channel."""
        encoder = DeltaEncoder(threshold=0.05, num_steps=1)
        encoder.reset()

        x1 = torch.tensor([[0.5]])
        encoder(x1)

        # Positive change
        x2 = torch.tensor([[0.8]])
        spikes_pos = encoder(x2)  # (1, 1, 2)
        on_val = spikes_pos[0, 0, 0].item()
        off_val = spikes_pos[0, 0, 1].item()
        assert on_val > 0, (
            "Positive change should trigger ON channel"
        )
        assert off_val == 0, (
            "Positive change should NOT trigger OFF channel"
        )

        # Negative change
        x3 = torch.tensor([[0.4]])
        spikes_neg = encoder(x3)
        on_val_neg = spikes_neg[0, 0, 0].item()
        off_val_neg = spikes_neg[0, 0, 1].item()
        assert on_val_neg == 0, (
            "Negative change should NOT trigger ON channel"
        )
        assert off_val_neg > 0, (
            "Negative change should trigger OFF channel"
        )

    def test_reset_state(self):
        """After reset, encoder carries no previous state."""
        encoder = DeltaEncoder(threshold=0.05, num_steps=5)

        x = torch.tensor([[1.0, 2.0]])
        encoder(x)

        encoder.reset()
        assert encoder.prev_input is None, (
            "prev_input should be None after reset"
        )

        x2 = torch.tensor([[0.5, 0.5]])
        spikes = encoder(x2)
        spike_sum = spikes.sum(dim=0).squeeze(0)
        assert spike_sum[0].item() > 0, (
            "Expected ON spike after reset for dim 0"
        )
        assert spike_sum[1].item() > 0, (
            "Expected ON spike after reset for dim 1"
        )

    def test_output_channels_doubled(self):
        """Output features = 2x input features (ON + OFF)."""
        encoder = DeltaEncoder(threshold=0.1, num_steps=10)
        encoder.reset()
        x = torch.rand(3, 7)
        spikes = encoder(x)  # (T, 3, 14)
        assert spikes.shape[-1] == 14, (
            f"Expected 14 output features, got {spikes.shape[-1]}"
        )
'''


def _section_test_spike_batch() -> str:
    return '''\
# ============================================================================
# TestSpikeBatchContract
# ============================================================================

class TestSpikeBatchContract:
    """SpikeBatch dataclass contract validation."""

    def test_binary(self, sample_spikes):
        """Spikes must be 0 or 1."""
        sb = SpikeBatch.from_dense(sample_spikes)
        unique = sb.spikes.unique().tolist()
        non_binary = [
            v for v in unique
            if abs(v) > 1e-6 and abs(v - 1.0) > 1e-6
        ]
        assert len(non_binary) == 0, (
            f"Non-binary values in SpikeBatch: {non_binary}"
        )

    def test_mask_shape(self, sample_spikes):
        """mask.shape must be (B, T)."""
        B, T, N = sample_spikes.shape
        mask = torch.ones(B, T)
        sb = SpikeBatch.from_dense(sample_spikes, mask=mask)
        assert sb.mask is not None
        assert sb.mask.shape == (B, T), (
            f"Expected mask shape ({B}, {T}), got {sb.mask.shape}"
        )

    def test_is_binary(self, sample_spikes):
        """is_binary() should return True for valid spike batch."""
        sb = SpikeBatch.from_dense(sample_spikes)
        assert sb.is_binary(), (
            "is_binary() should return True for binary spikes"
        )

    def test_time_steps(self, sample_spikes):
        """time_steps property must match T dimension."""
        sb = SpikeBatch.from_dense(sample_spikes)
        assert sb.time_steps == DEFAULT_T, (
            f"Expected time_steps={DEFAULT_T}, got {sb.time_steps}"
        )

    def test_from_dense(self, sample_spikes):
        """from_dense factory must work with and without mask."""
        sb1 = SpikeBatch.from_dense(sample_spikes)
        assert sb1.spikes.shape == sample_spikes.shape

        mask = torch.ones(
            sample_spikes.shape[0], sample_spikes.shape[1],
        )
        sb2 = SpikeBatch.from_dense(sample_spikes, mask=mask)
        assert sb2.mask is not None

    def test_to_device(self, sample_spikes):
        """to(device) must move both spikes and mask."""
        mask = torch.ones(
            sample_spikes.shape[0], sample_spikes.shape[1],
        )
        sb = SpikeBatch.from_dense(sample_spikes, mask=mask)
        sb_moved = sb.to("cpu")
        assert sb_moved.spikes.device.type == "cpu"
        assert sb_moved.mask.device.type == "cpu"

    def test_batch_indexing(self, sample_spikes):
        """__getitem__ must return a valid SpikeBatch."""
        mask = torch.ones(
            sample_spikes.shape[0], sample_spikes.shape[1],
        )
        sb = SpikeBatch.from_dense(sample_spikes, mask=mask)
        sb_single = sb[0]
        assert sb_single.spikes.shape[0] == 1, (
            f"Expected batch dim 1, got {sb_single.spikes.shape[0]}"
        )
        assert sb_single.spikes.shape[1] == DEFAULT_T
'''


def _section_test_axis_convention() -> str:
    return '''\
# ============================================================================
# TestAxisConvention
# ============================================================================

class TestAxisConvention:
    """Axis convention: all new-API outputs use (B, T, ...) batch-first."""

    def test_batch_first_output(self):
        """
        All encoder output spikes, when converted to (B, T, N), must
        have batch as dim 0.
        """
        encoder = RateEncoder(
            num_steps=10, method="bernoulli", gain=1.0,
        )
        torch.manual_seed(0)
        x = torch.rand(4, 5)
        spikes = encoder(x)  # Legacy: (T, B, N)

        # Convert to batch-first
        if spikes.shape[0] == 10:  # time-first
            spikes_bf = spikes.permute(1, 0, 2)
        else:
            spikes_bf = spikes

        assert spikes_bf.shape[0] == 4, (
            f"Batch dim should be 4, got {spikes_bf.shape[0]}"
        )
        assert spikes_bf.shape[1] == 10, (
            f"Time dim should be 10, got {spikes_bf.shape[1]}"
        )

    def test_helper_roundtrip(self):
        """x == time_to_batch_first(batch_to_time_first(x))."""
        x = torch.randn(4, 10, 5)  # (B, T, N)
        x_tf = batch_to_time_first(x)     # (T, B, N)
        x_bf = time_to_batch_first(x_tf)  # (B, T, N)
        assert torch.equal(x, x_bf), (
            "Round-trip batch_to_time_first -> "
            "time_to_batch_first failed"
        )

    def test_shape_constants(self):
        """TIME_DIM == 1, BATCH_DIM == 0."""
        assert TIME_DIM == 1, f"Expected TIME_DIM=1, got {TIME_DIM}"
        assert BATCH_DIM == 0, (
            f"Expected BATCH_DIM=0, got {BATCH_DIM}"
        )

    def test_time_first_detection(self):
        """
        A (T, B, N) tensor should convert to (B, T, N) with
        time_to_batch_first.
        """
        T, B, N = 10, 4, 5
        x_tf = torch.randn(T, B, N)
        x_bf = time_to_batch_first(x_tf)
        assert x_bf.shape[0] == B, (
            f"Expected B={B} at dim 0, got {x_bf.shape[0]}"
        )
        assert x_bf.shape[1] == T, (
            f"Expected T={T} at dim 1, got {x_bf.shape[1]}"
        )
'''


def _section_test_rate_decoder() -> str:
    return '''\
# ============================================================================
# TestRateDecoder
# ============================================================================

class TestRateDecoder:
    """Rate/spike-count decoder: sum spikes over time."""

    def test_correct_prediction(self):
        """Highest spike count class should be the prediction."""
        B, T, N = 2, 20, 5
        spikes = torch.zeros(B, T, N)
        spikes[0, :15, 3] = 1.0  # class 3 for batch 0
        spikes[1, :18, 1] = 1.0  # class 1 for batch 1

        out = rate_decode(spikes)
        assert out.prediction[0].item() == 3, (
            f"Expected class 3, got {out.prediction[0]}"
        )
        assert out.prediction[1].item() == 1, (
            f"Expected class 1, got {out.prediction[1]}"
        )

    def test_confidence_range(self):
        """Confidence must be in [0, 1]."""
        torch.manual_seed(0)
        spikes = (torch.rand(8, 25, 10) > 0.7).float()
        out = rate_decode(spikes)
        assert (out.confidence >= 0.0).all(), (
            "Confidence has values < 0"
        )
        assert (out.confidence <= 1.0).all(), (
            "Confidence has values > 1"
        )

    def test_decoder_output_shape(self):
        """logits (B, C), prediction (B,), confidence (B,)."""
        B, T, N = 4, 20, 8
        spikes = (torch.rand(B, T, N) > 0.7).float()
        out = rate_decode(spikes)

        assert out.logits_proxy.shape == (B, N), (
            f"Expected logits ({B}, {N}), got {out.logits_proxy.shape}"
        )
        assert out.prediction.shape == (B,), (
            f"Expected prediction ({B},), got {out.prediction.shape}"
        )
        assert out.confidence.shape == (B,), (
            f"Expected confidence ({B},), got {out.confidence.shape}"
        )

    def test_temperature_scaling(self):
        """Higher temperature produces softer probabilities."""
        spikes = torch.zeros(1, 20, 4)
        spikes[0, :10, 0] = 1.0
        spikes[0, :5, 1] = 1.0

        out_cold = rate_decode(spikes, temperature=0.1)
        out_warm = rate_decode(spikes, temperature=10.0)

        probs_cold = torch.softmax(out_cold.logits_proxy, dim=-1)
        probs_warm = torch.softmax(out_warm.logits_proxy, dim=-1)

        entropy_cold = -(
            probs_cold * (probs_cold + 1e-8).log()
        ).sum(dim=-1)
        entropy_warm = -(
            probs_warm * (probs_warm + 1e-8).log()
        ).sum(dim=-1)

        assert entropy_warm.item() > entropy_cold.item(), (
            f"Higher temperature should have higher entropy: "
            f"warm={entropy_warm.item():.3f} vs "
            f"cold={entropy_cold.item():.3f}"
        )
'''


def _section_test_first_spike_decoder() -> str:
    return '''\
# ============================================================================
# TestFirstSpikeDecoder
# ============================================================================

class TestFirstSpikeDecoder:
    """First-spike/latency decoder: earliest spike wins."""

    def test_earliest_wins(self):
        """Neuron with earliest spike should be the prediction."""
        B, T, N = 1, 20, 4
        spikes = torch.zeros(B, T, N)
        spikes[0, 3, 2] = 1.0   # neuron 2 at t=3
        spikes[0, 10, 0] = 1.0  # neuron 0 at t=10
        spikes[0, 15, 1] = 1.0  # neuron 1 at t=15

        out = first_spike_decode(spikes)
        assert out.prediction[0].item() == 2, (
            f"Expected neuron 2, got {out.prediction[0]}"
        )

    def test_no_spike_handling(self):
        """Non-spiking neurons should have t_first = T."""
        B, T, N = 2, 20, 4
        spikes = torch.zeros(B, T, N)
        spikes[0, 5, 0] = 1.0

        out = first_spike_decode(spikes)
        t_first = out.aux["first_spike_times"]

        assert t_first[0, 1].item() == T, (
            f"Expected T={T} for non-spiking neuron, "
            f"got {t_first[0, 1]}"
        )
        assert t_first[0, 2].item() == T, (
            f"Expected T={T} for non-spiking neuron, "
            f"got {t_first[0, 2]}"
        )

    def test_logits_negative(self):
        """logits_proxy should be <= 0 (earlier = less negative)."""
        B, T, N = 1, 20, 4
        spikes = torch.zeros(B, T, N)
        spikes[0, 2, 0] = 1.0
        spikes[0, 10, 1] = 1.0

        out = first_spike_decode(spikes)
        assert (out.logits_proxy <= 0.0).all(), (
            f"logits_proxy should be <= 0, "
            f"got max={out.logits_proxy.max().item()}"
        )
        assert out.logits_proxy[0, 0] > out.logits_proxy[0, 1], (
            "Earlier spike should have higher logit"
        )

    def test_output_shape(self):
        """Output shapes must match contract."""
        B, T, N = 4, 25, 8
        spikes = (torch.rand(B, T, N) > 0.9).float()
        out = first_spike_decode(spikes)

        assert out.logits_proxy.shape == (B, N)
        assert out.prediction.shape == (B,)
        assert out.confidence.shape == (B,)
'''


def _section_test_population_decoder() -> str:
    return '''\
# ============================================================================
# TestPopulationDecoder
# ============================================================================

class TestPopulationDecoder:
    """Population decoder: group neurons into classes/regression bins."""

    def test_classification(self):
        """
        Correct group with most spikes should be the prediction.
        """
        B, T = 2, 20
        neurons_per_group = 3
        num_groups = 4
        N = num_groups * neurons_per_group

        population_map = {
            g: list(range(
                g * neurons_per_group,
                (g + 1) * neurons_per_group,
            ))
            for g in range(num_groups)
        }

        spikes = torch.zeros(B, T, N)
        # Group 2 dominant for batch 0
        for idx in population_map[2]:
            spikes[0, :15, idx] = 1.0
        # Group 0 dominant for batch 1
        for idx in population_map[0]:
            spikes[1, :18, idx] = 1.0

        out = population_decode_classify(spikes, population_map)
        assert out.prediction[0].item() == 2, (
            f"Expected group 2, got {out.prediction[0]}"
        )
        assert out.prediction[1].item() == 0, (
            f"Expected group 0, got {out.prediction[1]}"
        )

    def test_regression(self):
        """Expectation over centers should approximate input."""
        B, T = 1, 50
        num_groups = 5
        neurons_per_group = 4
        N = num_groups * neurons_per_group

        population_map = {
            g: list(range(
                g * neurons_per_group,
                (g + 1) * neurons_per_group,
            ))
            for g in range(num_groups)
        }
        centers = torch.linspace(0, 1, num_groups)

        # Make group 2 (center=0.5) dominant
        torch.manual_seed(42)
        spikes = (torch.rand(B, T, N) > 0.9).float()
        for idx in population_map[2]:
            spikes[0, :, idx] = (
                torch.rand(T) > 0.3
            ).float()

        out = population_decode_regression(
            spikes, population_map, centers,
        )
        predicted_val = out.aux["predicted_value"][0].item()

        assert 0.2 < predicted_val < 0.8, (
            f"Expected predicted value near 0.5, "
            f"got {predicted_val:.3f}"
        )

    def test_logits_shape(self):
        """logits_proxy should be (B, num_groups)."""
        B, T = 4, 20
        num_groups = 3
        N = num_groups * 5

        population_map = {
            g: list(range(g * 5, (g + 1) * 5))
            for g in range(num_groups)
        }

        spikes = (torch.rand(B, T, N) > 0.7).float()
        out = population_decode_classify(spikes, population_map)

        assert out.logits_proxy.shape == (B, num_groups), (
            f"Expected ({B}, {num_groups}), "
            f"got {out.logits_proxy.shape}"
        )
'''


def _section_test_prob_spikes_loss() -> str:
    return '''\
# ============================================================================
# TestProbSpikesLoss
# ============================================================================

class TestProbSpikesLoss:
    """ProbSpikes loss: cross-entropy on normalized spike counts."""

    @pytest.mark.parametrize("T", [10, 25, 50])
    def test_finite(self, T: int):
        """Loss must be finite for all T."""
        B, C = 8, 10
        torch.manual_seed(42)
        spikes = (torch.rand(B, T, C) > 0.7).float()
        targets = torch.randint(0, C, (B,))
        membrane = torch.randn(B, T, C)

        term = ProbSpikesLoss(temperature=1.0, mode="softmax")
        loss, diag = term(spikes, membrane, targets)

        assert torch.isfinite(loss), (
            f"ProbSpikesLoss not finite at T={T}: {loss}"
        )

    @pytest.mark.parametrize("T", [10, 25, 50])
    def test_gradients(self, T: int):
        """backward() must produce non-zero grads."""
        B, C = 4, 5
        torch.manual_seed(42)

        linear = nn.Linear(C, C)
        x_input = torch.randn(B, T, C, requires_grad=True)
        spikes_soft = torch.sigmoid(linear(x_input))
        targets = torch.randint(0, C, (B,))

        term = ProbSpikesLoss(temperature=1.0, mode="softmax")
        loss, _ = term(spikes_soft, None, targets)
        loss.backward()

        assert x_input.grad is not None, "No gradient on input"
        assert x_input.grad.abs().sum() > 0, (
            "Input gradient is all-zero"
        )

    def test_fp32_counts(self):
        """Counts must be computed in fp32."""
        B, T, C = 4, 25, 10
        spikes_fp16 = (torch.rand(B, T, C) > 0.7).half()
        targets = torch.randint(0, C, (B,))

        counts = spikes_fp16.float().sum(dim=1)
        assert counts.dtype == torch.float32, (
            f"Expected fp32, got {counts.dtype}"
        )

        term = ProbSpikesLoss(temperature=1.0)
        loss, diag = term(spikes_fp16.float(), None, targets)
        assert torch.isfinite(loss), (
            "Loss not finite with fp16 input"
        )

    @pytest.mark.parametrize("T", [10, 25, 50])
    def test_temperature(self, T: int):
        """Higher temperature produces softer output distribution."""
        B, C = 4, 10
        torch.manual_seed(42)
        spikes = (torch.rand(B, T, C) > 0.7).float()
        targets = torch.randint(0, C, (B,))

        term_cold = ProbSpikesLoss(temperature=0.1)
        term_warm = ProbSpikesLoss(temperature=10.0)

        loss_cold, _ = term_cold(spikes, None, targets)
        loss_warm, _ = term_warm(spikes, None, targets)

        assert torch.isfinite(loss_cold), (
            f"Cold loss not finite: {loss_cold}"
        )
        assert torch.isfinite(loss_warm), (
            f"Warm loss not finite: {loss_warm}"
        )

    def test_diagnostics_keys(self):
        """Diagnostics dict must contain expected keys."""
        B, T, C = 4, 25, 10
        spikes = (torch.rand(B, T, C) > 0.7).float()
        targets = torch.randint(0, C, (B,))

        term = ProbSpikesLoss(temperature=1.0)
        _, diag = term(spikes, None, targets)

        assert "mean_count" in diag, "Missing 'mean_count'"
        assert "max_count" in diag, "Missing 'max_count'"
        assert "accuracy" in diag, "Missing 'accuracy'"

    def test_mode_normalize(self):
        """Normalize mode should produce finite loss."""
        B, T, C = 4, 25, 5
        torch.manual_seed(42)
        spikes = (torch.rand(B, T, C) > 0.5).float()
        targets = torch.randint(0, C, (B,))

        term = ProbSpikesLoss(temperature=1.0, mode="normalize")
        loss, _ = term(spikes, None, targets)
        assert torch.isfinite(loss), (
            f"Normalize mode loss not finite: {loss}"
        )
'''


def _section_test_spike_rate_reg() -> str:
    return '''\
# ============================================================================
# TestSpikeRateRegularization
# ============================================================================

class TestSpikeRateRegularization:
    """Spike rate regularization: penalize deviation from target."""

    def test_target_rate_exact(self):
        """When actual rate equals target, loss is near zero."""
        B, T, N = 4, 100, 10
        target = 0.1

        spikes = torch.zeros(B, T, N)
        for b in range(B):
            for n in range(N):
                indices = torch.randperm(T)[:int(T * target)]
                spikes[b, indices, n] = 1.0

        term = SpikeRateRegularization(
            target_rate=target,
            use_range_penalty=False,
            rate_type="l2",
        )
        loss, diag = term(
            spikes, None, torch.zeros(B, dtype=torch.long),
        )

        assert loss.item() < 0.01, (
            f"Loss should be near zero at target rate, "
            f"got {loss.item():.6f}"
        )

    def test_above_target_positive_loss(self):
        """Rate above target should produce positive loss."""
        B, T, N = 4, 25, 10
        spikes = (torch.rand(B, T, N) > 0.3).float()

        term = SpikeRateRegularization(
            target_rate=0.1, use_range_penalty=False,
        )
        loss, _ = term(
            spikes, None, torch.zeros(B, dtype=torch.long),
        )

        assert loss.item() > 0.0, (
            "Loss should be positive when rate > target"
        )

    def test_range_penalty(self):
        """Rate outside range incurs additional penalty."""
        B, T, N = 4, 25, 10
        spikes = torch.ones(B, T, N)

        term_no = SpikeRateRegularization(
            target_rate=0.1,
            use_range_penalty=False,
            rate_type="l2",
        )
        term_with = SpikeRateRegularization(
            target_rate=0.1,
            min_rate=0.01,
            max_rate=0.3,
            use_range_penalty=True,
            rate_type="l2",
        )

        targets_dummy = torch.zeros(B, dtype=torch.long)
        loss_no, _ = term_no(spikes, None, targets_dummy)
        loss_with, _ = term_with(spikes, None, targets_dummy)

        assert loss_with.item() > loss_no.item(), (
            f"Range penalty should increase loss: "
            f"with={loss_with.item():.4f} vs "
            f"no={loss_no.item():.4f}"
        )

    def test_diagnostics(self):
        """Diagnostics should include rate statistics."""
        B, T, N = 4, 25, 10
        spikes = (torch.rand(B, T, N) > 0.5).float()
        term = SpikeRateRegularization(target_rate=0.1)
        _, diag = term(
            spikes, None, torch.zeros(B, dtype=torch.long),
        )

        assert "mean_rate" in diag, "Missing 'mean_rate'"
        assert "max_rate" in diag, "Missing 'max_rate'"
        assert "min_rate" in diag, "Missing 'min_rate'"
'''


def _section_test_temporal_consistency() -> str:
    return '''\
# ============================================================================
# TestTemporalConsistency
# ============================================================================

class TestTemporalConsistency:
    """Temporal consistency: penalize flickering patterns."""

    @pytest.mark.parametrize("penalty", ["l1", "l2", "variance"])
    def test_constant_firing_low_loss(self, penalty: str):
        """Constant firing pattern yields near-zero loss."""
        B, T, N = 4, 50, 10
        spikes = torch.ones(B, T, N)

        term = TemporalConsistencyLoss(
            window_size=5, penalty_type=penalty,
        )
        loss, _ = term(
            spikes, None, torch.zeros(B, dtype=torch.long),
        )

        assert loss.item() < 0.01, (
            f"penalty={penalty}: constant pattern should have "
            f"near-zero loss, got {loss.item():.6f}"
        )

    @pytest.mark.parametrize("penalty", ["l1", "l2", "variance"])
    def test_flickering_high_loss(self, penalty: str):
        """Alternating 0-1 pattern yields high temporal loss."""
        B, T, N = 4, 50, 10

        spikes = torch.zeros(B, T, N)
        for t in range(T):
            if t % 2 == 0:
                spikes[:, t, :] = 1.0

        term = TemporalConsistencyLoss(
            window_size=5, penalty_type=penalty,
        )
        loss_flicker, _ = term(
            spikes, None, torch.zeros(B, dtype=torch.long),
        )

        spikes_const = torch.ones(B, T, N)
        loss_const, _ = term(
            spikes_const, None, torch.zeros(B, dtype=torch.long),
        )

        assert loss_flicker.item() > loss_const.item(), (
            f"penalty={penalty}: flickering "
            f"({loss_flicker.item():.4f}) should exceed "
            f"constant ({loss_const.item():.4f})"
        )

    def test_short_sequence_handling(self):
        """Variance mode with T < 2*window_size returns zero."""
        B, T, N = 4, 5, 10
        spikes = torch.ones(B, T, N)
        term = TemporalConsistencyLoss(
            window_size=5, penalty_type="variance",
        )
        loss, diag = term(
            spikes, None, torch.zeros(B, dtype=torch.long),
        )

        assert loss.item() == 0.0 or "skipped" in diag, (
            "Short sequence should return zero or skip"
        )
'''


def _section_test_isi_regularization() -> str:
    return '''\
# ============================================================================
# TestISIRegularization
# ============================================================================

class TestISIRegularization:
    """ISI regularization: penalize burst firing via conv1d."""

    def test_vectorized(self):
        """
        ISI must use conv1d. Verify kernel buffer exists.
        """
        rw = 5
        term = ISIRegularization(
            refractory_window=rw, kernel_type="exponential",
        )

        assert hasattr(term, "kernel"), (
            "ISI term must have 'kernel' buffer"
        )
        assert term.kernel.shape == (1, 1, rw), (
            f"Expected kernel (1, 1, {rw}), got {term.kernel.shape}"
        )

    def test_burst_penalty(self):
        """Consecutive spikes produce high penalty."""
        B, T, N = 2, 20, 5
        spikes_burst = torch.ones(B, T, N)

        term = ISIRegularization(
            refractory_window=5, kernel_type="exponential",
        )
        loss_burst, _ = term(
            spikes_burst, None, torch.zeros(B, dtype=torch.long),
        )

        assert loss_burst.item() > 0.0, (
            f"Burst should produce positive penalty, "
            f"got {loss_burst.item()}"
        )

    def test_regular_penalty(self):
        """Regular spacing produces lower penalty than bursts."""
        B, T, N = 2, 50, 5

        spikes_regular = torch.zeros(B, T, N)
        for t in range(0, T, 10):
            spikes_regular[:, t, :] = 1.0

        spikes_burst = torch.zeros(B, T, N)
        spikes_burst[:, :10, :] = 1.0

        term = ISIRegularization(
            refractory_window=5, kernel_type="exponential",
        )
        loss_regular, _ = term(
            spikes_regular, None,
            torch.zeros(B, dtype=torch.long),
        )
        loss_burst, _ = term(
            spikes_burst, None,
            torch.zeros(B, dtype=torch.long),
        )

        assert loss_regular.item() < loss_burst.item(), (
            f"Regular ({loss_regular.item():.4f}) should be < "
            f"burst ({loss_burst.item():.4f})"
        )

    @pytest.mark.parametrize(
        "kernel_type", ["exponential", "rectangular"],
    )
    def test_kernel_types(self, kernel_type: str):
        """Both kernel types should produce finite loss."""
        B, T, N = 4, 25, 10
        torch.manual_seed(42)
        spikes = (torch.rand(B, T, N) > 0.7).float()

        term = ISIRegularization(
            refractory_window=5, kernel_type=kernel_type,
        )
        loss, diag = term(
            spikes, None, torch.zeros(B, dtype=torch.long),
        )

        assert torch.isfinite(loss), (
            f"kernel={kernel_type}: loss not finite: {loss}"
        )
        assert "mean_refractory_penalty" in diag

    def test_no_spikes_zero_penalty(self):
        """All-zero spikes produce zero penalty."""
        B, T, N = 4, 25, 10
        spikes = torch.zeros(B, T, N)

        term = ISIRegularization(
            refractory_window=5, kernel_type="exponential",
        )
        loss, _ = term(
            spikes, None, torch.zeros(B, dtype=torch.long),
        )

        assert loss.item() == 0.0, (
            f"Expected zero penalty, got {loss.item()}"
        )
'''


def _section_test_loss_composer() -> str:
    return '''\
# ============================================================================
# TestLossComposer
# ============================================================================

class TestLossComposer:
    """SNNLossComposer: aggregate multiple loss terms."""

    def test_all_components(self):
        """Composer returns total plus all component losses."""
        B, T, C = 4, 25, 10
        torch.manual_seed(42)
        spikes = (torch.rand(B, T, C) > 0.7).float()
        membrane = torch.randn(B, T, C)
        targets = torch.randint(0, C, (B,))

        composer = SNNLossComposer(terms={
            "prob_spikes": (ProbSpikesLoss(temperature=1.0), 1.0),
            "spike_rate": (
                SpikeRateRegularization(target_rate=0.1), 0.1,
            ),
            "temporal": (
                TemporalConsistencyLoss(penalty_type="l2"), 0.01,
            ),
            "isi": (ISIRegularization(refractory_window=5), 0.01),
        })

        total, log_dict = composer(spikes, membrane, targets)

        assert torch.isfinite(total), (
            f"Total loss not finite: {total}"
        )
        assert "loss/total" in log_dict
        assert "loss/prob_spikes_raw" in log_dict
        assert "loss/spike_rate_raw" in log_dict
        assert "loss/temporal_raw" in log_dict
        assert "loss/isi_raw" in log_dict

    def test_zero_weights(self):
        """Terms with weight=0.0 should not contribute."""
        B, T, C = 4, 25, 10
        torch.manual_seed(42)
        spikes = (torch.rand(B, T, C) > 0.7).float()
        targets = torch.randint(0, C, (B,))

        composer = SNNLossComposer(terms={
            "prob_spikes": (ProbSpikesLoss(), 1.0),
            "spike_rate": (SpikeRateRegularization(), 0.0),
            "temporal": (TemporalConsistencyLoss(), 0.0),
        })

        total, log_dict = composer(spikes, None, targets)

        assert "loss/spike_rate_raw" not in log_dict, (
            "Zero-weight term should not appear"
        )
        assert "loss/temporal_raw" not in log_dict, (
            "Zero-weight term should not appear"
        )

    def test_diagnostics(self):
        """Diagnostics dict has keys from all active terms."""
        B, T, C = 4, 25, 10
        spikes = (torch.rand(B, T, C) > 0.5).float()
        targets = torch.randint(0, C, (B,))

        composer = SNNLossComposer(terms={
            "prob_spikes": (ProbSpikesLoss(), 1.0),
            "spike_rate": (SpikeRateRegularization(), 0.1),
        })

        _, log_dict = composer(spikes, None, targets)

        diag_keys = [k for k in log_dict if k.startswith("diag/")]
        assert len(diag_keys) > 0, (
            "Expected diagnostics from active terms"
        )

        prob_diag = [k for k in diag_keys if "prob_spikes" in k]
        rate_diag = [k for k in diag_keys if "spike_rate" in k]
        assert len(prob_diag) > 0, (
            "Expected diagnostics from prob_spikes"
        )
        assert len(rate_diag) > 0, (
            "Expected diagnostics from spike_rate"
        )

    def test_backward_works(self):
        """Total loss should be backpropagatable."""
        B, T, C = 4, 25, 5
        linear = nn.Linear(C, C)
        x = torch.randn(B, T, C)
        spikes = torch.sigmoid(linear(x))
        targets = torch.randint(0, C, (B,))

        composer = SNNLossComposer(terms={
            "prob_spikes": (ProbSpikesLoss(), 1.0),
        })

        total, _ = composer(spikes, None, targets)
        total.backward()

        assert linear.weight.grad is not None, (
            "No gradient on linear weight"
        )
        assert linear.weight.grad.abs().sum() > 0, (
            "Gradient is all-zero"
        )
'''


def _section_test_amp_hardening() -> str:
    return '''\
# ============================================================================
# TestAMPHardening
# ============================================================================

@pytest.mark.skipif(
    not HAS_CUDA, reason="CUDA required for AMP tests",
)
class TestAMPHardening:
    """AMP hardening: all components must be finite under autocast."""

    @pytest.mark.parametrize("T", [10, 25, 50])
    @pytest.mark.parametrize("B", [4, 16])
    def test_losses_under_autocast(self, T: int, B: int):
        """Each loss term must produce finite results."""
        C = 10
        spikes = (
            torch.rand(B, T, C, device="cuda") > 0.7
        ).float()
        membrane = torch.randn(B, T, C, device="cuda")
        targets = torch.randint(0, C, (B,), device="cuda")

        terms = {
            "prob_spikes": ProbSpikesLoss(
                temperature=1.0,
            ).cuda(),
            "spike_rate": SpikeRateRegularization(
                target_rate=0.1,
            ).cuda(),
            "temporal": TemporalConsistencyLoss(
                penalty_type="l2",
            ).cuda(),
            "isi": ISIRegularization(
                refractory_window=5,
            ).cuda(),
            "membrane": MembraneRegularization(
                max_membrane=1.5,
            ).cuda(),
        }

        with torch.cuda.amp.autocast():
            for name, term in terms.items():
                loss, diag = term(spikes, membrane, targets)
                assert torch.isfinite(loss), (
                    f"T={T}, B={B}: {name} loss not finite "
                    f"under autocast: {loss}"
                )

    @pytest.mark.parametrize("T", [10, 25, 50])
    @pytest.mark.parametrize("B", [4, 16])
    def test_encoders_under_autocast(self, T: int, B: int):
        """Encoders must not produce NaN under autocast."""
        N = 10
        encoders = {
            "rate": RateEncoder(num_steps=T, method="bernoulli"),
            "latency": LatencyEncoder(
                num_steps=T, normalize=False,
            ),
            "temporal": TemporalEncoder(num_steps=T, tau=5.0),
        }

        for name, enc in encoders.items():
            enc = enc.cuda()
            x = torch.rand(
                B, N, device="cuda",
            ).clamp(0.01, 0.99)
            with torch.cuda.amp.autocast():
                spikes = enc(x)
            assert not torch.isnan(spikes).any(), (
                f"T={T}, B={B}: {name} encoder NaN "
                f"under autocast"
            )

    @pytest.mark.parametrize("T", [10, 25, 50])
    @pytest.mark.parametrize("B", [4, 16])
    def test_decoders_under_autocast(self, T: int, B: int):
        """Decoders must produce finite logits under autocast."""
        N = 10
        spikes = (
            torch.rand(B, T, N, device="cuda") > 0.7
        ).float()

        with torch.cuda.amp.autocast():
            out_rate = rate_decode(spikes)
            assert out_rate.logits_proxy.isfinite().all(), (
                f"T={T}, B={B}: rate decoder logits not finite"
            )

            out_fs = first_spike_decode(spikes)
            assert out_fs.logits_proxy.isfinite().all(), (
                f"T={T}, B={B}: first_spike logits not finite"
            )
'''


def _section_test_gradient_flow() -> str:
    return '''\
# ============================================================================
# TestGradientFlow
# ============================================================================

class TestGradientFlow:
    """End-to-end gradient flow: encode -> SNN -> decode -> loss."""

    def test_end_to_end(self, snn_layer):
        """Full pipeline must be connected for backward."""
        linear, neuron = snn_layer
        B, T, N = 4, 15, DEFAULT_N

        torch.manual_seed(42)
        x_input = torch.randn(B, N, requires_grad=True)

        x_seq = x_input.unsqueeze(1).repeat(1, T, 1)

        if hasattr(neuron, "reset_mem"):
            neuron.reset_mem()

        spikes_list = []
        for t in range(T):
            h = linear(x_seq[:, t, :])
            out = neuron(h)
            spk = out[0] if isinstance(out, (tuple, list)) else out
            spikes_list.append(spk)

        spikes = torch.stack(spikes_list, dim=1)
        out = rate_decode(spikes)
        targets = torch.randint(0, N, (B,))
        loss = F.cross_entropy(out.logits_proxy, targets)
        loss.backward()

        assert torch.isfinite(loss), f"Loss not finite: {loss}"

    def test_all_params_grad(self, snn_layer):
        """SNN layer parameters should have non-zero gradients."""
        linear, neuron = snn_layer
        B, T, N = 4, 15, DEFAULT_N

        torch.manual_seed(42)
        x_input = torch.randn(B, N)

        if hasattr(neuron, "reset_mem"):
            neuron.reset_mem()

        spikes_list = []
        for t in range(T):
            h = linear(x_input)
            out = neuron(h)
            spk = out[0] if isinstance(out, (tuple, list)) else out
            spikes_list.append(spk)

        spikes = torch.stack(spikes_list, dim=1)
        out = rate_decode(spikes)
        targets = torch.randint(0, N, (B,))
        loss = F.cross_entropy(out.logits_proxy, targets)
        loss.backward()

        assert linear.weight.grad is not None, (
            "Linear weight has no gradient"
        )
        grad_sum = linear.weight.grad.abs().sum().item()
        assert grad_sum > 0.0, (
            f"Linear weight gradient all-zero: {grad_sum}"
        )

    def test_encoder_params_grad(self):
        """Learnable preprocessing params must receive gradients."""
        B, T, N = 4, 15, 5

        preprocess = nn.Linear(N, N)
        torch.manual_seed(42)
        x = torch.randn(B, N)
        x_processed = preprocess(x)

        encoder = RateEncoder(
            num_steps=T, method="deterministic", gain=1.0,
        )
        spikes = encoder(torch.sigmoid(x_processed))
        spikes_bf = spikes.permute(1, 0, 2)

        out = rate_decode(spikes_bf)
        targets = torch.randint(0, N, (B,))
        loss = F.cross_entropy(out.logits_proxy, targets)
        loss.backward()

        assert preprocess.weight.grad is not None, (
            "Preprocess weight has no gradient"
        )
'''


def _section_test_integration() -> str:
    return '''\
# ============================================================================
# TestIntegration
# ============================================================================

class TestIntegration:
    """Multi-step integration tests: training loops and pipelines."""

    def test_training_loop(self, snn_layer):
        """
        5 training steps with rate encode + rate decode + ProbSpikes.
        Loss should not explode.
        """
        linear, neuron = snn_layer
        B, T, C = 4, 15, DEFAULT_N

        optimizer = torch.optim.Adam(linear.parameters(), lr=0.01)
        term = ProbSpikesLoss(temperature=1.0)

        losses = []
        for step in range(5):
            torch.manual_seed(step)
            x = torch.randn(B, C) * 0.5
            targets = torch.randint(0, C, (B,))

            if hasattr(neuron, "reset_mem"):
                neuron.reset_mem()

            spikes_list = []
            for t in range(T):
                h = linear(x)
                out = neuron(h)
                spk = (
                    out[0]
                    if isinstance(out, (tuple, list))
                    else out
                )
                spikes_list.append(spk)

            spikes = torch.stack(spikes_list, dim=1)

            optimizer.zero_grad()
            loss, _ = term(spikes, None, targets)
            loss.backward()
            optimizer.step()

            losses.append(loss.item())

        for i, l_val in enumerate(losses):
            assert math.isfinite(l_val), (
                f"Step {i}: loss not finite: {l_val}"
            )

        assert losses[-1] < 10 * losses[0] + 1.0, (
            f"Loss exploded: first={losses[0]:.4f}, "
            f"last={losses[-1]:.4f}"
        )

    def test_ttfs_pipeline(self):
        """TTFS encode -> first-spike decode pipeline."""
        B, T, N = 4, 30, 5

        encoder = LatencyEncoder(num_steps=T, normalize=False)
        x = torch.rand(B, N).clamp(0.01, 0.99)

        spikes_tf = encoder(x)
        spikes_bf = spikes_tf.permute(1, 0, 2)

        out = first_spike_decode(spikes_bf)

        assert out.prediction.shape == (B,)
        assert out.logits_proxy.shape == (B, N)
        assert torch.isfinite(out.logits_proxy).all(), (
            "Non-finite logits in TTFS pipeline"
        )

    def test_population_pipeline(self):
        """Population encode -> population decode pipeline."""
        B, N_input = 4, 3
        P = 8
        T = 50

        encoder = PopulationEncoder(
            input_dim=N_input,
            num_neurons_per_dim=P,
            num_steps=T,
        )

        torch.manual_seed(42)
        x = torch.rand(B, N_input)
        spikes_tf = encoder(x)
        spikes_bf = spikes_tf.permute(1, 0, 2)

        total_neurons = N_input * P
        num_groups = N_input
        neurons_per_group = P

        population_map = {
            g: list(range(
                g * neurons_per_group,
                (g + 1) * neurons_per_group,
            ))
            for g in range(num_groups)
        }

        out = population_decode_classify(
            spikes_bf, population_map,
        )

        assert out.prediction.shape == (B,)
        assert out.logits_proxy.shape == (B, num_groups)
        assert torch.isfinite(out.logits_proxy).all(), (
            "Non-finite logits in population pipeline"
        )

    def test_full_composer_pipeline(self, snn_layer):
        """Full pipeline: SNN -> composed loss -> backward."""
        linear, neuron = snn_layer
        B, T, C = 4, 15, DEFAULT_N

        composer = SNNLossComposer(terms={
            "prob_spikes": (
                ProbSpikesLoss(temperature=1.0), 1.0,
            ),
            "spike_rate": (
                SpikeRateRegularization(target_rate=0.1), 0.1,
            ),
            "temporal": (
                TemporalConsistencyLoss(penalty_type="l2"), 0.01,
            ),
        })

        torch.manual_seed(42)
        x = torch.randn(B, C)
        targets = torch.randint(0, C, (B,))

        if hasattr(neuron, "reset_mem"):
            neuron.reset_mem()

        spikes_list = []
        membrane_list = []
        for t in range(T):
            h = linear(x)
            out = neuron(h)
            if isinstance(out, (tuple, list)):
                spk, mem = out[0], out[1]
            else:
                spk = out
                mem = torch.zeros_like(spk)
            spikes_list.append(spk)
            membrane_list.append(mem)

        spikes = torch.stack(spikes_list, dim=1)
        membrane = torch.stack(membrane_list, dim=1)

        total, log_dict = composer(spikes, membrane, targets)

        assert torch.isfinite(total), (
            f"Total loss not finite: {total}"
        )
        assert "loss/total" in log_dict

        total.backward()
        assert linear.weight.grad is not None, (
            "No gradient after composed loss"
        )
'''


# ---------------------------------------------------------------------------
# Assembly
# ---------------------------------------------------------------------------

def build_test_file() -> str:
    """Assemble the complete generated test file as a string."""
    sections = [
        _section_header(),
        _section_imports(),
        _section_fixtures(),
        _section_test_rate_coding(),
        _section_test_latency_ttfs(),
        _section_test_population_coding(),
        _section_test_delta_modulation(),
        _section_test_spike_batch(),
        _section_test_axis_convention(),
        _section_test_rate_decoder(),
        _section_test_first_spike_decoder(),
        _section_test_population_decoder(),
        _section_test_prob_spikes_loss(),
        _section_test_spike_rate_reg(),
        _section_test_temporal_consistency(),
        _section_test_isi_regularization(),
        _section_test_loss_composer(),
        _section_test_amp_hardening(),
        _section_test_gradient_flow(),
        _section_test_integration(),
    ]
    return "\n\n".join(sections) + "\n"


# ---------------------------------------------------------------------------
# Self-test and summary
# ---------------------------------------------------------------------------

def count_tests(content: str) -> Tuple[int, int]:
    """Count test classes and test cases in generated content."""
    classes = 0
    cases = 0
    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith("class Test"):
            classes += 1
        if stripped.startswith("def test_"):
            cases += 1
    return classes, cases


def verify_syntax(content: str) -> bool:
    """Verify that generated content is valid Python via ast.parse."""
    try:
        ast.parse(content)
        return True
    except SyntaxError as e:
        print(
            f"SYNTAX ERROR in generated file: {e}",
            file=sys.stderr,
        )
        return False


def print_summary(output_path: Path, content: str) -> None:
    """Print generation summary."""
    classes, cases = count_tests(content)
    lines = content.count("\n")
    chars = len(content)

    test_class_info = [
        (
            "TestRateCodingRoundTrip",
            "Rate coding: ordering, determinism, statistics",
        ),
        (
            "TestLatencyTTFSRoundTrip",
            "TTFS: monotonicity, single spike, no-spike",
        ),
        (
            "TestPopulationCodingRoundTrip",
            "Population: reconstruction, expansion",
        ),
        (
            "TestDeltaModulation",
            "Delta: change detection, ON/OFF, reset",
        ),
        (
            "TestSpikeBatchContract",
            "SpikeBatch: binary, mask, factory, device",
        ),
        (
            "TestAxisConvention",
            "Axis: batch-first, helpers, constants",
        ),
        (
            "TestRateDecoder",
            "Rate decode: prediction, confidence, shape",
        ),
        (
            "TestFirstSpikeDecoder",
            "First-spike: earliest wins, no-spike, logits",
        ),
        (
            "TestPopulationDecoder",
            "Population decode: classify, regression",
        ),
        (
            "TestProbSpikesLoss",
            "ProbSpikes: finite, gradients, fp32, temperature",
        ),
        (
            "TestSpikeRateRegularization",
            "Spike rate: target, above-target, range",
        ),
        (
            "TestTemporalConsistency",
            "Temporal: constant, flickering, short seq",
        ),
        (
            "TestISIRegularization",
            "ISI: vectorized, burst, regular, kernels",
        ),
        (
            "TestLossComposer",
            "Composer: all components, zero weights, diag",
        ),
        (
            "TestAMPHardening",
            "AMP: losses, encoders, decoders under autocast",
        ),
        (
            "TestGradientFlow",
            "Gradients: end-to-end, params, encoder params",
        ),
        (
            "TestIntegration",
            "Integration: training loop, TTFS, population",
        ),
    ]

    print()
    print("=" * 72)
    print(
        "  gen_codec_tests.py -- Generated spike codec & losses "
        "test suite"
    )
    print("=" * 72)
    print(f"  Output file : {output_path}")
    print(f"  File size   : {chars:,} chars, {lines:,} lines")
    print(f"  Test classes: {classes}")
    print(f"  Test cases  : {cases}")
    print()
    print("  Generated test classes:")
    for cls, desc in test_class_info:
        print(f"    {cls:<35s} -- {desc}")
    print()
    print("  Run all tests:")
    print(f"    pytest {output_path} -v --tb=short")
    print()
    print("  Run without CUDA tests:")
    print(f'    pytest {output_path} -v -k "not AMP"')
    print()
    print(
        "  Stub mode: tests use inline stubs if new API modules "
        "are not yet"
    )
    print(
        "  implemented. Once brain_ai.core.decoders, "
        "brain_ai.core.spike_batch,"
    )
    print(
        "  and the new LossTerm classes exist, stubs are "
        "bypassed automatically."
    )
    print("=" * 72)
    print()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    args = parse_args()

    content = build_test_file()

    # Verify syntax of generated content
    if not verify_syntax(content):
        print(
            "ERROR: Generated file has syntax errors. Aborting.",
            file=sys.stderr,
        )
        sys.exit(1)

    if args.dry_run:
        print(content)
        classes, cases = count_tests(content)
        print(
            f"\n# Dry run: {classes} test classes, "
            f"{cases} test cases",
            file=sys.stderr,
        )
        return

    output_path = (
        Path(args.output) if args.output else _default_output_path()
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)

    output_path.write_text(content, encoding="utf-8")

    print_summary(output_path, content)

    # Self-test: verify the written file
    written = output_path.read_text(encoding="utf-8")
    assert len(written) == len(content), (
        "Written content length mismatch"
    )
    assert verify_syntax(written), (
        "Written file fails syntax check"
    )

    classes, cases = count_tests(content)
    print(f"Written: {output_path}")
    print(
        f"Summary: {classes} test classes, "
        f"{cases} test cases generated"
    )
    print(
        f"File: {len(content):,} chars, "
        f"{content.count(chr(10)):,} lines"
    )


if __name__ == "__main__":
    main()
