#!/usr/bin/env python3
"""
gen_pipeline_tests.py — Generates pytest test cases covering all 6 phases of
the DataLoader Throughput + Sequence Packing skill.

Usage:
    python scripts/gen_pipeline_tests.py > tests/test_pipeline.py
    python scripts/gen_pipeline_tests.py --output tests/test_pipeline.py
    pytest tests/test_pipeline.py -v
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

TEST_TEMPLATE = '''\
"""
Auto-generated pipeline tests covering all 6 phases.
Generated by: scripts/gen_pipeline_tests.py

Run with: pytest {output_path} -v
"""

import json
import os
import sys
import time
import tempfile
from pathlib import Path

import numpy as np
import pytest

# Ensure asset modules are importable
SKILL_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SKILL_DIR / "assets"))


# ============================================================================
# Phase 1: Pipeline Measurement
# ============================================================================

class TestPhase1PipelineMeasurement:
    """Tests for timer instrumentation and metrics reporting."""

    def test_p1_1_timer_positive_t_data(self):
        from pipeline_auditor_template import PipelineAuditor
        auditor = PipelineAuditor(device=None)
        auditor.mark_data_start()
        time.sleep(0.005)
        auditor.mark_data_end()
        auditor.mark_compute_start()
        time.sleep(0.005)
        auditor.mark_compute_end()
        m = auditor.report()
        assert m.t_data_p50_ms > 0

    def test_p1_2_timer_positive_t_compute(self):
        from pipeline_auditor_template import PipelineAuditor
        auditor = PipelineAuditor(device=None)
        auditor.mark_data_start()
        time.sleep(0.002)
        auditor.mark_data_end()
        auditor.mark_compute_start()
        time.sleep(0.005)
        auditor.mark_compute_end()
        m = auditor.report()
        assert m.t_fwd_bwd_opt_p50_ms > 0

    def test_p1_3_total_ge_data(self):
        from pipeline_auditor_template import PipelineAuditor
        auditor = PipelineAuditor(device=None)
        auditor.mark_data_start()
        time.sleep(0.003)
        auditor.mark_data_end()
        auditor.mark_compute_start()
        time.sleep(0.005)
        auditor.mark_compute_end()
        m = auditor.report()
        # Allow small tolerance for timing jitter
        assert m.t_total_step_p50_ms >= m.t_data_p50_ms * 0.8

    def test_p1_4_stall_ratio_bounds(self):
        from pipeline_auditor_template import PipelineAuditor
        auditor = PipelineAuditor(device=None)
        for _ in range(10):
            auditor.mark_data_start()
            time.sleep(0.001)
            auditor.mark_data_end()
            auditor.mark_compute_start()
            time.sleep(0.003)
            auditor.mark_compute_end()
        m = auditor.report()
        assert 0.0 <= m.data_stall_ratio_p50 <= 1.0
        assert 0.0 <= m.data_stall_ratio_p90 <= 1.0

    def test_p1_5_stall_ratio_known_values(self):
        from pipeline_auditor_template import PipelineAuditor
        auditor = PipelineAuditor(device=None)
        # Make data ~1/3 of total time
        auditor.mark_data_start()
        time.sleep(0.010)
        auditor.mark_data_end()
        auditor.mark_compute_start()
        time.sleep(0.020)
        auditor.mark_compute_end()
        m = auditor.report()
        # Stall ratio should be roughly 0.33
        assert 0.1 < m.data_stall_ratio_p50 < 0.6

    def test_p1_6_percentile_aggregation(self):
        from pipeline_auditor_template import PipelineAuditor
        auditor = PipelineAuditor(device=None)
        for _ in range(50):
            auditor.mark_data_start()
            time.sleep(0.001)
            auditor.mark_data_end()
            auditor.mark_compute_start()
            time.sleep(0.002)
            auditor.mark_compute_end()
        m = auditor.report()
        assert m.steps_measured == 50
        assert m.data_stall_ratio_p90 >= m.data_stall_ratio_p50 - 1e-6

    def test_p1_7_json_schema(self):
        from pipeline_auditor_template import PipelineAuditor
        auditor = PipelineAuditor(device=None)
        auditor.mark_data_start()
        time.sleep(0.001)
        auditor.mark_data_end()
        auditor.mark_compute_start()
        time.sleep(0.001)
        auditor.mark_compute_end()

        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as f:
            tmp = f.name
        try:
            auditor.to_json(tmp)
            with open(tmp) as f:
                data = json.load(f)
            required = ["version", "steps_measured", "data_stall_ratio_p50",
                        "data_stall_ratio_p90", "t_data_p50_ms"]
            for key in required:
                assert key in data, f"Missing key: {{key}}"
        finally:
            os.unlink(tmp)

    def test_p1_8_json_round_trip(self):
        from pipeline_auditor_template import PipelineAuditor
        auditor = PipelineAuditor(device=None)
        auditor.mark_data_start()
        time.sleep(0.001)
        auditor.mark_data_end()
        auditor.mark_compute_start()
        time.sleep(0.001)
        auditor.mark_compute_end()
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as f:
            tmp = f.name
        try:
            auditor.to_json(tmp)
            with open(tmp) as f:
                data = json.load(f)
            assert isinstance(data, dict)
        finally:
            os.unlink(tmp)


# ============================================================================
# Phase 2: Streaming Reads + Caching
# ============================================================================

class TestPhase2StreamingReads:
    """Tests for streaming backends and caching."""

    def test_p2_1_synthetic_backend_yields_batches(self):
        from streaming_dataset_template import ShardedStreamDataset, StreamConfig
        cfg = StreamConfig(format="synthetic", num_samples=20, target_seq_len=32)
        ds = ShardedStreamDataset(cfg, rank=0, world_size=1)
        batches = list(ds)
        assert len(batches) == 20
        assert "input_ids" in batches[0]

    def test_p2_2_memmap_backend_loads(self):
        from streaming_dataset_template import ShardedStreamDataset, StreamConfig
        with tempfile.TemporaryDirectory() as tmpdir:
            tokens = np.arange(320, dtype=np.uint16)
            tokens.tofile(os.path.join(tmpdir, "data.bin"))
            cfg = StreamConfig(format="memmap",
                               data_path=os.path.join(tmpdir, "data"),
                               target_seq_len=32)
            ds = ShardedStreamDataset(cfg, rank=0, world_size=1)
            batches = list(ds)
            assert len(batches) > 0
            assert len(batches[0]["input_ids"]) == 32

    def test_p2_3_cache_stores_retrieves(self):
        from streaming_dataset_template import ShardCache
        with tempfile.TemporaryDirectory() as tmpdir:
            cache = ShardCache(tmpdir, max_bytes=10000)
            data = b"shard data content"
            cache.put("shard_001", data)
            assert cache.get("shard_001") == data

    def test_p2_4_checksum_validation(self):
        from streaming_dataset_template import ShardCache
        with tempfile.TemporaryDirectory() as tmpdir:
            cache = ShardCache(tmpdir, max_bytes=10000)
            data = b"valid data"
            cache.put("shard_002", data)
            checksum = cache.compute_checksum(data)
            stored = (Path(tmpdir) / "shard_002.checksum").read_text().strip()
            assert checksum == stored

    def test_p2_5_corruption_recovery(self):
        from streaming_dataset_template import ShardCache
        with tempfile.TemporaryDirectory() as tmpdir:
            cache = ShardCache(tmpdir, max_bytes=10000)
            cache.put("shard_003", b"original data")
            (Path(tmpdir) / "shard_003").write_bytes(b"corrupted!")
            assert cache.get("shard_003") is None

    def test_p2_6_set_epoch_changes_order(self):
        from streaming_dataset_template import ShardedStreamDataset, StreamConfig
        cfg = StreamConfig(format="synthetic", num_samples=50, target_seq_len=16)
        ds = ShardedStreamDataset(cfg, rank=0, world_size=1)
        ds.set_epoch(0)
        order_0 = [b["sample_id"] for b in ds]
        ds.set_epoch(1)
        order_1 = [b["sample_id"] for b in ds]
        assert order_0 != order_1

    def test_p2_7_yields_100_iterations(self):
        from streaming_dataset_template import ShardedStreamDataset, StreamConfig
        cfg = StreamConfig(format="synthetic", num_samples=100, target_seq_len=16)
        ds = ShardedStreamDataset(cfg, rank=0, world_size=1)
        count = 0
        for batch in ds:
            assert "input_ids" in batch
            count += 1
        assert count == 100

    def test_p2_8_lru_eviction(self):
        from streaming_dataset_template import ShardCache
        with tempfile.TemporaryDirectory() as tmpdir:
            cache = ShardCache(tmpdir, max_bytes=500)
            cache.put("a", b"x" * 200)
            cache.put("b", b"y" * 200)
            cache.get("a")  # touch a
            cache.put("c", b"z" * 200)  # should evict b
            assert cache.get("b") is None
            assert cache.get("a") is not None


# ============================================================================
# Phase 3: DataLoader Tuning
# ============================================================================

class TestPhase3DataLoaderTuning:
    """Tests for DataLoader configuration and tuning."""

    @pytest.fixture
    def torch_dataset(self):
        import torch
        from torch.utils.data import TensorDataset
        X = torch.randn(100, 32)
        Y = torch.randint(0, 10, (100,))
        return TensorDataset(X, Y)

    def test_p3_1_loader_nw0_yields(self, torch_dataset):
        from dataloader_tuner_template import create_dataloader, TunerConfig
        cfg = TunerConfig(num_workers_range=(0,), batch_size=8)
        loader = create_dataloader(torch_dataset, cfg, num_workers=0)
        batches = list(loader)
        assert len(batches) > 0

    def test_p3_2_loader_nw2_yields(self, torch_dataset):
        from dataloader_tuner_template import create_dataloader, TunerConfig
        cfg = TunerConfig(num_workers_range=(2,), batch_size=8)
        loader = create_dataloader(torch_dataset, cfg, num_workers=2, prefetch_factor=2)
        batches = list(loader)
        assert len(batches) > 0

    def test_p3_3_prefetch_factor(self, torch_dataset):
        from dataloader_tuner_template import create_dataloader, TunerConfig
        cfg = TunerConfig(batch_size=8)
        loader = create_dataloader(torch_dataset, cfg, num_workers=2, prefetch_factor=4)
        batches = list(loader)
        assert len(batches) > 0

    def test_p3_6_set_epoch_changes_order(self):
        import torch
        from torch.utils.data import TensorDataset, DistributedSampler
        ds = TensorDataset(torch.arange(100))
        sampler = DistributedSampler(ds, num_replicas=2, rank=0, shuffle=True, seed=42)
        sampler.set_epoch(0)
        order_0 = list(sampler)
        sampler.set_epoch(1)
        order_1 = list(sampler)
        assert order_0 != order_1

    def test_p3_7_tuning_grid(self, torch_dataset):
        from dataloader_tuner_template import run_tuning_grid, TunerConfig
        cfg = TunerConfig(
            num_workers_range=(0,),
            prefetch_factor_range=(2,),
            batch_size=16,
            warmup_steps=2,
            measure_steps=5,
        )
        result = run_tuning_grid(torch_dataset, cfg)
        assert result["best_config"] is not None
        assert result["best_config"]["throughput_samples_per_sec"] > 0

    def test_p3_8_watchdog_healthy(self):
        from dataloader_tuner_template import WorkerWatchdog
        wd = WorkerWatchdog(timeout_sec=5.0)
        wd.on_batch_received({{"step": 0}})
        assert wd.check() is True

    def test_p3_9_watchdog_stall(self):
        from dataloader_tuner_template import WorkerWatchdog
        wd = WorkerWatchdog(timeout_sec=0.02)
        time.sleep(0.05)
        assert wd.check() is False

    def test_p3_10_loader_respects_config(self, torch_dataset):
        from dataloader_tuner_template import create_dataloader, TunerConfig
        cfg = TunerConfig(pin_memory=False, batch_size=4, num_workers_range=(0,))
        loader = create_dataloader(torch_dataset, cfg, num_workers=0)
        assert loader.batch_size == 4
        assert loader.pin_memory is False


# ============================================================================
# Phase 4: Sequence Packing
# ============================================================================

class TestPhase4SequencePacking:
    """Tests for pretrain blocks, SFT packing, bucketing, padding ratio."""

    def _make_examples(self, lengths):
        from sequence_packer_template import TokenizedExample
        return [
            TokenizedExample(
                input_ids=list(range(1, l + 1)),
                labels=[-100] + list(range(2, l + 1)),
            )
            for l in lengths
        ]

    def test_p4_1_pretrain_block_length(self):
        from sequence_packer_template import SequencePacker, PackingConfig
        cfg = PackingConfig(target_seq_len=100)
        packer = SequencePacker(cfg)
        docs = [[1] * 50, [2] * 80, [3] * 120]
        blocks = list(packer.pack_pretrain(iter(docs)))
        for block in blocks:
            assert len(block.input_ids) == 100

    def test_p4_2_pretrain_near_zero_padding(self):
        from sequence_packer_template import SequencePacker, PackingConfig
        cfg = PackingConfig(target_seq_len=100)
        packer = SequencePacker(cfg)
        docs = [[i] * 50 for i in range(20)]
        blocks = list(packer.pack_pretrain(iter(docs)))
        total_padding = sum(b.padding_count for b in blocks)
        assert total_padding < cfg.target_seq_len

    def test_p4_3_pretrain_doc_boundaries(self):
        from sequence_packer_template import SequencePacker, PackingConfig
        cfg = PackingConfig(target_seq_len=100)
        packer = SequencePacker(cfg)
        blocks = list(packer.pack_pretrain(iter([[1] * 30, [2] * 70])))
        assert len(blocks[0].doc_boundaries) > 0

    def test_p4_4_sft_cu_seqlens_start_zero(self):
        from sequence_packer_template import SequencePacker, PackingConfig
        cfg = PackingConfig(mode="sft_boundary_aware")
        packer = SequencePacker(cfg)
        examples = self._make_examples([10, 20, 30])
        batch = packer.pack_sft(examples)
        assert batch.cu_seqlens[0] == 0

    def test_p4_5_sft_cu_seqlens_monotonic(self):
        from sequence_packer_template import SequencePacker, PackingConfig
        cfg = PackingConfig()
        packer = SequencePacker(cfg)
        examples = self._make_examples([15, 25, 10, 50])
        batch = packer.pack_sft(examples)
        for i in range(len(batch.cu_seqlens) - 1):
            assert batch.cu_seqlens[i] < batch.cu_seqlens[i + 1]

    def test_p4_6_sft_cu_seqlens_end_total(self):
        from sequence_packer_template import SequencePacker, PackingConfig
        cfg = PackingConfig()
        packer = SequencePacker(cfg)
        examples = self._make_examples([10, 20, 30])
        batch = packer.pack_sft(examples)
        assert batch.cu_seqlens[-1] == len(batch.input_ids)

    def test_p4_7_position_ids_reset(self):
        from sequence_packer_template import SequencePacker, PackingConfig
        cfg = PackingConfig()
        packer = SequencePacker(cfg)
        examples = self._make_examples([10, 20, 15])
        batch = packer.pack_sft(examples)
        for i in range(len(batch.cu_seqlens) - 1):
            assert batch.position_ids[batch.cu_seqlens[i]] == 0

    def test_p4_8_labels_preserved(self):
        from sequence_packer_template import SequencePacker, PackingConfig, TokenizedExample
        cfg = PackingConfig()
        packer = SequencePacker(cfg)
        ex1 = TokenizedExample(input_ids=[1, 2, 3], labels=[-100, 2, 3])
        ex2 = TokenizedExample(input_ids=[4, 5], labels=[4, 5])
        batch = packer.pack_sft([ex1, ex2])
        assert batch.labels == [-100, 2, 3, 4, 5]

    def test_p4_9_bucketing_assigns_correct(self):
        from sequence_packer_template import SequencePacker, PackingConfig
        cfg = PackingConfig(bucket_boundaries=(64, 128, 256))
        packer = SequencePacker(cfg)
        assert packer.assign_bucket(30) == 64
        assert packer.assign_bucket(64) == 64
        assert packer.assign_bucket(65) == 128
        assert packer.assign_bucket(200) == 256
        assert packer.assign_bucket(999) == 256

    def test_p4_10_bucketing_reduces_unique_lengths(self):
        from sequence_packer_template import SequencePacker, PackingConfig
        cfg = PackingConfig(bucket_boundaries=(64, 128, 256))
        packer = SequencePacker(cfg)
        lengths = [10, 20, 30, 50, 80, 100, 150, 200]
        buckets = set(packer.assign_bucket(l) for l in lengths)
        assert len(buckets) <= len(cfg.bucket_boundaries)

    def test_p4_11_padding_ratio_zero_packed(self):
        from sequence_packer_template import SequencePacker, PackingConfig
        cfg = PackingConfig()
        packer = SequencePacker(cfg)
        examples = self._make_examples([10, 20])
        batch = packer.pack_sft(examples)
        assert abs(packer.padding_ratio(batch)) < 1e-9

    def test_p4_12_padding_ratio_correct_value(self):
        from sequence_packer_template import SequencePacker, PackingConfig, PackedBatch
        cfg = PackingConfig()
        packer = SequencePacker(cfg)
        batch = PackedBatch(
            input_ids=[1]*80 + [0]*20,
            cu_seqlens=[0, 80], position_ids=list(range(80)) + [0]*20,
            labels=[1]*80 + [-100]*20, padding_count=20,
        )
        ratio = packer.padding_ratio(batch)
        assert abs(ratio - 0.2) < 1e-6


# ============================================================================
# Phase 5: Deterministic Sharding
# ============================================================================

class TestPhase5DeterministicSharding:
    """Tests for rank-level data sharding."""

    def test_p5_1_ranks_no_overlap(self):
        from streaming_dataset_template import ShardedStreamDataset, StreamConfig
        cfg = StreamConfig(format="synthetic", num_samples=100, target_seq_len=16)
        ids0 = set(b["sample_id"] for b in ShardedStreamDataset(cfg, 0, 2))
        ids1 = set(b["sample_id"] for b in ShardedStreamDataset(cfg, 1, 2))
        assert len(ids0 & ids1) == 0

    def test_p5_2_all_covered(self):
        from streaming_dataset_template import ShardedStreamDataset, StreamConfig
        cfg = StreamConfig(format="synthetic", num_samples=100, target_seq_len=16)
        ids0 = set(b["sample_id"] for b in ShardedStreamDataset(cfg, 0, 2))
        ids1 = set(b["sample_id"] for b in ShardedStreamDataset(cfg, 1, 2))
        assert len(ids0 | ids1) == 100

    def test_p5_3_set_epoch_changes(self):
        from streaming_dataset_template import ShardedStreamDataset, StreamConfig
        cfg = StreamConfig(format="synthetic", num_samples=50, target_seq_len=16)
        ds = ShardedStreamDataset(cfg, 0, 1)
        ds.set_epoch(0)
        o0 = [b["sample_id"] for b in ds]
        ds.set_epoch(1)
        o1 = [b["sample_id"] for b in ds]
        assert o0 != o1

    def test_p5_4_seed_reproducible(self):
        from streaming_dataset_template import ShardedStreamDataset, StreamConfig
        cfg = StreamConfig(format="synthetic", num_samples=50, target_seq_len=16)
        ds1 = ShardedStreamDataset(cfg, 0, 1)
        ds1.set_epoch(3)
        o1 = [b["sample_id"] for b in ds1]
        ds2 = ShardedStreamDataset(cfg, 0, 1)
        ds2.set_epoch(3)
        o2 = [b["sample_id"] for b in ds2]
        assert o1 == o2

    def test_p5_5_different_ranks_different_data(self):
        from streaming_dataset_template import ShardedStreamDataset, StreamConfig
        cfg = StreamConfig(format="synthetic", num_samples=200, target_seq_len=16)
        first_r0 = [b["sample_id"] for b in ShardedStreamDataset(cfg, 0, 4)][:10]
        first_r1 = [b["sample_id"] for b in ShardedStreamDataset(cfg, 1, 4)][:10]
        assert first_r0 != first_r1

    def test_p5_7_dedup_hash_check(self):
        import hashlib
        from streaming_dataset_template import ShardedStreamDataset, StreamConfig
        cfg = StreamConfig(format="synthetic", num_samples=100, target_seq_len=16)
        ds0 = ShardedStreamDataset(cfg, 0, 2)
        ds1 = ShardedStreamDataset(cfg, 1, 2)
        hashes0 = set(hashlib.md5(str(b["sample_id"]).encode()).hexdigest()[:8]
                       for b in ds0)
        hashes1 = set(hashlib.md5(str(b["sample_id"]).encode()).hexdigest()[:8]
                       for b in ds1)
        assert len(hashes0 & hashes1) == 0


# ============================================================================
# Phase 6: Metrics Integration
# ============================================================================

class TestPhase6MetricsIntegration:
    """Tests for metrics JSON and effective tokens computation."""

    def test_p6_1_json_all_fields(self):
        from pipeline_auditor_template import PipelineAuditor
        auditor = PipelineAuditor(device=None)
        for _ in range(5):
            auditor.mark_data_start()
            time.sleep(0.001)
            auditor.mark_data_end()
            auditor.mark_compute_start()
            time.sleep(0.002)
            auditor.mark_compute_end()
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as f:
            tmp = f.name
        try:
            auditor.to_json(tmp)
            with open(tmp) as f:
                data = json.load(f)
            required = ["data_stall_ratio_p50", "data_stall_ratio_p90",
                        "t_data_p50_ms", "t_data_p90_ms", "padding_ratio"]
            for key in required:
                assert key in data
        finally:
            os.unlink(tmp)

    def test_p6_2_stall_ratio_bounds(self):
        from pipeline_auditor_template import PipelineAuditor
        auditor = PipelineAuditor(device=None)
        for _ in range(10):
            auditor.mark_data_start()
            time.sleep(0.001)
            auditor.mark_data_end()
            auditor.mark_compute_start()
            time.sleep(0.002)
            auditor.mark_compute_end()
        m = auditor.report()
        assert 0.0 <= m.data_stall_ratio_p50 <= 1.0

    def test_p6_3_p90_ge_p50(self):
        from pipeline_auditor_template import PipelineAuditor
        auditor = PipelineAuditor(device=None)
        for _ in range(20):
            auditor.mark_data_start()
            time.sleep(0.001)
            auditor.mark_data_end()
            auditor.mark_compute_start()
            time.sleep(0.003)
            auditor.mark_compute_end()
        m = auditor.report()
        assert m.data_stall_ratio_p90 >= m.data_stall_ratio_p50 - 1e-6

    def test_p6_4_effective_tokens(self):
        from pipeline_auditor_template import PipelineAuditor
        auditor = PipelineAuditor(device=None)
        for _ in range(5):
            auditor.mark_data_start()
            time.sleep(0.001)
            auditor.mark_data_end()
            auditor.mark_compute_start()
            time.sleep(0.002)
            auditor.mark_compute_end()
            auditor.record_tokens(raw=2048, effective=1800)
        m = auditor.report()
        assert m.effective_tokens_per_sec_p50 > 0

    def test_p6_5_padding_ratio_bounds(self):
        from pipeline_auditor_template import PipelineAuditor
        auditor = PipelineAuditor(device=None)
        auditor.padding_ratio = 0.15
        auditor.mark_data_start()
        time.sleep(0.001)
        auditor.mark_data_end()
        auditor.mark_compute_start()
        time.sleep(0.001)
        auditor.mark_compute_end()
        m = auditor.report()
        assert 0.0 <= m.padding_ratio < 1.0

    def test_p6_7_config_in_metrics(self):
        from pipeline_config_template import DataPipelineConfig
        cfg = DataPipelineConfig(pack_mode="none", pack_enabled=False)
        d = cfg.to_dict()
        assert "pack_mode" in d

    def test_p6_10_metrics_round_trip(self):
        from pipeline_auditor_template import PipelineAuditor
        auditor = PipelineAuditor(device=None)
        auditor.mark_data_start()
        time.sleep(0.001)
        auditor.mark_data_end()
        auditor.mark_compute_start()
        time.sleep(0.001)
        auditor.mark_compute_end()
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as f:
            tmp = f.name
        try:
            auditor.to_json(tmp)
            with open(tmp) as f:
                data = json.load(f)
            # Write and read again
            with open(tmp, "w") as f:
                json.dump(data, f)
            with open(tmp) as f:
                data2 = json.load(f)
            assert data == data2
        finally:
            os.unlink(tmp)


# ============================================================================
# Config validation tests
# ============================================================================

class TestConfigValidation:
    """Tests for DataPipelineConfig validation and serialization."""

    def test_valid_config(self):
        from pipeline_config_template import DataPipelineConfig
        cfg = DataPipelineConfig()
        cfg.validate()

    def test_invalid_format_raises(self):
        from pipeline_config_template import DataPipelineConfig
        with pytest.raises(ValueError):
            DataPipelineConfig(format="bad").validate()

    def test_json_round_trip(self):
        from pipeline_config_template import DataPipelineConfig
        cfg = DataPipelineConfig(format="token_memmap", pack_enabled=True,
                                  pack_mode="pretrain_blocks")
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as f:
            tmp = f.name
        try:
            cfg.to_json(tmp)
            loaded = DataPipelineConfig.from_json(tmp)
            assert loaded.format == cfg.format
            assert loaded.pack_mode == cfg.pack_mode
        finally:
            os.unlink(tmp)
'''


def main():
    parser = argparse.ArgumentParser(
        description="Generate pytest test cases for the data pipeline skill"
    )
    parser.add_argument(
        "--output", "-o", type=str, default=None,
        help="Output file path (default: stdout)"
    )
    args = parser.parse_args()

    # Determine output path for template
    if args.output:
        output_path = args.output
    else:
        output_path = "tests/test_pipeline.py"

    content = TEST_TEMPLATE.format(output_path=output_path)

    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        with open(args.output, "w") as f:
            f.write(content)
        print(f"Generated test file: {args.output}")
    else:
        print(content)


if __name__ == "__main__":
    main()
