#!/usr/bin/env python3
"""
gen_data_tests.py
=================
Generates 100+ pytest test cases for the V-JEPA 2 data pipeline.

The generated file is written to:
    tests/test_vjepa2_data_pipeline.py

Usage
-----
    python scripts/gen_data_tests.py
    python scripts/gen_data_tests.py --output /path/to/tests/test_pipeline.py
    python scripts/gen_data_tests.py --run        # Generate + run immediately

The generated tests cover:
    - Clip modes (fps, duration, frame_step)
    - Circulant padding for short/single-frame videos
    - Transform pipeline shapes and dtypes
    - Augmentation determinism (fixed seed)
    - Temporal consistency (crop, flip)
    - Multi-source ConcatIndices
    - DistributedWeightedSampler (coverage, weights, reproducibility)
    - Worker seeding (LCG algorithm)
    - DataConfig and AugConfig validation
    - YAML round-trips
    - Edge cases
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# The generated test file content
# ---------------------------------------------------------------------------

GENERATED_TESTS = '''#!/usr/bin/env python3
"""
test_vjepa2_data_pipeline.py
=============================
Auto-generated pytest tests for the V-JEPA 2 data pipeline.
Generated by: scripts/gen_data_tests.py

Run with:
    pytest tests/test_vjepa2_data_pipeline.py -v
    pytest tests/test_vjepa2_data_pipeline.py -v --tb=short -q
"""

from __future__ import annotations

import math
import random
import sys
from pathlib import Path
from typing import List

import numpy as np
import pytest
import torch

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
SKILL_ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = SKILL_ROOT / "assets"
sys.path.insert(0, str(ASSETS_DIR))

from video_dataset_template import VideoDataset, compute_frame_indices
from video_transforms_template import (
    VideoTransformPipeline,
    VideoRandomResizedCrop,
    VideoRandomHorizontalFlip,
    VideoRandomErasing,
    VideoMotionShift,
    ClipToTensor,
    VideoNormalize,
    Compose,
)
from distributed_sampler_template import (
    DistributedWeightedSampler,
    ConcatIndices,
    expand_weights_to_samples,
)
from data_config_template import (
    DataConfig,
    AugConfig,
    merge_configs,
    get_section,
    validate_config,
)

try:
    from data_config_template import load_yaml_string, _YAML_AVAILABLE
except ImportError:
    _YAML_AVAILABLE = False
    load_yaml_string = None


# ===========================================================================
# Fixtures
# ===========================================================================

@pytest.fixture
def frames_8x64():
    """8 frames of 64x64 uint8 numpy arrays."""
    rng = np.random.RandomState(42)
    arr = rng.randint(0, 256, (8, 64, 64, 3), dtype=np.uint8)
    return [arr[t] for t in range(8)]

@pytest.fixture
def frames_16x224():
    """16 frames of 224x224 uint8 numpy arrays."""
    rng = np.random.RandomState(99)
    arr = rng.randint(0, 256, (16, 224, 224, 3), dtype=np.uint8)
    return [arr[t] for t in range(16)]

@pytest.fixture
def default_aug_cfg():
    return AugConfig()

@pytest.fixture
def default_data_cfg():
    return DataConfig(
        data_paths=[],
        clip_mode="fps",
        frames_per_clip=8,
        img_size=64,
        num_workers=0,
        batch_size=2,
        pin_memory=False,
        persistent_workers=False,
    )

@pytest.fixture
def pipeline_64(default_aug_cfg):
    return VideoTransformPipeline(default_aug_cfg, img_size=64)

@pytest.fixture
def uniform_weights_1000():
    return [1.0] * 1000


# ===========================================================================
# Section 1: Clip Mode Tests (clip modes, frame counts)
# ===========================================================================

class TestClipModes:

    def test_fps_mode_output_shape(self):
        ds = VideoDataset(data_paths=[], clip_mode="fps", frames_per_clip=8, img_size=64)
        sample = ds[0]
        assert sample["video"].shape == (3, 8, 64, 64)

    def test_duration_mode_output_shape(self):
        ds = VideoDataset(data_paths=[], clip_mode="duration", frames_per_clip=8, img_size=64)
        sample = ds[0]
        assert sample["video"].shape == (3, 8, 64, 64)

    def test_frame_step_mode_output_shape(self):
        ds = VideoDataset(data_paths=[], clip_mode="frame_step", frames_per_clip=8, img_size=64)
        sample = ds[0]
        assert sample["video"].shape == (3, 8, 64, 64)

    @pytest.mark.parametrize("mode", ["fps", "duration", "frame_step"])
    def test_all_modes_return_fpc_frames(self, mode):
        FPC = 6
        ds = VideoDataset(data_paths=[], clip_mode=mode, frames_per_clip=FPC, img_size=32)
        sample = ds[0]
        assert sample["video"].shape[1] == FPC, f"mode={mode}: got T={sample[\'video\'].shape[1]}"

    @pytest.mark.parametrize("fpc", [4, 8, 16, 32])
    def test_fps_mode_various_fpc(self, fpc):
        ds = VideoDataset(data_paths=[], clip_mode="fps", frames_per_clip=fpc, img_size=32)
        sample = ds[0]
        assert sample["video"].shape[1] == fpc

    def test_invalid_clip_mode_raises(self):
        with pytest.raises(ValueError, match="clip_mode"):
            VideoDataset(data_paths=[], clip_mode="bogus")

    def test_return_dict_has_video_key(self):
        ds = VideoDataset(data_paths=[], clip_mode="fps", frames_per_clip=4, img_size=32)
        sample = ds[0]
        assert "video" in sample

    def test_return_dict_has_label_key(self):
        ds = VideoDataset(data_paths=[], clip_mode="fps", frames_per_clip=4, img_size=32)
        sample = ds[0]
        assert "label" in sample

    def test_return_dict_has_path_key(self):
        ds = VideoDataset(data_paths=[], clip_mode="fps", frames_per_clip=4, img_size=32)
        sample = ds[0]
        assert "path" in sample

    def test_output_dtype_float32(self):
        ds = VideoDataset(data_paths=[], clip_mode="fps", frames_per_clip=4, img_size=32)
        sample = ds[0]
        assert sample["video"].dtype == torch.float32

    def test_output_values_in_zero_one(self):
        ds = VideoDataset(data_paths=[], clip_mode="fps", frames_per_clip=4, img_size=32)
        sample = ds[0]
        assert sample["video"].min().item() >= 0.0
        assert sample["video"].max().item() <= 1.0

    def test_fps_frame_step_calculation(self):
        """Native fps=30, target=10: step should be 3."""
        indices = compute_frame_indices(
            total_frames=300, frames_per_clip=16,
            clip_mode="fps", native_fps=30.0, target_fps=10.0
        )
        assert len(indices) == 16
        # Verify step = 3 (approximately)
        if len(indices) >= 2:
            steps = [indices[i+1] - indices[i] for i in range(len(indices)-1)]
            assert all(s == 3 for s in steps)

    def test_duration_mode_linspace_indices(self):
        """Duration=1s at 30fps: clip_len=30, indices should span [start, start+29]."""
        indices = compute_frame_indices(
            total_frames=300, frames_per_clip=8,
            clip_mode="duration", native_fps=30.0, clip_duration_sec=1.0
        )
        assert len(indices) == 8
        span = max(indices) - min(indices)
        assert span <= 30, f"span={span} should be <= 30 for 1s clip at 30fps"

    def test_frame_step_stride(self):
        """frame_step=4: consecutive indices should differ by 4."""
        indices = compute_frame_indices(
            total_frames=200, frames_per_clip=8,
            clip_mode="frame_step", frame_step=4
        )
        assert len(indices) == 8
        steps = [indices[i+1] - indices[i] for i in range(len(indices)-1)]
        assert all(s == 4 for s in steps)


# ===========================================================================
# Section 2: Padding Tests
# ===========================================================================

class TestPadding:

    def test_short_video_fps_mode(self):
        """Video with 3 frames, need 16: circulant padding."""
        ds = VideoDataset(
            data_paths=[], clip_mode="fps", frames_per_clip=16,
            img_size=32, synthetic_num_frames=3,
        )
        sample = ds[0]
        assert sample["video"].shape == (3, 16, 32, 32)

    def test_short_video_is_non_zero(self):
        """Padded short video should have non-zero content."""
        ds = VideoDataset(
            data_paths=[], clip_mode="fps", frames_per_clip=16,
            img_size=32, synthetic_num_frames=3,
        )
        sample = ds[0]
        assert sample["video"].abs().sum().item() > 0

    def test_single_frame_video(self):
        """Single-frame video: all T frames should be identical copies."""
        ds = VideoDataset(
            data_paths=[], clip_mode="fps", frames_per_clip=8,
            img_size=32, synthetic_num_frames=1,
        )
        sample = ds[0]
        v = sample["video"]
        assert v.shape == (3, 8, 32, 32)
        # All temporal slices should be identical (same frame)
        for t in range(1, 8):
            assert torch.allclose(v[:, 0], v[:, t])

    def test_circulant_indices_stay_in_range(self):
        """All computed indices must be within [0, total_frames-1]."""
        total = 5
        for mode in ["fps", "duration", "frame_step"]:
            indices = compute_frame_indices(
                total_frames=total, frames_per_clip=16,
                clip_mode=mode, native_fps=30.0, target_fps=10.0,
                clip_duration_sec=1.0, frame_step=2
            )
            assert all(0 <= i < total for i in indices), \\
                f"mode={mode}: out-of-range indices {indices}"

    def test_exact_fit_no_padding_needed(self):
        """Video exactly fits: frame_step=1, fpc=10, total=10."""
        indices = compute_frame_indices(
            total_frames=10, frames_per_clip=10,
            clip_mode="frame_step", frame_step=1
        )
        assert len(indices) == 10
        assert all(0 <= i < 10 for i in indices)

    def test_zero_frame_video_returns_correct_length(self):
        """compute_frame_indices with total_frames=0 returns zeros."""
        indices = compute_frame_indices(
            total_frames=0, frames_per_clip=8, clip_mode="fps"
        )
        assert len(indices) == 8
        assert all(i == 0 for i in indices)

    def test_duration_mode_short_video(self):
        ds = VideoDataset(
            data_paths=[], clip_mode="duration", frames_per_clip=8,
            img_size=32, synthetic_num_frames=2, clip_duration_sec=5.0,
        )
        sample = ds[0]
        assert sample["video"].shape[1] == 8


# ===========================================================================
# Section 3: Transform Tests
# ===========================================================================

class TestTransforms:

    def test_train_transform_shape(self, frames_8x64, pipeline_64):
        out = pipeline_64.get_train_transform()(frames_8x64)
        assert out.shape == (3, 8, 64, 64)

    def test_eval_transform_shape(self, frames_8x64, pipeline_64):
        out = pipeline_64.get_eval_transform()(frames_8x64)
        assert out.shape == (3, 8, 64, 64)

    def test_train_transform_dtype(self, frames_8x64, pipeline_64):
        out = pipeline_64.get_train_transform()(frames_8x64)
        assert out.dtype == torch.float32

    def test_eval_transform_dtype(self, frames_8x64, pipeline_64):
        out = pipeline_64.get_eval_transform()(frames_8x64)
        assert out.dtype == torch.float32

    def test_eval_is_deterministic(self, frames_8x64, pipeline_64):
        eval_tfm = pipeline_64.get_eval_transform()
        out1 = eval_tfm(frames_8x64)
        out2 = eval_tfm(frames_8x64)
        assert torch.allclose(out1, out2)

    def test_normalized_range(self, frames_8x64, pipeline_64):
        out = pipeline_64.get_train_transform()(frames_8x64)
        # After normalization, values should be roughly in [-3, 3]
        assert out.min().item() > -10.0
        assert out.max().item() < 10.0

    def test_channel_dim_is_3(self, frames_8x64, pipeline_64):
        out = pipeline_64.get_train_transform()(frames_8x64)
        assert out.shape[0] == 3

    def test_spatial_size_correct(self, frames_8x64, pipeline_64):
        out = pipeline_64.get_train_transform()(frames_8x64)
        assert out.shape[2] == 64
        assert out.shape[3] == 64

    def test_temporal_dim_correct(self, frames_8x64, pipeline_64):
        out = pipeline_64.get_train_transform()(frames_8x64)
        assert out.shape[1] == 8

    def test_clip_to_tensor_shape(self, frames_8x64):
        ctt = ClipToTensor()
        out = ctt(frames_8x64)
        assert out.shape == (3, 8, 64, 64)

    def test_clip_to_tensor_dtype(self, frames_8x64):
        ctt = ClipToTensor()
        out = ctt(frames_8x64)
        assert out.dtype == torch.float32

    def test_clip_to_tensor_range(self, frames_8x64):
        ctt = ClipToTensor()
        out = ctt(frames_8x64)
        assert out.min().item() >= 0.0
        assert out.max().item() <= 1.0

    def test_normalize_mean_shift(self):
        """White image after normalization should have negative values (mean subtracted)."""
        white_frames = [np.ones((64, 64, 3), dtype=np.uint8) * 255] * 4
        ctt = ClipToTensor()
        norm = VideoNormalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
        tensor = ctt(white_frames)
        normalized = norm(tensor)
        # White pixels (1.0) normalized by mean=0.5, std=0.5 -> (1.0-0.5)/0.5 = 1.0
        assert abs(normalized.mean().item() - 1.0) < 0.05


# ===========================================================================
# Section 4: Augmentation Determinism
# ===========================================================================

class TestAugmentationDeterminism:

    def test_fixed_seed_reproducibility(self, frames_8x64, pipeline_64):
        """Same seed -> same train transform output."""
        train_tfm = pipeline_64.get_train_transform()
        torch.manual_seed(42); random.seed(42)
        out1 = train_tfm(frames_8x64)
        torch.manual_seed(42); random.seed(42)
        out2 = train_tfm(frames_8x64)
        assert torch.allclose(out1, out2)

    def test_different_seeds_different_output(self, frames_8x64, pipeline_64):
        """Different seeds should (almost certainly) produce different crops."""
        train_tfm = pipeline_64.get_train_transform()
        torch.manual_seed(0); random.seed(0)
        out0 = train_tfm(frames_8x64)
        torch.manual_seed(99999); random.seed(99999)
        out1 = train_tfm(frames_8x64)
        # Not allclose (different crops should differ in general)
        assert not torch.allclose(out0, out1)

    def test_eval_same_output_twice(self, frames_8x64, pipeline_64):
        """Eval transform: calling twice gives same result (no randomness)."""
        eval_tfm = pipeline_64.get_eval_transform()
        a = eval_tfm(frames_8x64)
        b = eval_tfm(frames_8x64)
        assert torch.allclose(a, b)


# ===========================================================================
# Section 5: Temporal Consistency
# ===========================================================================

class TestTemporalConsistency:

    def test_rrc_same_crop_all_frames(self):
        """RandomResizedCrop must apply the same crop to all frames."""
        identical_frames = [np.ones((128, 128, 3), dtype=np.uint8) * 100] * 8
        # Vary pixel values so we can detect mismatched crops
        for t in range(8):
            identical_frames[t] = identical_frames[0].copy()
        rrc = VideoRandomResizedCrop(64)
        cropped = rrc(identical_frames)
        # Convert to tensors
        ctt = ClipToTensor()
        tensor = ctt(cropped)
        # All temporal frames should be identical
        for t in range(1, 8):
            assert torch.allclose(tensor[:, 0], tensor[:, t]), \\
                f"Frame {t} differs from frame 0 after RRC"

    def test_horizontal_flip_all_or_none(self):
        """HorizontalFlip: same decision for all frames (consistent)."""
        # Use IDENTICAL frames so we can verify the same flip is applied to all
        rng = np.random.RandomState(7)
        base_frame = rng.randint(0, 256, (64, 64, 3), dtype=np.uint8)
        frames = [base_frame.copy() for _ in range(8)]
        flip = VideoRandomHorizontalFlip(p=1.0)  # Always flip
        ctt = ClipToTensor()
        out = ctt(flip(frames))
        # All frames should be identical (same flip applied to identical content)
        for t in range(1, 8):
            assert torch.allclose(out[:, 0], out[:, t]), \\
                f"Flip inconsistent: frame {t} differs"

    def test_random_erasing_cube_same_region(self):
        """Cube-mode erasing: same region erased in all frames."""
        tensor = torch.ones(3, 8, 64, 64)
        eraser = VideoRandomErasing(p=1.0, scale=(0.1, 0.3), cube_mode=True)
        erased = eraser(tensor)
        zero_mask = (erased[:, 0] == 0)
        assert zero_mask.any(), "p=1.0 erasing should always erase something"
        for t in range(1, 8):
            assert (erased[:, t][zero_mask] == 0).all(), \\
                f"Frame {t} missing erased region"

    def test_motion_shift_output_shape(self):
        """MotionShift should not change frame shape."""
        frames = [np.ones((64, 64, 3), dtype=np.uint8) * 128] * 8
        shifter = VideoMotionShift(max_shift_frac=0.1)
        shifted = shifter(frames)
        assert len(shifted) == 8
        assert shifted[0].shape == (64, 64, 3)


# ===========================================================================
# Section 6: ConcatIndices Tests
# ===========================================================================

class TestConcatIndices:

    def test_basic_three_sources(self):
        ci = ConcatIndices([1000, 500, 250])
        assert ci[0]    == (0, 0)
        assert ci[999]  == (0, 999)
        assert ci[1000] == (1, 0)
        assert ci[1499] == (1, 499)
        assert ci[1500] == (2, 0)
        assert ci[1749] == (2, 249)

    def test_total_length(self):
        ci = ConcatIndices([1000, 500, 250])
        assert len(ci) == 1750

    def test_single_source(self):
        ci = ConcatIndices([500])
        assert ci[0]   == (0, 0)
        assert ci[499] == (0, 499)
        assert len(ci) == 500

    def test_two_equal_sources(self):
        ci = ConcatIndices([100, 100])
        assert ci[0]   == (0, 0)
        assert ci[99]  == (0, 99)
        assert ci[100] == (1, 0)
        assert ci[199] == (1, 99)

    def test_negative_index_raises(self):
        ci = ConcatIndices([100])
        with pytest.raises(IndexError):
            ci[-1]

    def test_out_of_range_raises(self):
        ci = ConcatIndices([100])
        with pytest.raises(IndexError):
            ci[100]

    def test_get_dataset_ranges(self):
        ci = ConcatIndices([1000, 500, 250])
        ranges = ci.get_dataset_ranges()
        assert ranges == [(0, 1000), (1000, 1500), (1500, 1750)]

    def test_zero_size_source(self):
        ci = ConcatIndices([0, 100, 0])
        assert len(ci) == 100
        assert ci[0] == (1, 0)
        assert ci[99] == (1, 99)

    def test_consecutive_mapping(self):
        """Every global idx must map to a valid (ds, sample) pair."""
        ci = ConcatIndices([3, 4, 2])
        all_pairs = [ci[i] for i in range(9)]
        assert all_pairs[0] == (0, 0)
        assert all_pairs[2] == (0, 2)
        assert all_pairs[3] == (1, 0)
        assert all_pairs[6] == (1, 3)
        assert all_pairs[7] == (2, 0)
        assert all_pairs[8] == (2, 1)

    def test_expand_weights_to_samples(self):
        expanded = expand_weights_to_samples([3, 2], [6.0, 4.0])
        assert len(expanded) == 5
        # Source 0: 6/3=2.0 per sample
        assert all(abs(w - 2.0) < 1e-9 for w in expanded[:3])
        # Source 1: 4/2=2.0 per sample
        assert all(abs(w - 2.0) < 1e-9 for w in expanded[3:])


# ===========================================================================
# Section 7: DistributedWeightedSampler Tests
# ===========================================================================

class TestDistributedWeightedSampler:

    def test_single_rank_no_duplicates(self, uniform_weights_1000):
        s = DistributedWeightedSampler(uniform_weights_1000, 1000, rank=0, world_size=1, seed=0)
        indices = list(s)
        assert len(set(indices)) == 1000

    def test_single_rank_full_coverage(self, uniform_weights_1000):
        s = DistributedWeightedSampler(uniform_weights_1000, 1000, rank=0, world_size=1, seed=0)
        assert set(list(s)) == set(range(1000))

    def test_two_ranks_no_cross_overlap(self, uniform_weights_1000):
        s0 = DistributedWeightedSampler(uniform_weights_1000, 1000, rank=0, world_size=2, seed=0)
        s1 = DistributedWeightedSampler(uniform_weights_1000, 1000, rank=1, world_size=2, seed=0)
        assert len(set(list(s0)) & set(list(s1))) == 0

    def test_two_ranks_full_coverage(self, uniform_weights_1000):
        s0 = DistributedWeightedSampler(uniform_weights_1000, 1000, rank=0, world_size=2, seed=0)
        s1 = DistributedWeightedSampler(uniform_weights_1000, 1000, rank=1, world_size=2, seed=0)
        covered = set(list(s0)) | set(list(s1))
        assert len(covered) >= 998  # Allow minor padding artifacts

    def test_four_ranks_no_cross_overlap(self, uniform_weights_1000):
        samplers = [
            DistributedWeightedSampler(uniform_weights_1000, 1000, rank=r, world_size=4, seed=0)
            for r in range(4)
        ]
        rank_sets = [set(list(s)) for s in samplers]
        for i in range(4):
            for j in range(i+1, 4):
                assert len(rank_sets[i] & rank_sets[j]) == 0, \\
                    f"Ranks {i} and {j} have overlap"

    def test_set_epoch_changes_order(self, uniform_weights_1000):
        s = DistributedWeightedSampler(uniform_weights_1000, 1000, rank=0, world_size=1, seed=0)
        s.set_epoch(0); order0 = list(s)
        s.set_epoch(1); order1 = list(s)
        assert order0 != order1

    def test_same_epoch_reproducible(self, uniform_weights_1000):
        s = DistributedWeightedSampler(uniform_weights_1000, 1000, rank=0, world_size=1, seed=0)
        s.set_epoch(42); run1 = list(s)
        s.set_epoch(42); run2 = list(s)
        assert run1 == run2

    def test_len_single_rank(self, uniform_weights_1000):
        s = DistributedWeightedSampler(uniform_weights_1000, 1000, rank=0, world_size=1)
        assert len(s) == 1000

    def test_len_two_ranks(self, uniform_weights_1000):
        for r in range(2):
            s = DistributedWeightedSampler(uniform_weights_1000, 1000, rank=r, world_size=2)
            assert len(s) == math.ceil(1000 / 2)

    def test_len_four_ranks(self, uniform_weights_1000):
        for r in range(4):
            s = DistributedWeightedSampler(uniform_weights_1000, 1000, rank=r, world_size=4)
            assert len(s) == math.ceil(1000 / 4)

    def test_weight_distribution_two_to_one(self):
        """Source A (600 samples, w=2.0) should appear ~2/3 of the time."""
        w_a = [2.0 / 600] * 600
        w_b = [1.0 / 400] * 400
        s = DistributedWeightedSampler(w_a + w_b, 1000, rank=0, world_size=1, seed=0)
        indices = list(s)
        count_a = sum(1 for i in indices if i < 600)
        prop_a = count_a / len(indices)
        assert abs(prop_a - 2/3) < 0.10, f"prop_a={prop_a:.3f}"

    def test_invalid_rank_raises(self, uniform_weights_1000):
        with pytest.raises(ValueError):
            DistributedWeightedSampler(uniform_weights_1000, 1000, rank=4, world_size=4)

    def test_invalid_rank_negative_raises(self, uniform_weights_1000):
        with pytest.raises(ValueError):
            DistributedWeightedSampler(uniform_weights_1000, 1000, rank=-1, world_size=4)

    def test_replacement_mode_yields_correct_count(self, uniform_weights_1000):
        s = DistributedWeightedSampler(
            uniform_weights_1000, 1000, rank=0, world_size=1, replacement=True
        )
        indices = list(s)
        assert len(indices) >= 1000

    def test_all_zero_weights_fallback(self):
        """All-zero weights should not crash; use random shuffle fallback."""
        zero_weights = [0.0] * 100
        s = DistributedWeightedSampler(zero_weights, 100, rank=0, world_size=1, seed=0)
        indices = list(s)
        assert len(indices) == 100


# ===========================================================================
# Section 8: Worker Seeding
# ===========================================================================

class TestWorkerSeeding:

    LCG_A = 1664525
    LCG_C = 1013904223
    LCG_M = 2**32

    def lcg_seed(self, worker_id, base_seed):
        return (self.LCG_A * (base_seed + worker_id) + self.LCG_C) % self.LCG_M

    def test_unique_seeds_per_worker(self):
        """8 workers should get 8 unique LCG seeds."""
        seeds = [self.lcg_seed(w, 12345) for w in range(8)]
        assert len(set(seeds)) == 8

    def test_reproducible_seed_same_worker(self):
        """Same worker_id + base_seed always produces same seed."""
        s1 = self.lcg_seed(3, 99999)
        s2 = self.lcg_seed(3, 99999)
        assert s1 == s2

    def test_different_base_seeds_different_result(self):
        """Different base seeds produce different worker seeds."""
        s1 = self.lcg_seed(0, 42)
        s2 = self.lcg_seed(0, 43)
        assert s1 != s2

    def test_seed_in_valid_range(self):
        """All seeds must be in [0, 2^32)."""
        for w in range(16):
            s = self.lcg_seed(w, 12345)
            assert 0 <= s < 2**32


# ===========================================================================
# Section 9: DataConfig Tests
# ===========================================================================

class TestDataConfig:

    def test_default_clip_mode(self):
        assert DataConfig().clip_mode == "fps"

    def test_default_frames_per_clip(self):
        assert DataConfig().frames_per_clip == 16

    def test_default_img_size(self):
        assert DataConfig().img_size == 224

    def test_default_batch_size(self):
        assert DataConfig().batch_size == 64

    def test_from_dict_partial(self):
        dc = DataConfig.from_dict({"batch_size": 32, "clip_mode": "duration"})
        assert dc.batch_size == 32
        assert dc.clip_mode == "duration"
        assert dc.frames_per_clip == 16  # Default preserved

    def test_from_dict_empty(self):
        dc = DataConfig.from_dict({})
        assert dc.clip_mode == "fps"

    def test_round_trip_to_dict(self):
        dc = DataConfig(batch_size=32, clip_mode="frame_step", data_paths=["/a"])
        dc2 = DataConfig.from_dict(dc.to_dict())
        assert dc == dc2

    def test_validate_invalid_clip_mode(self):
        errs = DataConfig(clip_mode="invalid").validate()
        assert any("clip_mode" in e for e in errs)

    def test_validate_weight_mismatch(self):
        errs = DataConfig(data_paths=["/a", "/b"], data_weights=[1.0]).validate()
        assert any("weight" in e.lower() for e in errs)

    def test_validate_zero_batch_size(self):
        errs = DataConfig(batch_size=0).validate()
        assert any("batch_size" in e for e in errs)

    def test_validate_negative_fpc(self):
        errs = DataConfig(frames_per_clip=-1).validate()
        assert any("frames_per_clip" in e for e in errs)

    def test_assert_valid_raises_on_invalid(self):
        with pytest.raises(ValueError):
            DataConfig(clip_mode="bad").assert_valid()

    def test_valid_config_passes_validation(self):
        dc = DataConfig(data_paths=["/a"], data_weights=[1.0], clip_mode="fps")
        assert dc.validate() == []

    def test_multiple_paths_and_weights_valid(self):
        dc = DataConfig(
            data_paths=["/a", "/b", "/c"],
            data_weights=[1.0, 2.0, 1.5],
            clip_mode="fps"
        )
        assert dc.validate() == []


# ===========================================================================
# Section 10: AugConfig Tests
# ===========================================================================

class TestAugConfig:

    def test_default_crop_scale(self):
        assert AugConfig().crop_scale == (0.3, 1.0)

    def test_default_horizontal_flip(self):
        assert AugConfig().horizontal_flip is True

    def test_default_auto_augment(self):
        assert AugConfig().auto_augment is False

    def test_default_random_erasing(self):
        assert AugConfig().random_erasing == 0.0

    def test_default_normalize_mean(self):
        assert AugConfig().normalize_mean == (0.485, 0.456, 0.406)

    def test_default_normalize_std(self):
        assert AugConfig().normalize_std == (0.229, 0.224, 0.225)

    def test_from_dict_partial(self):
        ac = AugConfig.from_dict({"auto_augment": True, "random_erasing": 0.25})
        assert ac.auto_augment is True
        assert ac.random_erasing == 0.25
        assert ac.horizontal_flip is True  # Default

    def test_round_trip(self):
        ac = AugConfig(crop_scale=(0.5, 0.9), auto_augment=True, random_erasing=0.25)
        ac2 = AugConfig.from_dict(ac.to_dict())
        assert ac == ac2

    def test_robotics_preset_no_flip(self):
        assert AugConfig.robotics().horizontal_flip is False

    def test_robotics_preset_fixed_scale(self):
        rob = AugConfig.robotics()
        assert rob.crop_scale[0] >= 0.85

    def test_robotics_no_motion_shift(self):
        assert AugConfig.robotics().motion_shift is False

    def test_validate_invalid_crop_scale(self):
        errs = AugConfig(crop_scale=(1.5, 0.5)).validate()
        assert len(errs) > 0

    def test_validate_invalid_erasing_prob(self):
        errs = AugConfig(random_erasing=1.5).validate()
        assert len(errs) > 0

    def test_validate_defaults_pass(self):
        assert AugConfig().validate() == []


# ===========================================================================
# Section 11: Config Utilities
# ===========================================================================

class TestConfigUtils:

    def test_get_section_existing(self):
        cfg = {"data": {"batch_size": 32}}
        assert get_section(cfg, "data") == {"batch_size": 32}

    def test_get_section_missing(self):
        assert get_section({}, "data") == {}

    def test_get_section_null_value(self):
        assert get_section({"data": None}, "data") == {}

    def test_merge_configs_simple(self):
        base = {"a": 1, "b": 2}
        over = {"b": 99, "c": 3}
        merged = merge_configs(base, over)
        assert merged == {"a": 1, "b": 99, "c": 3}

    def test_merge_configs_nested(self):
        base = {"data": {"batch_size": 64, "img_size": 224}}
        over = {"data": {"batch_size": 32}}
        merged = merge_configs(base, over)
        assert merged["data"]["batch_size"] == 32
        assert merged["data"]["img_size"] == 224

    def test_merge_configs_deep_nested(self):
        base = {"a": {"b": {"c": 1, "d": 2}}}
        over = {"a": {"b": {"c": 99}}}
        merged = merge_configs(base, over)
        assert merged["a"]["b"]["c"] == 99
        assert merged["a"]["b"]["d"] == 2

    def test_merge_configs_does_not_mutate_base(self):
        base = {"data": {"batch_size": 64}}
        over = {"data": {"batch_size": 32}}
        merge_configs(base, over)
        assert base["data"]["batch_size"] == 64

    def test_validate_config_valid(self):
        cfg = {
            "data": {"clip_mode": "fps", "batch_size": 64, "frames_per_clip": 16},
            "data_aug": {"crop_scale": [0.3, 1.0], "random_erasing": 0.0}
        }
        assert validate_config(cfg) == []

    def test_validate_config_invalid_clip_mode(self):
        cfg = {"data": {"clip_mode": "bad"}}
        errs = validate_config(cfg)
        assert len(errs) > 0

    @pytest.mark.skipif(not _YAML_AVAILABLE, reason="pyyaml not installed")
    def test_yaml_round_trip_data_config(self):
        dc = DataConfig(batch_size=32, frames_per_clip=8)
        from data_config_template import load_yaml_string
        yaml_str = dc.to_yaml_str()
        loaded = DataConfig.from_dict(yaml.safe_load(yaml_str) or {})
        assert dc == loaded

    @pytest.mark.skipif(not _YAML_AVAILABLE, reason="pyyaml not installed")
    def test_load_yaml_string_basic(self):
        yaml_str = "data:\\n  batch_size: 16\\n"
        raw = load_yaml_string(yaml_str)
        assert get_section(raw, "data")["batch_size"] == 16
'''

# Add yaml import for the yaml round-trip test
GENERATED_TESTS = GENERATED_TESTS.replace(
    "import pytest\nimport torch",
    "import pytest\nimport torch\ntry:\n    import yaml\nexcept ImportError:\n    yaml = None"
)


# ---------------------------------------------------------------------------
# Script entry point
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate pytest tests for V-JEPA 2 data pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--output", type=str,
        default=str(Path(__file__).resolve().parent.parent / "tests" / "test_vjepa2_data_pipeline.py"),
        help="Output path for generated test file"
    )
    parser.add_argument(
        "--run", action="store_true",
        help="Run the generated tests immediately after writing"
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    output_path.write_text(GENERATED_TESTS, encoding="utf-8")
    print(f"Generated {sum(1 for line in GENERATED_TESTS.splitlines() if 'def test_' in line)} test functions")
    print(f"Written to: {output_path}")

    if args.run:
        import subprocess
        print("\nRunning generated tests...")
        result = subprocess.run(
            [sys.executable, "-m", "pytest", str(output_path), "-v", "--tb=short"],
            cwd=str(output_path.parent.parent)
        )
        return result.returncode

    return 0


if __name__ == "__main__":
    sys.exit(main())
