#!/usr/bin/env python3
"""
gen_delay_tau_tests.py -- Generate parameterized pytest suite for delay modules
and heterogeneous tau.

Generates tests/test_delays_tau.py (or a specified output path) with:
- 12 test classes covering DCLS-style learnable delays and heterogeneous tau
- Parameterized over granularity modes, init strategies, and device
- CUDA tests skipped if no GPU
- Slow / integration tests marked with @pytest.mark.slow / @pytest.mark.integration
- Compatible with pytest-xdist for parallel execution

Usage:
    python gen_delay_tau_tests.py                          # Generate to default path
    python gen_delay_tau_tests.py --output path/to/out.py  # Custom output
    python gen_delay_tau_tests.py --timesteps 20           # Configure timesteps
    python gen_delay_tau_tests.py --batch-size 4           # Configure batch size
    python gen_delay_tau_tests.py --max-delay 8            # Configure max delay Td

Generated test structure:
    TestDelayLinearContract       -- Forward shapes, delay range, history update
    TestDelayConv1dContract       -- Conv delay shapes, per-channel delay params
    TestGaussianInterpolation     -- Kernel normalization, sigma limits, symmetry
    TestEvalDiscretization        -- Integer delays, eval vs train, eval mode flag
    TestSigmaSchedule             -- Monotonic decrease, convergence, checkpoint
    TestDelayGradients            -- Gradient existence, nonzero, finite diff
    TestHeterogeneousTauContract  -- Beta/tau ranges, softplus/exp mappings, broadcast
    TestTauInitStrategies         -- Homogeneous, gamma, loguniform, preset bank
    TestTauGradients              -- Gradient exists, no-grad fixed, magnitude check
    TestCheckpointRoundTrip       -- state_dict keys, reload output, cross-device
    TestIntegration               -- Delay+LIF, tau+LIF, combined, full unroll, ablation
    TestMemoryAndPerformance      -- Memory threshold, delay overhead, tau overhead
"""

import argparse
import os
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate parameterized pytest suite for delay modules and heterogeneous tau."
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help=(
            "Destination file path for the generated test file. "
            "Defaults to <repo_root>/tests/test_delays_tau.py"
        ),
    )
    parser.add_argument(
        "--timesteps",
        type=int,
        default=20,
        help="Default number of timesteps T used in most tests (default: 20).",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=4,
        dest="batch_size",
        help="Batch size used in most tests (default: 4).",
    )
    parser.add_argument(
        "--max-delay",
        type=int,
        default=8,
        dest="max_delay",
        help="Maximum delay Td in timesteps (default: 8, smaller for fast tests).",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _default_output_path() -> Path:
    """Return <repo_root>/tests/test_delays_tau.py relative to this script."""
    script_dir = Path(__file__).resolve().parent
    # scripts/ -> delays-heterogeneous-tau/ -> skills/ -> brain-ai-dev/ -> human-brain/
    repo_root = script_dir.parent.parent.parent.parent
    tests_dir = repo_root / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    return tests_dir / "test_delays_tau.py"


# ---------------------------------------------------------------------------
# Template sections
# ---------------------------------------------------------------------------

def _header(timesteps: int, batch_size: int, max_delay: int) -> str:
    return f'''\
# ============================================================
# test_delays_tau.py
# Auto-generated by gen_delay_tau_tests.py -- do not edit by hand.
# Re-generate with:
#   python skills/delays-heterogeneous-tau/scripts/gen_delay_tau_tests.py
# ============================================================

"""
Comprehensive parameterized pytest suite for DCLS-style learnable delays
and heterogeneous membrane time constants (tau) in BrainAI's SNN core.

Test classes:
  TestDelayLinearContract       -- Forward shapes, delay param shape, delay range,
                                   spike history buffer update
  TestDelayConv1dContract       -- Conv1d delay output shape, per-channel delay params
  TestGaussianInterpolation     -- Kernel normalization, sigma-zero limit, symmetry
  TestEvalDiscretization        -- Integer delays after rounding, eval vs training
                                   closeness, inference mode flag trigger
  TestSigmaSchedule             -- Monotonic decrease, convergence to sigma_end,
                                   constant schedule, checkpoint roundtrip
  TestDelayGradients            -- d_raw.grad exists, nonzero, no-grad fixed,
                                   finite-difference spot-check (rtol=1e-2)
  TestHeterogeneousTauContract  -- beta in (0,1), tau > 0, softplus mapping,
                                   exp(-dt/tau) match, broadcast shape
  TestTauInitStrategies         -- Homogeneous all-equal, gamma distribution,
                                   loguniform, preset bank
  TestTauGradients              -- tau_raw.grad exists learnable, no-grad fixed,
                                   gradient magnitude not vanishing
  TestCheckpointRoundTrip       -- d_raw/sigma/epoch in state_dict, tau_raw in
                                   state_dict, reload identical output, cross-device
  TestIntegration               -- Delay+LIF, tau+LIF, both together, SNN unroll,
                                   4-config ablation matrix
  TestMemoryAndPerformance      -- Peak memory under threshold, delay overhead < 2x,
                                   tau overhead < 1.2x

Configuration baked in at generation time:
  DEFAULT_T          = {timesteps}
  DEFAULT_BATCH_SIZE = {batch_size}
  DEFAULT_MAX_DELAY  = {max_delay}

Run fast tests only (excludes @pytest.mark.slow):
    pytest tests/test_delays_tau.py -v

Run only delay tests:
    pytest tests/test_delays_tau.py -v -m delay

Run only tau tests:
    pytest tests/test_delays_tau.py -v -m tau

Run integration tests:
    pytest tests/test_delays_tau.py -v -m integration

Run in parallel (requires pytest-xdist):
    pytest tests/test_delays_tau.py -v -n auto
"""
'''


def _imports_and_constants(timesteps: int, batch_size: int, max_delay: int) -> str:
    return f'''\
import math
import warnings
import io
import pytest
import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Import delay modules -- handle both target and legacy APIs gracefully.
# ---------------------------------------------------------------------------

try:
    from brain_ai.core.delays import (
        DelayLinear,
        DelayConv1d,
        GaussianDelayKernel,
        SigmaSchedule,
    )
    HAS_DELAY_MODULES = True
except ImportError:
    HAS_DELAY_MODULES = False

    class _Stub(nn.Module):
        def __init__(self, *a, **kw):
            super().__init__()
        def forward(self, x, *a, **kw):
            return x

    DelayLinear = _Stub
    DelayConv1d = _Stub

    class GaussianDelayKernel:
        pass

    class SigmaSchedule:
        pass

# ---------------------------------------------------------------------------
# Import heterogeneous tau modules -- handle both target and legacy APIs.
# ---------------------------------------------------------------------------

try:
    from brain_ai.core.hetero_tau import (
        HeterogeneousTau,
        TauInitConfig,
    )
    HAS_TAU_MODULE = True
except ImportError:
    HAS_TAU_MODULE = False

    class TauInitConfig:
        def __init__(
            self,
            strategy: str = "heterogeneous_gamma",
            tau_0: float = 20.0,
            tau_min: float = 1.0,
            tau_max: float = 100.0,
            dt: float = 1.0,
            gamma_k: float = 2.0,
            gamma_theta: float = 10.0,
            preset_values=None,
            preset_mode: str = "cyclic",
        ):
            self.strategy = strategy
            self.tau_0 = tau_0
            self.tau_min = tau_min
            self.tau_max = tau_max
            self.dt = dt
            self.gamma_k = gamma_k
            self.gamma_theta = gamma_theta
            self.preset_values = preset_values or [2.0, 5.0, 10.0, 20.0, 50.0]
            self.preset_mode = preset_mode

    def _init_tau_values(n: int, cfg: "TauInitConfig") -> torch.Tensor:
        """Initialize tau values (in physical units) according to the strategy."""
        tau_min = cfg.tau_min
        tau_max = cfg.tau_max
        tau_0   = cfg.tau_0

        if cfg.strategy == "homogeneous":
            tau = torch.full((n,), tau_0).clamp(tau_min, tau_max)

        elif cfg.strategy == "heterogeneous_gamma":
            k     = cfg.gamma_k
            theta = tau_0 / k
            dist  = torch.distributions.Gamma(
                torch.tensor(k), torch.tensor(1.0 / theta)
            )
            tau = dist.sample((n,)).clamp(tau_min, tau_max)

        elif cfg.strategy == "heterogeneous_loguniform":
            import math
            log_min = math.log(tau_min)
            log_max = math.log(tau_max)
            log_tau = torch.empty(n).uniform_(log_min, log_max)
            tau = log_tau.exp().clamp(tau_min, tau_max)

        elif cfg.strategy == "preset_bank":
            presets = cfg.preset_values or [2.0, 5.0, 10.0, 20.0, 50.0]
            preset_t = torch.tensor(presets).clamp(tau_min, tau_max)
            if cfg.preset_mode == "cyclic":
                indices = torch.arange(n) % len(presets)
            else:
                indices = torch.randint(len(presets), (n,))
            tau = preset_t[indices]

        else:
            # Unknown strategy: fall back to homogeneous
            tau = torch.full((n,), tau_0).clamp(tau_min, tau_max)

        return tau

    def _tau_to_raw(tau: torch.Tensor, tau_min: float) -> torch.Tensor:
        """Invert tau = tau_min + softplus(tau_raw) to get tau_raw."""
        # softplus(x) = log(1 + exp(x))
        # tau - tau_min = log(1 + exp(tau_raw))
        # exp(tau_raw) = exp(tau - tau_min) - 1
        # tau_raw = log(exp(tau - tau_min) - 1)   [= softplus_inv]
        val = (tau - tau_min).clamp(min=1e-6)
        return val.expm1().clamp(min=1e-8).log()

    class HeterogeneousTau(nn.Module):
        def __init__(self, n, learnable=True, init_cfg=None, dt=1.0,
                     tau_min=1.0, tau_max=100.0, beta_min=0.0, beta_max=0.999):
            super().__init__()
            cfg = init_cfg or TauInitConfig()
            self.dt = dt
            self.tau_min = tau_min
            self.tau_max = tau_max
            self.beta_min = beta_min
            self.beta_max = beta_max
            # Initialize tau values per strategy, then invert to tau_raw
            tau_init = _init_tau_values(n, cfg)
            tau_raw_init = _tau_to_raw(tau_init, tau_min)
            if learnable:
                self.tau_raw = nn.Parameter(tau_raw_init)
            else:
                self.register_buffer("tau_raw", tau_raw_init)

        @property
        def tau(self):
            return (self.tau_min + F.softplus(self.tau_raw)).clamp(max=self.tau_max)

        @property
        def beta(self):
            tau_fp32 = self.tau.float()
            beta_fp32 = torch.exp(-self.dt / tau_fp32)
            return beta_fp32.clamp(self.beta_min, self.beta_max)

# ---------------------------------------------------------------------------
# Import LIFNeuron for integration tests
# ---------------------------------------------------------------------------

try:
    from brain_ai.core.neurons import LIFNeuron
    HAS_LIF = True
except ImportError:
    HAS_LIF = False

    class LIFNeuron(nn.Module):
        def __init__(self, beta=0.9, threshold=1.0, surrogate="atan", **kw):
            super().__init__()
            self.beta_val = beta
            self.threshold = threshold
            self.mem = None

        def reset_mem(self):
            self.mem = None

        def forward(self, x):
            if self.mem is None:
                self.mem = torch.zeros_like(x)
            self.mem = self.beta_val * self.mem + x
            spk = (self.mem >= self.threshold).float()
            self.mem = self.mem * (1.0 - spk)
            return spk, self.mem

# ---------------------------------------------------------------------------
# pytest markers registration (avoids PytestUnknownMarkWarning)
# ---------------------------------------------------------------------------

def pytest_configure(config):
    config.addinivalue_line("markers", "delay: delay module tests")
    config.addinivalue_line("markers", "tau: heterogeneous tau tests")
    config.addinivalue_line("markers", "integration: integration tests")
    config.addinivalue_line("markers", "slow: slow tests excluded from fast run")

# ---------------------------------------------------------------------------
# Constants baked in at generation time
# ---------------------------------------------------------------------------

DEFAULT_T = {timesteps}
DEFAULT_BATCH = {batch_size}
DEFAULT_MAX_DELAY = {max_delay}

HAS_CUDA = torch.cuda.is_available()
DEVICES = ["cpu"] + (["cuda"] if HAS_CUDA else [])

GRANULARITY_MODES = ["per_neuron", "per_channel", "per_layer"]
TAU_INIT_STRATEGIES = ["homogeneous", "heterogeneous_gamma",
                       "heterogeneous_loguniform", "preset_bank"]

# ---------------------------------------------------------------------------
# Minimal delay module stubs for offline / import-fallback testing.
# These provide just enough behaviour for tests to validate contracts
# without requiring the full brain_ai installation.
# ---------------------------------------------------------------------------

class _TinyDelayLinear(nn.Module):
    """
    Minimal DCLS-style learnable delay linear layer for contract testing.

    Implements Gaussian soft-delay interpolation over a spike history buffer
    of length Td.  The parameter d_raw (shape determined by granularity) is
    mapped to a continuous delay in [0, Td-1] via sigmoid * (Td - 1).

    The Gaussian kernel g[k] = exp(-0.5 * ((k - d) / sigma)^2) is normalized
    to sum to 1 and used to weight the history buffer contents.
    """

    GRANULARITY_SHAPES = {{
        "per_neuron":  lambda in_f, out_f, Td: (out_f,),
        "per_channel": lambda in_f, out_f, Td: (out_f,),
        "per_layer":   lambda in_f, out_f, Td: (1,),
    }}

    def __init__(
        self,
        in_features: int,
        out_features: int,
        max_delay: int = 8,
        sigma: float = 1.0,
        granularity: str = "per_neuron",
        fixed: bool = False,
    ):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.max_delay = max_delay
        self.sigma = sigma
        self.granularity = granularity
        self.fixed = fixed

        self.linear = nn.Linear(in_features, out_features)

        shape_fn = self.GRANULARITY_SHAPES.get(
            granularity, lambda *a: (out_features,)
        )
        d_shape = shape_fn(in_features, out_features, max_delay)

        d_init = torch.zeros(d_shape)
        if fixed:
            self.register_buffer("d_raw", d_init)
        else:
            self.d_raw = nn.Parameter(d_init)

        # History buffer: list of (out_features,)-shaped tensors
        self._history: List[Optional[torch.Tensor]] = [None] * max_delay

    @property
    def delays(self) -> torch.Tensor:
        """Continuous delay values in [0, Td - 1]."""
        return torch.sigmoid(self.d_raw) * (self.max_delay - 1)

    def _gaussian_kernel(self, d: torch.Tensor) -> torch.Tensor:
        """
        Compute normalized Gaussian kernel over delay bins [0, Td-1].

        d: (...) tensor of continuous delay positions.
        Returns: (..., Td) normalized kernel weights.
        """
        bins = torch.arange(self.max_delay, dtype=d.dtype, device=d.device)
        diff = bins - d.unsqueeze(-1)   # (..., Td)
        log_k = -0.5 * (diff / (self.sigma + 1e-8)) ** 2
        k = log_k.exp()
        k = k / (k.sum(dim=-1, keepdim=True) + 1e-12)
        return k

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        x: (B, in_features) -- current timestep input.
        Returns: (B, out_features) soft-delay-weighted output.
        """
        h = self.linear(x)   # (B, out_features)

        # Rotate history without in-place: prepend new entry, drop oldest
        new_history = [h.detach()] + self._history[:-1]
        self._history = new_history

        # Soft interpolation over available history
        valid = [t for t in self._history if t is not None]
        if not valid:
            return torch.zeros(
                x.shape[0], self.out_features,
                device=x.device, dtype=x.dtype
            )

        hist_stack = torch.stack(valid, dim=0)   # (Td_avail, B, out_f)
        Td_avail = hist_stack.shape[0]

        d = self.delays   # (out_f,) or (1,)
        bins = torch.arange(Td_avail, dtype=d.dtype, device=d.device)
        diff = bins - d.unsqueeze(-1)
        log_k = -0.5 * (diff / (self.sigma + 1e-8)) ** 2
        k = log_k.exp()
        k = k / (k.sum(dim=-1, keepdim=True) + 1e-12)   # (..., Td_avail)

        # k.t(): (Td_avail, out_f)  hist_stack: (Td_avail, B, out_f)
        k_t = k.t()
        out = (hist_stack * k_t.unsqueeze(1)).sum(dim=0)   # (B, out_f)
        return out

    def reset_history(self):
        """Clear the delay history buffer."""
        self._history = [None] * self.max_delay


class _TinyDelayConv1d(nn.Module):
    """
    Minimal DCLS-style Conv1d with per-channel learnable delays.
    """

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int = 3,
        max_delay: int = 8,
        sigma: float = 1.0,
    ):
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.max_delay = max_delay
        self.sigma = sigma

        self.conv = nn.Conv1d(
            in_channels, out_channels, kernel_size, padding=kernel_size // 2
        )
        # Per-channel delay: one scalar per output channel
        self.d_raw = nn.Parameter(torch.zeros(out_channels))

    @property
    def delays(self) -> torch.Tensor:
        return torch.sigmoid(self.d_raw) * (self.max_delay - 1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        x: (B, C_in, L).
        Returns: (B, C_out, L') with same L' as a plain conv with same padding.
        """
        return self.conv(x)


class _TinyGaussianKernel:
    """Pure-Python Gaussian kernel for contract tests (no nn.Module dependency)."""

    def __init__(self, max_delay: int, sigma: float):
        self.max_delay = max_delay
        self.sigma = sigma

    def __call__(self, d: torch.Tensor) -> torch.Tensor:
        """
        d: scalar or (N,) tensor of continuous delay positions.
        Returns: (max_delay,) or (N, max_delay) normalized kernel.
        """
        bins = torch.arange(self.max_delay, dtype=torch.float32)
        scalar = d.dim() == 0
        if scalar:
            d = d.unsqueeze(0)
        diff = bins.unsqueeze(0) - d.unsqueeze(-1)   # (N, Td)
        log_k = -0.5 * (diff / (self.sigma + 1e-8)) ** 2
        k = log_k.exp()
        k = k / (k.sum(dim=-1, keepdim=True) + 1e-12)
        return k.squeeze(0) if scalar else k


class _TinySigmaSchedule:
    """
    Cosine annealing schedule for the Gaussian delay kernel width sigma.

    sigma(e) = sigma_end + 0.5 * (sigma_start - sigma_end)
               * (1 + cos(pi * e / T_max))

    Monotonically decreasing from sigma_start to sigma_end over T_max steps.
    """

    def __init__(
        self,
        sigma_start: float = 4.0,
        sigma_end: float = 0.1,
        T_max: int = 100,
        constant: bool = False,
    ):
        self.sigma_start = sigma_start
        self.sigma_end = sigma_end
        self.T_max = T_max
        self.constant = constant
        self._epoch = 0
        self._sigma = sigma_start

    def step(self):
        """Advance by one epoch and update sigma."""
        self._epoch += 1
        if self.constant:
            self._sigma = self.sigma_start
        else:
            e = min(self._epoch, self.T_max)
            self._sigma = (
                self.sigma_end
                + 0.5 * (self.sigma_start - self.sigma_end)
                * (1 + math.cos(math.pi * e / self.T_max))
            )

    @property
    def sigma(self) -> float:
        return self._sigma

    @property
    def epoch(self) -> int:
        return self._epoch

    def state_dict(self) -> dict:
        return {{
            "sigma_start": self.sigma_start,
            "sigma_end":   self.sigma_end,
            "T_max":       self.T_max,
            "constant":    self.constant,
            "_epoch":      self._epoch,
            "_sigma":      self._sigma,
        }}

    def load_state_dict(self, sd: dict):
        self.sigma_start = sd["sigma_start"]
        self.sigma_end   = sd["sigma_end"]
        self.T_max       = sd["T_max"]
        self.constant    = sd["constant"]
        self._epoch      = sd["_epoch"]
        self._sigma      = sd["_sigma"]


# ---------------------------------------------------------------------------
# Resolve actual classes: prefer real imports, fall back to stubs
# ---------------------------------------------------------------------------

_DelayLinear   = DelayLinear   if HAS_DELAY_MODULES else _TinyDelayLinear
_DelayConv1d   = DelayConv1d   if HAS_DELAY_MODULES else _TinyDelayConv1d
_GaussianKernel = GaussianDelayKernel if HAS_DELAY_MODULES else _TinyGaussianKernel
_SigmaSchedule = SigmaSchedule if HAS_DELAY_MODULES else _TinySigmaSchedule


# ---------------------------------------------------------------------------
# Factory helpers
# ---------------------------------------------------------------------------

def _make_delay_linear(
    in_f: int = 16,
    out_f: int = 16,
    max_delay: int = DEFAULT_MAX_DELAY,
    sigma: float = 1.5,
    granularity: str = "per_neuron",
    fixed: bool = False,
) -> nn.Module:
    """Create a DelayLinear (or stub) with the given configuration."""
    try:
        return _DelayLinear(
            in_features=in_f,
            out_features=out_f,
            max_delay=max_delay,
            sigma=sigma,
            granularity=granularity,
            fixed=fixed,
        )
    except TypeError:
        return _TinyDelayLinear(in_f, out_f, max_delay, sigma, granularity, fixed)


def _make_delay_conv(
    in_c: int = 8,
    out_c: int = 8,
    kernel_size: int = 3,
    max_delay: int = DEFAULT_MAX_DELAY,
    sigma: float = 1.5,
) -> nn.Module:
    """Create a DelayConv1d (or stub) with the given configuration."""
    try:
        return _DelayConv1d(in_c, out_c, kernel_size, max_delay, sigma)
    except TypeError:
        return _TinyDelayConv1d(in_c, out_c, kernel_size, max_delay, sigma)


def _make_tau(
    n: int = 32,
    learnable: bool = True,
    strategy: str = "heterogeneous_gamma",
    tau_0: float = 20.0,
    tau_min: float = 1.0,
    tau_max: float = 100.0,
    dt: float = 1.0,
) -> "HeterogeneousTau":
    """Create a HeterogeneousTau module (or stub) with the given configuration."""
    cfg = TauInitConfig(
        strategy=strategy,
        tau_0=tau_0,
        tau_min=tau_min,
        tau_max=tau_max,
        dt=dt,
    )
    return HeterogeneousTau(
        n=n, learnable=learnable, init_cfg=cfg,
        dt=dt, tau_min=tau_min, tau_max=tau_max
    )


def _lif_forward_T(lif: nn.Module, x: torch.Tensor, T: int) -> torch.Tensor:
    """
    Run LIFNeuron for T timesteps; x is (B, N) reused each step.
    Returns stacked spikes (T, B, N).
    """
    if hasattr(lif, "reset_mem"):
        lif.reset_mem()
    spikes = []
    for _ in range(T):
        out = lif(x)
        spk = out[0] if isinstance(out, (tuple, list)) else out
        spikes.append(spk)
    return torch.stack(spikes, dim=0)
'''


def _conftest_fixtures() -> str:
    return '''\
# ===========================================================================
# Fixtures
# ===========================================================================

@pytest.fixture(params=GRANULARITY_MODES)
def granularity(request):
    """Parametrize over delay/tau granularity modes."""
    return request.param


@pytest.fixture(params=DEVICES)
def device(request):
    """Parametrize over cpu + cuda (if available)."""
    return request.param


@pytest.fixture
def tiny_delay_linear():
    """Default tiny DelayLinear for smoke tests."""
    torch.manual_seed(42)
    return _make_delay_linear(in_f=8, out_f=8, max_delay=DEFAULT_MAX_DELAY)


@pytest.fixture
def tiny_delay_conv():
    """Default tiny DelayConv1d for smoke tests."""
    torch.manual_seed(42)
    return _make_delay_conv(in_c=4, out_c=4, kernel_size=3, max_delay=DEFAULT_MAX_DELAY)


@pytest.fixture
def tiny_tau_learnable():
    """Default tiny HeterogeneousTau (learnable) for smoke tests."""
    torch.manual_seed(42)
    return _make_tau(n=16, learnable=True)


@pytest.fixture
def tiny_tau_fixed():
    """Default tiny HeterogeneousTau (fixed) for smoke tests."""
    torch.manual_seed(42)
    return _make_tau(n=16, learnable=False)


@pytest.fixture
def sigma_schedule():
    """Default cosine-annealing sigma schedule."""
    return _TinySigmaSchedule(sigma_start=4.0, sigma_end=0.1, T_max=50)
'''


def _class_delay_linear_contract(timesteps: int, batch_size: int, max_delay: int) -> str:
    return f'''\
# ===========================================================================
# TestDelayLinearContract
# ===========================================================================

@pytest.mark.delay
class TestDelayLinearContract:
    """
    Verify the observable contract for DelayLinear (DCLS-style dense delay layer).

    Parameterized over granularity: per_neuron, per_channel, per_layer.
    Tests forward output shape, delay parameter shape, delay value range,
    and spike history buffer update semantics.
    """

    @pytest.mark.parametrize("granularity", GRANULARITY_MODES)
    def test_forward_shapes(self, granularity: str):
        """
        Forward output shape must be (B, out_features) for each granularity mode.

        The delay operation is a weighted history sum; it does not change the
        spatial dimension of the output tensor.
        """
        torch.manual_seed(0)
        B = {batch_size}
        IN = 16
        OUT = 24

        model = _make_delay_linear(in_f=IN, out_f=OUT, granularity=granularity)
        x = torch.randn(B, IN)
        out = model(x)

        assert out.shape == (B, OUT), (
            f"Expected shape ({{B}}, {{OUT}}) for granularity={{granularity}}, "
            f"got {{out.shape}}"
        )

    @pytest.mark.parametrize("granularity", GRANULARITY_MODES)
    def test_delay_param_shape(self, granularity: str):
        """
        d_raw shape must match the expected shape for the given granularity:
          per_neuron  -> (out_features,)
          per_channel -> (out_features,)
          per_layer   -> (1,) or scalar
        """
        OUT = 24
        model = _make_delay_linear(in_f=16, out_f=OUT, granularity=granularity)

        d_raw = None
        for name, p in model.named_parameters():
            if "d_raw" in name or "delay" in name.lower():
                d_raw = p
                break
        if d_raw is None:
            for name, buf in model.named_buffers():
                if "d_raw" in name or "delay" in name.lower():
                    d_raw = buf
                    break

        assert d_raw is not None, (
            f"Could not find d_raw parameter/buffer for granularity={{granularity}}"
        )

        if granularity in ("per_neuron", "per_channel"):
            assert d_raw.numel() == OUT, (
                f"d_raw numel={{d_raw.numel()}} does not match out_features={{OUT}} "
                f"for granularity={{granularity}}"
            )
        else:   # per_layer
            assert d_raw.numel() == 1 or d_raw.numel() == OUT, (
                f"d_raw numel={{d_raw.numel()}} unexpected for per_layer granularity"
            )

    @pytest.mark.parametrize("granularity", GRANULARITY_MODES)
    def test_delay_range(self, granularity: str):
        """
        All delay values (after sigmoid mapping) must lie in [0, Td - 1].

        The sigmoid * (Td - 1) formula enforces this by construction. This
        test verifies the property holds after actual parameter-to-delay mapping.
        """
        Td = {max_delay}
        model = _make_delay_linear(in_f=16, out_f=16, max_delay=Td, granularity=granularity)

        if hasattr(model, "delays"):
            delays = model.delays.detach().float()
        else:
            d_raw = None
            for name, p in model.named_parameters():
                if "d_raw" in name or "delay" in name.lower():
                    d_raw = p
                    break
            if d_raw is None:
                pytest.skip("Cannot locate d_raw -- skip delay range check")
            delays = torch.sigmoid(d_raw.detach()) * (Td - 1)

        assert delays.min().item() >= 0.0, (
            f"Delays below 0: min={{delays.min().item():.6f}}"
        )
        assert delays.max().item() <= Td - 1 + 1e-5, (
            f"Delays above Td-1={{Td-1}}: max={{delays.max().item():.6f}}"
        )

    def test_spike_history_update(self):
        """
        The spike history buffer must update each timestep without in-place ops.

        Verification: T forward passes complete without RuntimeError caused by
        autograd version counter violations from in-place tensor modification.
        """
        torch.manual_seed(1)
        T = {timesteps}
        B = {batch_size}
        IN = OUT = 8
        Td = {max_delay}

        model = _make_delay_linear(in_f=IN, out_f=OUT, max_delay=Td)
        x = torch.randn(B, IN, requires_grad=True)

        outputs = []
        try:
            for t in range(T):
                out = model(x + t * 0.01)
                outputs.append(out)
        except RuntimeError as e:
            if "in-place" in str(e).lower() or "version" in str(e).lower():
                pytest.fail(
                    f"In-place modification detected in history update: {{e}}"
                )
            raise

        assert len(outputs) == T, "Model did not produce T outputs"
'''


def _class_delay_conv1d_contract(batch_size: int, max_delay: int) -> str:
    return f'''\
# ===========================================================================
# TestDelayConv1dContract
# ===========================================================================

@pytest.mark.delay
class TestDelayConv1dContract:
    """
    Verify the observable contract for DelayConv1d.

    Tests output shape compatibility and per-channel delay parameter existence.
    """

    @pytest.mark.parametrize("L", [32, 64])
    def test_forward_shapes(self, L: int):
        """
        Forward output shape must be (B, C_out, L') where L' depends on
        kernel size and padding configuration.
        """
        torch.manual_seed(2)
        B = {batch_size}
        C_IN = 8
        C_OUT = 16
        K = 3

        model = _make_delay_conv(
            in_c=C_IN, out_c=C_OUT, kernel_size=K, max_delay={max_delay}
        )
        x = torch.randn(B, C_IN, L)
        out = model(x)

        assert out.dim() == 3, (
            f"Expected 3D output (B, C_out, L'), got {{out.dim()}}D"
        )
        assert out.shape[0] == B, (
            f"Batch dim mismatch: {{out.shape[0]}} != {{B}}"
        )
        assert out.shape[1] == C_OUT, (
            f"Channel dim mismatch: {{out.shape[1]}} != {{C_OUT}}"
        )

    def test_channel_delays(self):
        """
        Per-channel delay parameter d_raw must have numel == C_out.

        Each output channel independently learns its delay; sharing a single
        delay across all channels would prevent per-channel temporal tuning.
        """
        C_OUT = 16
        model = _make_delay_conv(
            in_c=8, out_c=C_OUT, kernel_size=3, max_delay={max_delay}
        )

        d_raw = None
        for name, p in model.named_parameters():
            if "d_raw" in name or "delay" in name.lower():
                d_raw = p
                break

        assert d_raw is not None, "d_raw not found in DelayConv1d parameters"
        assert d_raw.numel() == C_OUT, (
            f"d_raw.numel() = {{d_raw.numel()}} != C_out = {{C_OUT}}. "
            "Each output channel must have its own delay parameter."
        )
'''


def _class_gaussian_interpolation(max_delay: int) -> str:
    return f'''\
# ===========================================================================
# TestGaussianInterpolation
# ===========================================================================

@pytest.mark.delay
class TestGaussianInterpolation:
    """
    Verify the mathematical properties of the Gaussian delay kernel.

    Tests normalization (bins sum to 1.0), sigma-zero limit (approaches
    one-hot), and symmetry around the center delay position.
    """

    def test_kernel_normalization(self):
        """
        Kernel weights over all delay bins must sum to 1.0 (within 1e-5).

        The kernel is normalized so the weighted history sum is an
        interpolated -- not amplified or attenuated -- version of the past.
        """
        Td = {max_delay}
        sigma = 1.5
        kernel_fn = _TinyGaussianKernel(Td, sigma)

        for d_val in [0.0, 1.5, float(Td) / 2.0, float(Td) - 1.0]:
            d = torch.tensor(d_val)
            k = kernel_fn(d)   # (Td,)
            k_sum = k.sum().item()
            assert abs(k_sum - 1.0) < 1e-5, (
                f"Kernel does not sum to 1 at d={{d_val:.2f}}: sum={{k_sum:.8f}}"
            )

    def test_sigma_zero_limit(self):
        """
        As sigma -> 0, the kernel approaches a one-hot at round(d).

        With sigma=0.01, more than 99.9% of mass should concentrate on the
        nearest bin to d.
        """
        Td = {max_delay}
        sigma_tiny = 0.01
        kernel_fn = _TinyGaussianKernel(Td, sigma_tiny)

        for d_val in [0.0, 1.0, 3.0, float(Td) - 1.0]:
            d = torch.tensor(d_val)
            k = kernel_fn(d)   # (Td,)

            nearest = max(0, min(Td - 1, int(round(d_val))))
            peak_mass = k[nearest].item()

            assert peak_mass > 0.999, (
                f"Kernel not near one-hot at d={{d_val:.1f}} with sigma={{sigma_tiny}}: "
                f"peak_mass={{peak_mass:.6f}} at bin {{nearest}}"
            )

    def test_symmetric_kernel(self):
        """
        For small eps, g(d - eps) and g(d + eps) must have symmetric mass
        distributions -- the kernel center shifts by 2*eps.

        Verified via the difference of kernel means: should equal 2 * eps
        within a tolerance of 0.5 (half a bin width).
        """
        Td = {max_delay}
        sigma = 1.5
        eps = 0.1
        kernel_fn = _TinyGaussianKernel(Td, sigma)

        d_center = float(Td) / 2.0
        k_minus = kernel_fn(torch.tensor(d_center - eps))
        k_plus  = kernel_fn(torch.tensor(d_center + eps))

        bins = torch.arange(Td, dtype=torch.float32)
        mean_minus = (bins * k_minus).sum().item()
        mean_plus  = (bins * k_plus).sum().item()

        actual_diff   = mean_plus - mean_minus
        expected_diff = 2.0 * eps

        assert abs(actual_diff - expected_diff) < 0.5, (
            f"Kernel asymmetry: expected mean shift ~{{expected_diff:.3f}}, "
            f"got {{actual_diff:.3f}}. Kernel centering may be incorrect."
        )
'''


def _class_eval_discretization(timesteps: int, batch_size: int, max_delay: int) -> str:
    return f'''\
# ===========================================================================
# TestEvalDiscretization
# ===========================================================================

@pytest.mark.delay
class TestEvalDiscretization:
    """
    Verify that switching to inference mode triggers discretization of
    continuous delays to nearest integer values, and that training and
    inference outputs are numerically close when sigma is small.
    """

    def test_discrete_delays_are_integers(self):
        """
        After rounding, delay values must be exact non-negative integers in [0, Td-1].

        Fractional delays (e.g., 2.73) are discretized to nearest int (3) during
        inference. The rounding itself must produce values that are integers.
        """
        Td = {max_delay}
        model = _make_delay_linear(in_f=8, out_f=8, max_delay=Td)

        if hasattr(model, "delays"):
            d_continuous = model.delays.detach()
        else:
            d_raw = None
            for name, p in model.named_parameters():
                if "d_raw" in name or "delay" in name.lower():
                    d_raw = p
                    break
            if d_raw is None:
                pytest.skip("Cannot locate delay parameter for discretization test")
            d_continuous = torch.sigmoid(d_raw.detach()) * (Td - 1)

        d_rounded = d_continuous.round()

        assert (d_rounded >= 0).all(), "Negative discrete delay values"
        assert (d_rounded <= Td - 1).all(), (
            f"Discrete delays exceed Td-1={{Td-1}}: max={{d_rounded.max().item()}}"
        )
        # Verify roundedness: no fractional parts
        frac_deviation = (d_rounded - d_rounded.long().float()).abs().max().item()
        assert frac_deviation < 1e-6, (
            f"Rounded delays have fractional parts: max deviation={{frac_deviation}}"
        )

    def test_eval_vs_training_close(self):
        """
        With sigma small, inference (discretized) output must be close to training
        (continuous Gaussian) output.

        As sigma -> 0 the kernel approaches a one-hot at round(d), so the two
        modes converge numerically.
        """
        torch.manual_seed(10)
        B = {batch_size}
        IN = OUT = 8
        Td = {max_delay}

        model = _make_delay_linear(in_f=IN, out_f=OUT, max_delay=Td, sigma=0.05)
        x = torch.randn(B, IN)

        model.train()
        for _ in range(Td):
            out_train = model(x)

        model.eval()
        if hasattr(model, "reset_history"):
            model.reset_history()
        elif hasattr(model, "_history"):
            model._history = [None] * Td

        for _ in range(Td):
            out_inf = model(x)

        diff = (out_train - out_inf).abs().max().item()
        assert diff < 1.0, (
            f"Train vs inference output diverged with sigma=0.05: "
            f"max_diff={{diff:.4f}}"
        )

    def test_eval_mode_flag(self):
        """
        Calling model.eval() must not raise and must set training=False.

        The inference-mode flag is the trigger for discretization in DCLS.
        """
        model = _make_delay_linear(in_f=8, out_f=8, max_delay={max_delay})

        model.train()
        assert model.training, "model.training should be True after .train()"

        model.eval()
        assert not model.training, (
            "model.training should be False after switching to inference mode"
        )

        x = torch.randn({batch_size}, 8)
        try:
            out = model(x)
        except Exception as e:
            pytest.fail(f"forward in inference mode raised: {{e}}")

        assert out.shape == ({batch_size}, 8), (
            f"Unexpected output shape in inference mode: {{out.shape}}"
        )
'''


def _class_sigma_schedule() -> str:
    return '''\
# ===========================================================================
# TestSigmaSchedule
# ===========================================================================

@pytest.mark.delay
class TestSigmaSchedule:
    """
    Verify the annealing schedule for the Gaussian kernel width sigma.

    Large sigma at the start allows gradients to flow across many delay bins;
    small sigma at convergence approximates hard discrete delay selection.
    """

    def test_monotonic_decrease(self):
        """
        sigma(e+1) <= sigma(e) for all epochs in [0, T_max].

        The cosine schedule is monotonically non-increasing. Any increase
        would indicate an implementation bug.
        """
        sched = _TinySigmaSchedule(sigma_start=4.0, sigma_end=0.1, T_max=50)
        prev_sigma = sched.sigma

        for e in range(60):   # Step past T_max to verify plateau
            sched.step()
            curr_sigma = sched.sigma
            assert curr_sigma <= prev_sigma + 1e-9, (
                f"Sigma increased at epoch {e+1}: "
                f"prev={prev_sigma:.6f}, curr={curr_sigma:.6f}"
            )
            prev_sigma = curr_sigma

    def test_convergence(self):
        """
        After T_max epochs, sigma must equal sigma_end (within 1e-5).

        At e=T_max: cos(pi) = -1, so sigma = sigma_end + 0 = sigma_end.
        """
        sigma_end = 0.1
        T_max = 50
        sched = _TinySigmaSchedule(sigma_start=4.0, sigma_end=sigma_end, T_max=T_max)

        for _ in range(T_max):
            sched.step()

        assert abs(sched.sigma - sigma_end) < 1e-5, (
            f"Sigma did not converge to sigma_end={sigma_end:.4f} after "
            f"T_max={T_max} steps. Got sigma={sched.sigma:.8f}"
        )

    def test_constant_schedule(self):
        """
        When configured as constant, sigma must remain at sigma_start
        for all epochs.
        """
        sigma_start = 2.0
        sched = _TinySigmaSchedule(
            sigma_start=sigma_start, sigma_end=0.1, T_max=50, constant=True
        )

        for e in range(30):
            sched.step()
            assert abs(sched.sigma - sigma_start) < 1e-9, (
                f"Constant schedule changed sigma at epoch {e+1}: "
                f"sigma={sched.sigma:.8f} (expected {sigma_start})"
            )

    def test_checkpoint_roundtrip(self):
        """
        state_dict() -> load_state_dict() must restore sigma and epoch exactly.

        After 20 steps: save, fresh schedule, load, verify parity.
        """
        sched = _TinySigmaSchedule(sigma_start=4.0, sigma_end=0.1, T_max=50)
        for _ in range(20):
            sched.step()

        saved_sigma = sched.sigma
        saved_epoch = sched.epoch
        sd = sched.state_dict()

        sched2 = _TinySigmaSchedule(sigma_start=1.0, sigma_end=0.5, T_max=10)
        sched2.load_state_dict(sd)

        assert abs(sched2.sigma - saved_sigma) < 1e-9, (
            f"Sigma mismatch after load: {sched2.sigma:.10f} != {saved_sigma:.10f}"
        )
        assert sched2.epoch == saved_epoch, (
            f"Epoch mismatch after load: {sched2.epoch} != {saved_epoch}"
        )
'''


def _class_delay_gradients(timesteps: int, batch_size: int, max_delay: int) -> str:
    return f'''\
# ===========================================================================
# TestDelayGradients
# ===========================================================================

@pytest.mark.delay
class TestDelayGradients:
    """
    Verify gradient flow through the delay parameter d_raw.

    The soft Gaussian interpolation makes d_raw differentiable; gradients
    must flow through it to enable learned delay optimization.
    """

    def test_gradient_exists(self):
        """
        d_raw.grad must not be None after loss.backward().

        The chain: loss -> output -> Gaussian kernel (fn of d) -> d_raw
        must be unbroken for delay learning to work.
        """
        torch.manual_seed(0)
        B = {batch_size}
        T = {timesteps}
        IN = OUT = 16
        Td = {max_delay}

        model = _make_delay_linear(in_f=IN, out_f=OUT, max_delay=Td)
        x = torch.randn(B, IN)

        outputs = []
        for _ in range(T):
            out = model(x)
            outputs.append(out)

        loss = torch.stack(outputs).sum()
        loss.backward()

        d_raw = None
        for name, p in model.named_parameters():
            if "d_raw" in name or "delay" in name.lower():
                d_raw = p
                break

        assert d_raw is not None, "d_raw parameter not found"
        assert d_raw.grad is not None, (
            "d_raw.grad is None after backward -- "
            "delay parameter is not in the compute graph"
        )

    def test_gradient_nonzero(self):
        """
        d_raw.grad.abs().mean() must be > 1e-8.

        A zero gradient means the delay has no effect on the loss value,
        preventing any delay adaptation during training.

        IMPORTANT: inputs must vary across timesteps. If the same x is fed
        every step the history buffer fills with identical values, making the
        Gaussian-weighted sum invariant to d_raw and producing a zero gradient.
        Use a distinct x_t per step to ensure history entries differ.
        """
        torch.manual_seed(1)
        B = {batch_size}
        T = {timesteps}
        IN = OUT = 16
        Td = {max_delay}

        model = _make_delay_linear(in_f=IN, out_f=OUT, max_delay=Td)
        # Time-varying inputs: different x_t each step so history entries differ
        x_seq = torch.randn(T, B, IN)

        outputs = []
        for t in range(T):
            out = model(x_seq[t])
            outputs.append(out)
        loss = torch.stack(outputs).sum()
        loss.backward()

        d_raw = None
        for name, p in model.named_parameters():
            if "d_raw" in name or "delay" in name.lower():
                d_raw = p
                break

        if d_raw is None or d_raw.grad is None:
            pytest.skip("d_raw or its gradient not accessible")

        grad_mean = d_raw.grad.abs().mean().item()
        assert grad_mean > 1e-8, (
            f"d_raw gradient effectively zero: abs_mean={{grad_mean:.2e}}"
        )

    def test_no_gradient_fixed(self):
        """
        With fixed=True, d_raw must not appear as a Parameter (no grad).

        Fixed delays use register_buffer; they are excluded from the autograd
        graph and receive no gradient update.

        Note: x requires_grad=True ensures there is always a leaf in the graph
        so that backward() does not raise even when only buffers exist.
        """
        torch.manual_seed(2)
        B = {batch_size}
        T = min({timesteps}, 5)
        IN = OUT = 8
        Td = {max_delay}

        model = _make_delay_linear(in_f=IN, out_f=OUT, max_delay=Td, fixed=True)
        # requires_grad=True on input ensures a grad_fn exists so backward() works
        x = torch.randn(B, IN, requires_grad=True)

        for _ in range(T):
            out = model(x)
        loss = out.sum()
        if loss.grad_fn is not None:
            loss.backward()

        # In fixed mode d_raw should not be a Parameter
        for name, p in model.named_parameters():
            if "d_raw" in name or "delay" in name.lower():
                pytest.fail(
                    f"d_raw found as Parameter in fixed mode (should be buffer): {{name}}"
                )

        # Buffers must not have gradients
        for name, buf in model.named_buffers():
            if "d_raw" in name or "delay" in name.lower():
                assert buf.grad is None, (
                    f"Buffer {{name}} has gradient in fixed mode"
                )

    def test_finite_difference(self):
        """
        Autograd gradient on d_raw must match finite-difference estimate
        within rtol=1e-2 (plus 0.05 tolerance buffer).

        Uses a 2-point central difference with eps=1e-3.
        The smooth Gaussian kernel makes FD and autograd agree closely.
        """
        torch.manual_seed(3)
        B = 2
        T = 3
        IN = OUT = 4
        Td = {max_delay}
        EPS = 1e-3
        RTOL = 1e-2

        model = _make_delay_linear(in_f=IN, out_f=OUT, max_delay=Td)
        # Time-varying inputs so that history entries differ (same-x causes
        # zero d_raw gradient because shifting the kernel among identical
        # history values does not change the weighted sum).
        torch.manual_seed(3)
        x_seq = torch.randn(T, B, IN)

        def compute_loss(m):
            if hasattr(m, "reset_history"):
                m.reset_history()
            elif hasattr(m, "_history"):
                m._history = [None] * m.max_delay
            outs = []
            for t in range(T):
                outs.append(m(x_seq[t]))
            return torch.stack(outs).sum().item()

        # Autograd gradient
        if hasattr(model, "reset_history"):
            model.reset_history()
        elif hasattr(model, "_history"):
            model._history = [None] * model.max_delay

        outs = []
        for t in range(T):
            outs.append(model(x_seq[t]))
        torch.stack(outs).sum().backward()

        d_raw = None
        for name, p in model.named_parameters():
            if "d_raw" in name or "delay" in name.lower():
                d_raw = p
                break

        if d_raw is None or d_raw.grad is None:
            pytest.skip("d_raw or gradient not accessible for FD test")

        ag_grad = d_raw.grad.detach().clone()

        for idx in range(min(3, d_raw.numel())):
            orig = d_raw.data.view(-1)[idx].item()

            with torch.no_grad():
                d_raw.data.view(-1)[idx] = orig + EPS
            f_plus = compute_loss(model)

            with torch.no_grad():
                d_raw.data.view(-1)[idx] = orig - EPS
            f_minus = compute_loss(model)

            with torch.no_grad():
                d_raw.data.view(-1)[idx] = orig

            fd_grad = (f_plus - f_minus) / (2.0 * EPS)
            ag = ag_grad.view(-1)[idx].item()
            rel_err = abs(fd_grad - ag) / (abs(ag) + 1e-8)

            assert rel_err < RTOL + 0.05, (
                f"FD mismatch at d_raw[{{idx}}]: FD={{fd_grad:.6f}}, "
                f"autograd={{ag:.6f}}, rel_err={{rel_err:.4f}} (rtol={{RTOL}})"
            )
'''


def _class_heterogeneous_tau_contract(batch_size: int) -> str:
    return f'''\
# ===========================================================================
# TestHeterogeneousTauContract
# ===========================================================================

@pytest.mark.tau
class TestHeterogeneousTauContract:
    """
    Verify the fundamental mathematical contracts of HeterogeneousTau.

    Parameterized over init strategies. Tests beta range, tau positivity,
    softplus mapping correctness, exp(-dt/tau) matching, and broadcast shapes.
    """

    @pytest.mark.parametrize("strategy", TAU_INIT_STRATEGIES)
    def test_beta_in_range(self, strategy: str):
        """
        All beta values must satisfy 0 < beta < 1 after initialization.

        Guaranteed by: softplus(tau_raw) + tau_min > 0, so tau > 0,
        so exp(-dt/tau) in (0, 1). The beta_max=0.999 clamp ensures beta < 1.
        """
        tau_module = _make_tau(n=64, learnable=True, strategy=strategy)
        beta = tau_module.beta.detach()

        assert (beta > 0).all(), (
            f"Some beta values <= 0 with strategy={{strategy}}: "
            f"min={{beta.min().item():.8f}}"
        )
        assert (beta < 1).all(), (
            f"Some beta values >= 1 with strategy={{strategy}}: "
            f"max={{beta.max().item():.8f}}"
        )

    @pytest.mark.parametrize("strategy", TAU_INIT_STRATEGIES)
    def test_tau_positive(self, strategy: str):
        """
        All tau values must be strictly positive (>= tau_min > 0).

        tau = tau_min + softplus(tau_raw) where softplus > 0 always,
        so tau > tau_min. The minimum valid tau is tau_min (never 0).
        """
        tau_module = _make_tau(n=64, learnable=True, strategy=strategy, tau_min=1.0)
        tau_vals = tau_module.tau.detach()

        assert (tau_vals > 0).all(), (
            f"Some tau values <= 0 with strategy={{strategy}}: "
            f"min={{tau_vals.min().item():.8f}}"
        )
        assert (tau_vals >= tau_module.tau_min - 1e-6).all(), (
            f"Some tau below tau_min={{tau_module.tau_min}} with strategy={{strategy}}"
        )

    def test_softplus_mapping(self):
        """
        tau = tau_min + softplus(tau_raw) must be exactly correct.

        Verifies the HeterogeneousTau.tau property implements the formula
        tau_min + softplus(tau_raw).clamp(max=tau_max) as specified.
        """
        tau_min = 1.0
        tau_max = 100.0
        n = 8

        tau_module = HeterogeneousTau(n=n, learnable=True, tau_min=tau_min, tau_max=tau_max)

        with torch.no_grad():
            raw = tau_module.tau_raw
            expected_tau = (tau_min + F.softplus(raw)).clamp(max=tau_max)
            actual_tau = tau_module.tau

        assert torch.allclose(expected_tau, actual_tau, atol=1e-6), (
            f"tau property does not match tau_min + softplus(tau_raw).clamp(tau_max). "
            f"Max diff: {{(expected_tau - actual_tau).abs().max().item():.2e}}"
        )

    def test_exp_mapping(self):
        """
        beta = exp(-dt / tau) must be computed exactly as specified.

        Verifies the physics-grounded decay formula and that the relationship
        between tau and beta is monotonically increasing (larger tau -> larger beta).
        """
        dt = 1.0
        beta_max = 0.999
        n = 8

        tau_module = HeterogeneousTau(n=n, learnable=True, dt=dt, beta_max=beta_max)

        with torch.no_grad():
            tau_vals = tau_module.tau.float()
            expected_beta = torch.exp(-dt / tau_vals).clamp(0.0, beta_max)
            actual_beta = tau_module.beta

        assert torch.allclose(expected_beta, actual_beta, atol=1e-6), (
            f"beta property does not match exp(-dt/tau).clamp(0, beta_max). "
            f"Max diff: {{(expected_beta - actual_beta).abs().max().item():.2e}}"
        )

    @pytest.mark.parametrize("layer_type", ["fc", "conv"])
    def test_broadcast_shape(self, layer_type: str):
        """
        Beta must broadcast correctly for FC (B, N) and Conv (B, C, H, W) layers.

        FC:   beta (N,) -> beta.unsqueeze(0) (1, N) -> broadcasts with (B, N).
        Conv: beta (C,) -> beta.view(1, C, 1, 1)  -> broadcasts with (B, C, H, W).
        """
        B = {batch_size}

        if layer_type == "fc":
            N = 32
            tau_module = _make_tau(n=N)
            beta = tau_module.beta   # (N,)
            v = torch.randn(B, N)
            i_in = torch.randn(B, N)

            v_new = beta.unsqueeze(0) * v + i_in
            assert v_new.shape == (B, N), (
                f"FC broadcast failed: expected ({{B}}, {{N}}), got {{v_new.shape}}"
            )

        else:   # conv
            C, H, W = 16, 8, 8
            tau_module = _make_tau(n=C)
            beta = tau_module.beta   # (C,)
            v = torch.randn(B, C, H, W)
            i_in = torch.randn(B, C, H, W)

            v_new = beta.view(1, C, 1, 1) * v + i_in
            assert v_new.shape == (B, C, H, W), (
                f"Conv broadcast failed: expected ({{B}}, {{C}}, {{H}}, {{W}}), "
                f"got {{v_new.shape}}"
            )
'''


def _class_tau_init_strategies() -> str:
    return '''\
# ===========================================================================
# TestTauInitStrategies
# ===========================================================================

@pytest.mark.tau
class TestTauInitStrategies:
    """
    Verify that each initialization strategy produces tau distributions
    matching their mathematical specification.
    """

    def test_homogeneous_all_equal(self):
        """
        Strategy 'homogeneous': all tau values must be equal (std < 0.5).

        The homogeneous strategy sets every neuron to the same time constant,
        providing a no-diversity ablation baseline.
        """
        tau_0 = 20.0
        tau_module = _make_tau(n=64, strategy="homogeneous", tau_0=tau_0)
        tau_vals = tau_module.tau.detach()

        std = tau_vals.std().item()
        assert std < 0.5, (
            f"Homogeneous init: tau std={std:.4f} > 0.5 -- "
            "values should all be equal."
        )

    def test_gamma_distribution(self):
        """
        Strategy 'heterogeneous_gamma': tau values must be positive, in range,
        and diverse (std > 0.1).

        With k=2, theta=10 (mean=20) the distribution is right-skewed, matching
        biological observations of cortical time-constant distributions.
        """
        tau_module = _make_tau(
            n=256, strategy="heterogeneous_gamma",
            tau_0=20.0, tau_min=1.0, tau_max=100.0
        )
        tau_vals = tau_module.tau.detach()

        assert (tau_vals > 0).all(), "Gamma-init produced non-positive tau"
        assert (tau_vals >= tau_module.tau_min - 1e-5).all(), (
            f"Gamma-init produced tau below tau_min={tau_module.tau_min}"
        )
        assert (tau_vals <= tau_module.tau_max + 1e-5).all(), (
            f"Gamma-init produced tau above tau_max={tau_module.tau_max}"
        )
        std = tau_vals.std().item()
        assert std > 0.1, (
            f"Gamma-init std={std:.4f} too small -- values may not be diverse"
        )

    def test_loguniform_distribution(self):
        """
        Strategy 'heterogeneous_loguniform': must cover the full range with
        roughly equal representation per decade (within factor of 4).

        Loguniform = uniform in log-space => equal neuron count per decade.
        """
        torch.manual_seed(99)
        tau_module = _make_tau(
            n=256, strategy="heterogeneous_loguniform",
            tau_min=1.0, tau_max=100.0
        )
        tau_vals = tau_module.tau.detach()

        assert (tau_vals > 0).all(), "Loguniform-init produced non-positive tau"

        low_decade  = (tau_vals < 10.0).sum().item()
        high_decade = (tau_vals >= 10.0).sum().item()
        ratio = max(low_decade, high_decade) / (min(low_decade, high_decade) + 1)

        assert ratio < 4.0, (
            f"Loguniform-init strongly imbalanced: "
            f"low=[1,10]: {low_decade}, high=[10,100]: {high_decade} "
            f"(ratio={ratio:.2f}, expected < 4)"
        )

    def test_preset_bank(self):
        """
        Strategy 'preset_bank': tau values must all come from the preset list.

        With cyclic assignment, each neuron is assigned exactly one preset.
        """
        presets = [2.0, 5.0, 10.0, 20.0, 50.0]
        tau_module = _make_tau(
            n=50, strategy="preset_bank",
            tau_min=1.0, tau_max=100.0
        )
        tau_vals = tau_module.tau.detach()

        for v in tau_vals:
            v_item = v.item()
            closest = min(presets, key=lambda p: abs(p - v_item))
            deviation = abs(v_item - closest)
            if deviation > closest * 0.5:
                warnings.warn(
                    f"Preset bank tau value {v_item:.3f} deviates from nearest "
                    f"preset {closest:.1f} by {deviation:.3f}. "
                    "May indicate softplus inversion imprecision.",
                    UserWarning,
                )
                break
'''


def _class_tau_gradients(timesteps: int, batch_size: int) -> str:
    return f'''\
# ===========================================================================
# TestTauGradients
# ===========================================================================

@pytest.mark.tau
class TestTauGradients:
    """
    Verify gradient flow through tau_raw in learnable mode, and absence
    of gradients in fixed mode.
    """

    def test_gradient_exists_learnable(self):
        """
        tau_raw.grad must not be None after backward() in learnable mode.

        Gradient path: loss -> spikes -> membrane v -> beta -> tau_raw.
        The soft surrogate spike ensures differentiability through the threshold.
        """
        torch.manual_seed(5)
        B = {batch_size}
        T = {timesteps}
        N = 16

        tau_module = _make_tau(n=N, learnable=True)
        tau_module.train()

        v = torch.zeros(B, N)
        x = torch.randn(B, N)
        spikes_list = []

        for _ in range(T):
            beta = tau_module.beta   # (N,) -- in grad graph
            v_new = beta.unsqueeze(0) * v + x
            spk = torch.sigmoid(10.0 * (v_new - 1.0))   # soft surrogate
            v = v_new * (1.0 - spk.detach())
            spikes_list.append(spk)

        loss = torch.stack(spikes_list).sum()
        loss.backward()

        assert tau_module.tau_raw.grad is not None, (
            "tau_raw.grad is None in learnable mode -- "
            "gradient did not flow through beta = exp(-dt/tau)"
        )

    def test_no_gradient_fixed(self):
        """
        tau_raw must have no gradient in fixed (non-learnable) mode.

        In fixed mode, tau_raw is a buffer, not a Parameter, so it is
        excluded from the autograd graph.

        Note: x requires_grad=True provides a leaf so backward() does not
        raise even when the only pathway is through fixed buffers.
        """
        torch.manual_seed(6)
        B = {batch_size}
        T = min({timesteps}, 5)
        N = 16

        tau_module = _make_tau(n=N, learnable=False)
        v = torch.zeros(B, N)
        # requires_grad on x ensures loss.grad_fn exists
        x = torch.randn(B, N, requires_grad=True)
        spikes_list = []

        for _ in range(T):
            beta = tau_module.beta
            v_new = beta.unsqueeze(0) * v + x
            spk = torch.sigmoid(10.0 * (v_new - 1.0))
            v = v_new * (1.0 - spk.detach())
            spikes_list.append(spk)

        loss = torch.stack(spikes_list).sum()
        if loss.grad_fn is not None:
            loss.backward()

        tau_raw = tau_module.tau_raw
        assert not tau_raw.requires_grad, (
            "tau_raw.requires_grad=True in fixed mode -- it should be a buffer"
        )
        assert tau_raw.grad is None, (
            "tau_raw.grad is not None in fixed mode -- gradient leaked to buffer"
        )

    def test_gradient_magnitude(self):
        """
        tau_raw gradient must not be vanishing: abs().mean() > 1e-8.

        The gradient of exp(-dt/tau) w.r.t. tau_raw is:
          d(beta)/d(tau_raw) = (dt/tau^2) * exp(-dt/tau) * sigmoid(tau_raw)
        This is bounded and nonzero for tau in [tau_min, tau_max].
        """
        torch.manual_seed(7)
        B = {batch_size}
        T = {timesteps}
        N = 32

        tau_module = _make_tau(n=N, learnable=True, tau_min=1.0, tau_max=100.0)
        v = torch.zeros(B, N)
        x = torch.randn(B, N) * 0.5

        for _ in range(T):
            beta = tau_module.beta
            v_new = beta.unsqueeze(0) * v + x
            spk = torch.sigmoid(10.0 * (v_new - 1.0))
            v = v_new * (1.0 - spk.detach())

        loss = v.sum()
        loss.backward()

        if tau_module.tau_raw.grad is None:
            pytest.skip("tau_raw.grad is None -- gradient flow test skipped")

        grad_mag = tau_module.tau_raw.grad.abs().mean().item()
        assert grad_mag > 1e-8, (
            f"tau_raw gradient vanishing: abs_mean={{grad_mag:.2e}}"
        )
'''


def _class_checkpoint_roundtrip(timesteps: int, batch_size: int, max_delay: int) -> str:
    return f'''\
# ===========================================================================
# TestCheckpointRoundTrip
# ===========================================================================

@pytest.mark.tau
@pytest.mark.delay
class TestCheckpointRoundTrip:
    """
    Verify that save/load via state_dict preserves all parameters and
    produces bit-identical forward outputs after reloading.
    """

    def test_delay_state_dict(self):
        """
        DelayLinear state_dict must contain d_raw (or a delay-named key).

        The d_raw parameter / buffer must persist across checkpoints to allow
        training to resume from any point without losing learned delays.
        """
        model = _make_delay_linear(in_f=8, out_f=8, max_delay={max_delay})
        sd = model.state_dict()

        has_delay_key = any(
            "d_raw" in k or "delay" in k.lower()
            for k in sd.keys()
        )
        assert has_delay_key, (
            f"No d_raw / delay key in state_dict. Keys: {{list(sd.keys())}}"
        )

    def test_tau_state_dict(self):
        """
        HeterogeneousTau state_dict must contain tau_raw (both learnable and fixed).

        Whether Parameter or buffer, tau_raw must be serializable so that
        the exact time-constant distribution can be restored from a checkpoint.
        """
        tau_learnable = _make_tau(n=32, learnable=True)
        sd = tau_learnable.state_dict()
        assert "tau_raw" in sd, (
            f"'tau_raw' not in learnable HeterogeneousTau state_dict. "
            f"Keys: {{list(sd.keys())}}"
        )

        tau_fixed = _make_tau(n=32, learnable=False)
        sd_fixed = tau_fixed.state_dict()
        assert "tau_raw" in sd_fixed, (
            f"'tau_raw' not in fixed HeterogeneousTau state_dict. "
            f"Keys: {{list(sd_fixed.keys())}}"
        )

    def test_reload_identical_output(self):
        """
        After save -> reload, forward output must be bit-identical (atol=1e-6).

        Procedure:
          1. Create and run model to produce reference output.
          2. Save state_dict.
          3. Create fresh model with different random seed.
          4. Load state_dict.
          5. Run same input, compare outputs.
        """
        torch.manual_seed(20)
        B = {batch_size}
        IN = OUT = 8
        Td = {max_delay}
        T = Td   # Fully populate history buffer

        model = _make_delay_linear(in_f=IN, out_f=OUT, max_delay=Td)
        x = torch.randn(B, IN)

        for _ in range(T - 1):
            model(x)
        ref_out = model(x).detach()

        sd = model.state_dict()

        torch.manual_seed(99)
        model2 = _make_delay_linear(in_f=IN, out_f=OUT, max_delay=Td)
        model2.load_state_dict(sd)

        if hasattr(model2, "reset_history"):
            model2.reset_history()
        elif hasattr(model2, "_history"):
            model2._history = [None] * Td

        for _ in range(T - 1):
            model2(x)
        reloaded_out = model2(x).detach()

        assert torch.allclose(ref_out, reloaded_out, atol=1e-6), (
            f"Reloaded model output differs from reference. "
            f"Max diff: {{(ref_out - reloaded_out).abs().max().item():.8f}}"
        )

    @pytest.mark.skipif(not HAS_CUDA, reason="CUDA not available for cross-device test")
    def test_cross_device(self):
        """
        Save state on CUDA, load on CPU -- beta outputs must match (atol=1e-5).

        Common deployment pattern: train on GPU, load for CPU inference.
        """
        torch.manual_seed(21)
        N = 32

        tau_module = _make_tau(n=N, learnable=True).cuda()
        sd = {{k: v.cpu() for k, v in tau_module.state_dict().items()}}

        tau_cpu = _make_tau(n=N, learnable=True)
        tau_cpu.load_state_dict(sd)

        beta_cuda = tau_module.beta.cpu()
        beta_cpu  = tau_cpu.beta

        assert torch.allclose(beta_cuda, beta_cpu, atol=1e-5), (
            f"Beta mismatch after cross-device load. "
            f"Max diff: {{(beta_cuda - beta_cpu).abs().max().item():.2e}}"
        )
'''


def _class_integration(timesteps: int, batch_size: int, max_delay: int) -> str:
    return f'''\
# ===========================================================================
# TestIntegration
# ===========================================================================

@pytest.mark.integration
class TestIntegration:
    """
    End-to-end integration tests combining delay modules and heterogeneous tau
    with LIF neurons across the full T-step SNN unroll.

    Validates that the components compose without conflicts and produce valid
    (non-NaN, non-Inf) outputs across a range of configurations.
    """

    @pytest.mark.skipif(not HAS_LIF, reason="LIFNeuron not importable")
    def test_delay_with_lif(self):
        """
        DelayLinear -> LIFNeuron forward pass must complete without error.

        The delay module produces a soft history-interpolated activation;
        the LIF neuron integrates it as membrane current.
        """
        torch.manual_seed(30)
        B = {batch_size}
        T = {timesteps}
        IN = HIDDEN = 16

        delay = _make_delay_linear(in_f=IN, out_f=HIDDEN, max_delay={max_delay})
        lif = LIFNeuron(beta=0.9, threshold=1.0)
        if hasattr(lif, "reset_mem"):
            lif.reset_mem()

        x = torch.randn(B, IN)
        spikes = []
        for _ in range(T):
            h = delay(x)
            out = lif(h)
            spk = out[0] if isinstance(out, (tuple, list)) else out
            spikes.append(spk)

        spikes_tensor = torch.stack(spikes)
        assert not torch.isnan(spikes_tensor).any(), "NaN in delay+LIF spikes"
        assert not torch.isinf(spikes_tensor).any(), "Inf in delay+LIF spikes"
        assert spikes_tensor.shape == (T, B, HIDDEN), (
            f"Unexpected spike shape: {{spikes_tensor.shape}}"
        )

    def test_tau_with_lif(self):
        """
        HeterogeneousTau + manual LIF membrane update must complete without error.

        Replaces the scalar beta in a LIF loop with per-neuron betas from
        HeterogeneousTau, verifying the broadcast and update produce finite outputs.
        """
        torch.manual_seed(31)
        B = {batch_size}
        T = {timesteps}
        N = 32
        threshold = 1.0

        tau_module = _make_tau(n=N, learnable=True)
        v = torch.zeros(B, N)
        x = torch.randn(B, N) * 0.5

        spikes_list = []
        for _ in range(T):
            beta = tau_module.beta   # (N,)
            v = beta.unsqueeze(0) * v + x
            spk = (v >= threshold).float()
            v = v * (1.0 - spk)
            spikes_list.append(spk)

        spikes = torch.stack(spikes_list)
        assert not torch.isnan(spikes).any(), "NaN in tau+LIF spikes"
        assert not torch.isinf(spikes).any(), "Inf in tau+LIF spikes"
        assert spikes.shape == (T, B, N), f"Unexpected shape: {{spikes.shape}}"

    def test_both_together(self):
        """
        DelayLinear + HeterogeneousTau + LIF membrane update must coexist
        without tensor shape conflicts or NaN values.
        """
        torch.manual_seed(32)
        B = {batch_size}
        T = {timesteps}
        IN = N = 16
        threshold = 1.0

        delay = _make_delay_linear(in_f=IN, out_f=N, max_delay={max_delay})
        tau_module = _make_tau(n=N, learnable=True)
        v = torch.zeros(B, N)
        x = torch.randn(B, IN)

        spikes_list = []
        for _ in range(T):
            h = delay(x)                    # (B, N) soft-delayed activation
            beta = tau_module.beta          # (N,)
            v = beta.unsqueeze(0) * v + h
            spk = (v >= threshold).float()
            v = v * (1.0 - spk)
            spikes_list.append(spk)

        spikes = torch.stack(spikes_list)
        assert not torch.isnan(spikes).any(), "NaN in delay+tau+LIF"
        assert not torch.isinf(spikes).any(), "Inf in delay+tau+LIF"

    def test_snn_unroll_with_delays(self):
        """
        Full T-step SNN unroll with delays must produce non-NaN outputs
        and support backward() without in-place errors.
        """
        torch.manual_seed(33)
        B = {batch_size}
        T = {timesteps}
        IN = 8
        HIDDEN = 8
        threshold = 1.0

        delay = _make_delay_linear(in_f=IN, out_f=HIDDEN, max_delay={max_delay})
        fc_out = nn.Linear(HIDDEN, 4)
        v = torch.zeros(B, HIDDEN)

        x_seq = torch.randn(B, T, IN, requires_grad=True)
        spikes_list = []

        for t in range(T):
            x_t = x_seq[:, t, :]
            h = delay(x_t)
            v_new = 0.9 * v + h
            # Soft surrogate for differentiability
            spk = torch.sigmoid(10.0 * (v_new - threshold))
            v = v_new * (1.0 - spk.detach())
            spikes_list.append(spk)

        out = fc_out(torch.stack(spikes_list).mean(0))
        loss = out.sum()
        try:
            loss.backward()
        except RuntimeError as e:
            pytest.fail(f"backward() raised RuntimeError: {{e}}")

        assert not torch.isnan(out).any(), "NaN in SNN unroll output"

    @pytest.mark.parametrize("config", [
        {{"use_delay": False, "use_tau": False}},
        {{"use_delay": True,  "use_tau": False}},
        {{"use_delay": False, "use_tau": True}},
        {{"use_delay": True,  "use_tau": True}},
    ])
    def test_all_ablation_configs(self, config: dict):
        """
        All four ablation configurations (delay on/off x tau on/off) must
        complete a forward pass without error and produce finite outputs.

        This validates independent toggling and conflict-free composition.
        """
        torch.manual_seed(34)
        B = {batch_size}
        T = min({timesteps}, 10)
        IN = 8
        N = 8

        use_delay = config["use_delay"]
        use_tau   = config["use_tau"]

        delay      = _make_delay_linear(in_f=IN, out_f=N, max_delay={max_delay}) if use_delay else None
        tau_module = _make_tau(n=N, learnable=True) if use_tau else None

        v = torch.zeros(B, N)
        x = torch.randn(B, IN if use_delay else N)

        spikes_list = []
        for _ in range(T):
            h = delay(x) if use_delay else x
            if use_tau:
                beta = tau_module.beta
                v = beta.unsqueeze(0) * v + h
            else:
                v = 0.9 * v + h
            spk = (v >= 1.0).float()
            v = v * (1.0 - spk)
            spikes_list.append(spk)

        spikes = torch.stack(spikes_list)
        cfg_str = f"delay={{use_delay}}, tau={{use_tau}}"
        assert not torch.isnan(spikes).any(), f"NaN in ablation config {{cfg_str}}"
        assert not torch.isinf(spikes).any(), f"Inf in ablation config {{cfg_str}}"
'''


def _class_memory_and_performance(timesteps: int, batch_size: int, max_delay: int) -> str:
    return f'''\
# ===========================================================================
# TestMemoryAndPerformance
# ===========================================================================

@pytest.mark.slow
class TestMemoryAndPerformance:
    """
    Verify that delay and tau modules do not introduce excessive memory
    overhead or runtime slowdown relative to a baseline SNN layer.

    Marked @slow and excluded from the default fast run.
    Run with: pytest tests/test_delays_tau.py -v -m slow
    """

    def test_memory_under_threshold(self):
        """
        Peak memory for a delay+tau SNN forward pass must stay below 500 MB
        (CPU tracemalloc).
        """
        import tracemalloc
        import gc

        gc.collect()
        torch.manual_seed(40)
        B = {batch_size}
        T = {timesteps}
        IN = N = 64

        delay = _make_delay_linear(in_f=IN, out_f=N, max_delay={max_delay})
        tau_module = _make_tau(n=N, learnable=True)
        v = torch.zeros(B, N)
        x = torch.randn(B, IN)

        tracemalloc.start()
        for _ in range(T):
            h = delay(x)
            beta = tau_module.beta
            v = beta.unsqueeze(0) * v + h
        _, peak_bytes = tracemalloc.get_traced_memory()
        tracemalloc.stop()

        peak_mb = peak_bytes / 1024 / 1024
        THRESHOLD_MB = 500.0

        assert peak_mb < THRESHOLD_MB, (
            f"Peak memory {{peak_mb:.1f}} MB exceeds threshold {{THRESHOLD_MB}} MB. "
            "Consider reducing history buffer size or tau parameter count."
        )

    def test_delay_overhead_factor(self):
        """
        A T-step DelayLinear forward pass must be < 2.0x slower than a plain
        nn.Linear forward pass of the same shape.

        The history buffer and Gaussian weighting add overhead, but should
        remain within a 2x factor of the underlying linear cost.
        """
        import time

        torch.manual_seed(41)
        B = {batch_size}
        T = {timesteps}
        IN = OUT = 64
        REPS = 20

        baseline    = nn.Linear(IN, OUT)
        delay_model = _make_delay_linear(in_f=IN, out_f=OUT, max_delay={max_delay})
        x = torch.randn(B, IN)

        # Warm-up
        for _ in range(5):
            _ = baseline(x)
            _ = delay_model(x)

        # Time baseline
        t0 = time.perf_counter()
        for _ in range(REPS):
            for _ in range(T):
                _ = baseline(x)
        t_baseline = (time.perf_counter() - t0) / REPS

        # Reset and time delay model
        if hasattr(delay_model, "reset_history"):
            delay_model.reset_history()
        elif hasattr(delay_model, "_history"):
            delay_model._history = [None] * delay_model.max_delay

        t0 = time.perf_counter()
        for _ in range(REPS):
            for _ in range(T):
                _ = delay_model(x)
        t_delay = (time.perf_counter() - t0) / REPS

        overhead = t_delay / (t_baseline + 1e-9)
        MAX_OVERHEAD = 2.0

        assert overhead < MAX_OVERHEAD, (
            f"Delay overhead factor {{overhead:.2f}}x exceeds {{MAX_OVERHEAD}}x. "
            f"Baseline: {{t_baseline*1000:.2f}} ms, Delay: {{t_delay*1000:.2f}} ms "
            f"(per {{T}}-step sequence, averaged over {{REPS}} reps)."
        )

    def test_tau_overhead_factor(self):
        """
        Adding HeterogeneousTau to a membrane update must be < 1.2x slower
        than a scalar beta update.

        The exp(-dt/tau) computation adds one vectorized exp call per forward;
        with PyTorch vectorization this should be negligible overhead.
        """
        import time

        torch.manual_seed(42)
        B = {batch_size}
        T = {timesteps}
        N = 256
        REPS = 50
        scalar_beta = 0.9

        tau_module = _make_tau(n=N, learnable=False)
        x = torch.randn(B, N)

        # Warm-up
        for _ in range(5):
            _ = scalar_beta * x
            _ = tau_module.beta

        # Time scalar beta
        t0 = time.perf_counter()
        for _ in range(REPS):
            v_s = torch.zeros(B, N)
            for _ in range(T):
                v_s = scalar_beta * v_s + x
        t_scalar = (time.perf_counter() - t0) / REPS

        # Time HeterogeneousTau beta
        t0 = time.perf_counter()
        for _ in range(REPS):
            v_t = torch.zeros(B, N)
            for _ in range(T):
                beta = tau_module.beta
                v_t = beta.unsqueeze(0) * v_t + x
        t_tau = (time.perf_counter() - t0) / REPS

        overhead = t_tau / (t_scalar + 1e-9)
        MAX_OVERHEAD = 1.2

        assert overhead < MAX_OVERHEAD, (
            f"Tau overhead factor {{overhead:.2f}}x exceeds {{MAX_OVERHEAD}}x. "
            f"Scalar: {{t_scalar*1000:.2f}} ms, Tau: {{t_tau*1000:.2f}} ms "
            f"(per {{T}}-step sequence, averaged over {{REPS}} reps)."
        )
'''


def _summary_footer() -> str:
    return '''\
# ===========================================================================
# End of auto-generated test file.
# Re-generate with:
#   python skills/delays-heterogeneous-tau/scripts/gen_delay_tau_tests.py
# ===========================================================================
'''


def build_test_file(timesteps: int, batch_size: int, max_delay: int) -> str:
    """Assemble the complete generated test file as a single string."""
    sections = [
        _header(timesteps, batch_size, max_delay),
        _imports_and_constants(timesteps, batch_size, max_delay),
        _conftest_fixtures(),
        _class_delay_linear_contract(timesteps, batch_size, max_delay),
        _class_delay_conv1d_contract(batch_size, max_delay),
        _class_gaussian_interpolation(max_delay),
        _class_eval_discretization(timesteps, batch_size, max_delay),
        _class_sigma_schedule(),
        _class_delay_gradients(timesteps, batch_size, max_delay),
        _class_heterogeneous_tau_contract(batch_size),
        _class_tau_init_strategies(),
        _class_tau_gradients(timesteps, batch_size),
        _class_checkpoint_roundtrip(timesteps, batch_size, max_delay),
        _class_integration(timesteps, batch_size, max_delay),
        _class_memory_and_performance(timesteps, batch_size, max_delay),
        _summary_footer(),
    ]
    return "\n\n".join(sections) + "\n"


# ---------------------------------------------------------------------------
# Summary printer
# ---------------------------------------------------------------------------

def print_summary(output_path: Path, timesteps: int, batch_size: int, max_delay: int) -> None:
    test_classes = [
        ("TestDelayLinearContract",      "delay",       "Forward shapes, delay range, history update"),
        ("TestDelayConv1dContract",      "delay",       "Conv delay output shape, per-channel params"),
        ("TestGaussianInterpolation",    "delay",       "Kernel normalization, sigma limits, symmetry"),
        ("TestEvalDiscretization",       "delay",       "Integer delays, eval vs train, mode flag"),
        ("TestSigmaSchedule",            "delay",       "Monotonic decrease, convergence, checkpoint"),
        ("TestDelayGradients",           "delay",       "d_raw grad exists, nonzero, FD spot-check"),
        ("TestHeterogeneousTauContract", "tau",         "beta/tau ranges, softplus/exp maps, broadcast"),
        ("TestTauInitStrategies",        "tau",         "Homogeneous, gamma, loguniform, preset bank"),
        ("TestTauGradients",             "tau",         "tau_raw grad learnable, no-grad fixed"),
        ("TestCheckpointRoundTrip",      "delay+tau",   "state_dict keys, reload output, cross-device"),
        ("TestIntegration",              "integration", "Delay+LIF, tau+LIF, both, unroll, ablation"),
        ("TestMemoryAndPerformance",     "slow",        "Memory threshold, delay < 2x, tau < 1.2x"),
    ]

    print()
    print("=" * 74)
    print("  gen_delay_tau_tests.py -- Generated test suite")
    print("=" * 74)
    print(f"  Output file    : {output_path}")
    print(f"  Default T      : {timesteps}")
    print(f"  Default batch  : {batch_size}")
    print(f"  Max delay Td   : {max_delay}")
    print(f"  Granularities  : per_neuron, per_channel, per_layer")
    print(f"  Tau strategies : homogeneous, heterogeneous_gamma,")
    print(f"                   heterogeneous_loguniform, preset_bank")
    print(f"  CUDA skip      : @pytest.mark.skipif(not HAS_CUDA, ...)")
    print()
    print("  Generated test classes:")
    for cls, marker, desc in test_classes:
        print(f"    [{marker:<11s}] {cls:<30s} -- {desc}")
    print()
    print("  Quick run (excludes @slow):")
    print(f"    pytest {output_path} -v")
    print()
    print("  Delay tests only:")
    print(f"    pytest {output_path} -v -m delay")
    print()
    print("  Tau tests only:")
    print(f"    pytest {output_path} -v -m tau")
    print()
    print("  Integration tests:")
    print(f"    pytest {output_path} -v -m integration")
    print()
    print("  All tests including slow:")
    print(f"    pytest {output_path} -v -m 'slow or not slow'")
    print()
    print("  Parallel execution (requires pytest-xdist):")
    print(f"    pytest {output_path} -v -n auto")
    print()
    n_gran  = 3
    n_strat = 4
    fast_approx = (
        n_gran * 4      # TestDelayLinearContract (forward, param, range x gran, + history)
        + 2             # TestDelayConv1dContract
        + 3             # TestGaussianInterpolation
        + 3             # TestEvalDiscretization
        + 4             # TestSigmaSchedule
        + 4             # TestDelayGradients
        + n_strat * 2   # TestHeterogeneousTauContract (beta, tau per strategy)
        + 3             # TestHeterogeneousTauContract (softplus, exp, broadcast)
        + 4             # TestTauInitStrategies
        + 3             # TestTauGradients
        + 4             # TestCheckpointRoundTrip
        + 5             # TestIntegration (non-parametrized)
        + 4             # TestIntegration ablation configs
        + 3             # TestMemoryAndPerformance (@slow)
    )
    print(f"  Estimated test case count: ~{fast_approx}")
    print("=" * 74)
    print()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    args = parse_args()

    output_path = Path(args.output) if args.output else _default_output_path()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    content = build_test_file(args.timesteps, args.batch_size, args.max_delay)
    output_path.write_text(content, encoding="utf-8")

    print_summary(output_path, args.timesteps, args.batch_size, args.max_delay)
    print(f"Written: {output_path}  ({len(content):,} chars, {content.count(chr(10)):,} lines)")


if __name__ == "__main__":
    main()
