"""
gen_budget_tests.py
===================
Generates 100+ pytest test cases for the Compute-Optimal Budget Planner.

Running this script produces a test file at:
    tests/test_budget_planner_generated.py

The generated tests cover:
    - Chinchilla sanity (70B/1.4T, tokens_per_param=20)
    - FLOPs monotonicity (doubling tokens/params doubles FLOPs)
    - Wallclock scaling (doubling GPUs/util halves wallclock)
    - N_opt/D_opt solver correctness (k*N*D == C)
    - Undertraining threshold warnings (CRITICAL/WARNING/OK/INFO)
    - GPU spec lookup (A100/H100/H200/L40S/RTX4090/V100)
    - Report generation (JSON schema, TXT content, SVG)
    - CLI argument parsing (all subcommands)
    - Edge cases (zero, negative, very large, inf, nan)
    - Mode A/B/C correctness and consistency
    - Cost computation, multi-GPU scaling

Usage
-----
    python scripts/gen_budget_tests.py
    python scripts/gen_budget_tests.py --out /custom/path/test_file.py
    pytest tests/test_budget_planner_generated.py -v
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import List

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_SKILL_DIR = os.path.dirname(_SCRIPT_DIR)
_ASSETS_DIR = os.path.join(_SKILL_DIR, "assets")
_TESTS_DIR = os.path.join(_SKILL_DIR, "tests")
_DEFAULT_OUTPUT = os.path.join(_TESTS_DIR, "test_budget_planner_generated.py")


# ---------------------------------------------------------------------------
# Test case generator
# ---------------------------------------------------------------------------

def generate_test_file(output_path: str) -> int:
    """Generate the pytest test file at output_path.

    Returns
    -------
    int
        Number of test functions generated.
    """
    lines: List[str] = []

    def w(*args) -> None:
        lines.append(" ".join(str(a) for a in args))

    def blank() -> None:
        lines.append("")

    def section(title: str) -> None:
        blank()
        w("#" + " " + "=" * 70)
        w(f"# {title}")
        w("#" + " " + "=" * 70)
        blank()

    # Header
    w('"""')
    w("test_budget_planner_generated.py")
    w("Generated by scripts/gen_budget_tests.py — DO NOT EDIT BY HAND.")
    w()
    w("100+ pytest tests for the Compute-Optimal Budget Planner skill.")
    w('"""')
    blank()
    w("from __future__ import annotations")
    blank()
    w("import json")
    w("import math")
    w("import os")
    w("import sys")
    w("import tempfile")
    blank()
    w("import pytest")
    blank()
    w("# Add assets directory to path")
    w("_ASSETS = os.path.join(os.path.dirname(__file__), '..', 'assets')")
    w("sys.path.insert(0, os.path.abspath(_ASSETS))")
    blank()
    w("# Import planner modules")
    w("from budget_config_template import (")
    w("    BudgetConfig, RunSpec, ModelSpec, ComputeBudget, BudgetResult, GPUSpec")
    w(")")
    w("from gpu_specs_template import GPUSpecTable")
    w("from budget_planner_template import BudgetPlanner, _compute_flops, _compute_wallclock, _compute_cost")
    w("from chinchilla_solver_template import ChinchillaSolver")
    w("from report_generator_template import ReportGenerator")
    blank()
    w("# Check for optional deps")
    w("try:")
    w("    import matplotlib")
    w("    HAS_MATPLOTLIB = True")
    w("except ImportError:")
    w("    HAS_MATPLOTLIB = False")
    blank()

    # Fixtures
    w("# " + "-" * 70)
    w("# Fixtures")
    w("# " + "-" * 70)
    blank()
    w("@pytest.fixture")
    w("def planner():")
    w("    specs = GPUSpecTable()")
    w("    config = BudgetConfig(k=6.0, tokens_per_param_target=20.0,")
    w("                          default_utilization=0.35, num_gpus=8,")
    w("                          gpu_type='H100_SXM', dtype='bf16')")
    w("    return BudgetPlanner(specs, config)")
    blank()
    w("@pytest.fixture")
    w("def solver():")
    w("    return ChinchillaSolver(k=6.0, tokens_per_param=20.0)")
    blank()
    w("@pytest.fixture")
    w("def reporter():")
    w("    return ReportGenerator()")
    blank()
    w("@pytest.fixture")
    w("def gpu_table():")
    w("    return GPUSpecTable()")
    blank()
    w("@pytest.fixture")
    w("def standard_run():")
    w("    # 70B, near-optimal: 333863 steps * 2048 * 2048 ≈ 1.4T tokens")
    w("    steps = math.ceil(1.4e12 / (2048 * 2048))")
    w("    return RunSpec(n_params=70e9, seq_len=2048, global_batch=2048,")
    w("                   steps=steps, num_gpus=8, gpu_type='H100_SXM', dtype='bf16')")
    blank()

    test_count = [0]

    def test_fn(name: str, body: List[str]) -> None:
        test_count[0] += 1
        blank()
        w(f"def test_{name}(planner, solver, reporter, gpu_table, standard_run):")
        for line in body:
            w(f"    {line}")
        blank()

    def standalone_test(name: str, body: List[str]) -> None:
        """Test with no fixtures."""
        test_count[0] += 1
        blank()
        w(f"def test_{name}():")
        for line in body:
            w(f"    {line}")
        blank()

    # =========================================================================
    # Section 1: Chinchilla Sanity
    # =========================================================================
    section("1. Chinchilla Sanity Tests")

    standalone_test("chinchilla_70b_tokens_per_param", [
        "n, d = 70e9, 1.4e12",
        "tpp = d / n",
        "assert abs(tpp - 20.0) < 1e-9, f'tokens/param={tpp}, expected 20.0'",
    ])

    standalone_test("chinchilla_70b_flops", [
        "n, d, k = 70e9, 1.4e12, 6",
        "expected = k * n * d",
        "actual = _compute_flops(n, d, k)",
        "assert abs(actual - expected) / expected < 1e-10",
    ])

    standalone_test("chinchilla_undertraining_ratio_at_optimal", [
        "s = ChinchillaSolver(k=6.0, tokens_per_param=20.0)",
        "ratio = s.undertraining_ratio(70e9, 1.4e12)",
        "assert abs(ratio - 1.0) < 1e-10, f'Expected ratio=1.0, got {ratio}'",
    ])

    standalone_test("chinchilla_doubling_params_halves_ratio", [
        "s = ChinchillaSolver(k=6.0, tokens_per_param=20.0)",
        "ratio1 = s.undertraining_ratio(70e9, 1.4e12)",
        "ratio2 = s.undertraining_ratio(140e9, 1.4e12)  # doubled params",
        "assert abs(ratio2 / ratio1 - 0.5) < 1e-10",
    ])

    standalone_test("chinchilla_doubling_tokens_doubles_ratio", [
        "s = ChinchillaSolver(k=6.0, tokens_per_param=20.0)",
        "ratio1 = s.undertraining_ratio(70e9, 1.4e12)",
        "ratio2 = s.undertraining_ratio(70e9, 2.8e12)  # doubled tokens",
        "assert abs(ratio2 / ratio1 - 2.0) < 1e-10",
    ])

    standalone_test("chinchilla_target_tokens_7b", [
        "s = ChinchillaSolver(tokens_per_param=20.0)",
        "t = s.target_tokens(7e9)",
        "assert abs(t - 140e9) < 1, f'Expected 140B, got {t}'",
    ])

    standalone_test("chinchilla_target_tokens_70b", [
        "s = ChinchillaSolver(tokens_per_param=20.0)",
        "t = s.target_tokens(70e9)",
        "assert abs(t - 1.4e12) / 1.4e12 < 1e-10",
    ])

    standalone_test("chinchilla_required_flops_formula", [
        "s = ChinchillaSolver(k=6.0, tokens_per_param=20.0)",
        "f = s.required_flops(70e9, 1.4e12)",
        "expected = 6.0 * 70e9 * 1.4e12",
        "assert abs(f - expected) / expected < 1e-10",
    ])

    standalone_test("chinchilla_gpt3_undertrained", [
        "# GPT-3: 175B params, 300B tokens -> 1.7 tokens/param -> ratio=0.086 (CRITICAL)",
        "s = ChinchillaSolver(k=6.0, tokens_per_param=20.0)",
        "ratio = s.undertraining_ratio(175e9, 300e9)",
        "assert ratio < 0.5, f'GPT-3 should be CRITICAL undertrained, ratio={ratio:.3f}'",
        "assert any('[CRITICAL]' in w for w in s.warnings(ratio))",
    ])

    standalone_test("chinchilla_llama7b_overtrain", [
        "# LLaMA-1 7B: 7B params, 1T tokens -> ~143 tokens/param -> ratio=7.14 (INFO)",
        "s = ChinchillaSolver(k=6.0, tokens_per_param=20.0)",
        "ratio = s.undertraining_ratio(7e9, 1e12)",
        "assert ratio > 2.0, f'LLaMA-1 7B should be overtrain, ratio={ratio:.3f}'",
        "assert any('[INFO]' in w for w in s.warnings(ratio))",
    ])

    # =========================================================================
    # Section 2: FLOPs Monotonicity
    # =========================================================================
    section("2. FLOPs Monotonicity Tests")

    standalone_test("flops_monotonic_tokens", [
        "f1 = _compute_flops(70e9, 1e12, 6)",
        "f2 = _compute_flops(70e9, 2e12, 6)",
        "f3 = _compute_flops(70e9, 4e12, 6)",
        "assert f1 < f2 < f3",
        "assert abs(f2 / f1 - 2.0) < 1e-10",
        "assert abs(f3 / f1 - 4.0) < 1e-10",
    ])

    standalone_test("flops_monotonic_params", [
        "f1 = _compute_flops(7e9, 1e12, 6)",
        "f2 = _compute_flops(70e9, 1e12, 6)",
        "f3 = _compute_flops(700e9, 1e12, 6)",
        "assert f1 < f2 < f3",
        "assert abs(f2 / f1 - 10.0) < 1e-10",
        "assert abs(f3 / f1 - 100.0) < 1e-10",
    ])

    standalone_test("flops_k_linearity", [
        "f_k3 = _compute_flops(70e9, 1e12, 3)",
        "f_k6 = _compute_flops(70e9, 1e12, 6)",
        "assert abs(f_k6 / f_k3 - 2.0) < 1e-10",
    ])

    standalone_test("flops_joint_scaling", [
        "f_base = _compute_flops(70e9, 1.4e12, 6)",
        "f_2x = _compute_flops(140e9, 2.8e12, 6)",
        "assert abs(f_2x / f_base - 4.0) < 1e-10",
    ])

    standalone_test("flops_chinchilla_exact_value", [
        "f = _compute_flops(70e9, 1.4e12, 6)",
        "assert abs(f - 5.88e23) / 5.88e23 < 1e-10",
    ])

    # =========================================================================
    # Section 3: Wallclock Scaling
    # =========================================================================
    section("3. Wallclock Scaling Tests")

    standalone_test("wallclock_gpu_count_inverse", [
        "wc8 = _compute_wallclock(5e23, 8, 989.0, 0.35)",
        "wc16 = _compute_wallclock(5e23, 16, 989.0, 0.35)",
        "assert abs(wc8 / wc16 - 2.0) < 1e-10, f'Ratio should be 2.0, got {wc8/wc16}'",
    ])

    standalone_test("wallclock_utilization_inverse", [
        "wc35 = _compute_wallclock(5e23, 8, 989.0, 0.35)",
        "wc70 = _compute_wallclock(5e23, 8, 989.0, 0.70)",
        "assert abs(wc35 / wc70 - 2.0) < 1e-10",
    ])

    standalone_test("wallclock_token_proportional", [
        "wc1 = _compute_wallclock(6 * 70e9 * 1e12, 8, 989.0, 0.35)",
        "wc2 = _compute_wallclock(6 * 70e9 * 2e12, 8, 989.0, 0.35)",
        "assert abs(wc2 / wc1 - 2.0) < 1e-10",
    ])

    standalone_test("wallclock_positive", [
        "wc = _compute_wallclock(5e23, 8, 989.0, 0.35)",
        "assert wc > 0 and math.isfinite(wc)",
    ])

    standalone_test("wallclock_tflops_inverse", [
        "wc312 = _compute_wallclock(1e23, 8, 312.0, 0.35)",
        "wc989 = _compute_wallclock(1e23, 8, 989.0, 0.35)",
        "ratio = wc312 / wc989",
        "expected = 989.0 / 312.0",
        "assert abs(ratio - expected) / expected < 1e-10",
    ])

    # =========================================================================
    # Section 4: N_opt / D_opt Solver
    # =========================================================================
    section("4. N_opt / D_opt Solver Tests")

    standalone_test("solver_k_N_D_equals_C", [
        "s = ChinchillaSolver(k=6.0, tokens_per_param=20.0)",
        "for C in [1e18, 1e20, 5e22, 5.88e23, 1e25, 1e26]:",
        "    n = s.n_opt(C)",
        "    d = s.d_opt(C)",
        "    reconstructed = 6.0 * n * d",
        "    assert abs(reconstructed - C) / C < 1e-9, f'C={C:.2e}: k*N*D={reconstructed:.6e}'",
    ])

    standalone_test("solver_n_opt_sqrt_scaling", [
        "s = ChinchillaSolver(k=6.0, tokens_per_param=20.0)",
        "n1 = s.n_opt(1e23)",
        "n4 = s.n_opt(4e23)",
        "assert abs(n4 / n1 - 2.0) < 1e-9",
    ])

    standalone_test("solver_d_opt_sqrt_scaling", [
        "s = ChinchillaSolver(k=6.0, tokens_per_param=20.0)",
        "d1 = s.d_opt(1e23)",
        "d4 = s.d_opt(4e23)",
        "assert abs(d4 / d1 - 2.0) < 1e-9",
    ])

    standalone_test("solver_positive_values", [
        "s = ChinchillaSolver(k=6.0, tokens_per_param=20.0)",
        "for C in [1e18, 1e22, 1e26, 1e30]:",
        "    assert s.n_opt(C) > 0",
        "    assert s.d_opt(C) > 0",
        "    assert math.isfinite(s.n_opt(C))",
    ])

    standalone_test("solver_tokens_per_param_consistency", [
        "s = ChinchillaSolver(k=6.0, tokens_per_param=20.0)",
        "for C in [1e20, 5e23, 1e25]:",
        "    n, d = s.n_d_opt(C)",
        "    assert abs(d / n - 20.0) < 1e-6",
    ])

    standalone_test("solver_chinchilla_reference_point", [
        "s = ChinchillaSolver(k=6.0, tokens_per_param=20.0)",
        "C = 6 * 70e9 * 1.4e12",
        "n = s.n_opt(C)",
        "d = s.d_opt(C)",
        "assert abs(n - 70e9) / 70e9 < 1e-6",
        "assert abs(d - 1.4e12) / 1.4e12 < 1e-6",
    ])

    standalone_test("solver_different_k", [
        "s_k6 = ChinchillaSolver(k=6.0, tokens_per_param=20.0)",
        "s_k8 = ChinchillaSolver(k=8.0, tokens_per_param=20.0)",
        "C = 5e23",
        "n6 = s_k6.n_opt(C)",
        "n8 = s_k8.n_opt(C)",
        "# Higher k means more FLOPs per param, so smaller N_opt",
        "assert n8 < n6",
        "# Verify k*N*D == C for k=8",
        "d8 = s_k8.d_opt(C)",
        "assert abs(8.0 * n8 * d8 - C) / C < 1e-9",
    ])

    standalone_test("solver_frontier_monotonic", [
        "s = ChinchillaSolver(k=6.0, tokens_per_param=20.0)",
        "points = s.frontier_points()",
        "ns = [p[1] for p in points]",
        "ds = [p[2] for p in points]",
        "for i in range(1, len(ns)):",
        "    assert ns[i] > ns[i-1]",
        "    assert ds[i] > ds[i-1]",
    ])

    # =========================================================================
    # Section 5: Undertraining Warnings
    # =========================================================================
    section("5. Undertraining Warning Threshold Tests")

    standalone_test("warning_critical_ratio_0_3", [
        "s = ChinchillaSolver(tokens_per_param=20.0)",
        "w = s.warnings(0.3)",
        "assert len(w) > 0",
        "assert any('[CRITICAL]' in msg for msg in w)",
    ])

    standalone_test("warning_critical_ratio_0_49", [
        "s = ChinchillaSolver(tokens_per_param=20.0)",
        "w = s.warnings(0.49)",
        "assert any('[CRITICAL]' in msg for msg in w)",
    ])

    standalone_test("warning_boundary_exactly_0_5_is_warning", [
        "s = ChinchillaSolver(tokens_per_param=20.0)",
        "# ratio = 0.5 is NOT < 0.5, so it's WARNING (not CRITICAL)",
        "w = s.warnings(0.5)",
        "assert len(w) > 0",
        "assert not any('[CRITICAL]' in msg for msg in w)",
        "assert any('[WARNING]' in msg for msg in w)",
    ])

    standalone_test("warning_warning_ratio_0_65", [
        "s = ChinchillaSolver(tokens_per_param=20.0)",
        "w = s.warnings(0.65)",
        "assert any('[WARNING]' in msg for msg in w)",
        "assert not any('[CRITICAL]' in msg for msg in w)",
    ])

    standalone_test("warning_ok_at_0_8_exactly", [
        "s = ChinchillaSolver(tokens_per_param=20.0)",
        "w = s.warnings(0.8)",
        "assert len(w) == 0, f'Expected no warning at ratio=0.8, got: {w}'",
    ])

    standalone_test("warning_ok_at_1_0", [
        "s = ChinchillaSolver(tokens_per_param=20.0)",
        "w = s.warnings(1.0)",
        "assert len(w) == 0",
    ])

    standalone_test("warning_ok_at_1_5", [
        "s = ChinchillaSolver(tokens_per_param=20.0)",
        "w = s.warnings(1.5)",
        "assert len(w) == 0",
    ])

    standalone_test("warning_ok_at_2_0_exactly", [
        "s = ChinchillaSolver(tokens_per_param=20.0)",
        "w = s.warnings(2.0)",
        "assert len(w) == 0, f'Expected no warning at ratio=2.0, got: {w}'",
    ])

    standalone_test("warning_info_ratio_2_001", [
        "s = ChinchillaSolver(tokens_per_param=20.0)",
        "w = s.warnings(2.001)",
        "assert any('[INFO]' in msg for msg in w)",
        "assert not any('[CRITICAL]' in msg for msg in w)",
        "assert not any('[WARNING]' in msg for msg in w)",
    ])

    standalone_test("warning_info_ratio_7_1", [
        "s = ChinchillaSolver(tokens_per_param=20.0)",
        "w = s.warnings(7.1)",
        "assert any('[INFO]' in msg for msg in w)",
    ])

    # =========================================================================
    # Section 6: GPU Spec Lookup
    # =========================================================================
    section("6. GPU Spec Lookup Tests")

    standalone_test("gpu_a100_80gb_sxm_bf16", [
        "t = GPUSpecTable()",
        "spec = t.lookup('A100_80GB_SXM', dtype='bf16')",
        "assert spec is not None",
        "assert spec.peak_tflops == 312.0",
        "assert spec.mem_gb == 80.0",
        "assert spec.is_sparse is False",
    ])

    standalone_test("gpu_h100_sxm_bf16", [
        "t = GPUSpecTable()",
        "spec = t.lookup('H100_SXM', dtype='bf16')",
        "assert spec is not None",
        "assert spec.peak_tflops == 989.0",
        "assert spec.mem_gb == 80.0",
    ])

    standalone_test("gpu_h200_bf16", [
        "t = GPUSpecTable()",
        "spec = t.lookup('H200', dtype='bf16')",
        "assert spec is not None",
        "assert spec.peak_tflops == 989.0",
        "assert spec.mem_gb == 141.0",
    ])

    standalone_test("gpu_v100_fp16", [
        "t = GPUSpecTable()",
        "spec = t.lookup('V100', dtype='fp16')",
        "assert spec is not None",
        "assert spec.peak_tflops == 125.0",
        "assert spec.mem_gb == 32.0",
    ])

    standalone_test("gpu_l40s_bf16", [
        "t = GPUSpecTable()",
        "spec = t.lookup('L40S', dtype='bf16')",
        "assert spec is not None",
        "assert spec.peak_tflops == 362.0",
        "assert spec.mem_gb == 48.0",
    ])

    standalone_test("gpu_rtx4090_bf16", [
        "t = GPUSpecTable()",
        "spec = t.lookup('RTX 4090', dtype='bf16')",
        "assert spec is not None",
        "assert spec.peak_tflops == 330.0",
        "assert spec.mem_gb == 24.0",
    ])

    standalone_test("gpu_unknown_returns_none", [
        "t = GPUSpecTable()",
        "spec = t.lookup('NonExistentGPU9000')",
        "assert spec is None",
    ])

    standalone_test("gpu_validate_or_fallback_user_supplied", [
        "t = GPUSpecTable()",
        "spec = t.validate_or_fallback('UnknownGPU', user_peak_tflops=500.0, user_mem_gb=40.0)",
        "assert spec.peak_tflops == 500.0",
        "assert spec.mem_gb == 40.0",
        "assert spec.is_user_supplied is True",
    ])

    standalone_test("gpu_validate_or_fallback_raises_without_user_values", [
        "t = GPUSpecTable()",
        "with pytest.raises(ValueError):",
        "    t.validate_or_fallback('NonExistentGPU9000')",
    ])

    standalone_test("gpu_fuzzy_lowercase_h100", [
        "t = GPUSpecTable()",
        "spec = t.lookup('h100')",
        "assert spec is not None",
        "assert spec.peak_tflops == 989.0",
    ])

    standalone_test("gpu_fuzzy_h100_formats", [
        "t = GPUSpecTable()",
        "for q in ['H100 SXM', 'H100_SXM', 'h100_sxm', 'h100sxm']:",
        "    spec = t.lookup(q)",
        "    assert spec is not None, f'{q!r} not found'",
        "    assert spec.peak_tflops == 989.0",
    ])

    standalone_test("gpu_fuzzy_4090_shorthand", [
        "t = GPUSpecTable()",
        "spec = t.lookup('4090')",
        "assert spec is not None",
        "assert spec.peak_tflops == 330.0",
    ])

    standalone_test("gpu_dtype_selection_h100", [
        "t = GPUSpecTable()",
        "bf16 = t.lookup('H100_SXM', dtype='bf16')",
        "fp32 = t.lookup('H100_SXM', dtype='fp32')",
        "assert bf16.peak_tflops > fp32.peak_tflops",
    ])

    standalone_test("gpu_list_gpus", [
        "t = GPUSpecTable()",
        "gpus = t.list_gpus()",
        "assert 'H100 SXM' in gpus",
        "assert 'A100 80GB SXM' in gpus",
        "assert len(gpus) >= 5",
    ])

    standalone_test("gpu_h100_sxm_vs_pcie", [
        "t = GPUSpecTable()",
        "sxm = t.lookup('H100_SXM')",
        "pcie = t.lookup('H100_PCIe')",
        "assert sxm.peak_tflops > pcie.peak_tflops",
        "assert sxm.peak_tflops == 989.0",
        "assert pcie.peak_tflops == 756.0",
    ])

    standalone_test("gpu_a100_40gb_memory", [
        "t = GPUSpecTable()",
        "spec = t.lookup('a100_40gb')",
        "assert spec is not None",
        "assert spec.mem_gb == 40.0",
    ])

    # =========================================================================
    # Section 7: Report Generation
    # =========================================================================
    section("7. Report Generation Tests")

    # Helper to generate a mock result for report tests
    w("def _make_test_result(mode='validate_run'):")
    w("    n_params = 7e9")
    w("    steps = 100000")
    w("    seq_len = 2048")
    w("    global_batch = 2048")
    w("    total_tokens = steps * seq_len * global_batch")
    w("    return BudgetResult(")
    w("        mode=mode,")
    w("        inputs={'n_params': n_params, 'seq_len': seq_len, 'global_batch': global_batch,")
    w("                'steps': steps, 'num_gpus': 8, 'gpu_type': 'H100_SXM', 'dtype': 'bf16'},")
    w("        assumptions={'k': 6.0, 'tokens_per_param_target': 20.0, 'utilization': 0.35,")
    w("                     'gpu_type': 'H100_SXM', 'gpu_spec_source': 'table',")
    w("                     'peak_tflops': 989.0, 'is_sparse': False, 'dtype': 'bf16', 'num_gpus': 8},")
    w("        derived={")
    w("            'total_tokens': total_tokens,")
    w("            'tokens_per_param': total_tokens / n_params,")
    w("            'total_flops': 6 * n_params * total_tokens,")
    w("            'predicted_wallclock_hours': 42.0,")
    w("            'predicted_cost_usd': None,")
    w("            'undertraining_ratio': (total_tokens / n_params) / 20.0,")
    w("            'n_opt': 2.5e9,")
    w("            'd_opt': 5.0e10,")
    w("        },")
    w("        warnings=['[WARNING] Undertrained'],")
    w("        suggestions=['Increase tokens.'],")
    w("    )")
    blank()

    standalone_test("report_json_roundtrip", [
        "r = _make_test_result()",
        "rep = ReportGenerator()",
        "j = rep.write_json(r, path=None)",
        "loaded = json.loads(j)",
        "assert 'schema_version' in loaded",
        "assert loaded['mode'] == 'validate_run'",
        "assert 'inputs' in loaded",
        "assert 'assumptions' in loaded",
        "assert 'derived' in loaded",
        "assert 'warnings' in loaded",
        "assert 'suggestions' in loaded",
    ])

    standalone_test("report_json_to_file", [
        "r = _make_test_result()",
        "rep = ReportGenerator()",
        "with tempfile.TemporaryDirectory() as d:",
        "    p = os.path.join(d, 'budget.json')",
        "    rep.write_json(r, p)",
        "    assert os.path.exists(p)",
        "    assert os.path.getsize(p) > 0",
        "    loaded = json.loads(open(p).read())",
        "    assert loaded['mode'] == 'validate_run'",
    ])

    standalone_test("report_txt_non_empty", [
        "r = _make_test_result()",
        "rep = ReportGenerator()",
        "txt = rep.write_txt(r, path=None)",
        "assert len(txt) > 100",
    ])

    standalone_test("report_txt_contains_required_sections", [
        "r = _make_test_result()",
        "rep = ReportGenerator()",
        "txt = rep.write_txt(r, path=None)",
        "for phrase in ['COMPUTE BUDGET', 'CHINCHILLA CHECK', 'PLAN SUMMARY', 'tokens/param']:",
        "    assert phrase in txt, f'Missing section: {phrase!r}'",
    ])

    standalone_test("report_txt_all_modes", [
        "rep = ReportGenerator()",
        "for mode in ['validate_run', 'compute_required', 'solve_optimal']:",
        "    r = _make_test_result(mode)",
        "    txt = rep.write_txt(r, path=None)",
        "    assert len(txt) > 50",
    ])

    standalone_test("report_svg_no_exception", [
        "r = _make_test_result()",
        "rep = ReportGenerator()",
        "with tempfile.TemporaryDirectory() as d:",
        "    p = os.path.join(d, 'budget.svg')",
        "    success = rep.write_svg(r, p)",
        "    if HAS_MATPLOTLIB:",
        "        assert success is True",
        "        assert os.path.exists(p)",
        "        assert os.path.getsize(p) > 0",
        "    else:",
        "        assert success is False  # graceful skip",
    ])

    standalone_test("report_json_schema_version", [
        "r = _make_test_result()",
        "rep = ReportGenerator()",
        "j = json.loads(rep.write_json(r, None))",
        "assert j['schema_version'] == '1.0'",
    ])

    standalone_test("report_json_handles_inf_nan", [
        "r = _make_test_result()",
        "r.derived['total_flops'] = float('inf')",
        "r.derived['tokens_per_param'] = float('nan')",
        "rep = ReportGenerator()",
        "j = json.loads(rep.write_json(r, None))",
        "assert j['derived']['total_flops'] is None",
        "assert j['derived']['tokens_per_param'] is None",
    ])

    standalone_test("report_write_all_creates_files", [
        "r = _make_test_result()",
        "rep = ReportGenerator()",
        "with tempfile.TemporaryDirectory() as d:",
        "    written = rep.write_all(r, d, formats=['json', 'txt'])",
        "    assert 'json' in written",
        "    assert 'txt' in written",
        "    assert os.path.exists(written['json'])",
        "    assert os.path.exists(written['txt'])",
    ])

    # =========================================================================
    # Section 8: Mode A (Validate Run)
    # =========================================================================
    section("8. Mode A (Validate Run) Tests")

    standalone_test("mode_a_chinchilla_70b_1_4t", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig(k=6.0, tokens_per_param_target=20.0)",
        "p = BudgetPlanner(specs, config)",
        "steps = math.ceil(1.4e12 / (2048 * 2048))",
        "run = RunSpec(n_params=70e9, seq_len=2048, global_batch=2048, steps=steps, num_gpus=8, gpu_type='H100_SXM')",
        "result = p.validate_run(run)",
        "assert result.mode == 'validate_run'",
        "assert abs(result.derived['tokens_per_param'] - 20.0) < 0.01",
        "assert result.derived['undertraining_ratio'] >= 0.99",
        "assert result.derived['undertraining_ratio'] <= 1.01",
    ])

    standalone_test("mode_a_returns_budget_result", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "run = RunSpec(n_params=7e9, seq_len=2048, global_batch=2048, steps=10000, num_gpus=8)",
        "result = p.validate_run(run)",
        "assert isinstance(result, BudgetResult)",
        "assert result.warnings is not None",
        "assert result.suggestions is not None",
        "assert result.derived.get('total_flops') is not None",
    ])

    standalone_test("mode_a_undertraining_critical", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "# 500 steps * 2048 * 2048 ≈ 2B tokens, 2B/7B = 0.29 tokens/param -> ratio ≈ 0.014 (CRITICAL)",
        "run = RunSpec(n_params=7e9, seq_len=2048, global_batch=2048, steps=500, num_gpus=8)",
        "result = p.validate_run(run)",
        "assert result.has_critical_warnings()",
        "assert result.derived['undertraining_ratio'] < 0.5",
    ])

    standalone_test("mode_a_suggestions_for_undertrained", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "run = RunSpec(n_params=7e9, seq_len=2048, global_batch=2048, steps=1000, num_gpus=8)",
        "result = p.validate_run(run)",
        "assert len(result.suggestions) > 0",
    ])

    standalone_test("mode_a_wallclock_positive", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "run = RunSpec(n_params=7e9, seq_len=2048, global_batch=2048, steps=100000, num_gpus=8)",
        "result = p.validate_run(run)",
        "assert result.predicted_wallclock_hours is not None",
        "assert result.predicted_wallclock_hours > 0",
    ])

    standalone_test("mode_a_no_warnings_at_optimal", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "steps = math.ceil(20.0 * 7e9 / (2048 * 2048))",
        "run = RunSpec(n_params=7e9, seq_len=2048, global_batch=2048, steps=steps, num_gpus=8)",
        "result = p.validate_run(run)",
        "assert not result.has_critical_warnings()",
    ])

    # =========================================================================
    # Section 9: Mode B (Compute Required)
    # =========================================================================
    section("9. Mode B (Compute Required) Tests")

    standalone_test("mode_b_70b_tokens_per_param", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "model = ModelSpec(n_params=70e9, seq_len=2048, global_batch=2048)",
        "result = p.compute_required(model)",
        "tpp = result.derived['tokens_per_param']",
        "assert abs(tpp - 20.0) < 0.001",
    ])

    standalone_test("mode_b_steps_positive", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "model = ModelSpec(n_params=70e9)",
        "result = p.compute_required(model)",
        "assert result.derived['required_steps'] > 0",
    ])

    standalone_test("mode_b_actual_tokens_near_target", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "model = ModelSpec(n_params=70e9)",
        "result = p.compute_required(model)",
        "target = 20.0 * 70e9",
        "actual = result.derived['actual_tokens']",
        "assert abs(actual - target) / target < 0.001",
    ])

    standalone_test("mode_b_wallclock_positive", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "model = ModelSpec(n_params=7e9)",
        "result = p.compute_required(model)",
        "assert result.predicted_wallclock_hours > 0",
    ])

    standalone_test("mode_b_with_cost", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig(cost_per_gpu_hour=4.0)",
        "p = BudgetPlanner(specs, config)",
        "model = ModelSpec(n_params=7e9, cost_per_gpu_hour=4.0)",
        "result = p.compute_required(model)",
        "assert result.predicted_cost_usd is not None",
        "assert result.predicted_cost_usd > 0",
    ])

    # =========================================================================
    # Section 10: Mode C (Solve Optimal)
    # =========================================================================
    section("10. Mode C (Solve Optimal) Tests")

    standalone_test("mode_c_flops_kNoptDopt_eq_C", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "for C in [1e20, 5e23, 1e25]:",
        "    budget = ComputeBudget(mode='flops', total_flops=C)",
        "    result = p.solve_optimal(budget)",
        "    n, d = result.derived['n_opt'], result.derived['d_opt']",
        "    reconstructed = 6.0 * n * d",
        "    assert abs(reconstructed - C) / C < 1e-6",
    ])

    standalone_test("mode_c_time_budget", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "budget = ComputeBudget(mode='time', hours=1000.0, num_gpus=8,",
        "                        gpu_type='H100_SXM', utilization=0.35)",
        "result = p.solve_optimal(budget)",
        "assert result.derived['n_opt'] > 0",
        "assert result.derived['d_opt'] > 0",
        "assert result.predicted_wallclock_hours == 1000.0",
    ])

    standalone_test("mode_c_money_budget", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig(cost_per_gpu_hour=4.0)",
        "p = BudgetPlanner(specs, config)",
        "budget = ComputeBudget(mode='money', budget_dollars=10000.0,",
        "                        cost_per_gpu_hour=4.0, num_gpus=8, gpu_type='H100_SXM',",
        "                        utilization=0.35)",
        "result = p.solve_optimal(budget)",
        "assert result.derived['n_opt'] > 0",
        "assert result.derived['predicted_cost_usd'] == 10000.0",
    ])

    standalone_test("mode_c_tokens_per_param_at_optimal", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "budget = ComputeBudget(mode='flops', total_flops=5e23)",
        "result = p.solve_optimal(budget)",
        "tpp = result.derived['tokens_per_param']",
        "assert abs(tpp - 20.0) < 1e-6",
    ])

    standalone_test("mode_c_undertraining_ratio_1_0", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "budget = ComputeBudget(mode='flops', total_flops=5e23)",
        "result = p.solve_optimal(budget)",
        "assert abs(result.derived['undertraining_ratio'] - 1.0) < 1e-6",
    ])

    # =========================================================================
    # Section 11: Edge Cases
    # =========================================================================
    section("11. Edge Cases")

    standalone_test("edge_near_zero_params_flops", [
        "f = _compute_flops(n_params=1, total_tokens=1e9, k=6)",
        "assert f == 6e9",
    ])

    standalone_test("edge_near_zero_tokens_flops", [
        "f = _compute_flops(n_params=70e9, total_tokens=1, k=6)",
        "assert f == 6 * 70e9",
    ])

    standalone_test("edge_very_large_params", [
        "s = ChinchillaSolver(k=6.0, tokens_per_param=20.0)",
        "n = s.n_opt(1e28)",
        "assert n > 0 and math.isfinite(n)",
    ])

    standalone_test("edge_negative_params_raises", [
        "with pytest.raises(ValueError):",
        "    RunSpec(n_params=-1, seq_len=2048, global_batch=2048, steps=100)",
    ])

    standalone_test("edge_zero_params_raises", [
        "with pytest.raises(ValueError):",
        "    RunSpec(n_params=0, seq_len=2048, global_batch=2048, steps=100)",
    ])

    standalone_test("edge_negative_seq_len_raises", [
        "with pytest.raises(ValueError):",
        "    RunSpec(n_params=7e9, seq_len=-1, global_batch=2048, steps=100)",
    ])

    standalone_test("edge_budget_config_negative_k_raises", [
        "with pytest.raises(ValueError):",
        "    BudgetConfig(k=-1.0)",
    ])

    standalone_test("edge_budget_config_zero_utilization_raises", [
        "with pytest.raises(ValueError):",
        "    BudgetConfig(default_utilization=0.0)",
    ])

    standalone_test("edge_budget_config_over_1_utilization_raises", [
        "with pytest.raises(ValueError):",
        "    BudgetConfig(default_utilization=1.5)",
    ])

    standalone_test("edge_utilization_1_0_valid", [
        "# Utilization=1.0 is theoretical max, should be valid",
        "config = BudgetConfig(default_utilization=1.0)",
        "assert config.default_utilization == 1.0",
    ])

    standalone_test("edge_solver_negative_compute_raises", [
        "s = ChinchillaSolver()",
        "with pytest.raises(ValueError):",
        "    s.n_opt(-1.0)",
    ])

    standalone_test("edge_solver_zero_compute_raises", [
        "s = ChinchillaSolver()",
        "with pytest.raises(ValueError):",
        "    s.n_opt(0.0)",
    ])

    standalone_test("edge_very_large_budget_finite", [
        "s = ChinchillaSolver()",
        "n = s.n_opt(1e30)",
        "assert math.isfinite(n) and n > 0",
    ])

    standalone_test("edge_compute_budget_invalid_mode_raises", [
        "with pytest.raises(ValueError):",
        "    ComputeBudget(mode='invalid_mode')",
    ])

    standalone_test("edge_compute_budget_flops_no_total_raises", [
        "with pytest.raises(ValueError):",
        "    ComputeBudget(mode='flops')  # missing total_flops",
    ])

    # =========================================================================
    # Section 12: Cost Computation
    # =========================================================================
    section("12. Cost Computation Tests")

    standalone_test("cost_basic", [
        "cost = _compute_cost(100.0, 8, 4.0)",
        "assert abs(cost - 3200.0) < 1e-6",
    ])

    standalone_test("cost_none_when_no_price", [
        "cost = _compute_cost(100.0, 8, None)",
        "assert cost is None",
    ])

    standalone_test("cost_scales_with_gpus", [
        "cost1 = _compute_cost(100.0, 8, 4.0)",
        "cost2 = _compute_cost(100.0, 16, 4.0)",
        "assert abs(cost2 / cost1 - 2.0) < 1e-10",
    ])

    standalone_test("cost_scales_with_hours", [
        "cost1 = _compute_cost(100.0, 8, 4.0)",
        "cost2 = _compute_cost(200.0, 8, 4.0)",
        "assert abs(cost2 / cost1 - 2.0) < 1e-10",
    ])

    standalone_test("cost_scales_with_price", [
        "cost1 = _compute_cost(100.0, 8, 4.0)",
        "cost2 = _compute_cost(100.0, 8, 8.0)",
        "assert abs(cost2 / cost1 - 2.0) < 1e-10",
    ])

    # =========================================================================
    # Section 13: Dataclass Serialization
    # =========================================================================
    section("13. Dataclass Serialization Tests")

    standalone_test("budget_config_roundtrip", [
        "c = BudgetConfig(k=8.0, tokens_per_param_target=30.0, default_utilization=0.4)",
        "d = c.to_dict()",
        "c2 = BudgetConfig.from_dict(d)",
        "assert c2.k == 8.0",
        "assert c2.tokens_per_param_target == 30.0",
        "assert c2.default_utilization == 0.4",
    ])

    standalone_test("run_spec_roundtrip", [
        "r = RunSpec(n_params=7e9, seq_len=2048, global_batch=2048, steps=500, num_gpus=8)",
        "d = r.to_dict()",
        "r2 = RunSpec.from_dict(d)",
        "assert r2.n_params == 7e9",
        "assert r2.num_gpus == 8",
    ])

    standalone_test("model_spec_roundtrip", [
        "m = ModelSpec(n_params=70e9, seq_len=4096, global_batch=4096)",
        "d = m.to_dict()",
        "m2 = ModelSpec.from_dict(d)",
        "assert m2.n_params == 70e9",
        "assert m2.seq_len == 4096",
    ])

    standalone_test("budget_result_json_roundtrip", [
        "result = BudgetResult(",
        "    mode='validate_run',",
        "    inputs={'n_params': 7e9},",
        "    assumptions={'k': 6.0},",
        "    derived={'total_tokens': 2e12, 'tokens_per_param': 285.7, 'total_flops': 8.4e22,",
        "             'predicted_wallclock_hours': 131.6, 'predicted_cost_usd': None,",
        "             'undertraining_ratio': 14.3, 'n_opt': 2.65e9, 'd_opt': 5.3e10},",
        "    warnings=['[INFO] overtrain'],",
        ")",
        "j = result.to_json()",
        "result2 = BudgetResult.from_json(j)",
        "assert result2.mode == 'validate_run'",
        "assert result2.derived['total_tokens'] == 2e12",
    ])

    standalone_test("run_spec_total_tokens_property", [
        "r = RunSpec(n_params=7e9, seq_len=2048, global_batch=2048, steps=100)",
        "assert r.total_tokens == 100 * 2048 * 2048",
    ])

    # =========================================================================
    # Section 14: Multi-GPU Scaling
    # =========================================================================
    section("14. Multi-GPU Scaling Tests")

    standalone_test("multigpu_wallclock_scales_linearly", [
        "wc1 = _compute_wallclock(1e23, 1, 989.0, 0.35)",
        "wc8 = _compute_wallclock(1e23, 8, 989.0, 0.35)",
        "assert abs(wc1 / wc8 - 8.0) < 1e-10",
    ])

    standalone_test("multigpu_wallclock_256gpu", [
        "wc8 = _compute_wallclock(1e23, 8, 989.0, 0.35)",
        "wc256 = _compute_wallclock(1e23, 256, 989.0, 0.35)",
        "assert abs(wc8 / wc256 - 32.0) < 1e-10",
    ])

    standalone_test("multigpu_planner_validate_run", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "run1 = RunSpec(n_params=7e9, seq_len=2048, global_batch=2048, steps=100000, num_gpus=1)",
        "run8 = RunSpec(n_params=7e9, seq_len=2048, global_batch=2048, steps=100000, num_gpus=8)",
        "r1 = p.validate_run(run1)",
        "r8 = p.validate_run(run8)",
        "# Same total tokens, same FLOPs, 8x speedup",
        "assert abs(r1.derived['total_tokens'] - r8.derived['total_tokens']) < 1",
        "wc1 = r1.predicted_wallclock_hours",
        "wc8 = r8.predicted_wallclock_hours",
        "assert abs(wc1 / wc8 - 8.0) < 1e-6",
    ])

    # =========================================================================
    # Section 15: Mode Consistency Tests
    # =========================================================================
    section("15. Mode Consistency Tests")

    standalone_test("mode_a_b_consistency_at_optimal", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "model = ModelSpec(n_params=7e9, seq_len=2048, global_batch=2048)",
        "r_b = p.compute_required(model)",
        "steps = r_b.derived['required_steps']",
        "run = RunSpec(n_params=7e9, seq_len=2048, global_batch=2048, steps=steps, num_gpus=8)",
        "r_a = p.validate_run(run)",
        "# Both should give tokens/param close to 20",
        "assert abs(r_a.derived['tokens_per_param'] - 20.0) < 0.01",
        "assert abs(r_b.derived['tokens_per_param'] - 20.0) < 0.001",
    ])

    standalone_test("mode_c_b_consistency", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "budget = ComputeBudget(mode='flops', total_flops=5e23)",
        "r_c = p.solve_optimal(budget)",
        "n_opt = r_c.derived['n_opt']",
        "model = ModelSpec(n_params=n_opt, seq_len=2048, global_batch=2048)",
        "r_b = p.compute_required(model)",
        "# tokens_per_param should be ~20 in both",
        "assert abs(r_b.derived['tokens_per_param'] - 20.0) < 0.001",
    ])

    standalone_test("all_modes_produce_budget_result", [
        "specs = GPUSpecTable()",
        "config = BudgetConfig()",
        "p = BudgetPlanner(specs, config)",
        "run = RunSpec(n_params=7e9, seq_len=2048, global_batch=2048, steps=10000, num_gpus=8)",
        "r_a = p.validate_run(run)",
        "r_b = p.compute_required(ModelSpec(n_params=7e9))",
        "r_c = p.solve_optimal(ComputeBudget(mode='flops', total_flops=1e22))",
        "for r, m in [(r_a,'validate_run'), (r_b,'compute_required'), (r_c,'solve_optimal')]:",
        "    assert isinstance(r, BudgetResult), f'{m} did not return BudgetResult'",
        "    assert r.mode == m",
        "    assert r.warnings is not None",
        "    assert r.suggestions is not None",
        "    assert r.derived.get('total_flops') is not None",
    ])

    # Write the file
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    content = "\n".join(lines) + "\n"
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(content)

    return test_count[0]


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate pytest test cases for the Compute-Optimal Budget Planner."
    )
    parser.add_argument(
        "--out", type=str, default=_DEFAULT_OUTPUT,
        help=f"Output file path. Default: {_DEFAULT_OUTPUT}"
    )
    parser.add_argument(
        "--count_only", action="store_true",
        help="Print test count without writing the file."
    )
    args = parser.parse_args()

    if args.count_only:
        # Generate to a temp file and count
        import tempfile
        with tempfile.NamedTemporaryFile(suffix=".py", delete=False) as tf:
            tmp = tf.name
        n = generate_test_file(tmp)
        os.unlink(tmp)
        print(f"Would generate {n} test functions.")
        return 0

    n = generate_test_file(args.out)
    print(f"Generated {n} test functions -> {args.out}")
    print(f"Run with: pytest {args.out} -v")
    return 0


if __name__ == "__main__":
    sys.exit(main())
