"""
config_templates.py
===================
Generators for the four YAML configuration files in the world model scaffold.

Each function returns a valid YAML string.  The ``write_configs`` function
writes all four files to a given output directory.

Usage (self-test):
    python config_templates.py
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Model config
# ---------------------------------------------------------------------------


def generate_model_config(
    encoder_type: str = "vit",
    encoder_embed_dim: int = 512,
    dynamics_type: str = "rssm",
    decoder_type: str = "conv",
    include_memory: bool = False,
    include_planner: bool = False,
) -> str:
    """Generate YAML content for model.yaml.

    Parameters
    ----------
    encoder_type : str
        Registry key for the encoder implementation.
    encoder_embed_dim : int
        Embedding dimension; must match dynamics state_dim.
    dynamics_type : str
        Registry key for the dynamics implementation.
    decoder_type : str
        Registry key for the decoder implementation.
    include_memory : bool
        Whether to enable the memory section.
    include_planner : bool
        Whether to enable the planner section.

    Returns
    -------
    str
        Valid YAML string.
    """
    memory_block = f"""
memory:
  enabled: {str(include_memory).lower()}
  type: episodic
  params:
    capacity: 1000
    key_dim: {encoder_embed_dim}
    value_dim: {encoder_embed_dim}
"""

    planner_block = f"""
planner:
  enabled: {str(include_planner).lower()}
  type: cem
  params:
    num_samples: 1000
    num_elites: 100
    num_iterations: 5
    action_dim: 6
    horizon: 12
"""

    yaml_str = f"""# Model architecture configuration
# Generated by world-model-scaffold

encoder:
  type: {encoder_type}
  params:
    embed_dim: {encoder_embed_dim}
    image_size: 64
    patch_size: 8
    num_heads: 8
    depth: 6
    dropout: 0.1

dynamics:
  type: {dynamics_type}
  params:
    state_dim: {encoder_embed_dim}
    action_dim: 6
    hidden_dim: 256
    num_layers: 2
    cell_type: gru

decoder:
  type: {decoder_type}
  params:
    input_dim: {encoder_embed_dim}
    output_shape: [3, 64, 64]
    hidden_channels: [256, 128, 64]
{memory_block if include_memory else "memory:\\n  enabled: false\\n"}
{planner_block if include_planner else "planner:\\n  enabled: false\\n"}
"""
    return yaml_str


# ---------------------------------------------------------------------------
# Training config
# ---------------------------------------------------------------------------


def generate_training_config(
    lr: float = 3e-4,
    batch_size: int = 32,
    epochs: int = 100,
    optimizer_type: str = "adamw",
    scheduler_type: str = "cosine",
) -> str:
    """Generate YAML content for training.yaml.

    Parameters
    ----------
    lr : float
        Base learning rate.
    batch_size : int
        Training batch size.
    epochs : int
        Total training epochs.
    optimizer_type : str
        Optimizer identifier: adam, adamw, sgd, rmsprop.
    scheduler_type : str
        LR scheduler: cosine, linear, constant, one_cycle.

    Returns
    -------
    str
        Valid YAML string.
    """
    return f"""# Training hyperparameters
# Generated by world-model-scaffold

optimizer:
  type: {optimizer_type}
  lr: {lr}
  weight_decay: 1.0e-5
  betas: [0.9, 0.999]
  eps: 1.0e-8

scheduler:
  type: {scheduler_type}
  warmup_steps: 1000
  total_steps: 100000
  min_lr: 1.0e-6

loss:
  recon_weight: 1.0
  kl_weight: 0.1
  reward_weight: 1.0
  cont_weight: 0.1

training:
  epochs: {epochs}
  batch_size: {batch_size}
  grad_clip: 100.0
  log_every: 100
  validate_every: 1000
  save_every: 5000
  seed: 42

checkpoint:
  save_dir: checkpoints/
  keep_last: 5
  resume_from: null
"""


# ---------------------------------------------------------------------------
# Dataset config
# ---------------------------------------------------------------------------


def generate_dataset_config(
    data_root: str = "/data/world_model_dataset",
    data_format: str = "hdf5",
    sequence_length: int = 16,
    image_size: int = 64,
    num_workers: int = 4,
) -> str:
    """Generate YAML content for dataset.yaml.

    Parameters
    ----------
    data_root : str
        Root directory or environment variable substitution token.
    data_format : str
        Dataset file format: hdf5, zarr, folder.
    sequence_length : int
        Number of frames per training sequence.
    image_size : int
        Square image resolution.
    num_workers : int
        DataLoader worker count.

    Returns
    -------
    str
        Valid YAML string.
    """
    return f"""# Dataset configuration
# Generated by world-model-scaffold
# Use ${{DATA_ROOT}} syntax to substitute environment variables.

data:
  root: {data_root}
  format: {data_format}

splits:
  train: train/
  val: val/
  test: test/

sequence:
  length: {sequence_length}
  frame_skip: 1
  image_size: [{image_size}, {image_size}]
  channels: 3

preprocessing:
  normalize: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  random_crop: false
  horizontal_flip: false
  color_jitter:
    enabled: false
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4

loader:
  num_workers: {num_workers}
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true
"""


# ---------------------------------------------------------------------------
# Hardware config
# ---------------------------------------------------------------------------


def generate_hardware_config(
    device: str = "cuda",
    dtype: str = "float32",
    distributed_strategy: str = "none",
    num_gpus: int = 1,
    compile_enabled: bool = False,
) -> str:
    """Generate YAML content for hardware.yaml.

    Parameters
    ----------
    device : str
        Compute device: cpu, cuda, cuda:0, etc.
    dtype : str
        Default tensor dtype: float32, float16, bfloat16.
    distributed_strategy : str
        Distributed training: none, ddp, fsdp, deepspeed.
    num_gpus : int
        Number of GPUs for distributed training.
    compile_enabled : bool
        Whether to enable torch.compile.

    Returns
    -------
    str
        Valid YAML string.
    """
    return f"""# Hardware and device configuration
# Generated by world-model-scaffold

device: {device}

precision:
  dtype: {dtype}
  amp: false
  amp_dtype: float16

distributed:
  strategy: {distributed_strategy}
  num_gpus: {num_gpus}
  backend: nccl
  find_unused_parameters: false

compile:
  enabled: {str(compile_enabled).lower()}
  mode: default
  fullgraph: false
  dynamic: false

memory:
  gradient_checkpointing: false
  pin_memory: true
  empty_cache_every: 0

performance:
  cudnn_benchmark: true
  tf32: true
  deterministic: false
"""


# ---------------------------------------------------------------------------
# Writer
# ---------------------------------------------------------------------------


def write_configs(
    output_dir: str,
    encoder_type: str = "vit",
    encoder_embed_dim: int = 512,
    dynamics_type: str = "rssm",
    decoder_type: str = "conv",
    data_root: str = "/data/world_model_dataset",
    device: str = "cuda",
) -> None:
    """Write all four config YAML files to output_dir.

    Creates the output directory if it does not exist.

    Parameters
    ----------
    output_dir : str
        Directory in which to write model.yaml, training.yaml,
        dataset.yaml, and hardware.yaml.
    encoder_type : str
        Encoder registry key for model.yaml.
    encoder_embed_dim : int
        Shared embedding dimension for model.yaml.
    dynamics_type : str
        Dynamics registry key for model.yaml.
    decoder_type : str
        Decoder registry key for model.yaml.
    data_root : str
        Dataset root path for dataset.yaml.
    device : str
        Compute device for hardware.yaml.
    """
    Path(output_dir).mkdir(parents=True, exist_ok=True)

    files = {
        "model.yaml": generate_model_config(
            encoder_type=encoder_type,
            encoder_embed_dim=encoder_embed_dim,
            dynamics_type=dynamics_type,
            decoder_type=decoder_type,
        ),
        "training.yaml": generate_training_config(),
        "dataset.yaml": generate_dataset_config(data_root=data_root),
        "hardware.yaml": generate_hardware_config(device=device),
    }

    for filename, content in files.items():
        path = os.path.join(output_dir, filename)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)

    print(f"Wrote {len(files)} config files to: {output_dir}")


# ---------------------------------------------------------------------------
# Self-test block
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    import sys
    import tempfile

    try:
        import yaml  # type: ignore[import]
    except ImportError:
        print("pyyaml not installed; skipping YAML parse checks.")
        yaml = None  # type: ignore[assignment]

    errors: list[str] = []

    def fail(msg: str) -> None:
        errors.append(f"FAIL: {msg}")

    def ok(msg: str) -> None:
        print(f"  PASS: {msg}")

    # -----------------------------------------------------------------------
    # Test each generator
    # -----------------------------------------------------------------------
    REQUIRED_MODEL_KEYS = ["encoder", "dynamics", "decoder"]
    REQUIRED_TRAINING_KEYS = ["optimizer", "training", "loss"]
    REQUIRED_DATASET_KEYS = ["data", "splits", "sequence"]
    REQUIRED_HARDWARE_KEYS = ["device", "precision", "distributed", "compile"]

    generators = [
        ("model.yaml", generate_model_config, REQUIRED_MODEL_KEYS),
        ("training.yaml", generate_training_config, REQUIRED_TRAINING_KEYS),
        ("dataset.yaml", generate_dataset_config, REQUIRED_DATASET_KEYS),
        ("hardware.yaml", generate_hardware_config, REQUIRED_HARDWARE_KEYS),
    ]

    print("=== Config generation tests ===")
    for name, gen_fn, required_keys in generators:
        print(f"\n  --- {name} ---")
        try:
            content = gen_fn()
            assert isinstance(content, str), "Generator must return str"
            assert len(content) > 0, "Generator must return non-empty string"
            ok(f"{name}: non-empty string produced ({len(content)} chars)")
        except Exception as exc:
            fail(f"{name}: generation failed: {exc}")
            continue

        if yaml is not None:
            try:
                parsed = yaml.safe_load(content)
                assert isinstance(parsed, dict), "Parsed YAML must be a dict"
                ok(f"{name}: parses as valid YAML dict")
            except Exception as exc:
                fail(f"{name}: YAML parse failed: {exc}")
                continue

            for key in required_keys:
                if key not in parsed:
                    fail(f"{name}: missing required key '{key}'")
                else:
                    ok(f"{name}: required key '{key}' present")

    # -----------------------------------------------------------------------
    # Test dimensional consistency in model config
    # -----------------------------------------------------------------------
    print("\n=== Dimensional consistency test ===")
    if yaml is not None:
        try:
            content = generate_model_config(encoder_embed_dim=256)
            parsed = yaml.safe_load(content)
            enc_dim = parsed["encoder"]["params"]["embed_dim"]
            dyn_dim = parsed["dynamics"]["params"]["state_dim"]
            dec_dim = parsed["decoder"]["params"]["input_dim"]
            if enc_dim == dyn_dim == dec_dim:
                ok(f"All dims consistent: {enc_dim}")
            else:
                fail(
                    f"Dimension inconsistency: enc={enc_dim}, dyn={dyn_dim}, dec={dec_dim}"
                )
        except Exception as exc:
            fail(f"Dimensional consistency check failed: {exc}")

    # -----------------------------------------------------------------------
    # Test write_configs writes files
    # -----------------------------------------------------------------------
    print("\n=== write_configs file write test ===")
    with tempfile.TemporaryDirectory() as tmpdir:
        try:
            write_configs(tmpdir)
            for fname in ["model.yaml", "training.yaml", "dataset.yaml", "hardware.yaml"]:
                path = os.path.join(tmpdir, fname)
                assert os.path.isfile(path), f"Missing: {path}"
                assert os.path.getsize(path) > 0, f"Empty: {path}"
                ok(f"File written and non-empty: {fname}")
        except Exception as exc:
            fail(f"write_configs failed: {exc}")

    # -----------------------------------------------------------------------
    # Test numeric values in training config
    # -----------------------------------------------------------------------
    print("\n=== Numeric value validation ===")
    if yaml is not None:
        try:
            parsed = yaml.safe_load(generate_training_config(lr=1e-3, batch_size=64))
            assert parsed["optimizer"]["lr"] == 1e-3, "lr mismatch"
            assert parsed["training"]["batch_size"] == 64, "batch_size mismatch"
            assert parsed["training"]["epochs"] == 100, "epochs mismatch"
            ok("Numeric values correctly embedded in YAML")
        except Exception as exc:
            fail(f"Numeric value validation failed: {exc}")

    # -----------------------------------------------------------------------
    # Summary
    # -----------------------------------------------------------------------
    print("\n=== Summary ===")
    if errors:
        for e in errors:
            print(f"  {e}")
        print(f"\n{len(errors)} test(s) FAILED.")
        sys.exit(1)
    else:
        print("All config template tests PASSED.")
        sys.exit(0)
