#!/usr/bin/env python3
"""Generate comprehensive pytest test file for the Active Inference Agent.

This script produces ``tests/test_active_inference.py`` containing ~80+ test
cases across 13 test classes that map directly to the testing matrix described
in SKILL.md.

Three done-when gates are explicitly exercised:
    (a) EFE sum invariant -- ``TestEFEPureFunctions``
    (b) Horizon stability -- ``TestHorizonStability``
    (c) Minari end-to-end -- ``TestOfflineRL``

Usage::

    # Write to default location
    python scripts/gen_active_inference_tests.py

    # Write to custom path
    python scripts/gen_active_inference_tests.py --output /tmp/test_ai.py

    # Print to stdout without writing
    python scripts/gen_active_inference_tests.py --dry-run
"""

from __future__ import annotations

import argparse
import os
import sys
import textwrap
from pathlib import Path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _indent(text: str, level: int = 1) -> str:
    """Indent every line of *text* by *level* * 4 spaces."""
    prefix = "    " * level
    return textwrap.indent(textwrap.dedent(text), prefix)


def _section_comment(title: str) -> str:
    """Return a prominent section separator comment."""
    bar = "# " + "=" * 70
    return f"\n\n{bar}\n# {title}\n{bar}\n"


# ---------------------------------------------------------------------------
# Content blocks
# ---------------------------------------------------------------------------

def _build_header() -> str:
    """File-level docstring, imports, and top-level constants."""
    return textwrap.dedent('''\
        """Comprehensive pytest tests for the Active Inference Agent.

        Auto-generated by ``scripts/gen_active_inference_tests.py``.

        Covers 13 test classes with ~80+ test methods matching the testing matrix
        defined in SKILL.md.  Three done-when gates are exercised:

            (a) EFE sum invariant          -- TestEFEPureFunctions
            (b) Horizon stability           -- TestHorizonStability
            (c) Minari offline RL end-to-end -- TestOfflineRL

        Run with::

            python -m pytest tests/test_active_inference.py -v
        """

        from __future__ import annotations

        import json
        import math
        import os
        import time
        from dataclasses import dataclass
        from typing import Any, Dict, List, Optional, Tuple
        from unittest.mock import MagicMock, patch

        import pytest
        import torch
        import torch.nn as nn
        import torch.nn.functional as F

        # ---------------------------------------------------------------------------
        # Import the modules under test.
        # The template assets live under brain_ai/decision/ once deployed, but we
        # also support running directly against the template files in assets/.
        # ---------------------------------------------------------------------------
        _IMPORT_ERROR: Optional[str] = None
        try:
            # Production layout
            from brain_ai.decision.active_inference import (
                ActiveInferenceAgent,
                ActiveInferenceFullConfig,
                ActionOutput,
                AgentState,
                AmortizedPolicyConfig,
                EFEConfig,
                GenerativeModelConfig,
                PlannerConfig,
                _BuiltinAmortizedPolicy,
                _BuiltinCEMPlanner,
                _BuiltinEmpowerment,
                _BuiltinEncoder,
                _BuiltinLikelihood,
                _BuiltinPreferences,
                _BuiltinRandomShootingPlanner,
                _BuiltinRolloutEngine,
                _BuiltinTransition,
                _compute_epistemic,
                _compute_instrumental,
                _compute_pragmatic,
                _validate_efe_invariant,
            )
        except ImportError:
            try:
                # Template / standalone layout
                import importlib.util
                import sys as _sys

                _template_path = os.path.join(
                    os.path.dirname(os.path.abspath(__file__)),
                    "..",
                    "assets",
                    "active_inference_template.py",
                )
                _spec = importlib.util.spec_from_file_location(
                    "active_inference_template",
                    _template_path,
                )
                _mod = importlib.util.module_from_spec(_spec)
                _sys.modules["active_inference_template"] = _mod
                _spec.loader.exec_module(_mod)

                ActiveInferenceAgent = _mod.ActiveInferenceAgent
                ActiveInferenceFullConfig = _mod.ActiveInferenceFullConfig
                ActionOutput = _mod.ActionOutput
                AgentState = _mod.AgentState
                AmortizedPolicyConfig = _mod.AmortizedPolicyConfig
                EFEConfig = _mod.EFEConfig
                GenerativeModelConfig = _mod.GenerativeModelConfig
                PlannerConfig = _mod.PlannerConfig
                _BuiltinAmortizedPolicy = _mod._BuiltinAmortizedPolicy
                _BuiltinCEMPlanner = _mod._BuiltinCEMPlanner
                _BuiltinEmpowerment = _mod._BuiltinEmpowerment
                _BuiltinEncoder = _mod._BuiltinEncoder
                _BuiltinLikelihood = _mod._BuiltinLikelihood
                _BuiltinPreferences = _mod._BuiltinPreferences
                _BuiltinRandomShootingPlanner = _mod._BuiltinRandomShootingPlanner
                _BuiltinRolloutEngine = _mod._BuiltinRolloutEngine
                _BuiltinTransition = _mod._BuiltinTransition
                _compute_epistemic = _mod._compute_epistemic
                _compute_instrumental = _mod._compute_instrumental
                _compute_pragmatic = _mod._compute_pragmatic
                _validate_efe_invariant = _mod._validate_efe_invariant
            except Exception as exc:
                _IMPORT_ERROR = str(exc)

        # EFE pure functions from the dedicated template
        _EFE_IMPORT_ERROR: Optional[str] = None
        try:
            from brain_ai.decision.efe import (
                EFEComputer,
                EFEConfig as EFETemplateConfig,
                EmpowermentEstimator,
                RunningNormalization,
                analytical_gaussian_kl,
                analytical_gaussian_pragmatic,
                compute_efe_total,
                compute_epistemic as efe_compute_epistemic,
                compute_instrumental as efe_compute_instrumental,
                compute_pragmatic as efe_compute_pragmatic,
                EFE_SUM_INVARIANT_TOL,
            )
        except ImportError:
            try:
                import importlib.util as _ilu
                import sys as _sys2

                _efe_path = os.path.join(
                    os.path.dirname(os.path.abspath(__file__)),
                    "..",
                    "assets",
                    "efe_template.py",
                )
                _efe_spec = _ilu.spec_from_file_location(
                    "efe_template",
                    _efe_path,
                )
                _efe_mod = _ilu.module_from_spec(_efe_spec)
                _sys2.modules["efe_template"] = _efe_mod
                _efe_spec.loader.exec_module(_efe_mod)

                EFEComputer = _efe_mod.EFEComputer
                EFETemplateConfig = _efe_mod.EFEConfig
                EmpowermentEstimator = _efe_mod.EmpowermentEstimator
                RunningNormalization = _efe_mod.RunningNormalization
                analytical_gaussian_kl = _efe_mod.analytical_gaussian_kl
                analytical_gaussian_pragmatic = _efe_mod.analytical_gaussian_pragmatic
                compute_efe_total = _efe_mod.compute_efe_total
                efe_compute_epistemic = _efe_mod.compute_epistemic
                efe_compute_instrumental = _efe_mod.compute_instrumental
                efe_compute_pragmatic = _efe_mod.compute_pragmatic
                EFE_SUM_INVARIANT_TOL = _efe_mod.EFE_SUM_INVARIANT_TOL
            except Exception as exc:
                _EFE_IMPORT_ERROR = str(exc)

        # Optional dependency flags
        try:
            import pymdp
            PYMDP_AVAILABLE = True
        except ImportError:
            PYMDP_AVAILABLE = False

        try:
            import minari
            MINARI_AVAILABLE = True
        except ImportError:
            MINARI_AVAILABLE = False


        # ======================================================================
        # Constants
        # ======================================================================

        B = 4          # default batch size for tests
        OBS_DIM = 32   # tiny observation dim
        STATE_DIM = 16 # tiny state dim
        ACTION_DIM = 8 # tiny action dim
        HIDDEN_DIM = 32
        SEED = 42
        EFE_TOL = 1e-5
    ''')


def _build_fixtures() -> str:
    """Generate conftest-style fixtures."""
    return textwrap.dedent('''\

        # ======================================================================
        # Fixtures
        # ======================================================================


        @pytest.fixture(autouse=True)
        def seed_everything():
            """Set deterministic seeds before every test."""
            torch.manual_seed(SEED)
            if torch.cuda.is_available():
                torch.cuda.manual_seed_all(SEED)


        @pytest.fixture
        def device():
            """Return CPU device for testing."""
            return torch.device("cpu")


        @pytest.fixture
        def tiny_config() -> ActiveInferenceFullConfig:
            """Minimal config for unit tests: obs=32, state=16, action=8, hidden=32."""
            return ActiveInferenceFullConfig(
                generative=GenerativeModelConfig(
                    obs_dim=OBS_DIM,
                    state_dim=STATE_DIM,
                    action_dim=ACTION_DIM,
                    hidden_dim=HIDDEN_DIM,
                    encoder_layers=2,
                    decoder_layers=2,
                    transition_layers=1,
                    transition_ensemble_size=1,
                    use_residual_transition=False,
                    action_type="discrete",
                ),
                efe=EFEConfig(
                    pragmatic_weight=1.0,
                    epistemic_weight=1.0,
                    instrumental_weight=0.1,
                    num_samples=4,
                    discount_factor=0.99,
                    normalize_by_horizon=False,
                    use_empowerment=True,
                ),
                planner=PlannerConfig(
                    planner_type="random_shooting",
                    planning_horizon=2,
                    num_rollouts=8,
                ),
                amortized=AmortizedPolicyConfig(enabled=False),
                seed=SEED,
            )


        @pytest.fixture
        def toy_encoder(tiny_config):
            """Build a tiny latent encoder."""
            gc = tiny_config.generative
            return _BuiltinEncoder(
                obs_dim=gc.obs_dim,
                state_dim=gc.state_dim,
                hidden_dim=gc.hidden_dim,
                num_layers=gc.encoder_layers,
            )


        @pytest.fixture
        def toy_likelihood(tiny_config):
            """Build a tiny likelihood decoder."""
            gc = tiny_config.generative
            return _BuiltinLikelihood(
                state_dim=gc.state_dim,
                obs_dim=gc.obs_dim,
                hidden_dim=gc.hidden_dim,
                num_layers=gc.decoder_layers,
            )


        @pytest.fixture
        def toy_transition(tiny_config):
            """Build a tiny transition model."""
            gc = tiny_config.generative
            return _BuiltinTransition(
                state_dim=gc.state_dim,
                action_dim=gc.action_dim,
                hidden_dim=gc.hidden_dim,
                action_type=gc.action_type,
                use_residual=gc.use_residual_transition,
            )


        @pytest.fixture
        def toy_preferences(tiny_config):
            """Build a tiny preferences model."""
            gc = tiny_config.generative
            return _BuiltinPreferences(
                obs_dim=gc.obs_dim,
                num_goals=1,
                learnable=True,
            )


        @pytest.fixture
        def toy_empowerment(tiny_config):
            """Build a tiny empowerment estimator."""
            gc = tiny_config.generative
            return _BuiltinEmpowerment(
                state_dim=gc.state_dim,
                action_dim=gc.action_dim,
                hidden_dim=gc.hidden_dim,
            )


        @pytest.fixture
        def toy_rollout_engine(toy_transition, toy_likelihood, toy_preferences,
                               toy_empowerment, tiny_config):
            """Build a rollout engine from tiny sub-modules."""
            return _BuiltinRolloutEngine(
                transition=toy_transition,
                likelihood=toy_likelihood,
                preferences=toy_preferences,
                empowerment=toy_empowerment,
                efe_config=tiny_config.efe,
            )


        @pytest.fixture
        def toy_planner(tiny_config):
            """Build a random shooting planner."""
            gc = tiny_config.generative
            pc = tiny_config.planner
            return _BuiltinRandomShootingPlanner(
                action_dim=gc.action_dim,
                action_type=gc.action_type,
                planner_config=pc,
            )


        @pytest.fixture
        def toy_agent(tiny_config):
            """Build a fully wired ActiveInferenceAgent."""
            return ActiveInferenceAgent(tiny_config)


        @pytest.fixture
        def efe_config():
            """Build a tiny EFE config for the pure-function template."""
            if _EFE_IMPORT_ERROR is not None:
                pytest.skip(f"EFE template not available: {_EFE_IMPORT_ERROR}")
            return EFETemplateConfig(
                state_dim=STATE_DIM,
                action_dim=ACTION_DIM,
                hidden_dim=HIDDEN_DIM,
                pragmatic_weight=1.0,
                epistemic_weight=1.0,
                instrumental_weight=0.1,
            )


        @pytest.fixture
        def toy_efe_computer(efe_config):
            """Build a tiny EFEComputer from the efe template."""
            return EFEComputer(efe_config)


        @pytest.fixture
        def synthetic_gaussians(device):
            """Known mu/var pairs for closed-form tests."""
            torch.manual_seed(SEED)
            mu1 = torch.randn(B, STATE_DIM, device=device)
            var1 = torch.rand(B, STATE_DIM, device=device) + 0.1
            mu2 = torch.randn(B, STATE_DIM, device=device)
            var2 = torch.rand(B, STATE_DIM, device=device) + 0.1
            return {
                "mu1": mu1, "var1": var1, "log_var1": torch.log(var1),
                "mu2": mu2, "var2": var2, "log_var2": torch.log(var2),
            }


        @pytest.fixture
        def mock_minari_dataset():
            """Fake dataset dict mimicking Minari episode structure."""
            torch.manual_seed(SEED)
            num_episodes = 5
            ep_len = 20
            episodes = []
            for _ in range(num_episodes):
                obs = torch.randn(ep_len + 1, OBS_DIM)
                actions = torch.randint(0, ACTION_DIM, (ep_len,))
                rewards = torch.randn(ep_len)
                dones = torch.zeros(ep_len, dtype=torch.bool)
                dones[-1] = True
                episodes.append({
                    "observations": obs,
                    "actions": actions,
                    "rewards": rewards,
                    "terminations": dones,
                })
            return {"episodes": episodes, "obs_dim": OBS_DIM, "action_dim": ACTION_DIM}
    ''')


def _build_test_latent_encoder() -> str:
    """TestLatentEncoder class -- 8 tests."""
    return textwrap.dedent('''\

        # ======================================================================
        # 1. TestLatentEncoder
        # ======================================================================


        class TestLatentEncoder:
            """Tests for the _BuiltinEncoder (latent encoder q(s|o))."""

            def test_output_shape(self, toy_encoder, device):
                """Encoder produces (B, state_dim) mu and log_var."""
                obs = torch.randn(B, OBS_DIM, device=device)
                mu, log_var = toy_encoder(obs)
                assert mu.shape == (B, STATE_DIM), f"mu shape {mu.shape}"
                assert log_var.shape == (B, STATE_DIM), f"log_var shape {log_var.shape}"

            def test_reparameterization(self, toy_encoder, device):
                """Sampling via reparameterization produces valid output."""
                obs = torch.randn(B, OBS_DIM, device=device)
                (mu, log_var), sample = toy_encoder.sample(obs)
                assert sample.shape == (B, STATE_DIM)
                # Sample should differ from mu due to noise
                assert not torch.allclose(sample, mu, atol=1e-7), (
                    "Sample should differ from mu (reparameterization noise)"
                )

            def test_deterministic_mu(self, toy_encoder, device):
                """Same input produces same mu and log_var."""
                torch.manual_seed(SEED)
                obs = torch.randn(B, OBS_DIM, device=device)
                mu1, lv1 = toy_encoder(obs)
                mu2, lv2 = toy_encoder(obs)
                assert torch.allclose(mu1, mu2, atol=1e-6)
                assert torch.allclose(lv1, lv2, atol=1e-6)

            def test_with_context(self, tiny_config, device):
                """Encoder accepts optional context tensor."""
                gc = tiny_config.generative
                encoder = _BuiltinEncoder(
                    obs_dim=gc.obs_dim,
                    state_dim=gc.state_dim,
                    hidden_dim=gc.hidden_dim,
                    num_layers=2,
                    ctx_dim=16,
                    ctx_mode="concat",
                )
                obs = torch.randn(B, gc.obs_dim, device=device)
                ctx = torch.randn(B, 16, device=device)
                mu, log_var = encoder(obs, ctx)
                assert mu.shape == (B, STATE_DIM)

            def test_without_context(self, toy_encoder, device):
                """Encoder works correctly when ctx is None."""
                obs = torch.randn(B, OBS_DIM, device=device)
                mu, log_var = toy_encoder(obs, ctx=None)
                assert mu.shape == (B, STATE_DIM)

            def test_kl_nonneg(self, toy_encoder, device):
                """KL divergence of encoder posterior vs N(0,I) is non-negative."""
                obs = torch.randn(B, OBS_DIM, device=device)
                mu, log_var = toy_encoder(obs)
                # KL(N(mu, diag(exp(lv))) || N(0, I))
                kl = 0.5 * (torch.exp(log_var) + mu.pow(2) - 1.0 - log_var).sum(dim=-1)
                assert (kl >= -1e-5).all(), f"KL has negative values: {kl.min().item()}"

            def test_gradient_flow(self, toy_encoder, device):
                """Gradients flow from loss through encoder to parameters."""
                obs = torch.randn(B, OBS_DIM, device=device)
                mu, log_var = toy_encoder(obs)
                loss = mu.sum() + log_var.sum()
                loss.backward()
                has_grad = any(
                    p.grad is not None and p.grad.abs().sum() > 0
                    for p in toy_encoder.parameters()
                )
                assert has_grad, "No gradient flow through encoder"

            def test_fp32_output(self, toy_encoder, device):
                """Output tensors are float32 regardless of input dtype."""
                obs = torch.randn(B, OBS_DIM, device=device)
                mu, log_var = toy_encoder(obs)
                assert mu.dtype == torch.float32
                assert log_var.dtype == torch.float32
    ''')


def _build_test_likelihood_decoder() -> str:
    """TestLikelihoodDecoder -- 6 tests."""
    return textwrap.dedent('''\

        # ======================================================================
        # 2. TestLikelihoodDecoder
        # ======================================================================


        class TestLikelihoodDecoder:
            """Tests for the _BuiltinLikelihood (likelihood decoder P(o|s))."""

            def test_output_shape(self, toy_likelihood, device):
                """Decoder produces (B, obs_dim) mu and log_var."""
                state = torch.randn(B, STATE_DIM, device=device)
                obs_mu, obs_lv = toy_likelihood(state)
                assert obs_mu.shape == (B, OBS_DIM)
                assert obs_lv.shape == (B, OBS_DIM)

            def test_reconstruction_loss(self, toy_encoder, toy_likelihood, device):
                """Round-trip encode-decode yields finite reconstruction loss."""
                obs = torch.randn(B, OBS_DIM, device=device)
                mu, log_var = toy_encoder(obs)
                std = torch.exp(0.5 * log_var)
                z = mu + std * torch.randn_like(std)
                recon_mu, recon_lv = toy_likelihood(z)
                recon_loss = F.mse_loss(recon_mu, obs)
                assert torch.isfinite(recon_loss), "Reconstruction loss is not finite"

            def test_from_prior_sample(self, toy_likelihood, device):
                """Decoder accepts samples from N(0, I) without errors."""
                z_prior = torch.randn(B, STATE_DIM, device=device)
                obs_mu, obs_lv = toy_likelihood(z_prior)
                assert torch.isfinite(obs_mu).all()
                assert torch.isfinite(obs_lv).all()

            def test_gradient_flow(self, toy_likelihood, device):
                """Gradients flow through the decoder."""
                state = torch.randn(B, STATE_DIM, device=device, requires_grad=True)
                obs_mu, obs_lv = toy_likelihood(state)
                loss = obs_mu.sum()
                loss.backward()
                assert state.grad is not None and state.grad.abs().sum() > 0

            def test_log_prob_valid(self, toy_likelihood, device):
                """Gaussian log-prob from decoder output is finite."""
                state = torch.randn(B, STATE_DIM, device=device)
                obs_mu, obs_lv = toy_likelihood(state)
                obs = torch.randn(B, OBS_DIM, device=device)
                # Manual Gaussian log-prob
                var = torch.exp(obs_lv)
                log_p = -0.5 * (
                    (obs - obs_mu).pow(2) / (var + 1e-8)
                    + obs_lv
                    + math.log(2 * math.pi)
                )
                log_p_total = log_p.sum(dim=-1)
                assert torch.isfinite(log_p_total).all()

            def test_batch_independence(self, toy_likelihood, device):
                """Changing one batch element does not affect others."""
                state = torch.randn(B, STATE_DIM, device=device)
                mu1, _ = toy_likelihood(state)

                state_modified = state.clone()
                state_modified[0] = torch.randn(STATE_DIM, device=device)
                mu2, _ = toy_likelihood(state_modified)

                # Elements 1..B-1 should be identical
                assert torch.allclose(mu1[1:], mu2[1:], atol=1e-6), (
                    "Modifying batch element 0 affected other elements"
                )
    ''')


def _build_test_transition_model() -> str:
    """TestTransitionModel -- 8 tests."""
    return textwrap.dedent('''\

        # ======================================================================
        # 3. TestTransitionModel
        # ======================================================================


        class TestTransitionModel:
            """Tests for the _BuiltinTransition (transition model P(s\'|s,a))."""

            def test_output_shape(self, toy_transition, device):
                """Transition produces (B, state_dim) next-state distribution."""
                state = torch.randn(B, STATE_DIM, device=device)
                action = torch.randint(0, ACTION_DIM, (B,), device=device)
                mu, log_var = toy_transition(state, action)
                assert mu.shape == (B, STATE_DIM)
                assert log_var.shape == (B, STATE_DIM)

            def test_ensemble_disagreement(self, tiny_config, device):
                """Multiple independent transition models show disagreement."""
                gc = tiny_config.generative
                models = [
                    _BuiltinTransition(
                        state_dim=gc.state_dim,
                        action_dim=gc.action_dim,
                        hidden_dim=gc.hidden_dim,
                        action_type=gc.action_type,
                        use_residual=False,
                    )
                    for _ in range(3)
                ]
                state = torch.randn(B, STATE_DIM, device=device)
                action = torch.randint(0, ACTION_DIM, (B,), device=device)
                preds = [m(state, action)[0] for m in models]
                # Stack and compute variance across ensemble
                stacked = torch.stack(preds, dim=0)  # (3, B, state_dim)
                var = stacked.var(dim=0)  # (B, state_dim)
                assert var.mean() > 0, "Ensemble members should disagree with random init"

            def test_log_var_clamping(self, toy_transition, device):
                """Log-variance is clamped within safe bounds."""
                state = torch.randn(B, STATE_DIM, device=device) * 100
                action = torch.randint(0, ACTION_DIM, (B,), device=device)
                _, log_var = toy_transition(state, action)
                assert log_var.min() >= -10.0 - 1e-6, (
                    f"log_var below min: {log_var.min()}"
                )
                assert log_var.max() <= 2.0 + 1e-6, (
                    f"log_var above max: {log_var.max()}"
                )

            def test_deterministic_mode(self, toy_transition, device):
                """Same input yields same output (deterministic forward)."""
                torch.manual_seed(SEED)
                state = torch.randn(B, STATE_DIM, device=device)
                action = torch.randint(0, ACTION_DIM, (B,), device=device)
                mu1, lv1 = toy_transition(state, action)
                mu2, lv2 = toy_transition(state, action)
                assert torch.allclose(mu1, mu2, atol=1e-6)
                assert torch.allclose(lv1, lv2, atol=1e-6)

            def test_action_conditioning(self, toy_transition, device):
                """Different actions produce different outputs."""
                state = torch.randn(
                    1, STATE_DIM, device=device
                ).expand(B, -1).contiguous()
                action_a = torch.zeros(B, dtype=torch.long, device=device)
                action_b = torch.ones(B, dtype=torch.long, device=device)
                mu_a, _ = toy_transition(state, action_a)
                mu_b, _ = toy_transition(state, action_b)
                assert not torch.allclose(mu_a, mu_b, atol=1e-4), (
                    "Different actions should produce different predictions"
                )

            def test_gradient_flow(self, toy_transition, device):
                """Gradients flow through the transition model."""
                state = torch.randn(
                    B, STATE_DIM, device=device, requires_grad=True
                )
                action = torch.randint(0, ACTION_DIM, (B,), device=device)
                mu, _ = toy_transition(state, action)
                loss = mu.sum()
                loss.backward()
                assert state.grad is not None and state.grad.abs().sum() > 0

            def test_multi_step(self, toy_transition, device):
                """Chaining transition steps maintains valid shapes."""
                state = torch.randn(B, STATE_DIM, device=device)
                for step in range(5):
                    action = torch.randint(0, ACTION_DIM, (B,), device=device)
                    mu, log_var = toy_transition(state, action)
                    std = torch.exp(0.5 * log_var)
                    state = mu + std * torch.randn_like(std)
                assert state.shape == (B, STATE_DIM)
                assert torch.isfinite(state).all(), (
                    f"State has non-finite values after multi-step rollout"
                )

            def test_ensemble_size(self, tiny_config, device):
                """Constructing multiple ensemble members is valid."""
                gc = tiny_config.generative
                ensemble = nn.ModuleList([
                    _BuiltinTransition(
                        state_dim=gc.state_dim,
                        action_dim=gc.action_dim,
                        hidden_dim=gc.hidden_dim,
                        action_type=gc.action_type,
                    )
                    for _ in range(5)
                ])
                assert len(ensemble) == 5
                state = torch.randn(B, STATE_DIM, device=device)
                action = torch.randint(0, ACTION_DIM, (B,), device=device)
                for m in ensemble:
                    mu, lv = m(state, action)
                    assert mu.shape == (B, STATE_DIM)
    ''')


def _build_test_preferences() -> str:
    """TestPreferences -- 7 tests."""
    return textwrap.dedent('''\

        # ======================================================================
        # 4. TestPreferences
        # ======================================================================


        class TestPreferences:
            """Tests for the _BuiltinPreferences module."""

            def test_fixed_no_grad(self, device):
                """Fixed preferences have no trainable parameters for mu/log_var."""
                prefs = _BuiltinPreferences(obs_dim=OBS_DIM, learnable=False)
                trainable = sum(1 for p in prefs.parameters() if p.requires_grad)
                # goal_weights is always a Parameter
                # pref_mu and pref_log_var are buffers when not learnable
                assert trainable <= 1, (
                    f"Expected at most 1 trainable param, got {trainable}"
                )

            def test_learned_grad(self, toy_preferences, device):
                """Learned preferences have gradients for mu and log_var."""
                obs = torch.randn(B, OBS_DIM, device=device)
                log_p = toy_preferences.log_prob(obs)
                loss = -log_p.mean()
                loss.backward()
                assert toy_preferences.pref_mu.grad is not None
                assert toy_preferences.pref_mu.grad.abs().sum() > 0

            def test_reward_derived(self, device):
                """Preferences can be initialised from reward signals."""
                prefs = _BuiltinPreferences(obs_dim=OBS_DIM, learnable=True)
                # Simulate setting preferences from reward-correlated observations
                target_mu = torch.randn(1, OBS_DIM, device=device)
                with torch.no_grad():
                    prefs.pref_mu.copy_(target_mu)
                mu, _ = prefs.get_params()
                assert torch.allclose(mu, target_mu.squeeze(0), atol=1e-4)

            def test_log_prob(self, toy_preferences, device):
                """Log-probability under preferences is finite and valid shape."""
                obs = torch.randn(B, OBS_DIM, device=device)
                log_p = toy_preferences.log_prob(obs)
                assert log_p.shape == (B,)
                assert torch.isfinite(log_p).all()

            def test_serialization(self, toy_preferences, tmp_path, device):
                """Preferences survive save/load round-trip."""
                path = tmp_path / "prefs.pt"
                torch.save(toy_preferences.state_dict(), path)
                prefs2 = _BuiltinPreferences(obs_dim=OBS_DIM, learnable=True)
                prefs2.load_state_dict(torch.load(path, weights_only=True))
                mu1, lv1 = toy_preferences.get_params()
                mu2, lv2 = prefs2.get_params()
                assert torch.allclose(mu1, mu2, atol=1e-6)
                assert torch.allclose(lv1, lv2, atol=1e-6)

            def test_shape(self, toy_preferences, device):
                """Preference params have correct shape (obs_dim,)."""
                mu, log_var = toy_preferences.get_params()
                assert mu.shape == (OBS_DIM,), f"mu shape {mu.shape}"
                assert log_var.shape == (OBS_DIM,), f"log_var shape {log_var.shape}"

            def test_satisfaction_logging(self, toy_preferences, device):
                """Log-prob increases when observations match preference mean."""
                mu, _ = toy_preferences.get_params()
                obs_close = (
                    mu.unsqueeze(0).expand(B, -1)
                    + 0.01 * torch.randn(B, OBS_DIM)
                )
                obs_far = (
                    mu.unsqueeze(0).expand(B, -1)
                    + 10.0 * torch.randn(B, OBS_DIM)
                )
                lp_close = toy_preferences.log_prob(obs_close)
                lp_far = toy_preferences.log_prob(obs_far)
                assert lp_close.mean() > lp_far.mean(), (
                    "Observations near preference mean should have higher log-prob"
                )
    ''')


def _build_test_efe_pure_functions() -> str:
    """TestEFEPureFunctions -- 12 tests -- GATE (a)."""
    return textwrap.dedent('''\

        # ======================================================================
        # 5. TestEFEPureFunctions  [GATE (a): EFE sum invariant]
        # ======================================================================


        @pytest.mark.skipif(
            _EFE_IMPORT_ERROR is not None,
            reason="EFE template unavailable",
        )
        class TestEFEPureFunctions:
            """Tests for pure EFE functions and the sum invariant.

            GATE (a): |sum(efe_terms) - efe_total| < 1e-5 for every batch element.
            """

            def test_pragmatic_pure(self, device):
                """compute_pragmatic returns correct shape and finite values."""
                pred_mu = torch.randn(B, OBS_DIM, device=device)
                pred_lv = torch.randn(B, OBS_DIM, device=device) * 0.5
                pref_mu = torch.randn(OBS_DIM, device=device)
                pref_lv = torch.zeros(OBS_DIM, device=device) - 0.7  # precision ~2.0
                result = efe_compute_pragmatic(pred_mu, pred_lv, pref_mu, pref_lv)
                assert result.shape == (B,)
                assert torch.isfinite(result).all()

            def test_epistemic_pure(self, device):
                """compute_epistemic returns correct shape and non-negative KL."""
                mu1 = torch.randn(B, STATE_DIM, device=device)
                lv1 = torch.randn(B, STATE_DIM, device=device) * 0.5
                mu2 = torch.randn(B, STATE_DIM, device=device)
                lv2 = torch.randn(B, STATE_DIM, device=device) * 0.5
                result = efe_compute_epistemic(mu1, lv1, mu2, lv2)
                assert result.shape == (B,)
                assert (result >= -1e-5).all(), (
                    f"KL should be non-negative, min={result.min()}"
                )

            def test_instrumental_pure(self, device):
                """compute_instrumental returns correct shape."""
                src_lp = torch.randn(B, device=device) - 2.0
                plan_lp = torch.randn(B, device=device) - 1.0
                state = torch.randn(B, STATE_DIM, device=device)
                action = torch.randn(B, ACTION_DIM, device=device)
                next_state = torch.randn(B, STATE_DIM, device=device)
                result = efe_compute_instrumental(
                    state, action, next_state, src_lp, plan_lp
                )
                assert result.shape == (B,)

            def test_sum_invariant(self, efe_config, device):
                """GATE (a): |w_p*p + w_e*e + w_i*i - total| < 1e-5."""
                torch.manual_seed(SEED)
                p = torch.randn(B, device=device).abs()
                e = torch.randn(B, device=device).abs()
                i = -torch.randn(B, device=device).abs()  # negative empowerment
                total = compute_efe_total(p, e, i, efe_config)
                expected = (
                    efe_config.pragmatic_weight * p.float()
                    + efe_config.epistemic_weight * e.float()
                    + efe_config.instrumental_weight * i.float()
                )
                diff = (total - expected).abs().max().item()
                assert diff < EFE_TOL, (
                    f"Sum invariant violated: max diff = {diff:.2e}, "
                    f"tol = {EFE_TOL:.1e}"
                )

            def test_sum_invariant_batch(self, efe_config, device):
                """GATE (a): sum invariant holds across batch dimensions."""
                torch.manual_seed(SEED + 1)
                for batch_size in [1, 8, 32]:
                    p = torch.randn(batch_size, device=device).abs()
                    e = torch.randn(batch_size, device=device).abs()
                    i = -torch.randn(batch_size, device=device).abs()  # negative empowerment
                    total = compute_efe_total(p, e, i, efe_config)
                    expected = (
                        efe_config.pragmatic_weight * p.float()
                        + efe_config.epistemic_weight * e.float()
                        + efe_config.instrumental_weight * i.float()
                    )
                    diff = (total - expected).abs().max().item()
                    assert diff < EFE_TOL, (
                        f"Batch size {batch_size}: max diff = {diff:.2e}"
                    )

            def test_closed_form_gaussian_pragmatic(self, device):
                """Pragmatic matches analytical Gaussian NLL."""
                torch.manual_seed(SEED)
                pred_mu = torch.randn(B, OBS_DIM, device=device)
                pred_lv = torch.randn(B, OBS_DIM, device=device) * 0.5
                pref_mu = torch.randn(OBS_DIM, device=device)
                pref_lv = torch.zeros(OBS_DIM, device=device) - 0.4  # precision ~1.5
                from_fn = efe_compute_pragmatic(
                    pred_mu, pred_lv, pref_mu, pref_lv
                )
                from_analytical = analytical_gaussian_pragmatic(
                    pred_mu, torch.exp(pred_lv), pref_mu, pref_lv
                )
                max_diff = (from_fn - from_analytical).abs().max().item()
                assert max_diff < 1e-4, f"Pragmatic mismatch: {max_diff:.2e}"

            def test_closed_form_kl_epistemic(self, synthetic_gaussians, device):
                """Epistemic matches analytical KL divergence."""
                g = synthetic_gaussians
                from_fn = efe_compute_epistemic(
                    g["mu1"], g["log_var1"], g["mu2"], g["log_var2"]
                )
                from_analytical = analytical_gaussian_kl(
                    g["mu1"], g["var1"], g["mu2"], g["var2"]
                )
                max_diff = (from_fn - from_analytical).abs().max().item()
                assert max_diff < 1e-4, f"KL mismatch: {max_diff:.2e}"

            def test_pragmatic_monotonicity(self, device):
                """Further from preference -> higher pragmatic value."""
                pref_mu = torch.zeros(OBS_DIM, device=device)
                pref_lv = torch.zeros(OBS_DIM, device=device)  # precision = 1.0
                zero_lv = torch.zeros(B, OBS_DIM, device=device)
                close = (
                    pref_mu.unsqueeze(0).expand(B, -1)
                    + 0.01 * torch.randn(B, OBS_DIM)
                )
                far = (
                    pref_mu.unsqueeze(0).expand(B, -1)
                    + 5.0 * torch.randn(B, OBS_DIM)
                )
                p_close = efe_compute_pragmatic(close, zero_lv, pref_mu, pref_lv)
                p_far = efe_compute_pragmatic(far, zero_lv, pref_mu, pref_lv)
                assert p_far.mean() > p_close.mean(), (
                    f"close={p_close.mean():.4f} should be < "
                    f"far={p_far.mean():.4f}"
                )

            def test_epistemic_monotonicity(self, device):
                """Higher posterior variance -> higher epistemic value."""
                mu = torch.zeros(B, STATE_DIM, device=device)
                lv_low = torch.full((B, STATE_DIM), -2.0, device=device)
                lv_high = torch.full((B, STATE_DIM), 2.0, device=device)
                lv_prior = torch.zeros(B, STATE_DIM, device=device)
                e_low = efe_compute_epistemic(mu, lv_low, mu, lv_prior)
                e_high = efe_compute_epistemic(mu, lv_high, mu, lv_prior)
                assert e_high.mean() > e_low.mean()

            def test_instrumental_correlation(self, device):
                """Positive empowerment when planning > source log-prob."""
                high_plan = torch.zeros(B, device=device)
                low_source = torch.full((B,), -3.0, device=device)
                state = torch.randn(B, STATE_DIM, device=device)
                action = torch.randn(B, ACTION_DIM, device=device)
                ns = torch.randn(B, STATE_DIM, device=device)
                result = efe_compute_instrumental(
                    state, action, ns, low_source, high_plan
                )
                # Empowerment = plan_lp - src_lp > 0 when plan > source
                assert (result > -1e-5).all() or (result < 1e-5).all(), (
                    "Instrumental should be consistently signed"
                )

            def test_fp32_precision(self, device):
                """All EFE outputs are fp32 even with fp16 inputs."""
                pred_mu = torch.randn(B, OBS_DIM, device=device).half()
                pred_lv = torch.randn(B, OBS_DIM, device=device).half()
                pref_mu = torch.randn(OBS_DIM, device=device).half()
                pref_lv = torch.zeros(OBS_DIM, device=device)  # precision = 1.0.half()
                result = efe_compute_pragmatic(
                    pred_mu, pred_lv, pref_mu, pref_lv
                )
                assert result.dtype == torch.float32, (
                    f"Expected fp32, got {result.dtype}"
                )

            def test_gradient_independence(self, device):
                """Each EFE term has independent gradients (no cross-talk)."""
                pred_mu = torch.randn(
                    B, OBS_DIM, device=device, requires_grad=True
                )
                pred_lv = torch.randn(B, OBS_DIM, device=device) * 0.5
                pref_mu = torch.randn(OBS_DIM, device=device)
                pref_lv = torch.zeros(OBS_DIM, device=device)  # precision = 1.0
                p = efe_compute_pragmatic(pred_mu, pred_lv, pref_mu, pref_lv)
                p.sum().backward()
                grad_p = pred_mu.grad.clone()

                pred_mu.grad = None
                # Epistemic should not depend on pred_mu
                mu_state = torch.randn(
                    B, STATE_DIM, device=device, requires_grad=True
                )
                lv_state = torch.randn(B, STATE_DIM, device=device) * 0.5
                mu_prior = torch.randn(B, STATE_DIM, device=device)
                lv_prior = torch.randn(B, STATE_DIM, device=device) * 0.5
                e = efe_compute_epistemic(mu_state, lv_state, mu_prior, lv_prior)
                e.sum().backward()
                assert mu_state.grad is not None
                assert pred_mu.grad is None, (
                    "Pragmatic input should not receive epistemic grads"
                )
    ''')


def _build_test_rollout_engine() -> str:
    """TestRolloutEngine -- 6 tests."""
    return textwrap.dedent('''\

        # ======================================================================
        # 6. TestRolloutEngine
        # ======================================================================


        class TestRolloutEngine:
            """Tests for the _BuiltinRolloutEngine."""

            def test_output_shape(self, toy_rollout_engine, device):
                """Rollout returns (B, N) EFE tensor."""
                state = torch.randn(B, STATE_DIM, device=device)
                N, H = 8, 2
                actions = torch.randn(B, N, H, ACTION_DIM, device=device)
                efe, terms = toy_rollout_engine.rollout(state, actions, H)
                assert efe.shape == (B, N), f"EFE shape {efe.shape}"

            def test_trajectory_shape(self, toy_rollout_engine, device):
                """Term breakdown has correct keys and shapes."""
                state = torch.randn(B, STATE_DIM, device=device)
                N, H = 8, 2
                actions = torch.randn(B, N, H, ACTION_DIM, device=device)
                efe, terms = toy_rollout_engine.rollout(state, actions, H)
                for key in ["pragmatic", "epistemic", "instrumental"]:
                    assert key in terms, f"Missing key: {key}"
                    assert terms[key].shape == (B, N), (
                        f"{key} shape {terms[key].shape}"
                    )

            def test_deterministic(self, toy_rollout_engine, device):
                """Same input and seed produce same rollout output."""
                torch.manual_seed(SEED)
                state = torch.randn(B, STATE_DIM, device=device)
                N, H = 8, 2
                actions = torch.randn(B, N, H, ACTION_DIM, device=device)

                torch.manual_seed(100)
                efe1, _ = toy_rollout_engine.rollout(state, actions, H)
                torch.manual_seed(100)
                efe2, _ = toy_rollout_engine.rollout(state, actions, H)
                assert torch.allclose(efe1, efe2, atol=1e-5)

            def test_horizon_length(self, toy_rollout_engine, device):
                """Different horizon lengths produce different EFE magnitudes."""
                state = torch.randn(B, STATE_DIM, device=device)
                N = 8
                actions_short = torch.randn(
                    B, N, 1, ACTION_DIM, device=device
                )
                actions_long = torch.randn(
                    B, N, 5, ACTION_DIM, device=device
                )
                efe_short, _ = toy_rollout_engine.rollout(
                    state, actions_short, 1
                )
                efe_long, _ = toy_rollout_engine.rollout(
                    state, actions_long, 5
                )
                # Longer horizons accumulate more EFE
                assert not torch.allclose(efe_short, efe_long, atol=1e-2)

            def test_parallel_correct(self, toy_rollout_engine, device):
                """All N rollouts are computed with correct shapes."""
                state = torch.randn(B, STATE_DIM, device=device)
                N, H = 16, 3
                actions = torch.randn(B, N, H, ACTION_DIM, device=device)
                efe, _ = toy_rollout_engine.rollout(state, actions, H)
                assert efe.shape == (B, N)
                assert torch.isfinite(efe).all()

            def test_detach_eval(self, toy_rollout_engine, device):
                """Rollout in mode produces finite, detachable results."""
                toy_rollout_engine.eval()
                state = torch.randn(B, STATE_DIM, device=device)
                N, H = 8, 2
                actions = torch.randn(B, N, H, ACTION_DIM, device=device)
                with torch.no_grad():
                    efe, terms = toy_rollout_engine.rollout(state, actions, H)
                assert torch.isfinite(efe).all()
                toy_rollout_engine.train()
    ''')


def _build_test_random_shooting() -> str:
    """TestRandomShooting -- 5 tests."""
    return textwrap.dedent('''\

        # ======================================================================
        # 7. TestRandomShooting
        # ======================================================================


        class TestRandomShooting:
            """Tests for _BuiltinRandomShootingPlanner."""

            def test_selects_best(self, toy_planner, toy_rollout_engine, device):
                """Planner selects the sequence with lowest EFE."""
                state = torch.randn(B, STATE_DIM, device=device)
                actions = toy_planner.propose(B, device)
                efe, _ = toy_rollout_engine.rollout(
                    state, actions, toy_planner.cfg.planning_horizon
                )
                # Set temperature very low for near-deterministic selection
                selected_action, best_idx = toy_planner.select(
                    efe, actions, temperature=0.01
                )
                assert selected_action.shape[0] == B

            def test_output_format(self, toy_planner, device):
                """Proposed actions have correct shape (B, N, H, A)."""
                actions = toy_planner.propose(B, device)
                cfg = toy_planner.cfg
                expected_shape = (
                    B, cfg.num_rollouts, cfg.planning_horizon, ACTION_DIM
                )
                assert actions.shape == expected_shape

            def test_deterministic(self, toy_planner, device):
                """Same generator seed produces same proposals."""
                gen1 = torch.Generator(device=device).manual_seed(SEED)
                gen2 = torch.Generator(device=device).manual_seed(SEED)
                a1 = toy_planner.propose(B, device, generator=gen1)
                a2 = toy_planner.propose(B, device, generator=gen2)
                assert torch.allclose(a1, a2)

            def test_discrete_actions(self, device):
                """Planner correctly generates one-hot discrete actions."""
                cfg = PlannerConfig(
                    planner_type="random_shooting",
                    planning_horizon=2,
                    num_rollouts=8,
                )
                planner = _BuiltinRandomShootingPlanner(
                    action_dim=ACTION_DIM,
                    action_type="discrete",
                    planner_config=cfg,
                )
                actions = planner.propose(B, device)
                # Each action should be one-hot (sum to 1 along last dim)
                sums = actions.sum(dim=-1)
                assert torch.allclose(sums, torch.ones_like(sums), atol=1e-6)

            def test_continuous_actions(self, device):
                """Continuous actions are bounded by tanh to [-1, 1]."""
                cfg = PlannerConfig(
                    planner_type="random_shooting",
                    planning_horizon=2,
                    num_rollouts=8,
                )
                planner = _BuiltinRandomShootingPlanner(
                    action_dim=ACTION_DIM,
                    action_type="continuous",
                    planner_config=cfg,
                )
                actions = planner.propose(B, device)
                assert actions.min() >= -1.0 - 1e-6
                assert actions.max() <= 1.0 + 1e-6
    ''')


def _build_test_cem() -> str:
    """TestCEM -- 6 tests."""
    return textwrap.dedent('''\

        # ======================================================================
        # 8. TestCEM
        # ======================================================================


        class TestCEM:
            """Tests for _BuiltinCEMPlanner."""

            def _make_cem_planner(self, device):
                """Helper to build a CEM planner with test config."""
                cfg = PlannerConfig(
                    planner_type="cem",
                    planning_horizon=2,
                    num_rollouts=16,
                    cem_iterations=3,
                    cem_elite_fraction=0.25,
                    action_noise_std=0.5,
                )
                return _BuiltinCEMPlanner(
                    action_dim=ACTION_DIM,
                    action_type="continuous",
                    planner_config=cfg,
                ), cfg

            def test_improves_iterations(self, toy_rollout_engine, device):
                """CEM EFE is finite after iterative refinement."""
                planner, cfg = self._make_cem_planner(device)
                state = torch.randn(B, STATE_DIM, device=device)
                action, efe, terms, ps = planner.plan(
                    initial_state=state,
                    rollout_engine=toy_rollout_engine,
                )
                assert efe is not None
                assert torch.isfinite(efe).all()

            def test_elite_selection(self, toy_rollout_engine, device):
                """CEM returns valid planner state with cem_mu and cem_std."""
                planner, cfg = self._make_cem_planner(device)
                state = torch.randn(B, STATE_DIM, device=device)
                _, _, _, ps = planner.plan(
                    initial_state=state,
                    rollout_engine=toy_rollout_engine,
                )
                assert "cem_mu" in ps
                assert "cem_std" in ps
                assert ps["cem_std"].min() >= 0.01 - 1e-6, (
                    "CEM std should be clamped > 0"
                )

            def test_output_format(self, toy_rollout_engine, device):
                """CEM produces action of correct shape."""
                planner, cfg = self._make_cem_planner(device)
                state = torch.randn(B, STATE_DIM, device=device)
                action, efe, terms, _ = planner.plan(
                    initial_state=state,
                    rollout_engine=toy_rollout_engine,
                )
                assert action.shape == (B, ACTION_DIM), (
                    f"Action shape {action.shape}"
                )
                assert efe.shape == (B,), f"EFE shape {efe.shape}"

            def test_deterministic(self, toy_rollout_engine, device):
                """Same generator seed produces same CEM output."""
                planner, cfg = self._make_cem_planner(device)
                state = torch.randn(B, STATE_DIM, device=device)

                gen1 = torch.Generator().manual_seed(SEED)
                a1, e1, _, _ = planner.plan(
                    state, toy_rollout_engine, generator=gen1
                )

                gen2 = torch.Generator().manual_seed(SEED)
                a2, e2, _, _ = planner.plan(
                    state, toy_rollout_engine, generator=gen2
                )

                assert torch.allclose(a1, a2, atol=1e-5)
                assert torch.allclose(e1, e2, atol=1e-5)

            def test_better_than_random(self, toy_rollout_engine, device):
                """CEM should find EFE at least comparable to random shooting."""
                state = torch.randn(B, STATE_DIM, device=device)

                # Random shooting baseline
                rs_cfg = PlannerConfig(
                    planner_type="random_shooting",
                    planning_horizon=2,
                    num_rollouts=16,
                )
                rs_planner = _BuiltinRandomShootingPlanner(
                    action_dim=ACTION_DIM,
                    action_type="continuous",
                    planner_config=rs_cfg,
                )
                torch.manual_seed(SEED)
                rs_actions = rs_planner.propose(B, device)
                rs_efe, _ = toy_rollout_engine.rollout(state, rs_actions, 2)
                rs_best = rs_efe.min(dim=-1).values.mean()

                # CEM
                planner, _ = self._make_cem_planner(device)
                torch.manual_seed(SEED)
                _, cem_efe, _, _ = planner.plan(state, toy_rollout_engine)
                cem_best = cem_efe.mean()

                # CEM should do at least as well or close
                assert cem_best <= rs_best + 5.0, (
                    f"CEM ({cem_best:.4f}) much worse than RS ({rs_best:.4f})"
                )

            def test_action_bounds(self, toy_rollout_engine, device):
                """CEM continuous actions are bounded by tanh to [-1, 1]."""
                planner, _ = self._make_cem_planner(device)
                state = torch.randn(B, STATE_DIM, device=device)
                action, _, _, _ = planner.plan(state, toy_rollout_engine)
                assert action.min() >= -1.0 - 1e-5, (
                    f"Min action: {action.min()}"
                )
                assert action.max() <= 1.0 + 1e-5, (
                    f"Max action: {action.max()}"
                )
    ''')


def _build_test_horizon_stability() -> str:
    """TestHorizonStability -- 6 tests -- GATE (b)."""
    return textwrap.dedent('''\

        # ======================================================================
        # 9. TestHorizonStability  [GATE (b): horizon stability]
        # ======================================================================


        class TestHorizonStability:
            """Tests for horizon normalization and action stability across horizons.

            GATE (b): With normalization, per-step EFE is consistent across H
            values, and selected actions remain stable.
            """

            def _build_agent_with_horizon(self, horizon, normalize=True):
                """Helper to build agent with specific horizon and normalization."""
                return ActiveInferenceFullConfig(
                    generative=GenerativeModelConfig(
                        obs_dim=OBS_DIM,
                        state_dim=STATE_DIM,
                        action_dim=ACTION_DIM,
                        hidden_dim=HIDDEN_DIM,
                        encoder_layers=2,
                        decoder_layers=2,
                        transition_ensemble_size=1,
                        use_residual_transition=False,
                        action_type="discrete",
                    ),
                    efe=EFEConfig(
                        pragmatic_weight=1.0,
                        epistemic_weight=1.0,
                        instrumental_weight=0.1,
                        discount_factor=1.0,
                        normalize_by_horizon=normalize,
                        use_empowerment=False,
                    ),
                    planner=PlannerConfig(
                        planner_type="random_shooting",
                        planning_horizon=horizon,
                        num_rollouts=16,
                    ),
                    amortized=AmortizedPolicyConfig(enabled=False),
                    seed=SEED,
                )

            def test_normalized_efe_consistent(self, device):
                """GATE (b): Normalized EFE is consistent across H=3,5,7."""
                efe_per_step = {}
                for H in [3, 5, 7]:
                    cfg = self._build_agent_with_horizon(H, normalize=True)
                    agent = ActiveInferenceAgent(cfg)
                    torch.manual_seed(SEED)
                    obs = torch.randn(B, OBS_DIM, device=device)
                    result = agent.plan(obs)
                    efe_per_step[H] = result.efe_total.mean().item()

                # Ratios should be in reasonable range with normalization
                ratio_3_5 = abs(efe_per_step[3]) / (
                    abs(efe_per_step[5]) + 1e-8
                )
                ratio_5_7 = abs(efe_per_step[5]) / (
                    abs(efe_per_step[7]) + 1e-8
                )
                assert 0.2 < ratio_3_5 < 5.0, (
                    f"H=3/H=5 ratio={ratio_3_5:.3f}, expected near 1.0"
                )
                assert 0.2 < ratio_5_7 < 5.0, (
                    f"H=5/H=7 ratio={ratio_5_7:.3f}, expected near 1.0"
                )

            def test_action_stability(self, device):
                """Actions should be valid across different horizons."""
                actions_per_h = {}
                for H in [3, 5, 7]:
                    cfg = self._build_agent_with_horizon(H, normalize=True)
                    agent = ActiveInferenceAgent(cfg)
                    agent.config.planner.action_temperature = 0.01
                    torch.manual_seed(SEED)
                    obs = torch.randn(B, OBS_DIM, device=device)
                    result = agent.plan(obs)
                    actions_per_h[H] = result.action

                for H, act in actions_per_h.items():
                    assert act.shape[0] == B, f"H={H}: wrong batch size"
                    if act.dim() == 1:
                        assert (act >= 0).all() and (act < ACTION_DIM).all()

            def test_discount_consistency(self, device):
                """Discounted EFE magnitude is bounded relative to undiscounted."""
                cfg_disc = self._build_agent_with_horizon(5, normalize=False)
                cfg_disc.efe.discount_factor = 0.9
                cfg_nodisc = self._build_agent_with_horizon(5, normalize=False)
                cfg_nodisc.efe.discount_factor = 1.0

                agent_disc = ActiveInferenceAgent(cfg_disc)
                agent_nodisc = ActiveInferenceAgent(cfg_nodisc)
                agent_nodisc.load_state_dict(
                    agent_disc.state_dict(), strict=False
                )

                torch.manual_seed(SEED)
                obs = torch.randn(B, OBS_DIM, device=device)
                r_disc = agent_disc.plan(obs)
                torch.manual_seed(SEED)
                r_nodisc = agent_nodisc.plan(obs)

                assert r_disc.efe_total.abs().mean() <= (
                    r_nodisc.efe_total.abs().mean() + 1.0
                )

            def test_weight_independence(self, device):
                """Changing EFE weights changes the total EFE."""
                cfg1 = self._build_agent_with_horizon(3, normalize=False)
                cfg1.efe.pragmatic_weight = 1.0
                cfg2 = self._build_agent_with_horizon(3, normalize=False)
                cfg2.efe.pragmatic_weight = 2.0

                agent1 = ActiveInferenceAgent(cfg1)
                agent2 = ActiveInferenceAgent(cfg2)
                agent2.load_state_dict(agent1.state_dict(), strict=False)

                torch.manual_seed(SEED)
                obs = torch.randn(B, OBS_DIM, device=device)
                r1 = agent1.plan(obs)
                torch.manual_seed(SEED)
                r2 = agent2.plan(obs)

                assert not torch.allclose(r1.efe_total, r2.efe_total, atol=1e-3)

            def test_logging_present(self, device):
                """ActionOutput contains horizon and num_rollouts metadata."""
                cfg = self._build_agent_with_horizon(3)
                agent = ActiveInferenceAgent(cfg)
                obs = torch.randn(B, OBS_DIM, device=device)
                result = agent.plan(obs)
                assert result.horizon == 3
                assert result.num_rollouts == 16
                assert result.planner_type in ("random_shooting", "cem")

            def test_normalized_vs_raw(self, device):
                """Normalized EFE has smaller magnitude than raw for H > 1."""
                cfg_norm = self._build_agent_with_horizon(5, normalize=True)
                cfg_raw = self._build_agent_with_horizon(5, normalize=False)

                agent_norm = ActiveInferenceAgent(cfg_norm)
                agent_raw = ActiveInferenceAgent(cfg_raw)
                agent_raw.load_state_dict(
                    agent_norm.state_dict(), strict=False
                )

                torch.manual_seed(SEED)
                obs = torch.randn(B, OBS_DIM, device=device)
                r_norm = agent_norm.plan(obs)
                torch.manual_seed(SEED)
                r_raw = agent_raw.plan(obs)

                norm_mag = r_norm.efe_total.abs().mean().item()
                raw_mag = r_raw.efe_total.abs().mean().item()
                assert norm_mag <= raw_mag + 1e-2, (
                    f"Normalized ({norm_mag:.4f}) should be <= "
                    f"raw ({raw_mag:.4f})"
                )
    ''')


def _build_test_amortized_policy() -> str:
    """TestAmortizedPolicy -- 5 tests."""
    return textwrap.dedent('''\

        # ======================================================================
        # 10. TestAmortizedPolicy
        # ======================================================================


        class TestAmortizedPolicy:
            """Tests for the _BuiltinAmortizedPolicy and distillation."""

            def test_output_shape(self, device):
                """Amortized policy produces actions of correct shape."""
                policy = _BuiltinAmortizedPolicy(
                    state_dim=STATE_DIM,
                    action_dim=ACTION_DIM,
                    hidden_dim=HIDDEN_DIM,
                    num_layers=2,
                    continuous=False,
                )
                state = torch.randn(B, STATE_DIM, device=device)
                action = policy(state)
                assert action.shape == (B,), f"Action shape {action.shape}"
                assert (action >= 0).all() and (action < ACTION_DIM).all()

            def test_distillation_improves(self, device):
                """Distillation loss decreases over training steps."""
                policy = _BuiltinAmortizedPolicy(
                    state_dim=STATE_DIM,
                    action_dim=ACTION_DIM,
                    hidden_dim=HIDDEN_DIM,
                    continuous=True,
                )
                optimizer = torch.optim.Adam(policy.parameters(), lr=1e-3)
                state = torch.randn(32, STATE_DIM, device=device)
                target = torch.randn(32, ACTION_DIM, device=device) * 0.5

                losses = []
                for _ in range(50):
                    pred = policy(state, deterministic=True)
                    loss = F.mse_loss(pred, target)
                    optimizer.zero_grad()
                    loss.backward()
                    optimizer.step()
                    losses.append(loss.item())

                assert losses[-1] < losses[0], (
                    f"Loss should decrease: "
                    f"start={losses[0]:.4f}, end={losses[-1]:.4f}"
                )

            def test_matches_planner(self, device):
                """After distillation, amortized policy approximates target."""
                policy = _BuiltinAmortizedPolicy(
                    state_dim=STATE_DIM,
                    action_dim=ACTION_DIM,
                    hidden_dim=HIDDEN_DIM,
                    continuous=True,
                )
                optimizer = torch.optim.Adam(policy.parameters(), lr=1e-3)

                state = torch.randn(16, STATE_DIM, device=device)
                target_action = torch.tanh(
                    torch.randn(16, ACTION_DIM, device=device)
                )

                for _ in range(200):
                    pred = policy(state, deterministic=True)
                    loss = F.mse_loss(pred, target_action)
                    optimizer.zero_grad()
                    loss.backward()
                    optimizer.step()

                final_pred = policy(state, deterministic=True)
                mse = F.mse_loss(final_pred, target_action).item()
                assert mse < 0.5, f"Amortized policy MSE too high: {mse:.4f}"

            def test_speed_comparison(self, device):
                """Amortized forward is faster than a full planning loop."""
                config = ActiveInferenceFullConfig(
                    generative=GenerativeModelConfig(
                        obs_dim=OBS_DIM,
                        state_dim=STATE_DIM,
                        action_dim=ACTION_DIM,
                        hidden_dim=HIDDEN_DIM,
                        encoder_layers=2,
                        decoder_layers=2,
                        transition_ensemble_size=1,
                        action_type="continuous",
                    ),
                    efe=EFEConfig(
                        use_empowerment=False,
                        normalize_by_horizon=False,
                    ),
                    planner=PlannerConfig(
                        planner_type="random_shooting",
                        planning_horizon=4,
                        num_rollouts=32,
                    ),
                    amortized=AmortizedPolicyConfig(
                        enabled=True, hidden_dim=HIDDEN_DIM
                    ),
                    seed=SEED,
                )
                agent = ActiveInferenceAgent(config)
                obs = torch.randn(B, OBS_DIM, device=device)
                state = agent.reset(B, device)

                # Warm up
                _ = agent.plan(obs, state=state)

                # Time planning
                start = time.perf_counter()
                for _ in range(10):
                    agent.plan(obs, state=state)
                plan_time = time.perf_counter() - start

                # Time amortized
                start = time.perf_counter()
                for _ in range(10):
                    agent.act(obs, state=state, learn=False)
                amort_time = time.perf_counter() - start

                # Amortized should be faster (or not drastically slower)
                assert amort_time < plan_time * 5, (
                    f"Amortized ({amort_time:.4f}s) too slow "
                    f"vs plan ({plan_time:.4f}s)"
                )

            def test_efe_still_computed(self, device):
                """Even with amortized policy, EFE terms are still computed."""
                config = ActiveInferenceFullConfig(
                    generative=GenerativeModelConfig(
                        obs_dim=OBS_DIM,
                        state_dim=STATE_DIM,
                        action_dim=ACTION_DIM,
                        hidden_dim=HIDDEN_DIM,
                        encoder_layers=2,
                        decoder_layers=2,
                        transition_ensemble_size=1,
                        action_type="continuous",
                    ),
                    efe=EFEConfig(
                        use_empowerment=False,
                        normalize_by_horizon=False,
                    ),
                    planner=PlannerConfig(
                        planner_type="random_shooting",
                        planning_horizon=2,
                        num_rollouts=8,
                    ),
                    amortized=AmortizedPolicyConfig(
                        enabled=True, hidden_dim=HIDDEN_DIM
                    ),
                    seed=SEED,
                )
                agent = ActiveInferenceAgent(config)
                obs = torch.randn(B, OBS_DIM, device=device)
                state = agent.reset(B, device)
                result = agent.act(obs, state=state, learn=False)
                assert result.efe_total is not None
                assert "pragmatic" in result.efe_terms
                assert result.planner_type == "amortized"
    ''')


def _build_test_pymdp_backend() -> str:
    """TestPyMDPBackend -- 5 tests, skipif pymdp not installed."""
    return textwrap.dedent('''\

        # ======================================================================
        # 11. TestPyMDPBackend
        # ======================================================================


        @pytest.mark.skipif(
            not PYMDP_AVAILABLE, reason="pymdp not installed"
        )
        class TestPyMDPBackend:
            """Tests for the optional pymdp discrete POMDP backend."""

            def test_array_construction(self, device):
                """PyMDPBackend builds valid A/B/C/D arrays."""
                backend = _BuiltinPyMDPBackend(
                    num_obs=4, num_states=3, num_actions=2
                )
                backend.build_agent()
                assert backend._agent is not None

            def test_efe_computation(self, device):
                """pymdp backend can compute EFE and select actions."""
                backend = _BuiltinPyMDPBackend(
                    num_obs=4, num_states=3, num_actions=2
                )
                backend.build_agent()
                action = backend.select_action(observation_index=0)
                assert isinstance(action, int)
                assert 0 <= action < 2

            def test_regression_neural(self, device):
                """Neural and pymdp EFE agree directionally on toy problem."""
                backend = _BuiltinPyMDPBackend(
                    num_obs=4, num_states=3, num_actions=2
                )
                backend.build_agent()
                actions_pymdp = [backend.select_action(i) for i in range(4)]
                assert all(isinstance(a, int) for a in actions_pymdp)
                assert all(0 <= a < 2 for a in actions_pymdp)

            def test_policy_agreement(self, device):
                """pymdp returns consistent actions for same observation."""
                backend = _BuiltinPyMDPBackend(
                    num_obs=4, num_states=3, num_actions=2
                )
                backend.build_agent()
                a1 = backend.select_action(0)
                backend.build_agent()
                a2 = backend.select_action(0)
                assert 0 <= a1 < 2
                assert 0 <= a2 < 2

            def test_graceful_fallback(self, device):
                """Backend without build_agent returns default action 0."""
                backend = _BuiltinPyMDPBackend(
                    num_obs=4, num_states=3, num_actions=2
                )
                action = backend.select_action(0)
                assert action == 0


        @pytest.mark.skipif(
            PYMDP_AVAILABLE, reason="Testing pymdp-absent fallback"
        )
        class TestPyMDPBackendFallback:
            """Tests for graceful fallback when pymdp is not installed."""

            def test_graceful_fallback(self, device):
                """Backend returns 0 when pymdp is unavailable."""
                backend = _BuiltinPyMDPBackend(
                    num_obs=4, num_states=3, num_actions=2
                )
                backend.build_agent()
                action = backend.select_action(0)
                assert action == 0
    ''')


def _build_test_offline_rl() -> str:
    """TestOfflineRL -- 6 tests -- GATE (c)."""
    return textwrap.dedent('''\

        # ======================================================================
        # 12. TestOfflineRL  [GATE (c): Minari end-to-end]
        # ======================================================================


        class TestOfflineRL:
            """Tests for offline RL via mock Minari-like datasets.

            GATE (c): Load dataset -> train world model -> run planner ->
            produce actions + EFE logs -> metrics JSON.
            """

            def test_dataset_loading(self, mock_minari_dataset, device):
                """Mock dataset has correct structure."""
                ds = mock_minari_dataset
                assert "episodes" in ds
                assert len(ds["episodes"]) == 5
                ep = ds["episodes"][0]
                assert "observations" in ep
                assert "actions" in ep
                assert "rewards" in ep
                assert ep["observations"].shape[1] == OBS_DIM

            def test_episode_extraction(self, mock_minari_dataset, device):
                """Episodes can be split into transitions (o, a, o_next, done, r)."""
                ep = mock_minari_dataset["episodes"][0]
                obs = ep["observations"]
                actions = ep["actions"]
                rewards = ep["rewards"]
                dones = ep["terminations"]

                o_t = obs[:-1]
                o_next = obs[1:]
                assert o_t.shape[0] == actions.shape[0]
                assert o_next.shape[0] == actions.shape[0]
                assert rewards.shape[0] == actions.shape[0]
                assert dones.shape[0] == actions.shape[0]
                assert dones[-1] == True

            def test_world_model_training(
                self, mock_minari_dataset, tiny_config, device
            ):
                """Transition model loss decreases on offline data."""
                gc = tiny_config.generative
                transition = _BuiltinTransition(
                    state_dim=gc.state_dim,
                    action_dim=gc.action_dim,
                    hidden_dim=gc.hidden_dim,
                    action_type="discrete",
                    use_residual=False,
                )

                encoder = nn.Linear(OBS_DIM, STATE_DIM)
                optimizer = torch.optim.Adam(
                    list(transition.parameters())
                    + list(encoder.parameters()),
                    lr=1e-3,
                )

                ep = mock_minari_dataset["episodes"][0]
                o_t = ep["observations"][:-1].to(device)
                o_next = ep["observations"][1:].to(device)
                actions = ep["actions"].to(device)

                losses = []
                for epoch in range(20):
                    s_t = encoder(o_t)
                    s_next_true = encoder(o_next).detach()
                    mu_pred, _ = transition(s_t, actions)
                    loss = F.mse_loss(mu_pred, s_next_true)
                    optimizer.zero_grad()
                    loss.backward()
                    optimizer.step()
                    losses.append(loss.item())

                assert losses[-1] < losses[0], (
                    f"World model loss should decrease: "
                    f"{losses[0]:.4f} -> {losses[-1]:.4f}"
                )

            def test_planner_evaluation(
                self, mock_minari_dataset, tiny_config, device
            ):
                """Planner can evaluate actions on offline data states."""
                agent = ActiveInferenceAgent(tiny_config)
                ep = mock_minari_dataset["episodes"][0]
                obs = ep["observations"][:B].to(device)

                # Pad or trim to match obs_dim
                if obs.shape[1] != tiny_config.generative.obs_dim:
                    obs = obs[:, :tiny_config.generative.obs_dim]
                    if obs.shape[1] < tiny_config.generative.obs_dim:
                        pad = torch.zeros(
                            B,
                            tiny_config.generative.obs_dim - obs.shape[1],
                            device=device,
                        )
                        obs = torch.cat([obs, pad], dim=1)

                state = agent.reset(B, device)
                result = agent.plan(obs, state=state)
                assert result.action is not None
                assert result.efe_total.shape == (B,)

            def test_metrics_json(
                self, mock_minari_dataset, tiny_config, tmp_path, device
            ):
                """GATE (c): Metrics can be saved as JSON."""
                agent = ActiveInferenceAgent(tiny_config)
                ep = mock_minari_dataset["episodes"][0]
                obs = ep["observations"][:B].to(device)
                if obs.shape[1] < tiny_config.generative.obs_dim:
                    pad = torch.zeros(
                        B,
                        tiny_config.generative.obs_dim - obs.shape[1],
                        device=device,
                    )
                    obs = torch.cat([obs, pad], dim=1)
                elif obs.shape[1] > tiny_config.generative.obs_dim:
                    obs = obs[:, :tiny_config.generative.obs_dim]

                state = agent.reset(B, device)
                result = agent.plan(obs, state=state)

                metrics = {
                    "efe_total_mean": result.efe_total.mean().item(),
                    "pragmatic_mean": result.efe_terms.get(
                        "pragmatic", torch.tensor(0.0)
                    ).mean().item(),
                    "epistemic_mean": result.efe_terms.get(
                        "epistemic", torch.tensor(0.0)
                    ).mean().item(),
                    "instrumental_mean": result.efe_terms.get(
                        "instrumental", torch.tensor(0.0)
                    ).mean().item(),
                    "horizon": result.horizon,
                    "num_rollouts": result.num_rollouts,
                    "planner_type": result.planner_type,
                }

                metrics_path = tmp_path / "offline_metrics.json"
                with open(metrics_path, "w") as f:
                    json.dump(metrics, f, indent=2)

                assert metrics_path.exists()
                with open(metrics_path) as f:
                    loaded = json.load(f)
                assert "efe_total_mean" in loaded
                assert isinstance(loaded["efe_total_mean"], float)

            def test_end_to_end(
                self, mock_minari_dataset, tiny_config, tmp_path, device
            ):
                """GATE (c): Full offline RL pipeline -- no crashes, metrics."""
                agent = ActiveInferenceAgent(tiny_config)
                all_results = []

                for ep_data in mock_minari_dataset["episodes"][:3]:
                    obs_seq = ep_data["observations"].to(device)
                    if obs_seq.shape[1] < tiny_config.generative.obs_dim:
                        pad = torch.zeros(
                            obs_seq.shape[0],
                            tiny_config.generative.obs_dim - obs_seq.shape[1],
                            device=device,
                        )
                        obs_seq = torch.cat([obs_seq, pad], dim=1)
                    elif obs_seq.shape[1] > tiny_config.generative.obs_dim:
                        obs_seq = obs_seq[
                            :, :tiny_config.generative.obs_dim
                        ]

                    state = agent.reset(1, device)
                    ep_efe = []
                    for t in range(min(5, obs_seq.shape[0])):
                        obs_t = obs_seq[t:t+1]
                        result = agent.plan(obs_t, state=state)
                        ep_efe.append(result.efe_total.item())
                        _, _, state = agent.infer_state(obs_t, state=state)

                    all_results.append({
                        "episode_efe": ep_efe,
                        "num_steps": len(ep_efe),
                    })

                results_path = tmp_path / "e2e_results.json"
                with open(results_path, "w") as f:
                    json.dump(all_results, f, indent=2)

                assert results_path.exists()
                assert len(all_results) == 3
                for r in all_results:
                    assert r["num_steps"] > 0
                    assert all(
                        isinstance(v, float) and math.isfinite(v)
                        for v in r["episode_efe"]
                    )
    ''')


def _build_test_agent_integration() -> str:
    """TestAgentIntegration -- 6 tests."""
    return textwrap.dedent('''\

        # ======================================================================
        # 13. TestAgentIntegration
        # ======================================================================


        class TestAgentIntegration:
            """Integration tests for the full ActiveInferenceAgent."""

            def test_reset(self, toy_agent, device):
                """Agent reset produces valid initial AgentState."""
                state = toy_agent.reset(B, device)
                assert isinstance(state, AgentState)
                assert state.latent_state is not None
                assert state.latent_state.shape == (B, STATE_DIM)
                assert state.step_count == 0
                assert state.prev_action is None

            def test_infer_state(self, toy_agent, device):
                """infer_state produces valid posterior params and sample."""
                obs = torch.randn(B, OBS_DIM, device=device)
                state = toy_agent.reset(B, device)
                q_params, s_sample, updated_state = toy_agent.infer_state(
                    obs, state=state
                )
                mu, log_var = q_params
                assert mu.shape == (B, STATE_DIM)
                assert log_var.shape == (B, STATE_DIM)
                assert s_sample.shape == (B, STATE_DIM)
                assert updated_state.latent_state is not None

            def test_plan(self, toy_agent, device):
                """plan() produces valid ActionOutput with EFE breakdown."""
                obs = torch.randn(B, OBS_DIM, device=device)
                state = toy_agent.reset(B, device)
                result = toy_agent.plan(obs, state=state)
                assert isinstance(result, ActionOutput)
                assert result.action is not None
                assert result.efe_total.shape == (B,)
                assert "pragmatic" in result.efe_terms
                assert "epistemic" in result.efe_terms
                assert "instrumental" in result.efe_terms
                assert result.horizon == 2
                assert result.planner_type == "random_shooting"

            def test_act(self, toy_agent, device):
                """act() produces valid ActionOutput."""
                obs = torch.randn(B, OBS_DIM, device=device)
                state = toy_agent.reset(B, device)
                result = toy_agent.act(obs, state=state)
                assert isinstance(result, ActionOutput)
                assert result.action is not None

            def test_sequential_steps(self, toy_agent, device):
                """Agent can run multiple sequential steps without errors."""
                state = toy_agent.reset(B, device)
                obs = torch.randn(B, OBS_DIM, device=device)

                for step in range(5):
                    result = toy_agent.plan(obs, state=state)
                    _, _, state = toy_agent.infer_state(obs, state=state)
                    obs = torch.randn(B, OBS_DIM, device=device)

                assert state.step_count == 0  # infer_state does not increment
                assert torch.isfinite(result.efe_total).all()

            def test_workspace_integration(self, toy_agent, device):
                """Agent accepts workspace-shaped tensors (B, obs_dim)."""
                workspace_output = torch.randn(B, OBS_DIM, device=device)
                state = toy_agent.reset(B, device)
                result = toy_agent.act(workspace_output, state=state)
                assert result.action is not None
                assert result.efe_total is not None
                counts = toy_agent.parameter_count()
                assert counts["total"] > 0
                assert "encoder" in counts
                assert "transition" in counts
    ''')


# ---------------------------------------------------------------------------
# Assembly
# ---------------------------------------------------------------------------

def build_test_file() -> str:
    """Assemble the complete test file from all sections."""
    sections = [
        _build_header(),
        _build_fixtures(),
        _section_comment("Test Classes"),
        _build_test_latent_encoder(),
        _build_test_likelihood_decoder(),
        _build_test_transition_model(),
        _build_test_preferences(),
        _build_test_efe_pure_functions(),
        _build_test_rollout_engine(),
        _build_test_random_shooting(),
        _build_test_cem(),
        _build_test_horizon_stability(),
        _build_test_amortized_policy(),
        _build_test_pymdp_backend(),
        _build_test_offline_rl(),
        _build_test_agent_integration(),
    ]
    return "\n".join(sections)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Generate comprehensive pytest test file for "
            "the Active Inference Agent."
        ),
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help=(
            "Output path for the generated test file. "
            "Defaults to tests/test_active_inference.py relative to "
            "this script's parent skill directory."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated file to stdout instead of writing.",
    )
    args = parser.parse_args()

    content = build_test_file()

    if args.dry_run:
        print(content)
        return

    if args.output:
        output_path = Path(args.output)
    else:
        skill_dir = Path(__file__).resolve().parent.parent
        output_path = skill_dir / "tests" / "test_active_inference.py"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"Generated test file: {output_path}")
    print(f"  Size: {len(content)} bytes, {content.count(chr(10))} lines")

    # Count test methods
    test_count = content.count("    def test_")
    class_count = content.count("class Test")
    print(f"  Classes: {class_count}, Test methods: {test_count}")


if __name__ == "__main__":
    main()
