#!/usr/bin/env python3
"""
gen_spiking_tests.py — Generate parameterized pytest suite for spiking core.

Generates tests/test_spiking_core.py (or a specified output path) with:
- 8 test classes covering 6 testing categories
- Parameterized over neuron types and surrogates
- CUDA tests skipped if no GPU
- Slow convergence tests marked with @pytest.mark.slow
- Shared fixtures in module scope

Usage:
    python gen_spiking_tests.py                          # Generate to default path
    python gen_spiking_tests.py --output path/to/out.py  # Custom output
    python gen_spiking_tests.py --timesteps 50           # Configure timesteps
    python gen_spiking_tests.py --batch-size 8           # Configure batch size

Generated test structure:
    TestGradientPresence   -- Non-zero grads for all learnable params
    TestSurrogateSwap      -- Different surrogates produce different gradients
    TestFiniteDifference   -- Autograd matches numeric gradients (ATan only)
    TestStateResetCarry    -- Reset determinism, carry divergence, detach correctness
    TestTruncatedBPTT      -- Chunked forward matches full forward
    TestDeviceParity       -- CPU/CUDA output and gradient match (skipped w/o CUDA)
    TestDebugSurfaces      -- Firing rates, membrane stats, sparsity
    TestNumericalStability -- Long unrolls, beta bounds, threshold edge cases
"""

import argparse
import os
import sys
import textwrap
from pathlib import Path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate parameterized pytest suite for the spiking core."
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help=(
            "Destination file path for the generated test file. "
            "Defaults to <repo_root>/tests/test_spiking_core.py"
        ),
    )
    parser.add_argument(
        "--timesteps",
        type=int,
        default=10,
        help="Default number of timesteps T used in most tests (default: 10).",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=4,
        dest="batch_size",
        help="Batch size used in most tests (default: 4).",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _default_output_path() -> Path:
    """Return <repo_root>/tests/test_spiking_core.py relative to this script."""
    script_dir = Path(__file__).resolve().parent
    # scripts/ -> spiking-core/ -> skills/ -> brain-ai-dev/ -> human-brain/
    # Actual repo root for tests/ is the top-level human-brain project
    repo_root = script_dir.parent.parent.parent.parent
    tests_dir = repo_root / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    return tests_dir / "test_spiking_core.py"


def _indent(text: str, levels: int = 1) -> str:
    """Indent every non-empty line by 4 * levels spaces."""
    prefix = "    " * levels
    return "\n".join(
        (prefix + line) if line.strip() else line
        for line in text.splitlines()
    )


# ---------------------------------------------------------------------------
# Template sections
# ---------------------------------------------------------------------------

def _header(timesteps: int, batch_size: int) -> str:
    return f'''\
# ============================================================
# test_spiking_core.py
# Auto-generated by gen_spiking_tests.py — do not edit by hand.
# Re-generate with:
#   python scripts/gen_spiking_tests.py
# ============================================================

"""
Comprehensive parameterized pytest suite for the spiking core.

Categories covered:
  1a  TestGradientPresence   — Non-zero grads for all learnable params
  1b  TestSurrogateSwap      — Gradient norms differ across surrogates
  1c  TestFiniteDifference   — Autograd vs numeric FD (ATan surrogate)
  3   TestStateResetCarry    — Reset determinism, carry, detach semantics
  3c  TestTruncatedBPTT      — Chunked forward equals full forward
  4   TestDeviceParity       — CPU/CUDA output and gradient parity
  5   TestDebugSurfaces      — Firing rates, membrane stats, sparsity
  6   TestNumericalStability — Long unrolls, beta bounds, edge cases

Configuration baked in at generation time:
  DEFAULT_T          = {timesteps}
  DEFAULT_BATCH_SIZE = {batch_size}

Run fast tests only (excludes @pytest.mark.slow):
    pytest tests/test_spiking_core.py -v

Run all tests including slow convergence checks:
    pytest tests/test_spiking_core.py -v -m "slow or not slow"

Run only CUDA parity tests:
    pytest tests/test_spiking_core.py::TestDeviceParity -v
"""
'''


def _imports_and_constants(timesteps: int, batch_size: int) -> str:
    return f'''\
import math
import warnings
import pytest
import torch
import torch.nn as nn
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Import neuron classes — handle both explicit-state and legacy APIs.
# The legacy API stores state on self.mem; the explicit-state API uses a
# SpikingState dataclass and passes state through forward().
# ---------------------------------------------------------------------------

try:
    from brain_ai.core.neurons import (
        SpikingState,
        LIFNeuron,
        AdaptiveLIFNeuron,
        RecurrentLIFNeuron,
        AdvancedLIFNeuron,
        get_surrogate,
    )
    EXPLICIT_STATE = True
except ImportError:
    from brain_ai.core.neurons import (
        LIFNeuron,
        AdaptiveLIFNeuron,
        RecurrentLIFNeuron,
        AdvancedLIFNeuron,
        get_surrogate,
    )
    EXPLICIT_STATE = False

# ---------------------------------------------------------------------------
# Constants baked in at generation time
# ---------------------------------------------------------------------------

DEFAULT_T = {timesteps}
DEFAULT_BATCH = {batch_size}
HAS_CUDA = torch.cuda.is_available()

NEURON_NAMES = ["lif", "adaptive_lif", "recurrent_lif", "advanced_lif"]
SURROGATE_NAMES = ["atan", "fast_sigmoid", "straight_through"]

# ---------------------------------------------------------------------------
# Neuron factory
# ---------------------------------------------------------------------------

def _make_neuron(name: str, size: int = 16, surrogate: str = "atan", **kwargs):
    """
    Create a neuron of the given type with appropriate constructor args.

    RecurrentLIFNeuron and AdvancedLIFNeuron require an explicit size;
    LIFNeuron and AdaptiveLIFNeuron are size-agnostic (they take input
    as current rather than applying a linear projection internally).
    """
    if name == "lif":
        return LIFNeuron(surrogate=surrogate, **kwargs)
    elif name == "adaptive_lif":
        return AdaptiveLIFNeuron(surrogate=surrogate, **kwargs)
    elif name == "recurrent_lif":
        return RecurrentLIFNeuron(size=size, surrogate=surrogate, **kwargs)
    elif name == "advanced_lif":
        return AdvancedLIFNeuron(size=size, surrogate=surrogate, **kwargs)
    else:
        raise ValueError(f"Unknown neuron name: {{name}}")


def _reset_neuron(neuron) -> None:
    """Reset neuron state using whichever API is available."""
    if hasattr(neuron, "reset_state"):
        # Explicit-state API: reset_state returns a fresh state object.
        # The caller is responsible for passing it back; implicit self.mem
        # is irrelevant in this path.
        pass
    elif hasattr(neuron, "reset_mem"):
        neuron.reset_mem()


def _forward_timesteps(
    neuron,
    x_seq: torch.Tensor,
    T: Optional[int] = None,
    state=None,
) -> Tuple[torch.Tensor, list]:
    """
    Run the neuron for T timesteps, returning stacked spikes and membrane values.

    x_seq shape: (B, T, features) for neurons that accept shaped input, or
                 (B, features) for a single-step neuron (replicated T times).

    Handles both legacy (implicit self.mem) and explicit-state APIs.

    Returns:
        spikes  : (B, T, features)
        mems    : list of T tensors, each (B, features)
    """
    if T is None:
        T = x_seq.shape[1] if x_seq.dim() == 3 else DEFAULT_T

    spikes_list: list = []
    mems_list: list = []

    for t in range(T):
        # Slice the time dimension if provided, else reuse x_seq for each step
        if x_seq.dim() == 3:
            x_t = x_seq[:, t, :]
        else:
            x_t = x_seq

        if EXPLICIT_STATE and hasattr(neuron, "reset_state") and state is None:
            # First call: initialize state from the layer if supported
            result = neuron(x_t, state=None)
        elif EXPLICIT_STATE and hasattr(neuron, "forward") and state is not None:
            try:
                result = neuron(x_t, state=state)
            except TypeError:
                result = neuron(x_t)
        else:
            result = neuron(x_t)

        if isinstance(result, (tuple, list)):
            spk, mem_or_state = result[0], result[1]
            # For explicit-state API mem_or_state may be a SpikingState
            if EXPLICIT_STATE and hasattr(mem_or_state, "v"):
                state = mem_or_state
                mem = mem_or_state.v
            else:
                mem = mem_or_state
        else:
            spk = result
            mem = torch.zeros_like(spk)

        spikes_list.append(spk)
        mems_list.append(mem)

    spikes = torch.stack(spikes_list, dim=1)   # (B, T, features)
    return spikes, mems_list


# ---------------------------------------------------------------------------
# Tiny network helper for gradient tests
# ---------------------------------------------------------------------------

class TinySpikingNet(nn.Module):
    """
    Minimal network: Linear -> LIF -> Linear -> LIF.
    Provides W_in (first linear) with easily testable gradients.
    """

    def __init__(
        self,
        in_features: int = 8,
        hidden: int = 4,
        out_features: int = 2,
        surrogate: str = "atan",
        beta: float = 0.9,
    ):
        super().__init__()
        self.W_in = nn.Linear(in_features, hidden)
        self.lif1 = LIFNeuron(beta=beta, surrogate=surrogate)
        self.W_out = nn.Linear(hidden, out_features)
        self.lif2 = LIFNeuron(beta=beta, surrogate=surrogate)

    def reset(self):
        self.lif1.reset_mem()
        self.lif2.reset_mem()

    def forward_T(self, x_seq: torch.Tensor) -> torch.Tensor:
        """
        x_seq: (B, T, in_features)
        Returns: spikes (B, T, out_features)
        """
        T = x_seq.shape[1]
        out_list = []
        for t in range(T):
            h = self.W_in(x_seq[:, t, :])
            h, _ = self.lif1(h)
            o = self.W_out(h)
            o, _ = self.lif2(o)
            out_list.append(o)
        return torch.stack(out_list, dim=1)
'''


def _fixtures() -> str:
    return '''\
# ---------------------------------------------------------------------------
# Module-level fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(params=NEURON_NAMES)
def neuron_name(request):
    return request.param


@pytest.fixture(params=SURROGATE_NAMES)
def surrogate_name(request):
    return request.param


@pytest.fixture
def tiny_net():
    """Tiny spiking network: in=8, hidden=4, out=2, ATan surrogate."""
    net = TinySpikingNet(in_features=8, hidden=4, out_features=2, surrogate="atan")
    net.reset()
    return net


@pytest.fixture
def fixed_batch():
    """Fixed random batch for reproducibility: (batch=DEFAULT_BATCH, T=DEFAULT_T, in=8)."""
    torch.manual_seed(42)
    return torch.randn(DEFAULT_BATCH, DEFAULT_T, 8)
'''


def _class_gradient_presence(timesteps: int, batch_size: int) -> str:
    return f'''\
# ===========================================================================
# Category 1a: Gradient Presence
# ===========================================================================

class TestGradientPresence:
    """
    Verify that gradients are non-zero for all learnable parameters after a
    loss.backward() call through T timesteps of spiking activity.

    Specification: testing-matrix.md section 1a.
    """

    @pytest.mark.parametrize("neuron_name", NEURON_NAMES)
    @pytest.mark.parametrize("surrogate_name", SURROGATE_NAMES)
    def test_weight_gradients(self, neuron_name: str, surrogate_name: str):
        """
        W_in gradients must be non-zero for every (neuron_type, surrogate) pair.

        A zero gradient here means either:
          - The surrogate is not connected to the backward graph, or
          - The neuron forward path does not depend on its input weights.
        """
        torch.manual_seed(0)
        T = {timesteps}
        B = {batch_size}
        size = 16

        net = TinySpikingNet(in_features=size, hidden=8, out_features=4,
                             surrogate=surrogate_name)
        net.reset()

        x = torch.randn(B, T, size)
        spikes = net.forward_T(x)
        loss = spikes.sum()
        loss.backward()

        assert net.W_in.weight.grad is not None, (
            f"W_in.grad is None for neuron={{neuron_name}}, surrogate={{surrogate_name}}"
        )
        grad_sum = net.W_in.weight.grad.abs().sum().item()
        assert grad_sum > 0.0, (
            f"W_in.grad is all-zero for neuron={{neuron_name}}, surrogate={{surrogate_name}} "
            f"(grad_sum={{grad_sum}})"
        )

    @pytest.mark.parametrize("neuron_name", ["lif", "adaptive_lif"])
    def test_threshold_gradient(self, neuron_name: str):
        """
        Learnable threshold (v_th / threshold) must receive gradient when enabled.

        Chain rule: ds/dv_th = -sigma'(v - v_th), so gradient flows through
        the surrogate to the threshold parameter.
        """
        torch.manual_seed(1)
        T = {timesteps}
        B = {batch_size}
        size = 16

        neuron = _make_neuron(neuron_name, size=size)

        # Enable learnable threshold — may require re-instantiation.
        # Attempt via parameter upgrade if not already learnable.
        if neuron_name == "lif":
            neuron = LIFNeuron(threshold=1.0, learn_threshold=True, surrogate="atan")
        elif neuron_name == "adaptive_lif":
            # AdaptiveLIFNeuron uses a fixed threshold_base; try to make learnable.
            # Wrap it: we test the threshold_base attribute if it is a Parameter.
            neuron = AdaptiveLIFNeuron(threshold=1.0, surrogate="atan")
            # Attempt to convert threshold to a Parameter
            if not isinstance(neuron.threshold_base, nn.Parameter):
                try:
                    val = neuron.threshold_base.item() if hasattr(neuron.threshold_base, "item") else float(neuron.threshold_base)
                    neuron.threshold_base = nn.Parameter(torch.tensor(val))
                except Exception:
                    pytest.skip("Could not make threshold learnable for AdaptiveLIFNeuron")

        x = torch.randn(B, size) * 1.5

        spikes_list = []
        for _ in range(T):
            out = neuron(x)
            spk = out[0] if isinstance(out, (tuple, list)) else out
            spikes_list.append(spk)

        loss = torch.stack(spikes_list).sum()
        loss.backward()

        # Find the threshold-like parameter
        thresh_param = None
        for pname, p in neuron.named_parameters():
            if "threshold" in pname.lower() or "v_th" in pname.lower():
                thresh_param = p
                break

        if thresh_param is None:
            pytest.skip(f"No learnable threshold found in {{neuron_name}}")

        assert thresh_param.grad is not None, (
            f"Threshold grad is None for {{neuron_name}}"
        )
        assert thresh_param.grad.abs().sum().item() > 0.0, (
            f"Threshold grad is zero for {{neuron_name}}"
        )

    @pytest.mark.parametrize("neuron_name", ["lif", "advanced_lif"])
    def test_beta_gradient(self, neuron_name: str):
        """
        Learnable beta must receive gradients when configured as a nn.Parameter.

        For AdvancedLIFNeuron this is log_beta (constrained via sigmoid).
        For LIFNeuron this requires learn_beta=True.
        """
        torch.manual_seed(2)
        T = {timesteps}
        B = {batch_size}
        size = 16

        if neuron_name == "lif":
            neuron = LIFNeuron(beta=0.9, learn_beta=True, surrogate="atan")
        elif neuron_name == "advanced_lif":
            neuron = AdvancedLIFNeuron(size=size, learnable_beta=True, surrogate="atan")
        else:
            pytest.skip(f"{{neuron_name}} does not support learnable beta in this test")

        x = torch.randn(B, size) * 1.5

        spikes_list = []
        for _ in range(T):
            out = neuron(x)
            spk = out[0] if isinstance(out, (tuple, list)) else out
            spikes_list.append(spk)

        loss = torch.stack(spikes_list).sum()
        loss.backward()

        beta_param = None
        for pname, p in neuron.named_parameters():
            if "beta" in pname.lower() or "log_beta" in pname.lower():
                beta_param = p
                break

        if beta_param is None:
            pytest.skip(f"No learnable beta found in {{neuron_name}}")

        assert beta_param.grad is not None, (
            f"Beta grad is None for {{neuron_name}}"
        )
        assert beta_param.grad.abs().sum().item() > 0.0, (
            f"Beta grad is zero for {{neuron_name}}"
        )

    def test_recurrent_weight_gradient(self):
        """
        W_rec (recurrent.weight) must receive gradients in RecurrentLIFNeuron.

        RecurrentLIF adds W_rec @ s_{{t-1}} to the input; if this path has zero
        gradient, the recurrent connection is dead.
        """
        torch.manual_seed(3)
        T = {timesteps}
        B = {batch_size}
        size = 16

        neuron = RecurrentLIFNeuron(size=size, surrogate="atan")
        x = torch.randn(B, size) * 1.5

        spikes_list = []
        for _ in range(T):
            out = neuron(x)
            spk = out[0] if isinstance(out, (tuple, list)) else out
            spikes_list.append(spk)

        loss = torch.stack(spikes_list).sum()
        loss.backward()

        assert neuron.recurrent.weight.grad is not None, (
            "W_rec.grad is None for RecurrentLIFNeuron"
        )
        assert neuron.recurrent.weight.grad.abs().sum().item() > 0.0, (
            "W_rec.grad is all-zero for RecurrentLIFNeuron"
        )
'''


def _class_surrogate_swap(timesteps: int, batch_size: int) -> str:
    return f'''\
# ===========================================================================
# Category 1b: Surrogate Swap
# ===========================================================================

class TestSurrogateSwap:
    """
    Swapping the surrogate function must produce measurably different gradient
    norms.  This confirms the surrogate is genuinely wired into backprop and
    is not dead code.

    Specification: testing-matrix.md section 1b.
    """

    @pytest.mark.parametrize("neuron_name", NEURON_NAMES)
    def test_gradient_norms_differ(self, neuron_name: str):
        """
        Gradient norms of W_in under ATan, FastSigmoid, and STE must not all
        be identical.  All three must be finite and non-zero.
        """
        T = {timesteps}
        B = {batch_size}
        size = 16
        grad_norms: Dict[str, float] = {{}}

        for surrogate_name in SURROGATE_NAMES:
            torch.manual_seed(42)  # Identical init for every surrogate
            net = TinySpikingNet(in_features=size, hidden=8, out_features=4,
                                 surrogate=surrogate_name)
            net.reset()

            torch.manual_seed(42)  # Identical input for every surrogate
            x = torch.randn(B, T, size)

            spikes = net.forward_T(x)
            loss = spikes.sum()
            loss.backward()

            gn = net.W_in.weight.grad.norm().item()
            grad_norms[surrogate_name] = gn

            assert math.isfinite(gn) and gn > 0.0, (
                f"{{surrogate_name}} produced non-finite or zero grad_norm={{gn:.6f}} "
                f"for {{neuron_name}}"
            )

        norms = list(grad_norms.values())
        all_equal = all(abs(n - norms[0]) < 1e-9 for n in norms[1:])
        assert not all_equal, (
            f"All surrogates produced identical grad norms {{grad_norms}} for "
            f"{{neuron_name}} — surrogate is not wired into backward pass."
        )
'''


def _class_finite_difference(timesteps: int, batch_size: int) -> str:
    return f'''\
# ===========================================================================
# Category 1c: Finite Difference Spot-Check
# ===========================================================================

class TestFiniteDifference:
    """
    Compare autograd gradients against a numeric finite-difference
    approximation.

    IMPORTANT: The Heaviside forward pass has zero true derivative almost
    everywhere.  Finite difference estimates the Heaviside gradient, while
    autograd computes the surrogate gradient.  These agree only at operating
    points where the surrogate closely approximates the forward response.
    This test is valid ONLY with the ATan surrogate (the smoothest of the
    three) and a relative tolerance of 5%.

    Specification: testing-matrix.md section 1c.
    """

    def test_finite_difference_lif(self):
        """
        For 5 randomly selected entries of W_in, the relative error between
        autograd gradient and finite-difference approximation must be < 5%.

        Network: in=4, hidden=2, out=1, T=3 (tiny to keep FD tractable).
        """
        torch.manual_seed(7)
        EPS = 1e-4
        TOLS = 0.05   # 5% relative tolerance as per spec
        T = 3
        B = 2
        IN = 4

        # ---- helper: run the network and return scalar loss ----
        def compute_loss(net, x_seq):
            net.reset()
            spikes = net.forward_T(x_seq)
            return spikes.sum()

        net = TinySpikingNet(in_features=IN, hidden=2, out_features=1, surrogate="atan")
        torch.manual_seed(7)
        x_seq = torch.randn(B, T, IN)

        # Autograd gradient
        net.reset()
        loss = compute_loss(net, x_seq)
        loss.backward()
        autograd_grad = net.W_in.weight.grad.clone()

        # Finite-difference approximation for 5 randomly selected scalar entries
        torch.manual_seed(7)
        H_out, H_in = net.W_in.weight.shape
        indices = [
            (torch.randint(H_out, (1,)).item(), torch.randint(H_in, (1,)).item())
            for _ in range(5)
        ]

        for (i, j) in indices:
            original_val = net.W_in.weight.data[i, j].item()

            # f(w + eps)
            with torch.no_grad():
                net.W_in.weight.data[i, j] = original_val + EPS
            f_plus = compute_loss(net, x_seq).item()

            # f(w - eps)
            with torch.no_grad():
                net.W_in.weight.data[i, j] = original_val - EPS
            f_minus = compute_loss(net, x_seq).item()

            # Restore
            with torch.no_grad():
                net.W_in.weight.data[i, j] = original_val

            g_numeric = (f_plus - f_minus) / (2.0 * EPS)
            g_autograd = autograd_grad[i, j].item()

            rel_err = abs(g_numeric - g_autograd) / (abs(g_autograd) + 1e-8)

            assert rel_err < TOLS, (
                f"FD mismatch at W_in[{{i}},{{j}}]: "
                f"numeric={{g_numeric:.6f}}, autograd={{g_autograd:.6f}}, "
                f"rel_err={{rel_err:.4f}} (threshold={{TOLS}})"
            )
'''


def _class_state_reset_carry(timesteps: int, batch_size: int) -> str:
    return f'''\
# ===========================================================================
# Category 3: State Reset and Carry
# ===========================================================================

class TestStateResetCarry:
    """
    Verify the three fundamental state-management properties:
      - Reset determinism: same input + reset -> identical output
      - Carry changes output: carried state -> different output vs reset
      - Detach preserves values but cuts gradient flow

    Specification: testing-matrix.md sections 3a, 3b, 3d.
    """

    @pytest.mark.parametrize("neuron_name", NEURON_NAMES)
    def test_reset_determinism(self, neuron_name: str):
        """
        Two independent reset+forward runs with the same input must produce
        bitwise-identical spike outputs on CPU.
        """
        torch.manual_seed(10)
        T = {timesteps}
        B = {batch_size}
        size = 16

        neuron = _make_neuron(neuron_name, size=size, surrogate="atan")
        x = torch.randn(B, size)

        # Run 1
        _reset_neuron(neuron)
        spikes1, _ = _forward_timesteps(neuron, x, T=T)

        # Run 2
        _reset_neuron(neuron)
        spikes2, _ = _forward_timesteps(neuron, x, T=T)

        assert torch.equal(spikes1, spikes2), (
            f"Reset+forward not deterministic for {{neuron_name}}. "
            f"Max diff: {{(spikes1 - spikes2).abs().max().item():.6f}}"
        )

    @pytest.mark.parametrize("neuron_name", NEURON_NAMES)
    def test_carry_changes_output(self, neuron_name: str):
        """
        Carried state must change the forward output compared to a fresh reset.

        Procedure:
          y1 = forward(reset, x)
          y2 = forward(carry from y1, x)   <- different from y1
          y3 = forward(reset, x)           <- equal to y1
        """
        torch.manual_seed(11)
        T = {timesteps}
        B = {batch_size}
        size = 16

        neuron = _make_neuron(neuron_name, size=size, surrogate="atan")
        x = torch.randn(B, size) * 1.5   # Non-trivial input to ensure firing

        # Run 1: fresh reset
        _reset_neuron(neuron)
        spikes1, _ = _forward_timesteps(neuron, x, T=T)

        # Run 2: carry state (no reset between runs)
        spikes2, _ = _forward_timesteps(neuron, x, T=T)

        # Run 3: reset again
        _reset_neuron(neuron)
        spikes3, _ = _forward_timesteps(neuron, x, T=T)

        # y1 == y3 (reset recovers identical output)
        assert torch.equal(spikes1, spikes3), (
            f"Reset did not reproduce y1 for {{neuron_name}}. "
            f"Max diff: {{(spikes1 - spikes3).abs().max().item():.6f}}"
        )

        # y1 != y2 (carry changed output)
        # Sanity: if input is zero, carry has no effect — skip rather than fail
        if torch.all(x == 0):
            pytest.skip("Input is zero — carry has no effect; test is vacuous")

        assert not torch.equal(spikes1, spikes2), (
            f"Carry state did NOT change output for {{neuron_name}}. "
            "This means state carry is not connected to the forward computation."
        )

    @pytest.mark.parametrize("neuron_name", NEURON_NAMES)
    def test_detach_preserves_values(self, neuron_name: str):
        """
        detach_state() (explicit API) or manual detach must return tensors
        with identical numerical values but no grad_fn.
        """
        torch.manual_seed(12)
        T = {timesteps}
        B = {batch_size}
        size = 16

        neuron = _make_neuron(neuron_name, size=size, surrogate="atan")
        x = torch.randn(B, size)

        _reset_neuron(neuron)
        spikes, mems = _forward_timesteps(neuron, x, T=T)

        # Get the last membrane state
        last_mem = mems[-1]

        # Detach it
        detached = last_mem.detach()

        assert torch.equal(last_mem, detached), (
            f"Detach changed values for {{neuron_name}}"
        )
        assert detached.grad_fn is None, (
            f"Detached tensor still has grad_fn for {{neuron_name}}"
        )

    @pytest.mark.parametrize("neuron_name", NEURON_NAMES)
    def test_detach_cuts_gradient(self, neuron_name: str):
        """
        Gradients must not flow through a detach() boundary.

        Setup:
          W_proj_1 applied only to chunk 1 (timesteps 0..T//2).
          State is detached before chunk 2.
          W_proj_2 applied only to chunk 2 (timesteps T//2..T).
          Loss computed only from chunk 2.

        Expected:
          W_proj_1.grad is None or zero  (detach blocked it)
          W_proj_2.grad is non-zero      (chunk 2 trains normally)
        """
        torch.manual_seed(13)
        T = {timesteps}
        B = {batch_size}
        size = 16
        chunk = T // 2 or 1

        W_proj_1 = nn.Linear(size, size, bias=False)
        W_proj_2 = nn.Linear(size, size, bias=False)

        neuron = _make_neuron(neuron_name, size=size, surrogate="atan")
        _reset_neuron(neuron)

        x = torch.randn(B, size)

        # --- Chunk 1 ---
        spikes1_list = []
        for _ in range(chunk):
            h = W_proj_1(x)
            out = neuron(h)
            spk = out[0] if isinstance(out, (tuple, list)) else out
            spikes1_list.append(spk)

        # Get current membrane and detach it explicitly
        # For legacy API: grab self.mem and detach
        if hasattr(neuron, "mem") and neuron.mem is not None:
            neuron.mem = neuron.mem.detach()
        if hasattr(neuron, "adaptation") and neuron.adaptation is not None:
            neuron.adaptation = neuron.adaptation.detach()
        if hasattr(neuron, "prev_spk") and neuron.prev_spk is not None:
            neuron.prev_spk = neuron.prev_spk.detach()

        # --- Chunk 2 ---
        spikes2_list = []
        for _ in range(T - chunk):
            h = W_proj_2(x)
            out = neuron(h)
            spk = out[0] if isinstance(out, (tuple, list)) else out
            spikes2_list.append(spk)

        loss = torch.stack(spikes2_list).sum()
        loss.backward()

        # W_proj_2 should have gradient (chunk 2 is in the graph)
        assert W_proj_2.weight.grad is not None, (
            f"W_proj_2.grad is None for {{neuron_name}} — chunk 2 gradient missing"
        )
        assert W_proj_2.weight.grad.abs().sum().item() > 0.0, (
            f"W_proj_2.grad is zero for {{neuron_name}}"
        )

        # W_proj_1 should have no gradient (detach blocked it)
        grad1_sum = (
            W_proj_1.weight.grad.abs().sum().item()
            if W_proj_1.weight.grad is not None
            else 0.0
        )
        assert grad1_sum == 0.0, (
            f"Gradient leaked through detach into W_proj_1 for {{neuron_name}} "
            f"(grad_sum={{grad1_sum:.6f}})"
        )
'''


def _class_truncated_bptt(timesteps: int, batch_size: int) -> str:
    # Need at least T=10 for chunking to be meaningful
    T = max(timesteps, 10)
    return f'''\
# ===========================================================================
# Category 3c: Truncated BPTT
# ===========================================================================

class TestTruncatedBPTT:
    """
    Chunked unroll must produce the same spike outputs as full BPTT unroll,
    and truncated gradients must be bounded by full BPTT gradients.

    Specification: testing-matrix.md section 3c.
    """

    @pytest.mark.parametrize("neuron_name", NEURON_NAMES)
    def test_forward_match(self, neuron_name: str):
        """
        Chunked unroll spike output must equal full unroll spike output.

        T={T}, chunk_size=T//2.

        The forward computation is identical because detach() only severs the
        gradient graph; it does not alter the recurrent integration formula.
        """
        torch.manual_seed(20)
        T = {T}
        B = {batch_size}
        size = 16
        chunk = T // 2

        neuron_full = _make_neuron(neuron_name, size=size, surrogate="atan")
        neuron_chunk = _make_neuron(neuron_name, size=size, surrogate="atan")

        # Copy weights for identical initialization
        neuron_chunk.load_state_dict(neuron_full.state_dict())

        x = torch.randn(B, size)

        # --- Full unroll ---
        _reset_neuron(neuron_full)
        full_spikes = []
        for _ in range(T):
            out = neuron_full(x)
            spk = out[0] if isinstance(out, (tuple, list)) else out
            full_spikes.append(spk.detach())

        # --- Chunked unroll ---
        _reset_neuron(neuron_chunk)
        chunked_spikes = []

        for chunk_start in range(0, T, chunk):
            chunk_end = min(chunk_start + chunk, T)
            for _ in range(chunk_end - chunk_start):
                out = neuron_chunk(x)
                spk = out[0] if isinstance(out, (tuple, list)) else out
                chunked_spikes.append(spk.detach())
            # Detach state between chunks
            if hasattr(neuron_chunk, "mem") and neuron_chunk.mem is not None:
                neuron_chunk.mem = neuron_chunk.mem.detach()
            if hasattr(neuron_chunk, "adaptation") and neuron_chunk.adaptation is not None:
                neuron_chunk.adaptation = neuron_chunk.adaptation.detach()
            if hasattr(neuron_chunk, "prev_spk") and neuron_chunk.prev_spk is not None:
                neuron_chunk.prev_spk = neuron_chunk.prev_spk.detach()

        full_tensor = torch.stack(full_spikes, dim=1)
        chunk_tensor = torch.stack(chunked_spikes, dim=1)

        assert torch.equal(full_tensor, chunk_tensor), (
            f"Chunked spikes != full spikes for {{neuron_name}}. "
            f"Max diff: {{(full_tensor - chunk_tensor).abs().max().item():.8f}}"
        )

    @pytest.mark.parametrize("neuron_name", NEURON_NAMES)
    def test_gradient_bounded(self, neuron_name: str):
        """
        Truncated gradient norms must be <= full BPTT gradient norms.

        Truncation reduces or preserves gradient magnitude; it never amplifies.
        We compare gradient norms on the first linear projection applied to
        each step's input.
        """
        torch.manual_seed(21)
        T = {T}
        B = {batch_size}
        size = 16
        chunk = T // 2

        W_shared = nn.Linear(size, size, bias=False)

        def run_full():
            _neuron = _make_neuron(neuron_name, size=size, surrogate="atan")
            _reset_neuron(_neuron)
            spikes = []
            for _ in range(T):
                h = W_shared(torch.randn(B, size, requires_grad=True))
                out = _neuron(h)
                spk = out[0] if isinstance(out, (tuple, list)) else out
                spikes.append(spk)
            loss = torch.stack(spikes).sum()
            loss.backward()
            return W_shared.weight.grad.norm().item()

        def run_truncated():
            _neuron = _make_neuron(neuron_name, size=size, surrogate="atan")
            _reset_neuron(_neuron)
            spikes = []
            for chunk_start in range(0, T, chunk):
                chunk_end = min(chunk_start + chunk, T)
                for _ in range(chunk_end - chunk_start):
                    h = W_shared(torch.randn(B, size, requires_grad=True))
                    out = _neuron(h)
                    spk = out[0] if isinstance(out, (tuple, list)) else out
                    spikes.append(spk)
                # Detach between chunks
                if hasattr(_neuron, "mem") and _neuron.mem is not None:
                    _neuron.mem = _neuron.mem.detach()
                if hasattr(_neuron, "adaptation") and _neuron.adaptation is not None:
                    _neuron.adaptation = _neuron.adaptation.detach()
            # Backward only through last chunk
            torch.stack(spikes[-chunk:]).sum().backward()
            return W_shared.weight.grad.norm().item() if W_shared.weight.grad is not None else 0.0

        torch.manual_seed(21)
        W_shared.zero_grad()
        full_norm = run_full()

        torch.manual_seed(21)
        W_shared.zero_grad()
        trunc_norm = run_truncated()

        assert trunc_norm <= full_norm + 1e-4, (
            f"Truncated gradient norm {{trunc_norm:.6f}} > full BPTT norm {{full_norm:.6f}} "
            f"for {{neuron_name}} — truncation should not amplify gradients."
        )
'''


def _class_device_parity(timesteps: int, batch_size: int) -> str:
    return f'''\
# ===========================================================================
# Category 4: CPU vs CUDA Parity
# ===========================================================================

@pytest.mark.skipif(not HAS_CUDA, reason="CUDA not available")
class TestDeviceParity:
    """
    CPU and CUDA must produce numerically matching outputs and gradient norms.

    Binary spikes must be bitwise-identical (Heaviside is deterministic);
    membrane values may differ within atol=1e-5 due to floating-point
    accumulation order differences across hardware.

    Specification: testing-matrix.md sections 4a, 4b, 4c.
    """

    @pytest.mark.parametrize("neuron_name", NEURON_NAMES)
    def test_output_parity(self, neuron_name: str):
        """
        Spike outputs must be bitwise identical; membrane values within atol=1e-5.
        """
        torch.manual_seed(42)
        T = {timesteps}
        B = {batch_size}
        size = 16

        neuron_cpu = _make_neuron(neuron_name, size=size, surrogate="atan")
        neuron_cuda = _make_neuron(neuron_name, size=size, surrogate="atan")
        neuron_cuda.load_state_dict(neuron_cpu.state_dict())
        neuron_cuda = neuron_cuda.cuda()

        x_cpu = torch.randn(B, size)
        x_cuda = x_cpu.cuda()

        _reset_neuron(neuron_cpu)
        spikes_cpu, mems_cpu = _forward_timesteps(neuron_cpu, x_cpu, T=T)

        _reset_neuron(neuron_cuda)
        spikes_cuda, mems_cuda = _forward_timesteps(neuron_cuda, x_cuda, T=T)

        spikes_cuda_cpu = spikes_cuda.cpu()
        assert torch.equal(spikes_cpu, spikes_cuda_cpu), (
            f"Spike outputs differ between CPU and CUDA for {{neuron_name}}. "
            f"Mismatch count: {{(spikes_cpu != spikes_cuda_cpu).sum().item()}}"
        )

        mem_cpu = torch.stack(mems_cpu, dim=1)
        mem_cuda = torch.stack(mems_cuda, dim=1).cpu()
        assert torch.allclose(mem_cpu, mem_cuda, atol=1e-5, rtol=1e-4), (
            f"Membrane potentials differ CPU vs CUDA for {{neuron_name}}. "
            f"Max diff: {{(mem_cpu - mem_cuda).abs().max().item():.8f}}"
        )

    @pytest.mark.parametrize("neuron_name", NEURON_NAMES)
    def test_gradient_parity(self, neuron_name: str):
        """
        Gradient norms must match between CPU and CUDA within atol=1e-4, rtol=1e-3.
        """
        torch.manual_seed(42)
        T = {timesteps}
        B = {batch_size}
        size = 16

        # Use TinySpikingNet for a real W_in gradient to compare
        net_cpu = TinySpikingNet(in_features=size, hidden=8, out_features=4,
                                  surrogate="atan")
        net_cuda = TinySpikingNet(in_features=size, hidden=8, out_features=4,
                                   surrogate="atan")
        net_cuda.load_state_dict(net_cpu.state_dict())
        net_cuda = net_cuda.cuda()

        torch.manual_seed(42)
        x_cpu = torch.randn(B, T, size)
        x_cuda = x_cpu.cuda()

        net_cpu.reset()
        net_cuda.reset()

        net_cpu.forward_T(x_cpu).sum().backward()
        net_cuda.forward_T(x_cuda).sum().backward()

        for name, p_cpu in net_cpu.named_parameters():
            p_cuda = dict(net_cuda.named_parameters())[name]
            if p_cpu.grad is None:
                continue
            gn_cpu = p_cpu.grad.norm().item()
            gn_cuda = p_cuda.grad.norm().item()
            assert abs(gn_cpu - gn_cuda) < 1e-4 + 1e-3 * gn_cpu, (
                f"Gradient norm mismatch for {{name}}: "
                f"CPU={{gn_cpu:.6f}}, CUDA={{gn_cuda:.6f}} (neuron={{neuron_name}})"
            )

    def test_mixed_precision_spikes(self):
        """
        bf16 input with fp32 state accumulation must produce valid binary spikes.

        This verifies that the AMP mixed-precision pattern (input in bf16,
        state in fp32, output spike cast back to bf16) does not introduce NaN
        or non-binary values.
        """
        torch.manual_seed(42)
        T = {timesteps}
        B = {batch_size}
        size = 32

        neuron = LIFNeuron(beta=0.9, threshold=1.0, surrogate="atan").cuda()
        _reset_neuron(neuron)

        x_fp32 = torch.randn(B, size).cuda()
        x_bf16 = x_fp32.to(torch.bfloat16)

        spikes_list = []
        for _ in range(T):
            with torch.autocast(device_type="cuda", dtype=torch.bfloat16):
                out = neuron(x_bf16)
            spk = out[0] if isinstance(out, (tuple, list)) else out
            spikes_list.append(spk)

        spikes = torch.stack(spikes_list)
        assert not torch.isnan(spikes).any(), "NaN in bf16 spike outputs"
        # Spikes should be binary (0.0 or 1.0) even in mixed precision
        unique_vals = spikes.float().unique().tolist()
        non_binary = [v for v in unique_vals if abs(v) > 1e-3 and abs(v - 1.0) > 1e-3]
        assert len(non_binary) == 0, (
            f"Non-binary spike values in mixed precision: {{non_binary}}"
        )
'''


def _class_debug_surfaces(timesteps: int, batch_size: int) -> str:
    return f'''\
# ===========================================================================
# Category 5: Debug Surfaces
# ===========================================================================

class TestDebugSurfaces:
    """
    Diagnostic probes must return reasonable values.  This category validates
    that the debug instrumentation built into (or derivable from) the network
    is accurate and not trivially broken.

    Specification: testing-matrix.md sections 5a, 5b, 5c.
    """

    @pytest.mark.parametrize("neuron_name", NEURON_NAMES)
    def test_firing_rate_range(self, neuron_name: str):
        """
        Mean firing rate (fraction of spikes / total possible) must be in (0, 1).

        A rate of 0.0 indicates dead neurons; 1.0 indicates saturated neurons.
        Both are pathological.
        """
        torch.manual_seed(30)
        T = {timesteps}
        B = {batch_size}
        size = 16

        neuron = _make_neuron(neuron_name, size=size, surrogate="atan")
        _reset_neuron(neuron)

        x = torch.randn(B, size) * 0.8  # Moderate input

        spikes, _ = _forward_timesteps(neuron, x, T=T)
        firing_rate = spikes.mean().item()

        assert firing_rate > 0.0, (
            f"Firing rate is 0 (dead neurons) for {{neuron_name}}"
        )
        assert firing_rate < 1.0, (
            f"Firing rate is 1 (saturated neurons) for {{neuron_name}}"
        )

        if not (0.01 <= firing_rate <= 0.50):
            warnings.warn(
                f"{{neuron_name}} firing rate {{firing_rate:.4f}} is outside the "
                f"expected range [0.01, 0.50]. This may indicate pathological "
                f"threshold or input scaling.",
                UserWarning,
            )

    @pytest.mark.parametrize("neuron_name", NEURON_NAMES)
    def test_membrane_stats_finite(self, neuron_name: str):
        """
        Membrane mean, variance, and max must be finite after T timesteps.
        max < 10 * v_th (membrane is not running away).
        var > 0 (there is actual variation — no constant-output pathology).
        """
        torch.manual_seed(31)
        T = {timesteps}
        B = {batch_size}
        size = 16
        V_TH = 1.0  # Default threshold

        neuron = _make_neuron(neuron_name, size=size, surrogate="atan")
        _reset_neuron(neuron)

        x = torch.randn(B, size)

        _, mems = _forward_timesteps(neuron, x, T=T)
        mem_tensor = torch.stack(mems)  # (T, B, features)

        mem_mean = mem_tensor.mean().item()
        mem_var = mem_tensor.var().item()
        mem_max = mem_tensor.abs().max().item()

        assert math.isfinite(mem_mean), f"Membrane mean is not finite: {{mem_mean}}"
        assert math.isfinite(mem_var), f"Membrane var is not finite: {{mem_var}}"
        assert math.isfinite(mem_max), f"Membrane max is not finite: {{mem_max}}"

        assert mem_max < 10.0 * V_TH, (
            f"Membrane max {{mem_max:.4f}} >= 10 * v_th={{10*V_TH}} for {{neuron_name}}. "
            "Membrane potential is running away."
        )
        assert mem_var > 0.0, (
            f"Membrane variance is 0 for {{neuron_name}} — constant output pathway."
        )

    def test_spike_sparsity(self):
        """
        Spikes must be sparse (> 50% zeros) but not fully dead (< 99% zeros).

        Sparsity in [0.50, 0.99] is the expected regime for a well-calibrated SNN.
        """
        torch.manual_seed(32)
        T = {timesteps}
        B = {batch_size}
        size = 32

        net = TinySpikingNet(in_features=size, hidden=16, out_features=8,
                              surrogate="atan")
        net.reset()

        x_seq = torch.randn(B, T, size) * 0.7
        spikes = net.forward_T(x_seq)  # (B, T, 8)

        sparsity = (spikes == 0).float().mean().item()

        assert sparsity > 0.50, (
            f"Spike sparsity {{sparsity:.4f}} < 0.50 — too many spikes; "
            "threshold may be too low or input too large."
        )
        assert sparsity < 0.99, (
            f"Spike sparsity {{sparsity:.4f}} >= 0.99 — layer is nearly dead; "
            "threshold may be too high or surrogate gradient vanishing."
        )
'''


def _class_numerical_stability(timesteps: int, batch_size: int) -> str:
    return f'''\
# ===========================================================================
# Category 6: Numerical Stability
# ===========================================================================

class TestNumericalStability:
    """
    Edge cases and boundary conditions.  All tests must pass without NaN,
    Inf, or non-finite gradients.

    Specification: testing-matrix.md sections 6a, 6b, 6c, 6d.
    """

    @pytest.mark.parametrize("neuron_name", NEURON_NAMES)
    def test_long_unroll_no_nan(self, neuron_name: str):
        """
        T=200 timesteps must produce no NaN or Inf in spikes or gradients.

        Specification: testing-matrix.md 6a.
        """
        torch.manual_seed(40)
        T_LONG = 200
        B = {batch_size}
        size = 16

        net = TinySpikingNet(in_features=size, hidden=8, out_features=4,
                              surrogate="atan")
        net.reset()

        x_seq = torch.randn(B, T_LONG, size)
        spikes = net.forward_T(x_seq)

        assert not torch.isnan(spikes).any(), (
            f"NaN in spike output at T=200 for neuron type underlying net "
            f"(neuron_name={{neuron_name}})"
        )
        assert not torch.isinf(spikes).any(), (
            f"Inf in spike output at T=200"
        )

        loss = spikes.sum()
        loss.backward()

        for pname, p in net.named_parameters():
            if p.grad is not None:
                assert torch.isfinite(p.grad).all(), (
                    f"Non-finite gradient in {{pname}} after T=200 unroll"
                )

    @pytest.mark.parametrize("beta", [0.0, 0.001, 0.5, 0.95, 0.999])
    def test_beta_boundaries(self, beta: float):
        """
        Beta values 0.0, 0.001, 0.5, 0.95, and 0.999 must all complete
        forward and backward without error.

        For beta=0.0, the neuron has no memory: y_carry should equal y_reset
        because each timestep is independent.

        Specification: testing-matrix.md 6b.
        """
        torch.manual_seed(41)
        T = {timesteps}
        B = {batch_size}
        size = 16

        neuron = LIFNeuron(beta=beta, threshold=1.0, surrogate="atan")
        _reset_neuron(neuron)

        x = torch.randn(B, size)
        spikes, mems = _forward_timesteps(neuron, x, T=T)

        assert not torch.isnan(spikes).any(), (
            f"NaN in spikes for beta={{beta}}"
        )
        assert not torch.isinf(spikes).any(), (
            f"Inf in spikes for beta={{beta}}"
        )

        loss = spikes.sum()
        loss.backward()

        if spikes.requires_grad or any(
            p.requires_grad for p in neuron.parameters()
        ):
            pass  # gradients may or may not flow through a pure buffer

        # For beta=0.0: carry state test — output should not depend on history
        if abs(beta) < 1e-9:
            _reset_neuron(neuron)
            spikes_reset, _ = _forward_timesteps(neuron, x, T=T)
            spikes_carry, _ = _forward_timesteps(neuron, x, T=T)
            assert torch.equal(spikes_reset, spikes_carry), (
                "beta=0 neuron should produce identical output regardless of carry state "
                "(no membrane memory)"
            )

    def test_zero_threshold(self):
        """
        v_th = 0.0 must not produce NaN.

        With threshold=0, any positive membrane value should spike immediately.
        The test checks that no division-by-zero or log(0) occurs.

        Specification: testing-matrix.md 6c.
        """
        torch.manual_seed(50)
        T = {timesteps}
        B = {batch_size}
        size = 16

        neuron = LIFNeuron(beta=0.9, threshold=0.0, surrogate="atan")
        _reset_neuron(neuron)

        x = torch.abs(torch.randn(B, size)) * 0.5  # Positive input -> all above 0 threshold

        spikes, mems = _forward_timesteps(neuron, x, T=T)

        assert not torch.isnan(spikes).any(), (
            "NaN in spikes with v_th=0.0"
        )
        assert not torch.isinf(spikes).any(), (
            "Inf in spikes with v_th=0.0"
        )

        mem_tensor = torch.stack(mems)
        assert not torch.isnan(mem_tensor).any(), (
            "NaN in membrane potential with v_th=0.0"
        )

    def test_large_input(self):
        """
        x = 100.0 must not cause Inf in membrane potential.

        The spike output must be a valid binary tensor.

        Specification: testing-matrix.md 6d (large input case).
        """
        torch.manual_seed(51)
        T = {timesteps}
        B = {batch_size}
        size = 16

        neuron = LIFNeuron(beta=0.9, threshold=1.0, surrogate="atan")
        _reset_neuron(neuron)

        x = torch.full((B, size), 100.0)

        spikes, mems = _forward_timesteps(neuron, x, T=T)

        assert not torch.isinf(torch.stack(mems)).any(), (
            "Inf in membrane potential with x=100.0"
        )
        assert not torch.isnan(spikes).any(), (
            "NaN in spike output with x=100.0"
        )
        # Spikes must be binary
        unique_vals = spikes.unique().tolist()
        non_binary = [v for v in unique_vals if abs(v) > 1e-6 and abs(v - 1.0) > 1e-6]
        assert len(non_binary) == 0, (
            f"Non-binary spike values with x=100.0: {{non_binary}}"
        )

    def test_tiny_input(self):
        """
        x = 1e-6 must still produce non-zero gradients.

        With tiny inputs, few or no spikes occur, but the surrogate gradient
        must still provide signal to W_in via the ATan surrogate's non-zero
        tails.

        Specification: testing-matrix.md 6d (small input case).
        """
        torch.manual_seed(52)
        T = {timesteps}
        B = {batch_size}
        size = 16

        net = TinySpikingNet(in_features=size, hidden=8, out_features=4,
                              surrogate="atan")
        net.reset()

        x_seq = torch.full((B, T, size), 1e-6)

        spikes = net.forward_T(x_seq)
        assert not torch.isnan(spikes).any(), "NaN in spike output with x=1e-6"

        loss = spikes.sum()
        loss.backward()

        assert net.W_in.weight.grad is not None, (
            "W_in.grad is None with x=1e-6 input"
        )
        grad_sum = net.W_in.weight.grad.abs().sum().item()
        assert grad_sum > 0.0, (
            f"W_in.grad is all-zero with x=1e-6 input (grad_sum={{grad_sum:.2e}}). "
            "ATan surrogate should provide non-zero gradient even with rare spikes."
        )
'''


def _slow_convergence_stub() -> str:
    return '''\
# ===========================================================================
# Category 2: Convergence (slow — excluded from default run)
# ===========================================================================

class TestConvergence:
    """
    End-to-end training convergence checks.

    These tests require dataset downloads (MNIST, CIFAR-10) and multiple
    training epochs.  They are excluded from the default pytest run.

    Run with:
        pytest tests/test_spiking_core.py -v -m slow

    Specification: testing-matrix.md sections 2a, 2b, 2c.
    """

    @pytest.mark.slow
    def test_mnist_rate_coded_accuracy(self):
        """
        MNIST rate-coded classification with ATan surrogate must reach >90%
        test accuracy within 5 epochs.

        This test requires torchvision.  It is skipped if torchvision is not
        installed or MNIST is not accessible.
        """
        try:
            import torchvision
            import torchvision.transforms as T_transforms
        except ImportError:
            pytest.skip("torchvision not installed — skipping MNIST convergence test")

        # Stub: implement the full MNIST training loop here.
        # The scaffold below outlines the required structure per spec 2a.
        pytest.skip(
            "MNIST convergence test is a scaffold — implement the training loop "
            "in the body of this test using the SNNCore class and rate-coded encoding."
        )

    @pytest.mark.slow
    def test_cifar10_dev_mode(self):
        """
        CIFAR-10 dev mode must exceed 40% accuracy and improve over 10 epochs.

        Specification: testing-matrix.md 2b.
        """
        pytest.skip(
            "CIFAR-10 convergence test is a scaffold — implement the ConvSNN "
            "training loop in the body of this test."
        )

    @pytest.mark.slow
    def test_training_stability_20_epochs(self):
        """
        No NaN/Inf in parameters across 20 training epochs.
        Mean firing rate per layer must be in (0.05, 0.90).

        Specification: testing-matrix.md 2c.
        """
        pytest.skip(
            "Long-run stability test is a scaffold — implement the 20-epoch "
            "MNIST training loop with per-epoch parameter and firing-rate checks."
        )
'''


def build_test_file(timesteps: int, batch_size: int) -> str:
    """Assemble the complete generated test file as a string."""
    sections = [
        _header(timesteps, batch_size),
        _imports_and_constants(timesteps, batch_size),
        _fixtures(),
        _class_gradient_presence(timesteps, batch_size),
        _class_surrogate_swap(timesteps, batch_size),
        _class_finite_difference(timesteps, batch_size),
        _class_state_reset_carry(timesteps, batch_size),
        _class_truncated_bptt(timesteps, batch_size),
        _class_device_parity(timesteps, batch_size),
        _class_debug_surfaces(timesteps, batch_size),
        _class_numerical_stability(timesteps, batch_size),
        _slow_convergence_stub(),
    ]
    return "\n\n".join(sections) + "\n"


# ---------------------------------------------------------------------------
# Summary printer
# ---------------------------------------------------------------------------

def print_summary(output_path: Path, timesteps: int, batch_size: int) -> None:
    test_classes = [
        ("TestGradientPresence",   "1a",  "Non-zero grads for all learnable params"),
        ("TestSurrogateSwap",      "1b",  "Gradient norms differ across surrogates"),
        ("TestFiniteDifference",   "1c",  "Autograd vs numeric FD (ATan only)"),
        ("TestStateResetCarry",    "3",   "Reset determinism, carry, detach semantics"),
        ("TestTruncatedBPTT",      "3c",  "Chunked forward equals full forward"),
        ("TestDeviceParity",       "4",   "CPU/CUDA output and gradient parity"),
        ("TestDebugSurfaces",      "5",   "Firing rates, membrane stats, sparsity"),
        ("TestNumericalStability", "6",   "Long unrolls, beta bounds, edge cases"),
        ("TestConvergence",        "2",   "End-to-end convergence (slow, scaffold)"),
    ]

    print()
    print("=" * 66)
    print("  gen_spiking_tests.py — Generated test suite")
    print("=" * 66)
    print(f"  Output file   : {output_path}")
    print(f"  Default T     : {timesteps}")
    print(f"  Default batch : {batch_size}")
    print(f"  Neuron types  : lif, adaptive_lif, recurrent_lif, advanced_lif")
    print(f"  Surrogates    : atan, fast_sigmoid, straight_through")
    print(f"  CUDA skip     : @pytest.mark.skipif(not HAS_CUDA, ...)")
    print()
    print("  Generated test classes:")
    for cls, cat, desc in test_classes:
        print(f"    [{cat:3s}] {cls:<30s} — {desc}")
    print()
    print("  Run fast tests (excludes @slow):")
    print(f"    pytest {output_path} -v")
    print()
    print("  Run all tests including slow convergence:")
    print(f"    pytest {output_path} -v -m 'slow or not slow'")
    print()
    print("  Run only CUDA parity tests:")
    print(f"    pytest {output_path}::TestDeviceParity -v")
    print()
    print("  Parameterized test count estimate:")
    n_neuron = 4
    n_surr = 3
    fast_approx = (
        n_neuron * n_surr      # test_weight_gradients
        + 2                    # test_threshold_gradient
        + 2                    # test_beta_gradient
        + 1                    # test_recurrent_weight_gradient
        + n_neuron             # test_gradient_norms_differ
        + 1                    # test_finite_difference_lif
        + n_neuron * 4         # TestStateResetCarry (4 parameterized methods)
        + n_neuron * 2         # TestTruncatedBPTT
        + n_neuron * 2         # TestDeviceParity output+gradient (if CUDA)
        + 1                    # test_mixed_precision_spikes
        + n_neuron * 2         # TestDebugSurfaces (firing_rate, membrane)
        + 1                    # test_spike_sparsity
        + n_neuron             # test_long_unroll_no_nan
        + 5                    # test_beta_boundaries
        + 1                    # test_zero_threshold
        + 1                    # test_large_input
        + 1                    # test_tiny_input
    )
    print(f"    ~{fast_approx} test cases (fast only, CUDA tests conditional)")
    print("=" * 66)
    print()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    args = parse_args()

    output_path = Path(args.output) if args.output else _default_output_path()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    content = build_test_file(args.timesteps, args.batch_size)

    output_path.write_text(content, encoding="utf-8")

    print_summary(output_path, args.timesteps, args.batch_size)
    print(f"Written: {output_path}  ({len(content):,} chars, {content.count(chr(10)):,} lines)")


if __name__ == "__main__":
    main()
