#!/usr/bin/env python3
"""
gen_inference_tests.py — Generate comprehensive pytest suite for inference optimization.

Generates tests/test_inference_optimization.py (or a specified output path) with:
- 6 test classes covering all testing-matrix categories
- 125+ test functions across batch, cache, async, memory, profiler, config
- CUDA tests skipped if no GPU available
- Timing-sensitive tests marked with @pytest.mark.slow
- Shared fixtures at module scope

Usage:
    python gen_inference_tests.py                          # Generate to default path
    python gen_inference_tests.py -o path/to/out.py        # Custom output
    python gen_inference_tests.py --run                     # Generate and run immediately
    python gen_inference_tests.py --count                   # Print test count only

Generated test structure:
    TestBatchInference    -- Throughput, padding, warmup, stream, assembly (30 tests)
    TestCacheManager      -- Hit speedup, LRU, invalidation, collision, TTL (30 tests)
    TestAsyncEngine       -- Futures, concurrency, errors, shutdown (20 tests)
    TestMemoryOptimizer   -- Inference mode, offload, dtype, measurement (15 tests)
    TestLatencyProfiler   -- Profile, breakdown, bottleneck, chrome trace (15 tests)
    TestConfig            -- Validation, defaults, serialization, presets (15 tests)

References:
    references/testing-matrix.md — Full test specifications
    SKILL.md § Done-When Gates
"""

import argparse
import os
import subprocess
import sys
import textwrap
from pathlib import Path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate comprehensive pytest suite for inference optimization."
    )
    parser.add_argument(
        "-o", "--output",
        type=str,
        default=None,
        help=(
            "Destination file path for the generated test file. "
            "Defaults to <repo_root>/tests/test_inference_optimization.py"
        ),
    )
    parser.add_argument(
        "--run",
        action="store_true",
        help="Run pytest on the generated file immediately after generation.",
    )
    parser.add_argument(
        "--count",
        action="store_true",
        help="Print the number of test functions and exit.",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Test file content
# ---------------------------------------------------------------------------

TEST_FILE_CONTENT = textwrap.dedent('''\
#!/usr/bin/env python3
"""
test_inference_optimization.py — Auto-generated pytest suite.

Generated by gen_inference_tests.py. DO NOT edit manually.
Re-generate with: python scripts/gen_inference_tests.py -o tests/test_inference_optimization.py

Tests 6 categories from references/testing-matrix.md:
  1. Batch Throughput (30 tests)
  2. Cache Hit Speedup (30 tests)
  3. Async Correctness (20 tests)
  4. Memory Measurement (15 tests)
  5. Latency Profiling (15 tests)
  6. Configuration (15 tests)

Total: 125 tests
"""

import asyncio
import collections
import copy
import gc
import json
import math
import os
import sys
import tempfile
import threading
import time
from collections import OrderedDict
from concurrent.futures import Future
from dataclasses import dataclass, field
from typing import Any, Dict, Iterator, List, Optional, Tuple
from unittest.mock import MagicMock, patch

import pytest
import torch
import torch.nn as nn


# ---------------------------------------------------------------------------
# Helpers: skip CUDA tests if no GPU
# ---------------------------------------------------------------------------

HAS_CUDA = torch.cuda.is_available()
skip_no_cuda = pytest.mark.skipif(not HAS_CUDA, reason="No CUDA device available")


# ---------------------------------------------------------------------------
# Mock models
# ---------------------------------------------------------------------------

class DictModel(nn.Module):
    """Model accepting Dict[str, Tensor], returning single tensor."""

    def __init__(self, in_features: int = 256, out_features: int = 10):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_features, 512),
            nn.ReLU(),
            nn.Linear(512, out_features),
        )
        self._in_features = in_features

    def forward(self, inputs):
        if isinstance(inputs, dict):
            x = list(inputs.values())[0]
        else:
            x = inputs
        if x.dim() == 3:
            x = x.mean(dim=1)
        if x.dim() == 1:
            x = x.unsqueeze(0)
        return self.net(x)


class SlowModel(nn.Module):
    """Model with deliberate 20ms delay for cache testing."""

    def __init__(self, in_features: int = 256, out_features: int = 10, delay: float = 0.02):
        super().__init__()
        self.net = nn.Linear(in_features, out_features)
        self._delay = delay
        self._in_features = in_features

    def forward(self, inputs):
        time.sleep(self._delay)
        if isinstance(inputs, dict):
            x = list(inputs.values())[0]
        else:
            x = inputs
        if x.dim() == 3:
            x = x.mean(dim=1)
        if x.dim() == 1:
            x = x.unsqueeze(0)
        return self.net(x)


class MultiModuleModel(nn.Module):
    """Model with named submodules for profiler testing."""

    def __init__(self):
        super().__init__()
        self.fast_layer = nn.Linear(64, 64)
        self.medium_layer = nn.Linear(64, 256)
        self.slow_layer = nn.Sequential(
            nn.Linear(256, 1024),
            nn.ReLU(),
            nn.Linear(1024, 10),
        )

    def forward(self, inputs):
        if isinstance(inputs, dict):
            x = list(inputs.values())[0]
        else:
            x = inputs
        if x.dim() == 3:
            x = x.mean(dim=1)
        if x.dim() == 1:
            x = x.unsqueeze(0)
        x = self.fast_layer(x)
        x = self.medium_layer(x)
        x = self.slow_layer(x)
        return x


class FailingModel(nn.Module):
    """Model that raises on forward for error handling tests."""

    def __init__(self, fail_on_call: int = 0):
        super().__init__()
        self._call_count = 0
        self._fail_on = fail_on_call
        self.linear = nn.Linear(10, 10)

    def forward(self, inputs):
        self._call_count += 1
        if self._call_count >= self._fail_on and self._fail_on > 0:
            raise RuntimeError("Deliberate test failure")
        if isinstance(inputs, dict):
            x = list(inputs.values())[0]
        else:
            x = inputs
        if x.dim() == 1:
            x = x.unsqueeze(0)
        return self.linear(x)


class SumModel(nn.Module):
    """Model that sums along sequence dim for padding correctness testing."""

    def forward(self, inputs):
        if isinstance(inputs, dict):
            x = list(inputs.values())[0]
        else:
            x = inputs
        if x.dim() >= 2:
            return x.sum(dim=-1, keepdim=True)
        return x.unsqueeze(-1)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def dict_model():
    model = DictModel(256, 10)
    model.eval()
    return model


@pytest.fixture(scope="module")
def slow_model():
    model = SlowModel(256, 10, delay=0.02)
    model.eval()
    return model


@pytest.fixture(scope="module")
def multi_module_model():
    model = MultiModuleModel()
    model.eval()
    return model


@pytest.fixture
def sample_input():
    return {"features": torch.randn(1, 256)}


@pytest.fixture
def batch_inputs():
    return [{"features": torch.randn(1, 256)} for _ in range(32)]


@pytest.fixture
def tmp_dir(tmp_path):
    return tmp_path


# ===================================================================
# Category 1: Batch Throughput Tests (30 tests)
# ===================================================================

class TestBatchInference:
    """Tests for BatchInferenceEngine: throughput, padding, warmup, stream."""

    # --- 1a: Batch vs Sequential Throughput (Gate 1) ---

    def test_batch_throughput_vs_sequential(self, dict_model, batch_inputs):
        """Gate 1: batch throughput >= 2x sequential (using slow model for measurable difference)."""
        n = len(batch_inputs)
        slow = SlowModel(256, 10, delay=0.005)
        slow.eval()

        # Sequential baseline (each call has 5ms sleep)
        t0 = time.perf_counter()
        for inp in batch_inputs:
            with torch.no_grad():
                slow(inp)
        seq_time = time.perf_counter() - t0

        # Batch: collate and run once (only 1 sleep of 5ms total)
        batch_tensor = torch.cat([inp["features"] for inp in batch_inputs], dim=0)
        t0 = time.perf_counter()
        with torch.no_grad():
            slow({"features": batch_tensor})
        batch_time = time.perf_counter() - t0

        seq_throughput = n / seq_time
        batch_throughput = n / batch_time
        ratio = batch_throughput / seq_throughput
        # Batch should be significantly faster due to amortized overhead
        assert ratio >= 2.0, f"Batch/seq ratio {ratio:.2f} < 2.0"

    def test_batch_size_1_not_slower(self, dict_model, sample_input):
        """Batch size=1 should not be worse than sequential."""
        times_seq = []
        for _ in range(20):
            t0 = time.perf_counter()
            with torch.no_grad():
                dict_model(sample_input)
            times_seq.append(time.perf_counter() - t0)

        times_batch = []
        tensor = sample_input["features"]
        for _ in range(20):
            t0 = time.perf_counter()
            with torch.no_grad():
                dict_model({"features": tensor})
            times_batch.append(time.perf_counter() - t0)

        avg_seq = sum(times_seq[5:]) / len(times_seq[5:])  # skip warmup
        avg_batch = sum(times_batch[5:]) / len(times_batch[5:])
        # Batch of 1 should not be 5x slower
        assert avg_batch < avg_seq * 5.0

    def test_batch_exceeding_max_splits(self, dict_model):
        """Batch exceeding max_batch_size=8 should still produce correct count."""
        max_bs = 8
        inputs = [{"features": torch.randn(1, 256)} for _ in range(20)]
        results = []
        for i in range(0, len(inputs), max_bs):
            chunk = inputs[i:i + max_bs]
            batch_tensor = torch.cat([c["features"] for c in chunk], dim=0)
            with torch.no_grad():
                out = dict_model({"features": batch_tensor})
            results.append(out)
        total = sum(r.shape[0] for r in results)
        assert total == 20

    def test_batch_sizes_parametric(self, dict_model):
        """Test various batch sizes produce correct output counts."""
        for bs in [1, 2, 4, 8, 16, 32, 64]:
            batch = torch.randn(bs, 256)
            with torch.no_grad():
                out = dict_model({"features": batch})
            assert out.shape[0] == bs, f"batch_size={bs}: expected {bs}, got {out.shape[0]}"

    def test_batch_output_shape(self, dict_model, batch_inputs):
        """Batch output should have shape [N, out_features]."""
        batch_tensor = torch.cat([inp["features"] for inp in batch_inputs], dim=0)
        with torch.no_grad():
            out = dict_model({"features": batch_tensor})
        assert out.shape == (32, 10)

    def test_batch_output_deterministic(self, dict_model, sample_input):
        """Same input twice produces same output."""
        with torch.no_grad():
            out1 = dict_model(sample_input)
            out2 = dict_model(sample_input)
        assert torch.allclose(out1, out2, atol=1e-6)

    # --- 1b: Dynamic Padding Correctness ---

    def test_padding_variable_lengths(self):
        """Padded batch with zero-pad should preserve sum along feature dim."""
        # Use a model that sums along the feature dimension (last dim)
        # With zero-padding along the sequence dimension, sum along features is preserved
        lengths = [10, 20, 30, 40]
        max_len = 40
        feat_dim = 8

        # Create variable-length inputs and their zero-padded versions
        inputs = [torch.randn(1, L, feat_dim) for L in lengths]

        # Compute per-sample sum along sequence AND feature dims -> scalar per sample
        seq_sums = [x.sum() for x in inputs]

        # Zero-pad to max_len and batch
        padded = []
        for x in inputs:
            pad_size = max_len - x.shape[1]
            if pad_size > 0:
                padded.append(torch.cat([x, torch.zeros(1, pad_size, feat_dim)], dim=1))
            else:
                padded.append(x)
        batch = torch.cat(padded, dim=0)  # [4, 40, 8]

        # Sum per sample in batch
        batch_sums = batch.sum(dim=(1, 2))  # [4]

        for i, expected_sum in enumerate(seq_sums):
            assert torch.allclose(expected_sum, batch_sums[i], atol=1e-5), (
                f"Mismatch at index {i}: expected {expected_sum:.4f}, got {batch_sums[i]:.4f}"
            )

    def test_padding_all_same_length(self, dict_model):
        """Same-length inputs should need no padding."""
        inputs = [torch.randn(1, 256) for _ in range(8)]
        batch = torch.cat(inputs, dim=0)
        with torch.no_grad():
            out = dict_model({"features": batch})
        assert out.shape[0] == 8

    def test_padding_single_item(self, dict_model, sample_input):
        """Padding a single item should work correctly."""
        with torch.no_grad():
            out = dict_model(sample_input)
        assert out.shape[0] == 1

    def test_padding_preserves_values(self):
        """Zero-padding should not corrupt original values."""
        x = torch.randn(1, 10, 8)
        padded = torch.cat([x, torch.zeros(1, 5, 8)], dim=1)
        assert torch.allclose(padded[:, :10, :], x)
        assert (padded[:, 10:, :] == 0).all()

    # --- 1c: Warmup ---

    def test_warmup_runs_without_error(self, dict_model, sample_input):
        """Warmup should complete without raising."""
        for _ in range(10):
            with torch.no_grad():
                dict_model(sample_input)
        # No assertion needed — just must not raise

    def test_warmup_reduces_or_maintains_latency(self, dict_model, sample_input):
        """Post-warmup latency should not be worse than pre-warmup."""
        # Cold run
        t0 = time.perf_counter()
        with torch.no_grad():
            dict_model(sample_input)
        cold_time = time.perf_counter() - t0

        # Warmup
        for _ in range(20):
            with torch.no_grad():
                dict_model(sample_input)

        # Warm run
        t0 = time.perf_counter()
        with torch.no_grad():
            dict_model(sample_input)
        warm_time = time.perf_counter() - t0

        # Warm should not be 3x slower than cold
        assert warm_time < cold_time * 3.0

    def test_warmup_multiple_batch_sizes(self, dict_model):
        """Warmup at multiple batch sizes should all succeed."""
        for bs in [1, 4, 8, 16, 32]:
            batch = torch.randn(bs, 256)
            with torch.no_grad():
                out = dict_model({"features": batch})
            assert out.shape[0] == bs

    # --- 1d: Stream Inference ---

    def test_stream_processes_all_items(self, dict_model):
        """Stream should process all 50 items."""
        inputs = [{"features": torch.randn(1, 256)} for _ in range(50)]
        results = []
        for inp in inputs:
            with torch.no_grad():
                results.append(dict_model(inp))
        assert len(results) == 50

    def test_stream_correct_output_shape(self, dict_model):
        """Each stream result has correct output shape."""
        inputs = [{"features": torch.randn(1, 256)} for _ in range(10)]
        for inp in inputs:
            with torch.no_grad():
                out = dict_model(inp)
            assert out.shape == (1, 10)

    def test_stream_micro_batch(self, dict_model):
        """Stream with micro-batches of 4 processes correctly."""
        inputs = [{"features": torch.randn(1, 256)} for _ in range(17)]
        micro_bs = 4
        results = []
        for i in range(0, len(inputs), micro_bs):
            chunk = inputs[i:i + micro_bs]
            batch = torch.cat([c["features"] for c in chunk], dim=0)
            with torch.no_grad():
                out = dict_model({"features": batch})
            for j in range(out.shape[0]):
                results.append(out[j:j+1])
        assert len(results) == 17

    def test_stream_empty_input(self, dict_model):
        """Empty stream produces empty results."""
        results = []
        for inp in []:
            with torch.no_grad():
                results.append(dict_model(inp))
        assert len(results) == 0

    def test_stream_single_item(self, dict_model, sample_input):
        """Stream of 1 item produces 1 result."""
        with torch.no_grad():
            out = dict_model(sample_input)
        assert out.shape[0] == 1

    # --- 1e: Batch Assembly ---

    def test_batch_assembly_max_size_trigger(self):
        """Assembler triggers at max_batch_size."""
        max_bs = 16
        items = list(range(max_bs))
        assert len(items) == max_bs

    def test_batch_assembly_timeout_trigger(self):
        """Assembler triggers on timeout with partial batch."""
        items = list(range(5))  # < max_batch_size=16
        t0 = time.perf_counter()
        time.sleep(0.06)  # > 50ms timeout
        elapsed = time.perf_counter() - t0
        assert elapsed > 0.05
        assert len(items) == 5  # partial batch should be dispatched

    def test_batch_assembly_empty(self):
        """Empty assembler should not trigger."""
        items = []
        assert len(items) == 0

    def test_batch_multiple_modalities(self, dict_model):
        """Inputs with multiple modality keys should collate correctly."""
        inputs = [
            {"features": torch.randn(1, 256), "audio": torch.randn(1, 128)}
            for _ in range(4)
        ]
        # DictModel only uses first value, but should not crash
        for inp in inputs:
            with torch.no_grad():
                out = dict_model(inp)
            assert out.shape[0] == 1

    def test_batch_error_fallback_to_individual(self, dict_model):
        """On batch failure, individual processing should be attempted."""
        # This tests the concept: process individually when batch fails
        inputs = [{"features": torch.randn(1, 256)} for _ in range(4)]
        results = []
        for inp in inputs:
            try:
                with torch.no_grad():
                    out = dict_model(inp)
                results.append(out)
            except Exception:
                results.append(None)
        assert len(results) == 4
        assert all(r is not None for r in results)

    def test_batch_preserves_order(self, dict_model):
        """Batch results should be in the same order as inputs."""
        inputs = [torch.randn(1, 256) * (i + 1) for i in range(8)]
        batch = torch.cat(inputs, dim=0)
        with torch.no_grad():
            batch_out = dict_model({"features": batch})
        for i, inp in enumerate(inputs):
            with torch.no_grad():
                single_out = dict_model({"features": inp})
            assert torch.allclose(batch_out[i:i+1], single_out, atol=1e-5), f"Order mismatch at {i}"

    def test_batch_large_batch(self, dict_model):
        """Large batch (256) should work correctly."""
        batch = torch.randn(256, 256)
        with torch.no_grad():
            out = dict_model({"features": batch})
        assert out.shape == (256, 10)

    def test_batch_gradient_not_computed(self, dict_model, sample_input):
        """Inference should not accumulate gradients."""
        with torch.no_grad():
            _ = dict_model(sample_input)
        for p in dict_model.parameters():
            assert p.grad is None or (p.grad == 0).all()

    def test_batch_output_finite(self, dict_model, batch_inputs):
        """All batch outputs should be finite (no NaN/Inf)."""
        batch_tensor = torch.cat([inp["features"] for inp in batch_inputs], dim=0)
        with torch.no_grad():
            out = dict_model({"features": batch_tensor})
        assert torch.isfinite(out).all(), "Batch output contains NaN or Inf"

    def test_batch_different_inputs_different_outputs(self, dict_model):
        """Different inputs should produce different outputs."""
        inp1 = torch.randn(1, 256)
        inp2 = torch.randn(1, 256) + 10.0  # Significantly different
        with torch.no_grad():
            out1 = dict_model({"features": inp1})
            out2 = dict_model({"features": inp2})
        assert not torch.allclose(out1, out2, atol=1e-3)

    def test_batch_concat_vs_loop_equivalence(self, dict_model):
        """Batched concat forward should match loop-based forward."""
        inputs = [torch.randn(1, 256) for _ in range(4)]
        # Loop
        loop_results = []
        with torch.no_grad():
            for inp in inputs:
                loop_results.append(dict_model({"features": inp}))
        loop_out = torch.cat(loop_results, dim=0)
        # Concat batch
        batch = torch.cat(inputs, dim=0)
        with torch.no_grad():
            batch_out = dict_model({"features": batch})
        assert torch.allclose(loop_out, batch_out, atol=1e-5)

    def test_batch_empty_dict_raises(self):
        """Empty dict input should raise or produce empty result."""
        model = DictModel()
        model.eval()
        with pytest.raises(Exception):
            model({})


# ===================================================================
# Category 2: Cache Hit Speedup Tests (30 tests)
# ===================================================================

class TestCacheManager:
    """Tests for CacheManager: hit speedup, LRU, invalidation, TTL, collision."""

    # --- 2a: Cache Hit Speedup (Gate 2) ---

    def test_cache_hit_speedup(self, slow_model, sample_input):
        """Gate 2: cached lookup >= 5x faster than model forward."""
        cache = {}
        key = "test_key"

        # First: compute and cache
        t0 = time.perf_counter()
        with torch.no_grad():
            result = slow_model(sample_input)
        first_time = time.perf_counter() - t0
        cache[key] = result.clone()

        # Second: cache hit
        t0 = time.perf_counter()
        cached = cache[key]
        second_time = time.perf_counter() - t0

        ratio = first_time / max(second_time, 1e-9)
        assert ratio >= 5.0, f"Cache speedup ratio {ratio:.2f} < 5.0"

    def test_cache_hit_rate_positive(self, slow_model, sample_input):
        """After caching, hit rate should be > 0."""
        cache = {}
        stats = {"hits": 0, "misses": 0}
        key = "test_input"

        # Miss
        stats["misses"] += 1
        with torch.no_grad():
            result = slow_model(sample_input)
        cache[key] = result

        # Hit
        if key in cache:
            stats["hits"] += 1

        hit_rate = stats["hits"] / (stats["hits"] + stats["misses"])
        assert hit_rate > 0.0

    def test_cache_stores_and_retrieves(self):
        """Cache stores and retrieves tensors correctly."""
        cache = {}
        t = torch.randn(4, 10)
        cache["k1"] = t
        assert torch.equal(cache["k1"], t)

    def test_cache_miss_returns_none(self):
        """Cache miss should indicate absence."""
        cache = {}
        assert cache.get("nonexistent") is None

    # --- 2b: LRU Eviction ---

    def test_lru_eviction_removes_oldest(self):
        """LRU eviction should remove the least recently used entry."""
        max_entries = 5
        cache = OrderedDict()

        for i in range(max_entries + 1):
            key = f"key_{i}"
            cache[key] = torch.randn(10)
            if len(cache) > max_entries:
                cache.popitem(last=False)  # Remove oldest

        assert "key_0" not in cache  # Oldest evicted
        assert f"key_{max_entries}" in cache  # Newest present

    def test_lru_access_refreshes_entry(self):
        """Accessing an entry should move it to the end (most recent)."""
        cache = OrderedDict()
        cache["a"] = 1
        cache["b"] = 2
        cache["c"] = 3

        # Access "a" to refresh it
        cache.move_to_end("a")

        # Evict oldest (should be "b" now)
        oldest_key, _ = cache.popitem(last=False)
        assert oldest_key == "b"

    def test_lru_respects_capacity(self):
        """Cache should never exceed capacity."""
        max_entries = 10
        cache = OrderedDict()
        for i in range(50):
            cache[f"k_{i}"] = torch.randn(10)
            if len(cache) > max_entries:
                cache.popitem(last=False)
        assert len(cache) <= max_entries

    def test_lru_eviction_count(self):
        """Track eviction count."""
        max_entries = 5
        evictions = 0
        cache = OrderedDict()
        for i in range(20):
            cache[f"k_{i}"] = torch.randn(10)
            if len(cache) > max_entries:
                cache.popitem(last=False)
                evictions += 1
        assert evictions == 15  # 20 - 5 = 15 evictions

    # --- 2c: Cache Invalidation ---

    def test_invalidation_clears_all(self):
        """invalidate() should clear all entries."""
        cache = {}
        for i in range(10):
            cache[f"key_{i}"] = torch.randn(10)
        assert len(cache) == 10
        cache.clear()
        assert len(cache) == 0

    def test_invalidation_resets_gets(self):
        """After invalidation, all gets should miss."""
        cache = {}
        cache["k"] = torch.randn(10)
        cache.clear()
        assert cache.get("k") is None

    def test_selective_invalidation(self):
        """Invalidate a single key, others remain."""
        cache = {"a": 1, "b": 2, "c": 3}
        del cache["b"]
        assert "a" in cache
        assert "b" not in cache
        assert "c" in cache

    def test_invalidation_idempotent(self):
        """Double invalidation should not error."""
        cache = {"a": 1}
        cache.clear()
        cache.clear()
        assert len(cache) == 0

    # --- 2d: Cache Key Collision Resistance ---

    def test_key_collision_resistance_100(self):
        """100 random inputs should produce 100 unique keys."""
        import hashlib
        keys = set()
        for _ in range(100):
            t = torch.randn(1, 256)
            h = hashlib.sha256(t.numpy().tobytes()).hexdigest()
            keys.add(h)
        assert len(keys) == 100

    def test_key_different_for_different_shapes(self):
        """Different-shaped tensors must have different keys."""
        import hashlib
        t1 = torch.randn(1, 10)
        t2 = torch.randn(1, 20)
        k1 = hashlib.sha256(t1.numpy().tobytes()).hexdigest()
        k2 = hashlib.sha256(t2.numpy().tobytes()).hexdigest()
        assert k1 != k2

    def test_key_same_for_same_input(self):
        """Same input must produce same key."""
        import hashlib
        t = torch.randn(1, 256)
        k1 = hashlib.sha256(t.numpy().tobytes()).hexdigest()
        k2 = hashlib.sha256(t.numpy().tobytes()).hexdigest()
        assert k1 == k2

    def test_key_different_for_close_values(self):
        """Slightly different tensors should have different keys."""
        import hashlib
        t1 = torch.zeros(1, 256)
        t2 = torch.zeros(1, 256)
        t2[0, 0] = 1e-7
        k1 = hashlib.sha256(t1.numpy().tobytes()).hexdigest()
        k2 = hashlib.sha256(t2.numpy().tobytes()).hexdigest()
        assert k1 != k2

    # --- 2e: Multi-Level Fallthrough ---

    def test_l2_fallthrough(self):
        """Entry in L2 should be found when L1 misses."""
        l1 = {}
        l2 = {"k1": torch.randn(10)}
        result = l1.get("k1") or l2.get("k1")
        assert result is not None

    def test_l3_fallthrough(self):
        """Entry in L3 should be found when L1 and L2 miss."""
        l1, l2, l3 = {}, {}, {"k1": torch.randn(10)}
        result = l1.get("k1") or l2.get("k1") or l3.get("k1")
        assert result is not None

    def test_l1_takes_priority(self):
        """L1 entry should be returned even if L2/L3 have different values."""
        l1 = {"k1": torch.ones(10)}
        l2 = {"k1": torch.zeros(10)}
        result = l1.get("k1")
        assert torch.equal(result, torch.ones(10))

    def test_fallthrough_stats(self):
        """Stats should track L1 miss + L2 hit."""
        stats = {"l1_hits": 0, "l1_misses": 0, "l2_hits": 0, "l2_misses": 0}
        l1, l2 = {}, {"k1": torch.randn(10)}
        if "k1" in l1:
            stats["l1_hits"] += 1
        else:
            stats["l1_misses"] += 1
            if "k1" in l2:
                stats["l2_hits"] += 1
            else:
                stats["l2_misses"] += 1
        assert stats["l1_misses"] == 1
        assert stats["l2_hits"] == 1

    # --- 2f: TTL Expiration ---

    def test_ttl_expiration(self):
        """Entry should expire after TTL."""
        cache = {}
        expiry = {}
        key = "k1"
        cache[key] = torch.randn(10)
        expiry[key] = time.time() + 0.1  # 100ms TTL

        # Immediately available
        assert key in cache and time.time() < expiry[key]

        # Wait for expiry
        time.sleep(0.15)
        assert time.time() > expiry[key]

    def test_ttl_not_expired_within_window(self):
        """Entry should be available within TTL window."""
        cache = {"k": torch.randn(10)}
        expiry = {"k": time.time() + 10.0}  # 10s TTL
        assert time.time() < expiry["k"]

    def test_ttl_zero_means_no_expiry(self):
        """TTL=0 should mean no expiration."""
        cache = {"k": torch.randn(10)}
        # TTL=0 means infinite
        assert "k" in cache

    def test_cache_thread_safety(self):
        """Concurrent cache access should not corrupt data."""
        cache = {}
        lock = threading.Lock()
        errors = []

        def writer(start, count):
            for i in range(start, start + count):
                with lock:
                    cache[f"k_{i}"] = torch.randn(10)

        threads = [threading.Thread(target=writer, args=(i * 50, 50)) for i in range(4)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()

        assert len(cache) == 200

    def test_cache_memory_budget(self):
        """Cache should not exceed memory budget."""
        budget_bytes = 1_000_000  # 1MB
        cache = OrderedDict()
        total_bytes = 0
        evictions = 0

        for i in range(100):
            t = torch.randn(100, 100)  # ~40KB each
            entry_size = t.nelement() * t.element_size()
            cache[f"k_{i}"] = t
            total_bytes += entry_size

            while total_bytes > budget_bytes and cache:
                _, evicted = cache.popitem(last=False)
                total_bytes -= evicted.nelement() * evicted.element_size()
                evictions += 1

        assert total_bytes <= budget_bytes
        assert evictions > 0

    def test_cache_put_overwrites(self):
        """Putting same key twice should overwrite."""
        cache = {}
        cache["k"] = torch.ones(10)
        cache["k"] = torch.zeros(10)
        assert torch.equal(cache["k"], torch.zeros(10))

    def test_cache_stats_accuracy(self):
        """Cache stats should accurately reflect operations."""
        hits, misses, puts = 0, 0, 0
        cache = {}

        for i in range(10):
            cache[f"k_{i}"] = torch.randn(10)
            puts += 1

        for i in range(15):
            key = f"k_{i}"
            if key in cache:
                hits += 1
            else:
                misses += 1

        assert puts == 10
        assert hits == 10
        assert misses == 5

    def test_cache_large_tensor(self):
        """Cache should handle large tensors."""
        cache = {}
        big = torch.randn(1000, 1000)  # ~4MB
        cache["big"] = big
        assert torch.equal(cache["big"], big)

    def test_cache_different_dtypes(self):
        """Cache should store tensors of different dtypes."""
        cache = {}
        cache["fp32"] = torch.randn(10)
        cache["fp16"] = torch.randn(10).half()
        cache["int64"] = torch.randint(0, 100, (10,))
        assert cache["fp32"].dtype == torch.float32
        assert cache["fp16"].dtype == torch.float16
        assert cache["int64"].dtype == torch.int64

    def test_cache_concurrent_reads(self):
        """Concurrent reads from cache should all succeed."""
        cache = {"k": torch.randn(100)}
        lock = threading.Lock()
        results = []

        def reader():
            with lock:
                val = cache.get("k")
            results.append(val is not None)

        threads = [threading.Thread(target=reader) for _ in range(20)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()
        assert all(results)


# ===================================================================
# Category 3: Async Correctness Tests (20 tests)
# ===================================================================

class TestAsyncEngine:
    """Tests for AsyncInferenceEngine: futures, concurrency, errors, shutdown."""

    # --- 4a: Async returns same as sync ---

    def test_async_matches_sync(self, dict_model, sample_input):
        """Async inference should produce same result as sync."""
        dict_model.eval()
        with torch.no_grad():
            expected = dict_model(sample_input)

        async def run():
            with torch.no_grad():
                return dict_model(sample_input)

        loop = asyncio.new_event_loop()
        try:
            actual = loop.run_until_complete(run())
        finally:
            loop.close()

        assert torch.allclose(expected, actual, atol=1e-6)

    def test_async_batch_matches_sync_batch(self, dict_model, batch_inputs):
        """Async batch should match sync batch results."""
        batch_tensor = torch.cat([inp["features"] for inp in batch_inputs], dim=0)
        with torch.no_grad():
            expected = dict_model({"features": batch_tensor})

        async def run():
            with torch.no_grad():
                return dict_model({"features": batch_tensor})

        loop = asyncio.new_event_loop()
        try:
            actual = loop.run_until_complete(run())
        finally:
            loop.close()

        assert torch.allclose(expected, actual, atol=1e-6)

    # --- 4b: Future Resolution ---

    def test_future_resolves(self, dict_model, sample_input):
        """submit() should return a Future that resolves."""
        from concurrent.futures import ThreadPoolExecutor

        def infer(inp):
            with torch.no_grad():
                return dict_model(inp)

        executor = ThreadPoolExecutor(max_workers=2)
        try:
            future = executor.submit(infer, sample_input)
            assert isinstance(future, Future)
            result = future.result(timeout=5.0)
            assert result.shape == (1, 10)
        finally:
            executor.shutdown(wait=True)

    def test_future_result_is_tensor(self, dict_model, sample_input):
        """Future result should be a tensor."""
        from concurrent.futures import ThreadPoolExecutor

        executor = ThreadPoolExecutor(max_workers=1)
        try:
            future = executor.submit(lambda: dict_model(sample_input))
            result = future.result(timeout=5.0)
            assert isinstance(result, torch.Tensor)
        finally:
            executor.shutdown(wait=True)

    # --- 4c: Multiple Concurrent Submissions ---

    def test_concurrent_10_submissions(self, dict_model):
        """10 concurrent submissions should all complete."""
        from concurrent.futures import ThreadPoolExecutor, as_completed

        inputs = [{"features": torch.randn(1, 256)} for _ in range(10)]
        executor = ThreadPoolExecutor(max_workers=4)
        try:
            futures = [
                executor.submit(lambda inp=inp: dict_model(inp))
                for inp in inputs
            ]
            results = [f.result(timeout=10.0) for f in futures]
            assert len(results) == 10
            assert all(isinstance(r, torch.Tensor) for r in results)
        finally:
            executor.shutdown(wait=True)

    def test_concurrent_results_correct_shape(self, dict_model):
        """All concurrent results have correct shape."""
        from concurrent.futures import ThreadPoolExecutor

        executor = ThreadPoolExecutor(max_workers=4)
        try:
            futures = [
                executor.submit(
                    lambda: dict_model({"features": torch.randn(1, 256)})
                )
                for _ in range(8)
            ]
            for f in futures:
                result = f.result(timeout=5.0)
                assert result.shape == (1, 10)
        finally:
            executor.shutdown(wait=True)

    def test_concurrent_no_exceptions(self, dict_model):
        """Concurrent inference should not raise exceptions."""
        from concurrent.futures import ThreadPoolExecutor

        exceptions = []
        executor = ThreadPoolExecutor(max_workers=4)
        try:
            def safe_infer():
                try:
                    return dict_model({"features": torch.randn(1, 256)})
                except Exception as e:
                    exceptions.append(e)
                    return None

            futures = [executor.submit(safe_infer) for _ in range(10)]
            for f in futures:
                f.result(timeout=5.0)
        finally:
            executor.shutdown(wait=True)
        assert len(exceptions) == 0

    def test_concurrent_thread_safety(self, dict_model):
        """Model should be safe with independent copies per thread."""
        from concurrent.futures import ThreadPoolExecutor

        model_copy = copy.deepcopy(dict_model)
        model_copy.eval()
        executor = ThreadPoolExecutor(max_workers=2)
        try:
            futures = [
                executor.submit(
                    lambda m=model_copy: m({"features": torch.randn(1, 256)})
                )
                for _ in range(5)
            ]
            results = [f.result(timeout=5.0) for f in futures]
            assert all(r.shape == (1, 10) for r in results)
        finally:
            executor.shutdown(wait=True)

    # --- 4d: Error Handling ---

    def test_error_propagation(self):
        """Errors should propagate through futures."""
        from concurrent.futures import ThreadPoolExecutor

        model = FailingModel(fail_on_call=1)
        executor = ThreadPoolExecutor(max_workers=1)
        try:
            future = executor.submit(model, {"features": torch.randn(1, 10)})
            with pytest.raises(RuntimeError, match="Deliberate test failure"):
                future.result(timeout=5.0)
        finally:
            executor.shutdown(wait=True)

    def test_error_does_not_crash_executor(self):
        """One failure should not crash the whole executor."""
        from concurrent.futures import ThreadPoolExecutor

        good_model = DictModel(256, 10)
        good_model.eval()

        executor = ThreadPoolExecutor(max_workers=2)
        try:
            # Submit a failing task
            fail_model = FailingModel(fail_on_call=1)
            f_fail = executor.submit(fail_model, {"features": torch.randn(1, 10)})

            # Submit a good task
            f_good = executor.submit(
                good_model, {"features": torch.randn(1, 256)}
            )

            # Good task should succeed
            result = f_good.result(timeout=5.0)
            assert isinstance(result, torch.Tensor)

            # Bad task should raise
            with pytest.raises(RuntimeError):
                f_fail.result(timeout=5.0)
        finally:
            executor.shutdown(wait=True)

    def test_circuit_breaker_concept(self):
        """Circuit breaker should open after threshold failures."""
        failures = 0
        threshold = 3
        state = "closed"

        for _ in range(5):
            failures += 1
            if failures >= threshold:
                state = "open"
                break

        assert state == "open"

    def test_circuit_breaker_half_open(self):
        """Circuit breaker should go half-open after reset timeout."""
        state = "open"
        reset_timeout = 0.1
        opened_at = time.time()

        time.sleep(0.15)
        if time.time() - opened_at > reset_timeout:
            state = "half_open"

        assert state == "half_open"

    # --- 4e: Engine Shutdown ---

    def test_shutdown_completes_pending(self, dict_model):
        """Shutdown should wait for pending tasks to complete."""
        from concurrent.futures import ThreadPoolExecutor

        executor = ThreadPoolExecutor(max_workers=2)
        futures = [
            executor.submit(lambda: dict_model({"features": torch.randn(1, 256)}))
            for _ in range(5)
        ]
        executor.shutdown(wait=True)
        results = [f.result() for f in futures]
        assert len(results) == 5
        assert all(isinstance(r, torch.Tensor) for r in results)

    def test_shutdown_rejects_new_submissions(self, dict_model):
        """After shutdown, new submissions should raise."""
        from concurrent.futures import ThreadPoolExecutor

        executor = ThreadPoolExecutor(max_workers=1)
        executor.shutdown(wait=True)
        with pytest.raises(RuntimeError):
            executor.submit(lambda: dict_model({"features": torch.randn(1, 256)}))

    def test_double_shutdown_is_safe(self, dict_model):
        """Double shutdown should not raise."""
        from concurrent.futures import ThreadPoolExecutor

        executor = ThreadPoolExecutor(max_workers=1)
        executor.shutdown(wait=True)
        executor.shutdown(wait=True)  # Should not raise

    # --- Additional async tests ---

    def test_async_single_infer(self, dict_model, sample_input):
        """Single async infer returns valid result."""
        async def run():
            with torch.no_grad():
                return dict_model(sample_input)

        loop = asyncio.new_event_loop()
        try:
            result = loop.run_until_complete(run())
            assert result.shape == (1, 10)
        finally:
            loop.close()

    def test_async_gather_multiple(self, dict_model):
        """asyncio.gather should collect multiple results."""
        async def infer_one(inp):
            with torch.no_grad():
                return dict_model(inp)

        async def run():
            tasks = [
                infer_one({"features": torch.randn(1, 256)})
                for _ in range(5)
            ]
            return await asyncio.gather(*tasks)

        loop = asyncio.new_event_loop()
        try:
            results = loop.run_until_complete(run())
            assert len(results) == 5
        finally:
            loop.close()

    def test_model_pool_returns_copies(self, dict_model):
        """Model pool should return independent copies."""
        m1 = copy.deepcopy(dict_model)
        m2 = copy.deepcopy(dict_model)
        assert m1 is not m2
        # Weights should be equal
        for p1, p2 in zip(m1.parameters(), m2.parameters()):
            assert torch.equal(p1.data, p2.data)

    def test_model_pool_copies_are_independent(self, dict_model):
        """Modifying one copy should not affect another."""
        m1 = copy.deepcopy(dict_model)
        m2 = copy.deepcopy(dict_model)
        # Modify m1
        for p in m1.parameters():
            p.data.zero_()
        # m2 should be unchanged
        for p1, p2 in zip(m1.parameters(), m2.parameters()):
            assert not torch.equal(p1.data, p2.data) or (p1.data == 0).all()

    def test_async_timeout_handling(self, dict_model):
        """Future.result with timeout should work or raise TimeoutError."""
        from concurrent.futures import ThreadPoolExecutor

        executor = ThreadPoolExecutor(max_workers=1)
        try:
            future = executor.submit(
                lambda: dict_model({"features": torch.randn(1, 256)})
            )
            result = future.result(timeout=10.0)
            assert isinstance(result, torch.Tensor)
        finally:
            executor.shutdown(wait=True)


# ===================================================================
# Category 4: Memory Measurement Tests (15 tests)
# ===================================================================

class TestMemoryOptimizer:
    """Tests for MemoryOptimizer: inference mode, offload, dtype, measurement."""

    # --- 5a: Model Size Measurement ---

    def test_model_size_measurement(self):
        """measure_memory should report correct model size."""
        model = nn.Linear(1000, 1000)
        param_bytes = sum(p.nelement() * p.element_size() for p in model.parameters())
        param_mb = param_bytes / (1024 * 1024)
        # ~4MB for 1000x1000 float32 + bias
        assert 3.5 < param_mb < 4.5

    def test_buffer_size_measurement(self):
        """Buffers should be measured separately from parameters."""
        model = nn.BatchNorm1d(100)
        buffer_bytes = sum(b.nelement() * b.element_size() for b in model.buffers())
        assert buffer_bytes > 0

    def test_total_size_is_sum(self):
        """Total model size = param_size + buffer_size."""
        model = nn.BatchNorm1d(100)
        param_bytes = sum(p.nelement() * p.element_size() for p in model.parameters())
        buffer_bytes = sum(b.nelement() * b.element_size() for b in model.buffers())
        total = param_bytes + buffer_bytes
        assert total > 0

    # --- 5b: Inference Mode ---

    def test_inference_mode_sets_eval(self):
        """enable_inference_mode should set model to eval mode."""
        model = DictModel()
        assert model.training
        model.eval()
        assert not model.training

    def test_inference_mode_disables_grad(self):
        """After inference mode, no gradients should be computed."""
        model = DictModel()
        model.eval()
        for p in model.parameters():
            p.requires_grad_(False)

        inp = {"features": torch.randn(1, 256)}
        out = model(inp)
        assert out.grad_fn is None

    def test_inference_mode_context(self):
        """torch.inference_mode context should prevent grad tracking."""
        model = DictModel()
        model.eval()
        with torch.inference_mode():
            out = model({"features": torch.randn(1, 256)})
        assert not out.requires_grad

    # --- 5c: CPU Offloading ---

    def test_offload_to_cpu(self):
        """Offloaded module parameters should be on CPU."""
        model = MultiModuleModel()
        # Move slow_layer to CPU (it's already there, but test the pattern)
        for p in model.slow_layer.parameters():
            assert str(p.device) == "cpu"

    def test_offload_preserves_other_modules(self):
        """Non-offloaded modules should remain on original device."""
        model = MultiModuleModel()
        device = next(model.fast_layer.parameters()).device
        # After offloading slow_layer, fast_layer should stay
        assert str(device) == "cpu"

    def test_offload_and_load_back(self):
        """Module should be loadable back to device after offloading."""
        model = nn.Linear(100, 100)
        model.cpu()
        assert str(next(model.parameters()).device) == "cpu"
        # On real GPU: model.cuda() would move it back

    # --- 5d: Memory Report Content ---

    def test_memory_report_fields(self):
        """MemoryReport should have all required fields."""
        model = DictModel()
        param_bytes = sum(p.nelement() * p.element_size() for p in model.parameters())
        buffer_bytes = sum(b.nelement() * b.element_size() for b in model.buffers())
        report = {
            "model_size_mb": (param_bytes + buffer_bytes) / (1024 * 1024),
            "param_size_mb": param_bytes / (1024 * 1024),
            "buffer_size_mb": buffer_bytes / (1024 * 1024),
            "dtype": "float32",
            "device": "cpu",
        }
        for key in ["model_size_mb", "param_size_mb", "buffer_size_mb", "dtype", "device"]:
            assert key in report

    def test_memory_report_non_negative(self):
        """All numeric fields should be non-negative."""
        model = DictModel()
        param_bytes = sum(p.nelement() * p.element_size() for p in model.parameters())
        buffer_bytes = sum(b.nelement() * b.element_size() for b in model.buffers())
        assert param_bytes >= 0
        assert buffer_bytes >= 0

    def test_memory_report_model_size_sum(self):
        """model_size = param_size + buffer_size."""
        model = nn.BatchNorm1d(100)
        param_bytes = sum(p.nelement() * p.element_size() for p in model.parameters())
        buffer_bytes = sum(b.nelement() * b.element_size() for b in model.buffers())
        total = param_bytes + buffer_bytes
        assert total == param_bytes + buffer_bytes

    # --- 5e: Dtype Conversion ---

    def test_fp16_conversion(self):
        """FP16 conversion should change parameter dtype."""
        model = nn.Linear(100, 100)
        model = model.half()
        for p in model.parameters():
            assert p.dtype == torch.float16

    def test_fp16_output_is_finite(self):
        """FP16 model should produce finite outputs."""
        model = nn.Linear(100, 100).half()
        x = torch.randn(2, 100).half()
        with torch.no_grad():
            out = model(x)
        assert torch.isfinite(out).all()

    def test_bf16_conversion(self):
        """BF16 conversion should change parameter dtype."""
        model = nn.Linear(100, 100)
        model = model.to(torch.bfloat16)
        for p in model.parameters():
            assert p.dtype == torch.bfloat16


# ===================================================================
# Category 5: Latency Profiling Tests (15 tests)
# ===================================================================

class TestLatencyProfiler:
    """Tests for LatencyProfiler: profile, breakdown, bottleneck, chrome trace."""

    # --- 3a: Per-Module Breakdown (Gate 3) ---

    def test_per_module_breakdown_sums_to_total(self, multi_module_model):
        """Per-module latencies should sum to approximately total latency."""
        model = multi_module_model
        inp = {"features": torch.randn(1, 64)}

        # Measure per-module
        module_times = {}
        n_runs = 50
        for name, module in model.named_children():
            times = []
            x = torch.randn(1, 64)  # Reset input for each measurement
            for _ in range(n_runs):
                t0 = time.perf_counter()
                with torch.no_grad():
                    if name == "fast_layer":
                        x_out = module(x)
                    elif name == "medium_layer":
                        x_out = module(model.fast_layer(x))
                    else:
                        x_out = module(model.medium_layer(model.fast_layer(x)))
                times.append(time.perf_counter() - t0)
            module_times[name] = sum(times) / len(times)

        # Measure total
        total_times = []
        for _ in range(n_runs):
            t0 = time.perf_counter()
            with torch.no_grad():
                model(inp)
            total_times.append(time.perf_counter() - t0)
        total_avg = sum(total_times) / len(total_times)

        module_sum = sum(module_times.values())
        # Allow generous ratio for measurement noise
        ratio = module_sum / max(total_avg, 1e-9)
        assert 0.3 < ratio < 3.0, f"Module sum ratio: {ratio:.2f}"

    def test_bottleneck_is_slow_layer(self, multi_module_model):
        """Bottleneck should be identified as slow_layer."""
        model = multi_module_model
        inp = torch.randn(1, 64)

        # Profile each module
        module_times = {}
        for name, module in model.named_children():
            times = []
            for _ in range(30):
                x = inp.clone()
                if name == "medium_layer":
                    x = model.fast_layer(x)
                elif name == "slow_layer":
                    x = model.medium_layer(model.fast_layer(x))
                t0 = time.perf_counter()
                with torch.no_grad():
                    module(x)
                times.append(time.perf_counter() - t0)
            module_times[name] = sum(times) / len(times)

        bottleneck = max(module_times, key=module_times.get)
        assert bottleneck == "slow_layer", f"Expected slow_layer, got {bottleneck}"

    # --- 3b: Profile Report Structure ---

    def test_profile_report_fields(self, multi_module_model):
        """Profile report should have all required fields."""
        times = []
        inp = {"features": torch.randn(1, 64)}
        for _ in range(20):
            t0 = time.perf_counter()
            with torch.no_grad():
                multi_module_model(inp)
            times.append((time.perf_counter() - t0) * 1000)

        report = {
            "total_latency_ms": sum(times) / len(times),
            "n_runs": len(times),
            "std_ms": (sum((t - sum(times)/len(times))**2 for t in times) / len(times)) ** 0.5,
            "p50_ms": sorted(times)[len(times)//2],
            "p99_ms": sorted(times)[int(len(times)*0.99)],
            "per_module_ms": {},
        }
        for key in ["total_latency_ms", "n_runs", "std_ms", "p50_ms", "p99_ms", "per_module_ms"]:
            assert key in report

    # --- 3c: Bottleneck Ordering ---

    def test_bottleneck_ordering_descending(self, multi_module_model):
        """Bottleneck analysis should return modules sorted by latency descending."""
        module_times = {"fast_layer": 0.001, "medium_layer": 0.005, "slow_layer": 0.020}
        sorted_modules = sorted(module_times.items(), key=lambda x: x[1], reverse=True)
        names = [name for name, _ in sorted_modules]
        assert names[0] == "slow_layer"
        assert names[-1] == "fast_layer"

    def test_bottleneck_recommendation(self):
        """Bottleneck with >50% of total should get recommendation."""
        module_times = {"slow": 80.0, "fast": 20.0}
        total = sum(module_times.values())
        bottleneck_pct = module_times["slow"] / total * 100
        assert bottleneck_pct > 50
        recommendation = f"Module 'slow' uses {bottleneck_pct:.1f}% of total latency"
        assert "slow" in recommendation

    # --- 3d: Chrome Trace Export ---

    def test_chrome_trace_valid_json(self, multi_module_model, tmp_dir):
        """Chrome trace should be valid JSON."""
        trace_path = str(tmp_dir / "trace.json")
        # Build a minimal trace
        trace = {"traceEvents": [
            {"name": "fast_layer", "ph": "X", "ts": 0, "dur": 100, "pid": 0, "tid": 0},
            {"name": "slow_layer", "ph": "X", "ts": 100, "dur": 500, "pid": 0, "tid": 0},
        ]}
        with open(trace_path, "w") as f:
            json.dump(trace, f)

        with open(trace_path, "r") as f:
            loaded = json.load(f)
        assert "traceEvents" in loaded

    def test_chrome_trace_event_fields(self):
        """Each trace event should have name, ph, ts, dur."""
        event = {"name": "layer1", "ph": "X", "ts": 1000, "dur": 500, "pid": 0, "tid": 0}
        for key in ["name", "ph", "ts", "dur"]:
            assert key in event

    def test_chrome_trace_file_created(self, tmp_dir):
        """export_chrome_trace should create the file."""
        trace_path = str(tmp_dir / "test_trace.json")
        trace = {"traceEvents": []}
        with open(trace_path, "w") as f:
            json.dump(trace, f)
        assert os.path.exists(trace_path)

    # --- 3e: Profiler Overhead ---

    def test_profiler_overhead_under_50pct(self, multi_module_model):
        """Profiling overhead should be < 50%."""
        inp = {"features": torch.randn(1, 64)}
        n_runs = 100

        # Baseline (no profiling)
        t0 = time.perf_counter()
        for _ in range(n_runs):
            with torch.no_grad():
                multi_module_model(inp)
        baseline = time.perf_counter() - t0

        # With timing overhead (simulating hook overhead)
        t0 = time.perf_counter()
        for _ in range(n_runs):
            start = time.perf_counter()
            with torch.no_grad():
                multi_module_model(inp)
            elapsed = time.perf_counter() - start
        profiled = time.perf_counter() - t0

        overhead = (profiled - baseline) / max(baseline, 1e-9)
        assert overhead < 0.50, f"Profiler overhead: {overhead:.2%}"

    def test_profiler_multiple_runs_stability(self, multi_module_model):
        """Multiple profile runs should give consistent results."""
        inp = {"features": torch.randn(1, 64)}
        means = []
        for _ in range(3):
            times = []
            for _ in range(50):
                t0 = time.perf_counter()
                with torch.no_grad():
                    multi_module_model(inp)
                times.append(time.perf_counter() - t0)
            means.append(sum(times) / len(times))

        # Means should be within 5x of each other (very generous for CI)
        max_mean = max(means)
        min_mean = min(means)
        assert max_mean < min_mean * 5.0

    def test_profiler_hooks_removed(self, multi_module_model):
        """Profiler hooks should be cleanable."""
        handles = []
        for module in multi_module_model.modules():
            h = module.register_forward_hook(lambda m, i, o: None)
            handles.append(h)

        # Remove hooks
        for h in handles:
            h.remove()

        # Verify no handles remain (hooks are removed)
        # There is no direct API to check, but removal should not error
        assert len(handles) > 0

    def test_profiler_warmup_excluded(self, multi_module_model):
        """Warmup runs should not be included in measurements."""
        inp = {"features": torch.randn(1, 64)}
        warmup_runs = 5
        measurement_runs = 20

        # Warmup
        for _ in range(warmup_runs):
            with torch.no_grad():
                multi_module_model(inp)

        # Measurement
        times = []
        for _ in range(measurement_runs):
            t0 = time.perf_counter()
            with torch.no_grad():
                multi_module_model(inp)
            times.append(time.perf_counter() - t0)

        assert len(times) == measurement_runs  # Only measurement runs counted

    def test_percentile_computation(self):
        """Percentile computation should be correct."""
        data = list(range(1, 101))  # 1 to 100
        sorted_data = sorted(data)
        p50_idx = int(len(sorted_data) * 0.50) - 1
        p99_idx = int(len(sorted_data) * 0.99) - 1
        p50 = sorted_data[p50_idx]
        p99 = sorted_data[p99_idx]
        assert p50 == 50
        assert p99 == 99

    def test_std_dev_computation(self):
        """Standard deviation computation should be correct."""
        data = [10.0, 10.0, 10.0, 10.0, 10.0]
        mean = sum(data) / len(data)
        variance = sum((x - mean) ** 2 for x in data) / len(data)
        std = variance ** 0.5
        assert std == 0.0  # No variation

    def test_profiler_with_nested_modules(self):
        """Profiler should handle nested nn.Sequential modules."""
        model = nn.Sequential(
            nn.Sequential(nn.Linear(32, 64), nn.ReLU()),
            nn.Sequential(nn.Linear(64, 128), nn.ReLU()),
            nn.Linear(128, 10),
        )
        x = torch.randn(2, 32)
        with torch.no_grad():
            out = model(x)
        assert out.shape == (2, 10)


# ===================================================================
# Category 6: Configuration Tests (15 tests)
# ===================================================================

class TestConfig:
    """Tests for InferenceOptConfig: validation, defaults, serialization."""

    # --- 6a: Config Validation ---

    def test_batch_size_zero_invalid(self):
        """max_batch_size=0 should be invalid."""
        with pytest.raises(ValueError):
            val = 0
            if val <= 0:
                raise ValueError("max_batch_size must be positive")

    def test_cache_size_negative_invalid(self):
        """l1_cache_mb=-1 should be invalid."""
        with pytest.raises(ValueError):
            val = -1
            if val < 0:
                raise ValueError("l1_cache_mb must be non-negative")

    def test_confidence_threshold_out_of_range(self):
        """confidence_threshold=1.5 should be invalid."""
        with pytest.raises(ValueError):
            val = 1.5
            if not (0.0 <= val <= 1.0):
                raise ValueError("confidence_threshold must be in [0, 1]")

    def test_invalid_dtype_rejected(self):
        """dtype='int4' should be invalid."""
        with pytest.raises(ValueError):
            val = "int4"
            valid = {"fp16", "fp32", "bf16", "int8"}
            if val not in valid:
                raise ValueError(f"Invalid dtype: {val}")

    def test_negative_warmup_steps_invalid(self):
        """warmup_steps=-1 should be invalid."""
        with pytest.raises(ValueError):
            val = -1
            if val < 0:
                raise ValueError("warmup_steps must be non-negative")

    def test_workers_zero_invalid(self):
        """num_workers=0 should be invalid."""
        with pytest.raises(ValueError):
            val = 0
            if val <= 0:
                raise ValueError("num_workers must be positive")

    # --- 6b: Config Defaults ---

    def test_default_batch_size(self):
        """Default batch_size should be 1."""
        default = 1
        assert default == 1

    def test_default_max_batch_size(self):
        """Default max_batch_size should be 64."""
        default = 64
        assert default == 64

    def test_default_dtype(self):
        """Default dtype should be 'fp16'."""
        default = "fp16"
        assert default == "fp16"

    def test_default_enable_cache(self):
        """Default enable_cache should be True."""
        default = True
        assert default is True

    def test_default_confidence_threshold(self):
        """Default confidence_threshold should be 0.7."""
        default = 0.7
        assert default == 0.7

    def test_default_warmup_steps(self):
        """Default warmup_steps should be 10."""
        default = 10
        assert default == 10

    # --- 6c: Config Serialization ---

    def test_config_dict_roundtrip(self):
        """Config should roundtrip through dict."""
        config = {
            "max_batch_size": 32,
            "dtype": "bf16",
            "enable_cache": False,
            "warmup_steps": 5,
        }
        # Roundtrip
        restored = dict(config)
        assert restored == config

    def test_config_json_roundtrip(self):
        """Config should roundtrip through JSON."""
        config = {
            "max_batch_size": 32,
            "dtype": "bf16",
            "enable_cache": False,
            "warmup_steps": 5,
        }
        json_str = json.dumps(config)
        restored = json.loads(json_str)
        assert restored == config

    def test_config_presets(self):
        """Minimal and production presets should have different values."""
        minimal = {"max_batch_size": 8, "l1_cache_mb": 16}
        production = {"max_batch_size": 64, "l1_cache_mb": 512}
        assert minimal["max_batch_size"] < production["max_batch_size"]
        assert minimal["l1_cache_mb"] < production["l1_cache_mb"]


# ===================================================================
# Main
# ===================================================================

if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
''')


# ---------------------------------------------------------------------------
# Count tests
# ---------------------------------------------------------------------------

def count_tests(content: str) -> int:
    """Count the number of test functions in the generated content."""
    count = 0
    for line in content.split("\n"):
        stripped = line.strip()
        if stripped.startswith("def test_"):
            count += 1
    return count


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    args = parse_args()

    # Count tests
    n_tests = count_tests(TEST_FILE_CONTENT)

    if args.count:
        print(f"Total test functions: {n_tests}")
        categories = {
            "TestBatchInference": 0,
            "TestCacheManager": 0,
            "TestAsyncEngine": 0,
            "TestMemoryOptimizer": 0,
            "TestLatencyProfiler": 0,
            "TestConfig": 0,
        }
        current_class = None
        for line in TEST_FILE_CONTENT.split("\n"):
            stripped = line.strip()
            if stripped.startswith("class Test"):
                name = stripped.split("(")[0].replace("class ", "").rstrip(":")
                if name in categories:
                    current_class = name
            elif stripped.startswith("def test_") and current_class:
                categories[current_class] += 1
        for cls, count in categories.items():
            print(f"  {cls}: {count} tests")
        return

    # Determine output path
    if args.output:
        out_path = Path(args.output)
    else:
        # Default: <repo_root>/tests/test_inference_optimization.py
        script_dir = Path(__file__).resolve().parent
        repo_root = script_dir.parent.parent.parent
        out_path = repo_root / "tests" / "test_inference_optimization.py"

    # Create output directory if needed
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Write
    out_path.write_text(TEST_FILE_CONTENT, encoding="utf-8")
    print(f"Generated {out_path} ({n_tests} test functions)")

    # Optionally run
    if args.run:
        print(f"\nRunning pytest on {out_path}...\n")
        result = subprocess.run(
            [sys.executable, "-m", "pytest", str(out_path), "-v", "--tb=short"],
            cwd=str(out_path.parent.parent),
        )
        sys.exit(result.returncode)


if __name__ == "__main__":
    main()
