#!/usr/bin/env python3
"""
gen_distributed_tests.py
=========================
Generates a comprehensive pytest test file (100+ tests) for the V-JEPA 2
distributed training skill assets.

The generated file is written to:
    <skill_root>/tests/test_distributed_training.py

Usage:
    python scripts/gen_distributed_tests.py
    python scripts/gen_distributed_tests.py --output /path/to/tests/test_dist.py
    python scripts/gen_distributed_tests.py --run   # Generate then run with pytest

Test categories generated (100+ tests total):
    1. Distributed initialization (12 tests)
    2. Custom distributed ops — forward (18 tests)
    3. Custom distributed ops — backward / gradient flow (14 tests)
    4. Checkpoint save/load roundtrip (15 tests)
    5. Checkpoint retry logic (10 tests)
    6. Prefix stripping (12 tests)
    7. Pretrained loading strict=False (8 tests)
    8. SLURM detection logic (10 tests)
    9. Trainer callable and submitit (8 tests)
    10. Code snapshotting (10 tests)
    11. PerformanceOptimizer (14 tests)
    12. Integration: done-when gates (3 tests)
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from textwrap import dedent

_SKILL_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# ---------------------------------------------------------------------------
# Test file content
# ---------------------------------------------------------------------------

TEST_FILE_CONTENT = '''#!/usr/bin/env python3
"""
test_distributed_training.py
==============================
Auto-generated pytest test suite for V-JEPA 2 distributed training skill.
Generated by: scripts/gen_distributed_tests.py

Run with:
    pytest tests/test_distributed_training.py -v
    pytest tests/test_distributed_training.py -v -k "AllGather"
    pytest tests/test_distributed_training.py -v --tb=short
"""

from __future__ import annotations

import glob
import os
import sys
import tempfile
import time
from typing import Any, Dict, List, Optional
from unittest.mock import MagicMock, patch

import pytest
import torch
import torch.nn as nn

# Make assets importable
_SKILL_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_SKILL_DIR, "assets"))

# ---------------------------------------------------------------------------
# Import helpers (skip gracefully if import fails)
# ---------------------------------------------------------------------------

try:
    from distributed_setup_template import DistributedSetup
    _DIST_SETUP_OK = True
except ImportError as e:
    _DIST_SETUP_OK = False
    _DIST_SETUP_ERR = str(e)

try:
    from custom_dist_ops_template import AllGather, AllReduceSum, AllReduce
    from custom_dist_ops_template import all_gather, all_reduce_sum, all_reduce
    _DIST_OPS_OK = True
except ImportError as e:
    _DIST_OPS_OK = False
    _DIST_OPS_ERR = str(e)

try:
    from checkpoint_manager_template import CheckpointManager
    _CKPT_OK = True
except ImportError as e:
    _CKPT_OK = False
    _CKPT_ERR = str(e)

try:
    from slurm_submitter_template import (
        SLURMConfig, SLURMSubmitter, Trainer, snapshot_code
    )
    _SLURM_OK = True
except ImportError as e:
    _SLURM_OK = False
    _SLURM_ERR = str(e)

try:
    from perf_optimizer_template import PerformanceOptimizer, PerfConfig
    from torch.cuda.amp import GradScaler
    _PERF_OK = True
except ImportError as e:
    _PERF_OK = False
    _PERF_ERR = str(e)

# ---------------------------------------------------------------------------
# Module-level helpers (must be at module scope to be serializable)
# ---------------------------------------------------------------------------

def _module_level_train_fn(**kwargs):
    """Top-level training stub used by Trainer serialization tests."""
    pass


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def tmp_dir():
    """Provides a temporary directory that is cleaned up after the test."""
    with tempfile.TemporaryDirectory() as d:
        yield d


@pytest.fixture
def simple_model():
    """Simple 2-layer MLP for testing."""
    return nn.Sequential(nn.Linear(16, 16), nn.ReLU(), nn.Linear(16, 8))


@pytest.fixture
def clean_env(monkeypatch):
    """Removes all distributed env vars for clean single-process tests."""
    vars_to_remove = [
        "SLURM_NTASKS", "SLURM_PROCID", "SLURM_LOCALID",
        "SLURM_JOB_ID", "SLURM_JOB_TMPDIR", "SLURM_NODEID",
        "RANK", "LOCAL_RANK", "WORLD_SIZE", "MASTER_ADDR", "MASTER_PORT",
    ]
    for var in vars_to_remove:
        monkeypatch.delenv(var, raising=False)
    return monkeypatch


@pytest.fixture
def vjepa2_checkpoint_state():
    """Standard V-JEPA 2 checkpoint structure."""
    return {
        "epoch": 10,
        "encoder": {"weight": torch.randn(16, 8), "bias": torch.zeros(16)},
        "predictor": {"fc.weight": torch.randn(8, 16), "fc.bias": torch.zeros(8)},
        "target_encoder": {"weight": torch.randn(16, 8)},
        "opt": {"state": {}, "param_groups": [{"lr": 1e-4, "weight_decay": 0.05}]},
        "scaler": None,
    }


# ===========================================================================
# Category 1: Distributed Initialization (12 tests)
# ===========================================================================

class TestDistributedSetup:

    @pytest.mark.skipif(not _DIST_SETUP_OK, reason="distributed_setup_template not importable")
    def test_single_process_fallback_returns_0_0_1(self, clean_env):
        """Single-process fallback returns (rank=0, local_rank=0, world_size=1)."""
        setup = DistributedSetup()
        rank, local_rank, world_size = setup.init()
        assert rank == 0
        assert local_rank == 0
        assert world_size == 1

    @pytest.mark.skipif(not _DIST_SETUP_OK, reason="distributed_setup_template not importable")
    def test_single_process_dist_not_initialized(self, clean_env):
        """dist.is_initialized() is False after single-process init."""
        import torch.distributed as dist
        setup = DistributedSetup()
        setup.init()
        assert not dist.is_initialized()

    @pytest.mark.skipif(not _DIST_SETUP_OK, reason="distributed_setup_template not importable")
    def test_is_slurm_false_without_vars(self, clean_env):
        """is_slurm() returns False when no SLURM env vars present."""
        setup = DistributedSetup()
        assert not setup.is_slurm()

    @pytest.mark.skipif(not _DIST_SETUP_OK, reason="distributed_setup_template not importable")
    def test_is_slurm_false_with_only_procid(self, monkeypatch):
        """is_slurm() returns False when only SLURM_PROCID is set."""
        monkeypatch.setenv("SLURM_PROCID", "0")
        monkeypatch.delenv("SLURM_NTASKS", raising=False)
        monkeypatch.delenv("SLURM_LOCALID", raising=False)
        setup = DistributedSetup()
        assert not setup.is_slurm()

    @pytest.mark.skipif(not _DIST_SETUP_OK, reason="distributed_setup_template not importable")
    def test_is_slurm_false_with_only_ntasks_and_procid(self, monkeypatch):
        """is_slurm() requires all three SLURM vars."""
        monkeypatch.setenv("SLURM_NTASKS", "8")
        monkeypatch.setenv("SLURM_PROCID", "0")
        monkeypatch.delenv("SLURM_LOCALID", raising=False)
        setup = DistributedSetup()
        assert not setup.is_slurm()

    @pytest.mark.skipif(not _DIST_SETUP_OK, reason="distributed_setup_template not importable")
    def test_is_slurm_true_with_all_required_vars(self, monkeypatch):
        """is_slurm() returns True when all three required vars are set."""
        monkeypatch.setenv("SLURM_NTASKS", "8")
        monkeypatch.setenv("SLURM_PROCID", "0")
        monkeypatch.setenv("SLURM_LOCALID", "0")
        setup = DistributedSetup()
        assert setup.is_slurm()

    @pytest.mark.skipif(not _DIST_SETUP_OK, reason="distributed_setup_template not importable")
    def test_cleanup_idempotent_no_dist(self, clean_env):
        """cleanup() does not raise when dist not initialized."""
        setup = DistributedSetup()
        setup.init()
        setup.cleanup()
        setup.cleanup()  # Second call must not raise

    @pytest.mark.skipif(not _DIST_SETUP_OK, reason="distributed_setup_template not importable")
    def test_cleanup_triple_call(self, clean_env):
        """cleanup() can be called any number of times without error."""
        setup = DistributedSetup()
        setup.init()
        for _ in range(5):
            setup.cleanup()

    @pytest.mark.skipif(not _DIST_SETUP_OK, reason="distributed_setup_template not importable")
    def test_is_main_true_for_single_process(self, clean_env):
        """is_main is True for rank=0 (single-process)."""
        setup = DistributedSetup()
        setup.init()
        assert setup.is_main

    @pytest.mark.skipif(not _DIST_SETUP_OK, reason="distributed_setup_template not importable")
    def test_device_property_cpu_fallback(self, clean_env):
        """device property returns CPU device when CUDA not available."""
        setup = DistributedSetup()
        setup.init()
        device = setup.device
        if not torch.cuda.is_available():
            assert device == torch.device("cpu")
        else:
            assert device.type == "cuda"

    @pytest.mark.skipif(not _DIST_SETUP_OK, reason="distributed_setup_template not importable")
    def test_barrier_no_op_single_process(self, clean_env):
        """barrier() completes without hanging in single-process mode."""
        setup = DistributedSetup()
        setup.init()
        setup.barrier()  # Must not block

    @pytest.mark.skipif(not _DIST_SETUP_OK, reason="distributed_setup_template not importable")
    def test_repr_contains_rank_and_world_size(self, clean_env):
        """__repr__ contains rank and world_size information."""
        setup = DistributedSetup()
        setup.init()
        r = repr(setup)
        assert "rank=0" in r
        assert "world_size=1" in r


# ===========================================================================
# Category 2: Custom Distributed Ops — Forward (18 tests)
# ===========================================================================

class TestDistOpsForward:

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    @pytest.mark.parametrize("shape", [(4, 128), (1, 512), (8, 32, 64), (2,)])
    def test_allgather_forward_identity_shapes(self, shape):
        """AllGather forward produces same shape as input (world_size=1)."""
        x = torch.randn(*shape)
        y = AllGather.apply(x)
        assert y.shape == x.shape

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allgather_forward_identity_values(self):
        """AllGather forward produces identical values (world_size=1)."""
        x = torch.randn(4, 32)
        y = AllGather.apply(x)
        assert torch.allclose(y, x)

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allgather_output_is_clone_not_same_storage(self):
        """AllGather output should not share storage with input."""
        x = torch.randn(4, 8)
        y = AllGather.apply(x)
        assert not x.data_ptr() == y.data_ptr() or not torch.is_same_size(x, y)

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    @pytest.mark.parametrize("shape", [(4, 128), (1, 64), (3, 7)])
    def test_allreducesum_forward_identity(self, shape):
        """AllReduceSum forward is identity for world_size=1."""
        x = torch.randn(*shape)
        y = AllReduceSum.apply(x)
        assert y.shape == x.shape
        assert torch.allclose(y, x)

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    @pytest.mark.parametrize("shape", [(4, 128), (2, 32), (5,)])
    def test_allreduce_forward_identity(self, shape):
        """AllReduce forward is identity for world_size=1."""
        x = torch.randn(*shape)
        y = AllReduce.apply(x)
        assert y.shape == x.shape
        assert torch.allclose(y, x)

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allgather_preserves_dtype_float32(self):
        """AllGather preserves float32 dtype."""
        x = torch.randn(4, 8, dtype=torch.float32)
        y = AllGather.apply(x)
        assert y.dtype == torch.float32

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allgather_preserves_dtype_float64(self):
        """AllGather preserves float64 dtype."""
        x = torch.randn(4, 8, dtype=torch.float64)
        y = AllGather.apply(x)
        assert y.dtype == torch.float64

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allgather_has_grad_fn(self):
        """AllGather output has grad_fn when input requires_grad."""
        x = torch.randn(4, 8, requires_grad=True)
        y = AllGather.apply(x)
        assert y.grad_fn is not None

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allreducesum_has_grad_fn(self):
        """AllReduceSum output has grad_fn when input requires_grad."""
        x = torch.randn(4, 8, requires_grad=True)
        y = AllReduceSum.apply(x)
        assert y.grad_fn is not None

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allreduce_has_grad_fn(self):
        """AllReduce output has grad_fn when input requires_grad."""
        x = torch.randn(4, 8, requires_grad=True)
        y = AllReduce.apply(x)
        assert y.grad_fn is not None

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_functional_all_gather_wrapper(self):
        """Functional all_gather wrapper produces same result as AllGather.apply."""
        x = torch.randn(4, 16)
        assert torch.allclose(all_gather(x), AllGather.apply(x))

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_functional_all_reduce_sum_wrapper(self):
        """Functional all_reduce_sum wrapper produces same result as AllReduceSum.apply."""
        x = torch.randn(4, 16)
        assert torch.allclose(all_reduce_sum(x), AllReduceSum.apply(x))

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_functional_all_reduce_wrapper(self):
        """Functional all_reduce wrapper produces same result as AllReduce.apply."""
        x = torch.randn(4, 16)
        assert torch.allclose(all_reduce(x), AllReduce.apply(x))

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allgather_no_grad_input(self):
        """AllGather works with input that does not require grad."""
        x = torch.randn(4, 8)
        assert not x.requires_grad
        y = AllGather.apply(x)
        assert y is not None

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allreduce_symmetry_world_size1(self):
        """AllReduce and AllReduceSum are identical for world_size=1."""
        x = torch.randn(4, 4)
        y_sum = AllReduceSum.apply(x)
        y_avg = AllReduce.apply(x)
        assert torch.allclose(y_sum, y_avg)

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allgather_3d_tensor(self):
        """AllGather handles 3D tensors (batch, seq, dim)."""
        x = torch.randn(2, 10, 64)
        y = AllGather.apply(x)
        assert y.shape == (2, 10, 64)

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allgather_zero_batch(self):
        """AllGather handles edge case of batch size 1."""
        x = torch.randn(1, 128)
        y = AllGather.apply(x)
        assert y.shape == (1, 128)

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_all_ops_compose_in_pipeline(self):
        """AllGather -> AllReduce composes without error."""
        x = torch.randn(4, 8, requires_grad=True)
        y = AllGather.apply(x)
        z = AllReduce.apply(y)
        z.sum().backward()
        assert x.grad is not None


# ===========================================================================
# Category 3: Custom Distributed Ops — Backward / Gradient Flow (14 tests)
# ===========================================================================

class TestDistOpsGradient:

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    @pytest.mark.parametrize("shape", [(4, 32), (2, 8, 16), (1, 128)])
    def test_allgather_grad_shape_matches_input(self, shape):
        """AllGather backward: grad.shape == input.shape."""
        x = torch.randn(*shape, requires_grad=True)
        AllGather.apply(x).sum().backward()
        assert x.grad is not None
        assert x.grad.shape == x.shape

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allgather_grad_is_not_none(self):
        """AllGather backward: gradient is not None."""
        x = torch.randn(4, 32, requires_grad=True)
        AllGather.apply(x).sum().backward()
        assert x.grad is not None

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allgather_grad_nonzero(self):
        """AllGather backward: gradient is non-zero."""
        x = torch.randn(3, 5, requires_grad=True)
        (AllGather.apply(x) * 2.0).sum().backward()
        assert x.grad.abs().sum().item() > 0

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allgather_backward_values_world_size1(self):
        """AllGather backward (world_size=1): grad == upstream."""
        x = torch.randn(4, 8, requires_grad=True)
        upstream = torch.ones_like(x)
        AllGather.apply(x).backward(upstream)
        assert torch.allclose(x.grad, upstream)

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    @pytest.mark.parametrize("shape", [(4, 4), (2, 8), (1, 16)])
    def test_allreducesum_backward_identity(self, shape):
        """AllReduceSum backward is identity: grad_input == grad_output."""
        x = torch.randn(*shape, requires_grad=True)
        upstream = torch.randn(*shape)
        AllReduceSum.apply(x).backward(upstream)
        assert torch.allclose(x.grad, upstream)

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    @pytest.mark.parametrize("shape", [(4, 4), (3, 7)])
    def test_allreduce_backward_identity(self, shape):
        """AllReduce backward is identity: grad_input == grad_output."""
        x = torch.randn(*shape, requires_grad=True)
        upstream = torch.randn(*shape)
        AllReduce.apply(x).backward(upstream)
        assert torch.allclose(x.grad, upstream)

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allgather_multiple_backward_passes(self):
        """AllGather supports multiple independent backward passes."""
        for _ in range(3):
            x = torch.randn(4, 8, requires_grad=True)
            AllGather.apply(x).sum().backward()
            assert x.grad is not None

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allgather_backward_through_linear_layer(self):
        """Gradient flows through AllGather to upstream linear layer."""
        linear = nn.Linear(8, 4)
        x = torch.randn(3, 8)
        z = linear(x)
        g = AllGather.apply(z)
        g.sum().backward()
        for p in linear.parameters():
            assert p.grad is not None

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allreducesum_backward_nonzero(self):
        """AllReduceSum backward produces non-zero gradient."""
        x = torch.randn(4, 8, requires_grad=True)
        upstream = torch.randn(4, 8)
        AllReduceSum.apply(x).backward(upstream)
        assert x.grad.abs().sum().item() > 0

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allreduce_no_requires_grad_input(self):
        """AllReduce does not crash when input does not require grad."""
        x = torch.randn(4, 8)
        y = AllReduce.apply(x)
        assert y is not None  # Should not raise

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allgather_gradient_check(self):
        """torch.autograd.gradcheck passes for AllGather (world_size=1)."""
        x = torch.randn(2, 4, dtype=torch.float64, requires_grad=True)
        # gradcheck requires float64 and small perturbations
        assert torch.autograd.gradcheck(AllGather.apply, (x,), eps=1e-6, atol=1e-4)

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allreducesum_gradient_check(self):
        """torch.autograd.gradcheck passes for AllReduceSum (world_size=1)."""
        x = torch.randn(2, 4, dtype=torch.float64, requires_grad=True)
        assert torch.autograd.gradcheck(AllReduceSum.apply, (x,), eps=1e-6, atol=1e-4)

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allreduce_gradient_check(self):
        """torch.autograd.gradcheck passes for AllReduce (world_size=1)."""
        x = torch.randn(2, 4, dtype=torch.float64, requires_grad=True)
        assert torch.autograd.gradcheck(AllReduce.apply, (x,), eps=1e-6, atol=1e-4)

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_allgather_zero_gradient_for_zero_upstream(self):
        """AllGather: zero upstream gradient produces zero grad_input."""
        x = torch.randn(4, 8, requires_grad=True)
        y = AllGather.apply(x)
        y.backward(torch.zeros_like(y))
        assert torch.allclose(x.grad, torch.zeros_like(x))


# ===========================================================================
# Category 4: Checkpoint Save/Load Roundtrip (15 tests)
# ===========================================================================

class TestCheckpointRoundtrip:

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_save_creates_file(self, tmp_dir, vjepa2_checkpoint_state):
        manager = CheckpointManager(tmp_dir)
        path = manager.save(vjepa2_checkpoint_state, epoch=10)
        assert os.path.exists(path)

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_save_filename_contains_epoch(self, tmp_dir, vjepa2_checkpoint_state):
        manager = CheckpointManager(tmp_dir)
        path = manager.save(vjepa2_checkpoint_state, epoch=5)
        assert "0005" in os.path.basename(path)

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_save_with_tag(self, tmp_dir, vjepa2_checkpoint_state):
        manager = CheckpointManager(tmp_dir)
        path = manager.save(vjepa2_checkpoint_state, epoch=5, tag="best")
        assert "best" in os.path.basename(path)

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_epoch_matches(self, tmp_dir, vjepa2_checkpoint_state):
        manager = CheckpointManager(tmp_dir)
        path = manager.save(vjepa2_checkpoint_state, epoch=10)
        loaded = manager.load(path)
        assert loaded["epoch"] == 10

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_encoder_weights_match(self, tmp_dir, vjepa2_checkpoint_state):
        manager = CheckpointManager(tmp_dir)
        path = manager.save(vjepa2_checkpoint_state, epoch=10)
        loaded = manager.load(path)
        assert torch.allclose(
            loaded["encoder"]["weight"],
            vjepa2_checkpoint_state["encoder"]["weight"]
        )

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_predictor_weights_match(self, tmp_dir, vjepa2_checkpoint_state):
        manager = CheckpointManager(tmp_dir)
        path = manager.save(vjepa2_checkpoint_state, epoch=10)
        loaded = manager.load(path)
        assert torch.allclose(
            loaded["predictor"]["fc.weight"],
            vjepa2_checkpoint_state["predictor"]["fc.weight"]
        )

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_target_encoder_matches(self, tmp_dir, vjepa2_checkpoint_state):
        manager = CheckpointManager(tmp_dir)
        path = manager.save(vjepa2_checkpoint_state, epoch=10)
        loaded = manager.load(path)
        assert torch.allclose(
            loaded["target_encoder"]["weight"],
            vjepa2_checkpoint_state["target_encoder"]["weight"]
        )

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_optimizer_lr_matches(self, tmp_dir, vjepa2_checkpoint_state):
        manager = CheckpointManager(tmp_dir)
        path = manager.save(vjepa2_checkpoint_state, epoch=10)
        loaded = manager.load(path)
        assert loaded["opt"]["param_groups"][0]["lr"] == 1e-4

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_none_scaler_preserved(self, tmp_dir, vjepa2_checkpoint_state):
        manager = CheckpointManager(tmp_dir)
        path = manager.save(vjepa2_checkpoint_state, epoch=10)
        loaded = manager.load(path)
        assert loaded["scaler"] is None

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_all_vjepa2_keys_present(self, tmp_dir, vjepa2_checkpoint_state):
        manager = CheckpointManager(tmp_dir)
        path = manager.save(vjepa2_checkpoint_state, epoch=10)
        loaded = manager.load(path)
        expected_keys = {"epoch", "encoder", "predictor", "target_encoder", "opt", "scaler"}
        assert expected_keys <= set(loaded.keys())

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_atomic_write_no_tmp_files(self, tmp_dir):
        manager = CheckpointManager(tmp_dir)
        manager.save({"epoch": 0}, epoch=0)
        tmp_files = glob.glob(os.path.join(tmp_dir, "*.tmp"))
        assert len(tmp_files) == 0

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_multiple_checkpoints_saved(self, tmp_dir):
        manager = CheckpointManager(tmp_dir)
        for epoch in range(3):
            manager.save({"epoch": epoch}, epoch=epoch)
        ckpts = manager.list_checkpoints()
        assert len(ckpts) == 3

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_latest_checkpoint_returns_newest(self, tmp_dir):
        manager = CheckpointManager(tmp_dir)
        manager.save({"epoch": 0}, epoch=0)
        manager.save({"epoch": 3}, epoch=3)
        latest = manager.latest_checkpoint()
        assert latest is not None
        assert "0003" in latest

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_latest_checkpoint_returns_none_when_empty(self, tmp_dir):
        manager = CheckpointManager(tmp_dir)
        assert manager.latest_checkpoint() is None

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_checkpoint_rotation_keep_last_2(self, tmp_dir):
        manager = CheckpointManager(tmp_dir, keep_last=2)
        for epoch in range(5):
            manager.save({"epoch": epoch}, epoch=epoch)
        remaining = manager.list_checkpoints()
        assert len(remaining) == 2
        assert "0003" in remaining[0]
        assert "0004" in remaining[1]


# ===========================================================================
# Category 5: Checkpoint Retry Logic (10 tests)
# ===========================================================================

class TestCheckpointRetry:

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_first_try_no_retries(self, tmp_dir):
        """Load succeeds on first try without any retries."""
        manager = CheckpointManager(tmp_dir, max_retries=5)
        path = manager.save({"epoch": 1}, epoch=1)
        call_count = [0]
        original = torch.load

        def counting_load(p, *a, **kw):
            call_count[0] += 1
            return original(p, *a, **kw)

        with patch("torch.load", side_effect=counting_load):
            manager.load(path)
        assert call_count[0] == 1

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_retry_after_one_failure(self, tmp_dir):
        """Load succeeds after 1 failure (2 total attempts)."""
        manager = CheckpointManager(tmp_dir, max_retries=5)
        path = manager.save({"epoch": 2}, epoch=2)
        call_count = [0]
        original = torch.load

        def flaky(p, *a, **kw):
            call_count[0] += 1
            if call_count[0] == 1:
                raise IOError("Simulated error")
            return original(p, *a, **kw)

        with patch("torch.load", side_effect=flaky), patch("time.sleep"):
            result = manager.load(path)
        assert result["epoch"] == 2
        assert call_count[0] == 2

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_retry_after_two_failures(self, tmp_dir):
        """Load succeeds after 2 failures (3 total attempts)."""
        manager = CheckpointManager(tmp_dir, max_retries=5)
        path = manager.save({"epoch": 3}, epoch=3)
        call_count = [0]
        original = torch.load

        def flaky(p, *a, **kw):
            call_count[0] += 1
            if call_count[0] < 3:
                raise IOError("Simulated transient NFS error")
            return original(p, *a, **kw)

        with patch("torch.load", side_effect=flaky), patch("time.sleep"):
            result = manager.load(path)
        assert result["epoch"] == 3
        assert call_count[0] == 3

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_all_retries_exhausted_raises_runtime_error(self, tmp_dir):
        """RuntimeError raised when all retry attempts fail."""
        manager = CheckpointManager(tmp_dir, max_retries=3)
        fake_path = os.path.join(tmp_dir, "nonexistent.pth")
        with pytest.raises(RuntimeError):
            with patch("time.sleep"):
                manager.load(fake_path)

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_max_retries_1_fails_immediately(self, tmp_dir):
        """With max_retries=1, any failure immediately raises."""
        manager = CheckpointManager(tmp_dir, max_retries=1)
        fake_path = os.path.join(tmp_dir, "fake.pth")
        with pytest.raises(RuntimeError):
            with patch("time.sleep"):
                manager.load(fake_path)

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_retry_waits_between_attempts(self, tmp_dir):
        """time.sleep is called between retry attempts."""
        manager = CheckpointManager(tmp_dir, max_retries=3)
        fake_path = os.path.join(tmp_dir, "fake.pth")
        sleep_calls = []

        with patch("time.sleep", side_effect=lambda t: sleep_calls.append(t)):
            with pytest.raises(RuntimeError):
                manager.load(fake_path)

        assert len(sleep_calls) >= 2  # At least 2 sleeps for 3 attempts

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_retry_wait_is_positive(self, tmp_dir):
        """All retry waits are positive durations."""
        manager = CheckpointManager(tmp_dir, max_retries=4)
        fake_path = os.path.join(tmp_dir, "fake.pth")
        sleep_calls = []

        with patch("time.sleep", side_effect=lambda t: sleep_calls.append(t)):
            with pytest.raises(RuntimeError):
                manager.load(fake_path)

        for wait in sleep_calls:
            assert wait > 0, f"Wait time should be positive, got {wait}"

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_retry_error_message_mentions_attempts(self, tmp_dir):
        """RuntimeError message mentions the number of attempts."""
        manager = CheckpointManager(tmp_dir, max_retries=3)
        fake_path = os.path.join(tmp_dir, "fake.pth")
        with pytest.raises(RuntimeError, match="3"):
            with patch("time.sleep"):
                manager.load(fake_path)

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_retry_4_failures_then_success(self, tmp_dir):
        """Load succeeds after 4 failures with max_retries=5."""
        manager = CheckpointManager(tmp_dir, max_retries=5)
        path = manager.save({"epoch": 99}, epoch=99)
        call_count = [0]
        original = torch.load

        def flaky(p, *a, **kw):
            call_count[0] += 1
            if call_count[0] < 5:
                raise IOError("Transient error")
            return original(p, *a, **kw)

        with patch("torch.load", side_effect=flaky), patch("time.sleep"):
            result = manager.load(path)
        assert result["epoch"] == 99

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_map_location_cpu(self, tmp_dir):
        """Loaded tensors are on CPU regardless of save device."""
        manager = CheckpointManager(tmp_dir)
        path = manager.save({"epoch": 0, "w": torch.randn(4, 4)}, epoch=0)
        loaded = manager.load(path)
        assert loaded["w"].device.type == "cpu"


# ===========================================================================
# Category 6: Prefix Stripping (12 tests)
# ===========================================================================

class TestPrefixStripping:

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_strip_module_prefix(self):
        sd = {"module.layer.weight": torch.randn(4, 4), "module.layer.bias": torch.zeros(4)}
        cleaned = CheckpointManager.strip_prefix(sd, "module.")
        assert "layer.weight" in cleaned
        assert "layer.bias" in cleaned

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_strip_backbone_prefix(self):
        sd = {"backbone.encoder.weight": torch.randn(4, 4)}
        cleaned = CheckpointManager.strip_prefix(sd, "backbone.")
        assert "encoder.weight" in cleaned
        assert "backbone.encoder.weight" not in cleaned

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_strip_preserves_keys_without_prefix(self):
        sd = {"layer.weight": torch.randn(4, 4), "other.key": 1.0}
        cleaned = CheckpointManager.strip_prefix(sd, "module.")
        assert cleaned == sd

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_strip_empty_dict(self):
        cleaned = CheckpointManager.strip_prefix({}, "module.")
        assert cleaned == {}

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_strip_partial_match_not_stripped(self):
        """A key starting with part of the prefix should not be stripped."""
        sd = {"module_extra.weight": torch.randn(4)}
        cleaned = CheckpointManager.strip_prefix(sd, "module.")
        # "module_extra.weight" does NOT start with "module.", so preserved
        assert "module_extra.weight" in cleaned

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_strip_preserves_tensor_values(self):
        w = torch.randn(4, 4)
        sd = {"module.layer.weight": w}
        cleaned = CheckpointManager.strip_prefix(sd, "module.")
        assert torch.allclose(cleaned["layer.weight"], w)

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_strip_double_prefix_single_call(self):
        """Strip 'module.' from 'module.backbone.weight'."""
        sd = {"module.backbone.weight": 1.0}
        cleaned = CheckpointManager.strip_prefix(sd, "module.")
        assert "backbone.weight" in cleaned

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_strip_then_strip_chain(self):
        """Chain two strip_prefix calls for 'backbone.module.' prefix."""
        sd = {"backbone.module.layer.weight": torch.randn(4)}
        s1 = CheckpointManager.strip_prefix(sd, "backbone.")
        s2 = CheckpointManager.strip_prefix(s1, "module.")
        assert "layer.weight" in s2

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_strip_result_is_new_dict(self):
        """strip_prefix returns a new dict, not a view of the original."""
        sd = {"module.weight": 1.0}
        cleaned = CheckpointManager.strip_prefix(sd, "module.")
        assert cleaned is not sd

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_strip_mixed_prefix_and_no_prefix(self):
        sd = {"module.layer.weight": torch.randn(4), "layer.bias": torch.zeros(4)}
        cleaned = CheckpointManager.strip_prefix(sd, "module.")
        assert "layer.weight" in cleaned
        assert "layer.bias" in cleaned
        assert "module.layer.weight" not in cleaned

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_strip_prefix_length_1(self):
        """Strip a single-character prefix."""
        sd = {"a.weight": 1.0, "b.bias": 2.0}
        cleaned = CheckpointManager.strip_prefix(sd, "a.")
        assert "weight" in cleaned
        assert "b.bias" in cleaned

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_strip_all_keys_have_prefix(self):
        sd = {f"module.layer{i}.w": float(i) for i in range(10)}
        cleaned = CheckpointManager.strip_prefix(sd, "module.")
        assert len(cleaned) == 10
        assert all(not k.startswith("module.") for k in cleaned)


# ===========================================================================
# Category 7: Pretrained Loading strict=False (8 tests)
# ===========================================================================

class TestPretrainedLoading:

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_pretrained_strict_false_missing_keys(self, tmp_dir):
        manager = CheckpointManager(tmp_dir)
        ckpt = {"encoder": {"0.weight": torch.randn(4, 4), "0.bias": torch.zeros(4),
                             "pos_embed": torch.randn(1, 10, 4)}}
        path = manager.save(ckpt, epoch=0)
        model = nn.Sequential(nn.Linear(4, 4))
        missing, unexpected = manager.load_pretrained(model, path, key="encoder", strict=False)
        assert "pos_embed" in unexpected

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_pretrained_weights_match(self, tmp_dir):
        manager = CheckpointManager(tmp_dir)
        w = torch.randn(4, 4)
        ckpt = {"encoder": {"0.weight": w, "0.bias": torch.zeros(4)}}
        path = manager.save(ckpt, epoch=0)
        model = nn.Sequential(nn.Linear(4, 4))
        manager.load_pretrained(model, path, key="encoder", strict=False)
        assert torch.allclose(model[0].weight.data, w)

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_pretrained_returns_tuple(self, tmp_dir):
        manager = CheckpointManager(tmp_dir)
        ckpt = {"encoder": {"0.weight": torch.randn(4, 4), "0.bias": torch.zeros(4)}}
        path = manager.save(ckpt, epoch=0)
        model = nn.Sequential(nn.Linear(4, 4))
        result = manager.load_pretrained(model, path, key="encoder", strict=False)
        assert isinstance(result, tuple) and len(result) == 2

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_pretrained_module_prefix_stripped(self, tmp_dir):
        manager = CheckpointManager(tmp_dir)
        ckpt = {"encoder": {"module.0.weight": torch.randn(4, 4),
                             "module.0.bias": torch.zeros(4)}}
        path = manager.save(ckpt, epoch=0)
        model = nn.Sequential(nn.Linear(4, 4))
        missing, unexpected = manager.load_pretrained(model, path, key="encoder", strict=False)
        # After stripping "module.", all keys should match
        assert len(unexpected) == 0

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_pretrained_strict_true_exact_match(self, tmp_dir):
        manager = CheckpointManager(tmp_dir)
        model = nn.Linear(4, 2)
        ckpt = {"encoder": model.state_dict()}
        path = manager.save(ckpt, epoch=0)
        model2 = nn.Linear(4, 2)
        missing, unexpected = manager.load_pretrained(model2, path, key="encoder", strict=True)
        assert len(missing) == 0
        assert len(unexpected) == 0

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_pretrained_uses_retry(self, tmp_dir):
        """load_pretrained uses retry logic from load()."""
        manager = CheckpointManager(tmp_dir, max_retries=5)
        model = nn.Linear(4, 2)
        ckpt = {"encoder": model.state_dict()}
        path = manager.save(ckpt, epoch=0)

        call_count = [0]
        original = torch.load

        def flaky(p, *a, **kw):
            call_count[0] += 1
            if call_count[0] < 2:
                raise IOError("transient error")
            return original(p, *a, **kw)

        with patch("torch.load", side_effect=flaky), patch("time.sleep"):
            manager.load_pretrained(model, path, key="encoder", strict=False)
        assert call_count[0] == 2

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_pretrained_fallback_when_key_absent(self, tmp_dir):
        """When the key is absent, the whole checkpoint is treated as state_dict."""
        manager = CheckpointManager(tmp_dir)
        model = nn.Linear(4, 2)
        # Save raw state_dict (no wrapping key)
        path = manager.save(model.state_dict(), epoch=0)
        model2 = nn.Linear(4, 2)
        # key="encoder" won't exist — should fall back to full ckpt as state_dict
        missing, unexpected = manager.load_pretrained(model2, path, key="encoder", strict=False)
        # Model keys should be present (weight, bias)
        assert len(unexpected) == 0

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_load_pretrained_weight_values_after_strip_and_load(self, tmp_dir):
        """Correct values are loaded even after prefix stripping."""
        manager = CheckpointManager(tmp_dir)
        w_value = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
        ckpt = {"encoder": {"module.weight": w_value, "module.bias": torch.zeros(2)}}
        path = manager.save(ckpt, epoch=0)
        model = nn.Linear(2, 2)
        manager.load_pretrained(model, path, key="encoder", strict=False)
        assert torch.allclose(model.weight.data, w_value)


# ===========================================================================
# Category 8: SLURM Detection Logic (10 tests)
# ===========================================================================

class TestSLURMDetection:

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_slurm_config_default_nodes(self):
        cfg = SLURMConfig()
        assert cfg.nodes == 1

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_slurm_config_default_gpus_per_node(self):
        cfg = SLURMConfig()
        assert cfg.gpus_per_node == 8

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_slurm_config_default_timeout(self):
        cfg = SLURMConfig()
        assert cfg.timeout_min == 4320

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_slurm_config_default_partition(self):
        cfg = SLURMConfig()
        assert cfg.partition == "learn"

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_slurm_config_default_account_empty(self):
        cfg = SLURMConfig()
        assert cfg.account == ""

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_slurm_config_default_qos_empty(self):
        cfg = SLURMConfig()
        assert cfg.qos == ""

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_slurm_config_custom_values(self):
        cfg = SLURMConfig(nodes=4, gpus_per_node=4, partition="gpu-large")
        assert cfg.nodes == 4
        assert cfg.gpus_per_node == 4
        assert cfg.partition == "gpu-large"

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_slurm_submitter_repr(self, tmp_dir):
        sub = SLURMSubmitter(SLURMConfig(nodes=2), log_dir=tmp_dir)
        r = repr(sub)
        assert "nodes=2" in r

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_slurm_submitter_config_dict(self, tmp_dir):
        cfg = SLURMConfig(nodes=3)
        sub = SLURMSubmitter(cfg, log_dir=tmp_dir)
        d = sub.config_dict()
        assert d["nodes"] == 3
        assert "gpus_per_node" in d

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_slurm_submitter_raises_without_submitit(self, tmp_dir):
        """submit() raises RuntimeError when submitit is not installed."""
        from slurm_submitter_template import _SUBMITIT_AVAILABLE

        if _SUBMITIT_AVAILABLE:
            pytest.skip("submitit is installed; cannot test absence")

        sub = SLURMSubmitter(SLURMConfig(), log_dir=tmp_dir)
        with pytest.raises(RuntimeError, match="submitit"):
            sub.submit(train_fn=lambda: None, args={})


# ===========================================================================
# Category 9: Trainer Callable and submitit (8 tests)
# ===========================================================================

class TestTrainerCallable:

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_trainer_call_invokes_train_fn(self):
        called = [False]

        def my_train(**kwargs):
            called[0] = True

        trainer = Trainer(train_fn=my_train, args={"x": 1})
        trainer()
        assert called[0]

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_trainer_passes_args_to_train_fn(self):
        received = {}

        def my_train(**kwargs):
            received.update(kwargs)

        trainer = Trainer(train_fn=my_train, args={"lr": 1e-3, "epochs": 10})
        trainer()
        assert received["lr"] == 1e-3
        assert received["epochs"] == 10

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_trainer_none_train_fn_no_crash(self):
        trainer = Trainer(train_fn=None, args={})
        trainer()  # Should not raise

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_trainer_repr_contains_fn_name(self):
        def my_fn(**kwargs):
            pass

        trainer = Trainer(train_fn=my_fn, args={"a": 1})
        assert "my_fn" in repr(trainer)

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_trainer_default_args_empty_dict(self):
        trainer = Trainer(train_fn=None)
        assert trainer.args == {}

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_trainer_checkpoint_requires_submitit(self):
        from slurm_submitter_template import _SUBMITIT_AVAILABLE
        trainer = Trainer(train_fn=None, args={})
        if _SUBMITIT_AVAILABLE:
            import submitit
            ds = trainer.checkpoint()
            assert isinstance(ds, submitit.helpers.DelayedSubmission)
        else:
            with pytest.raises(RuntimeError, match="submitit"):
                trainer.checkpoint()

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_trainer_is_serializable(self):
        """Trainer can be serialized and deserialized (required by submitit).

        Uses a module-level function so serialization can resolve it by name.
        """
        import io
        import torch

        # _module_level_train_fn is defined at module level (serializable)
        trainer = Trainer(train_fn=_module_level_train_fn, args={"x": 42})
        buf = io.BytesIO()
        torch.save(trainer, buf)
        buf.seek(0)
        restored = torch.load(buf, weights_only=False)
        assert restored.args["x"] == 42

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_trainer_args_preserved_across_roundtrip(self):
        """Trainer args are identical after serialization roundtrip.

        Uses a module-level function so serialization can resolve it by name.
        """
        import io
        import torch

        original_args = {"lr": 1e-4, "epochs": 100, "checkpoint_dir": "/tmp/exp"}
        trainer = Trainer(train_fn=_module_level_train_fn, args=original_args)
        buf = io.BytesIO()
        torch.save(trainer, buf)
        buf.seek(0)
        restored = torch.load(buf, weights_only=False)
        assert restored.args == original_args


# ===========================================================================
# Category 10: Code Snapshotting (10 tests)
# ===========================================================================

class TestCodeSnapshotting:

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_snapshot_copies_py_files(self, tmp_dir):
        src = os.path.join(tmp_dir, "src")
        os.makedirs(src)
        with open(os.path.join(src, "train.py"), "w") as f:
            f.write("x = 1")
        dest = os.path.join(tmp_dir, "snap")
        snapshot_code(src, dest, extensions=[".py"])
        assert os.path.exists(os.path.join(dest, "train.py"))

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_snapshot_preserves_dir_structure(self, tmp_dir):
        src = os.path.join(tmp_dir, "src")
        os.makedirs(os.path.join(src, "models"))
        with open(os.path.join(src, "models", "vit.py"), "w") as f:
            f.write("class ViT: pass")
        dest = os.path.join(tmp_dir, "snap")
        snapshot_code(src, dest, extensions=[".py"])
        assert os.path.exists(os.path.join(dest, "models", "vit.py"))

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_snapshot_excludes_pycache(self, tmp_dir):
        src = os.path.join(tmp_dir, "src")
        os.makedirs(os.path.join(src, "__pycache__"))
        with open(os.path.join(src, "__pycache__", "cached.py"), "w") as f:
            f.write("garbage")
        dest = os.path.join(tmp_dir, "snap")
        snapshot_code(src, dest, extensions=[".py"])
        assert not os.path.exists(os.path.join(dest, "__pycache__"))

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_snapshot_excludes_git_dir(self, tmp_dir):
        src = os.path.join(tmp_dir, "src")
        os.makedirs(os.path.join(src, ".git"))
        with open(os.path.join(src, ".git", "config"), "w") as f:
            f.write("[core]")
        dest = os.path.join(tmp_dir, "snap")
        snapshot_code(src, dest, extensions=[".py"])
        assert not os.path.exists(os.path.join(dest, ".git"))

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_snapshot_creates_dest_dir(self, tmp_dir):
        src = os.path.join(tmp_dir, "src")
        os.makedirs(src)
        dest = os.path.join(tmp_dir, "new_dest", "deep", "path")
        snapshot_code(src, dest, extensions=[".py"])
        assert os.path.exists(dest)

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_snapshot_idempotent(self, tmp_dir):
        src = os.path.join(tmp_dir, "src")
        os.makedirs(src)
        with open(os.path.join(src, "main.py"), "w") as f:
            f.write("pass")
        dest = os.path.join(tmp_dir, "snap")
        snapshot_code(src, dest, extensions=[".py"])
        snapshot_code(src, dest, extensions=[".py"])  # Second run should not fail
        assert os.path.exists(os.path.join(dest, "main.py"))

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_snapshot_only_copies_specified_extensions(self, tmp_dir):
        src = os.path.join(tmp_dir, "src")
        os.makedirs(src)
        with open(os.path.join(src, "train.py"), "w") as f:
            f.write("pass")
        with open(os.path.join(src, "config.yaml"), "w") as f:
            f.write("lr: 1e-3")
        dest = os.path.join(tmp_dir, "snap")
        snapshot_code(src, dest, extensions=[".py"])
        assert os.path.exists(os.path.join(dest, "train.py"))
        assert not os.path.exists(os.path.join(dest, "config.yaml"))

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_snapshot_copies_yaml_when_specified(self, tmp_dir):
        src = os.path.join(tmp_dir, "src")
        os.makedirs(src)
        with open(os.path.join(src, "config.yaml"), "w") as f:
            f.write("lr: 1e-3")
        dest = os.path.join(tmp_dir, "snap")
        snapshot_code(src, dest, extensions=[".yaml"])
        assert os.path.exists(os.path.join(dest, "config.yaml"))

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_snapshot_copies_multiple_extensions(self, tmp_dir):
        src = os.path.join(tmp_dir, "src")
        os.makedirs(src)
        for ext, content in [(".py", "pass"), (".sh", "#!/bin/bash"), (".yaml", "key: val")]:
            with open(os.path.join(src, f"file{ext}"), "w") as f:
                f.write(content)
        dest = os.path.join(tmp_dir, "snap")
        snapshot_code(src, dest, extensions=[".py", ".sh", ".yaml"])
        for ext in [".py", ".sh", ".yaml"]:
            assert os.path.exists(os.path.join(dest, f"file{ext}"))

    @pytest.mark.skipif(not _SLURM_OK, reason="slurm_submitter_template not importable")
    def test_snapshot_empty_source(self, tmp_dir):
        """Snapshot of an empty directory succeeds without error."""
        src = os.path.join(tmp_dir, "empty_src")
        os.makedirs(src)
        dest = os.path.join(tmp_dir, "snap")
        snapshot_code(src, dest, extensions=[".py"])
        assert os.path.exists(dest)


# ===========================================================================
# Category 11: PerformanceOptimizer (14 tests)
# ===========================================================================

class TestPerformanceOptimizer:

    @pytest.fixture
    def transformer_model(self):
        class Block(nn.Module):
            def __init__(self):
                super().__init__()
                self.linear = nn.Linear(32, 32)
                self.norm = nn.LayerNorm(32)

            def forward(self, x):
                return self.norm(self.linear(x) + x)

        class Model(nn.Module):
            def __init__(self):
                super().__init__()
                self.blocks = nn.ModuleList([Block() for _ in range(3)])

            def forward(self, x):
                for b in self.blocks:
                    x = b(x)
                return x

        return Model()

    @pytest.mark.skipif(not _PERF_OK, reason="perf_optimizer_template not importable")
    def test_activation_checkpointing_output_unchanged(self, transformer_model):
        torch.manual_seed(0)
        ref = nn.Sequential(*list(transformer_model.children()))
        ref.load_state_dict(transformer_model.state_dict(), strict=False)

        perf = PerformanceOptimizer(
            transformer_model, PerfConfig(use_activation_checkpointing=True)
        )
        perf.enable_activation_checkpointing()
        x = torch.randn(2, 8, 32)
        out = transformer_model(x)
        assert out.shape == (2, 8, 32)

    @pytest.mark.skipif(not _PERF_OK, reason="perf_optimizer_template not importable")
    def test_activation_checkpointing_backward_works(self, transformer_model):
        perf = PerformanceOptimizer(
            transformer_model, PerfConfig(use_activation_checkpointing=True)
        )
        perf.enable_activation_checkpointing()
        x = torch.randn(2, 8, 32)
        out = transformer_model(x)
        out.sum().backward()
        for p in transformer_model.parameters():
            assert p.grad is not None

    @pytest.mark.skipif(not _PERF_OK, reason="perf_optimizer_template not importable")
    def test_enable_mixed_precision_returns_grad_scaler(self, simple_model):
        perf = PerformanceOptimizer(simple_model, PerfConfig(use_bfloat16=True))
        scaler = perf.enable_mixed_precision()
        assert isinstance(scaler, GradScaler)

    @pytest.mark.skipif(not _PERF_OK, reason="perf_optimizer_template not importable")
    def test_grad_scaler_initial_scale_positive(self, simple_model):
        perf = PerformanceOptimizer(simple_model, PerfConfig(use_bfloat16=True))
        scaler = perf.enable_mixed_precision()
        assert scaler.get_scale() > 0

    @pytest.mark.skipif(not _PERF_OK, reason="perf_optimizer_template not importable")
    def test_compile_returns_nn_module(self, simple_model):
        perf = PerformanceOptimizer(simple_model, PerfConfig(compile_model=True))
        compiled = perf.compile_model()
        assert isinstance(compiled, nn.Module)

    @pytest.mark.skipif(not _PERF_OK, reason="perf_optimizer_template not importable")
    def test_compile_output_numerically_equivalent(self, simple_model):
        torch.manual_seed(42)
        x = torch.randn(4, 16)
        ref = simple_model(x).detach()

        perf = PerformanceOptimizer(simple_model, PerfConfig(compile_model=True))
        compiled = perf.compile_model()
        out = compiled(x).detach()
        assert torch.allclose(ref, out, atol=1e-4)

    @pytest.mark.skipif(not _PERF_OK, reason="perf_optimizer_template not importable")
    def test_compile_fallback_old_pytorch(self, simple_model):
        """compile_model returns original model when torch.compile absent."""
        with patch.object(torch, "compile", None, create=True):
            # Temporarily hide torch.compile
            original = getattr(torch, "compile", None)
            if hasattr(torch, "compile"):
                delattr_safe = True
                backup = torch.compile
                del torch.compile
            else:
                delattr_safe = False

            perf = PerformanceOptimizer(simple_model, PerfConfig(compile_model=True))
            result = perf.compile_model()
            assert isinstance(result, nn.Module)

            if delattr_safe:
                torch.compile = backup

    @pytest.mark.skipif(not _PERF_OK, reason="perf_optimizer_template not importable")
    def test_measure_memory_returns_dict(self, simple_model):
        perf = PerformanceOptimizer(simple_model)
        mem = perf.measure_memory()
        assert isinstance(mem, dict)

    @pytest.mark.skipif(not _PERF_OK, reason="perf_optimizer_template not importable")
    def test_measure_memory_expected_keys(self, simple_model):
        perf = PerformanceOptimizer(simple_model)
        mem = perf.measure_memory()
        assert {"allocated_mb", "reserved_mb", "peak_mb"} <= set(mem.keys())

    @pytest.mark.skipif(not _PERF_OK, reason="perf_optimizer_template not importable")
    def test_measure_memory_nonnegative_values(self, simple_model):
        perf = PerformanceOptimizer(simple_model)
        mem = perf.measure_memory()
        for k, v in mem.items():
            assert v >= 0.0, f"{k} = {v} should be >= 0"

    @pytest.mark.skipif(not _PERF_OK, reason="perf_optimizer_template not importable")
    def test_autocast_context_runs(self, simple_model):
        perf = PerformanceOptimizer(simple_model, PerfConfig(use_bfloat16=True))
        x = torch.randn(2, 16)
        with perf.autocast_context():
            out = simple_model(x)
        assert out.shape == (2, 8)

    @pytest.mark.skipif(not _PERF_OK, reason="perf_optimizer_template not importable")
    def test_apply_all_returns_grad_scaler(self, transformer_model):
        perf = PerformanceOptimizer(
            transformer_model,
            PerfConfig(use_activation_checkpointing=True, use_bfloat16=True)
        )
        scaler = perf.apply_all()
        assert isinstance(scaler, GradScaler)

    @pytest.mark.skipif(not _PERF_OK, reason="perf_optimizer_template not importable")
    def test_sdpa_availability_returns_bool(self):
        result = PerformanceOptimizer.sdpa_is_available()
        assert isinstance(result, bool)

    @pytest.mark.skipif(not _PERF_OK, reason="perf_optimizer_template not importable")
    def test_perf_optimizer_repr(self, simple_model):
        perf = PerformanceOptimizer(simple_model, PerfConfig(use_bfloat16=True))
        r = repr(perf)
        assert "use_bfloat16=True" in r


# ===========================================================================
# Category 12: Integration — Done-When Gates (3 tests)
# ===========================================================================

class TestDoneWhenGates:

    @pytest.mark.skipif(not _DIST_SETUP_OK, reason="distributed_setup_template not importable")
    def test_gate1_distributed_init(self):
        """Gate 1: DistributedSetup.init() returns valid rank/world_size."""
        setup = DistributedSetup()
        rank, local_rank, world_size = setup.init()
        assert rank == 0
        assert local_rank == 0
        assert world_size == 1
        setup.cleanup()
        setup.cleanup()  # Idempotent

    @pytest.mark.skipif(not _DIST_OPS_OK, reason="custom_dist_ops_template not importable")
    def test_gate2_allgather_gradient_flow(self):
        """Gate 2: AllGather gradient correctly flows to originating tensor."""
        x = torch.randn(4, 32, requires_grad=True)
        y = AllGather.apply(x)
        assert y.shape == x.shape
        y.sum().backward()
        assert x.grad is not None
        assert x.grad.shape == x.shape

    @pytest.mark.skipif(not _CKPT_OK, reason="checkpoint_manager_template not importable")
    def test_gate3_checkpoint_robustness(self, tmp_dir):
        """Gate 3: CheckpointManager retries on failure and loads matching state."""
        manager = CheckpointManager(tmp_dir, max_retries=5)
        enc_weight = torch.randn(16, 8)
        state = {
            "epoch": 42,
            "encoder": {"weight": enc_weight},
            "predictor": {"bias": torch.zeros(16)},
            "target_encoder": {"weight": enc_weight.clone()},
            "opt": {"state": {}, "param_groups": []},
            "scaler": None,
        }
        path = manager.save(state, epoch=42)
        loaded = manager.load(path)
        assert loaded["epoch"] == 42
        assert torch.allclose(loaded["encoder"]["weight"], enc_weight)
'''

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate pytest test file for V-JEPA 2 distributed training"
    )
    parser.add_argument(
        "--output", "-o",
        default=os.path.join(_SKILL_DIR, "tests", "test_distributed_training.py"),
        help="Output path for the generated test file"
    )
    parser.add_argument(
        "--run", action="store_true",
        help="Generate and immediately run the tests with pytest"
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true",
        help="Pass -v to pytest when --run is specified"
    )
    args = parser.parse_args()

    # Ensure output directory exists
    os.makedirs(os.path.dirname(args.output), exist_ok=True)

    # Write the test file
    with open(args.output, "w") as f:
        f.write(TEST_FILE_CONTENT)

    # Count tests
    test_count = TEST_FILE_CONTENT.count("\n    def test_")
    print(f"Generated {test_count} tests -> {args.output}")
    print(f"Run with: pytest {args.output} -v")

    # Optionally run
    if args.run:
        cmd = [sys.executable, "-m", "pytest", args.output]
        if args.verbose:
            cmd.append("-v")
        print(f"\nRunning: {' '.join(cmd)}\n")
        result = subprocess.run(cmd, cwd=_SKILL_DIR)
        sys.exit(result.returncode)


if __name__ == "__main__":
    main()
