"""
Fallback Predictors -- Neural network sequence predictors with SequenceOutput contract.

Template for: brain_ai/temporal/fallback_predictors.py
Generated by: brain-ai-dev/skills/htm-spatial-temporal-reflex

Drop-in replacements for HTM TM when online Hebbian learning is not needed.
All fallbacks return the same SequenceOutput as TemporalMemory, ensuring
downstream consumers work identically regardless of backend.

Unlike HTM (which uses pure Hebbian rules on buffers), these fallbacks are
standard nn.Modules with trainable parameters updated via gradient descent.
They accept both dense float input and SDR index input, and compute anomaly
using the same overlap-based method as HTM for consistency.
"""

from __future__ import annotations

import abc
import math
import warnings
from collections import deque
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple, Union

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor


# ---------------------------------------------------------------------------
# SequenceOutput contract (shared with temporal_memory.py)
# ---------------------------------------------------------------------------
# When temporal_memory.py is available, import from there. Otherwise define
# locally so this module is self-contained for testing.

try:
    from brain_ai.temporal.temporal_memory import SequenceOutput
except ImportError:
    @dataclass
    class SequenceOutput:
        """Output contract for all temporal sequence predictors.

        Attributes:
            sdr: (B, K) int -- active column indices this step.
            pred_sdr: (B, K_pred) int -- predicted column indices for next step.
            anomaly_score: (B,) float in [0, 1] -- fraction of unpredicted
                active columns.
            aux: dict -- debug/diagnostic info, not used in forward path.
        """

        sdr: Tensor
        pred_sdr: Tensor
        anomaly_score: Tensor
        aux: dict


# ---------------------------------------------------------------------------
# SDR utility imports (with inline fallbacks)
# ---------------------------------------------------------------------------
# Prefer the canonical sdr_utils module when installed; provide minimal
# fallback implementations so this file remains runnable in isolation.

try:
    from brain_ai.temporal.sdr_utils import (
        indices_to_dense,
        dense_to_indices,
        sdr_overlap,
    )
except ImportError:
    def indices_to_dense(indices: Tensor, N: int) -> Tensor:
        """Convert index-form SDR to dense boolean vector.

        Args:
            indices: (B, K) int64 active bit positions.  -1 = padding.
            N: Total number of columns.

        Returns:
            (B, N) bool tensor with True at active positions.
        """
        B, K = indices.shape
        dense = torch.zeros(B, N, dtype=torch.bool, device=indices.device)
        valid = indices >= 0
        safe_idx = indices.clamp(min=0)
        dense.scatter_(1, safe_idx, valid)
        return dense

    def dense_to_indices(dense: Tensor, K: int) -> Tensor:
        """Convert dense SDR to index form by selecting top-K positions.

        Args:
            dense: (B, N) bool or float tensor.
            K: Number of active indices to extract per row.

        Returns:
            (B, K) int64 tensor.  Rows with fewer than K active bits are
            right-padded with -1.
        """
        B, N = dense.shape
        device = dense.device
        actual_k = min(K, N)
        _, top_idx = torch.topk(dense.float(), actual_k, dim=1, sorted=True)
        top_idx = top_idx.long()

        if dense.dtype == torch.bool:
            gathered = torch.gather(dense.long(), 1, top_idx)
            top_idx[gathered == 0] = -1

        if actual_k < K:
            pad = torch.full(
                (B, K - actual_k), -1, dtype=torch.long, device=device
            )
            top_idx = torch.cat([top_idx, pad], dim=1)
        return top_idx

    def sdr_overlap(a: Tensor, b: Tensor) -> Tensor:
        """Count shared active indices between two index-form SDRs.

        Args:
            a: (B, K_a) int64 active indices.
            b: (B, K_b) int64 active indices.

        Returns:
            (B,) int64 -- number of matching indices per row.
        """
        match = (a.unsqueeze(2) == b.unsqueeze(1))
        a_valid = (a >= 0).unsqueeze(2)
        b_valid = (b >= 0).unsqueeze(1)
        match = match & a_valid & b_valid
        return match.any(dim=2).sum(dim=1).long()


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

@dataclass
class FallbackConfig:
    """Configuration for fallback neural-network sequence predictors.

    Attributes:
        backend: Which predictor architecture to use.
            One of ``"lstm"``, ``"gru"``, ``"transformer"``.
        input_size: Dimension of the input feature vector (or N_columns
            when receiving SDR index input that gets converted to dense).
        hidden_size: Size of the recurrent hidden state.
        num_layers: Number of stacked RNN layers or transformer encoder
            layers.
        num_columns: SDR output width (N).  The output projection maps
            hidden_size -> num_columns logits, then top-K selection
            produces the predicted SDR.
        num_active: Number of active columns per output SDR (K).  Must
            be <= num_columns.
        dropout: Dropout probability applied between layers.
        num_heads: Number of attention heads (transformer only).
        max_seq_len: Maximum sequence length for positional encoding and
            the internal buffer (transformer only).
        anomaly_mode: Method for computing anomaly.
            ``"overlap"`` -- SDR overlap-based (same as HTM, default).
            ``"learned"`` -- learned anomaly head on hidden state.
            ``"mse"`` -- mean squared error between predicted and actual.
        anomaly_window: Window size for rolling anomaly likelihood
            smoothing.
    """

    backend: str = "lstm"
    input_size: int = 4096
    hidden_size: int = 2048
    num_layers: int = 2
    num_columns: int = 2048
    num_active: int = 41
    dropout: float = 0.1
    # Transformer-specific
    num_heads: int = 8
    max_seq_len: int = 100
    # Anomaly
    anomaly_mode: str = "overlap"
    anomaly_window: int = 1000

    def __post_init__(self) -> None:
        valid_backends = {"lstm", "gru", "transformer"}
        if self.backend not in valid_backends:
            raise ValueError(
                f"backend must be one of {valid_backends}, got '{self.backend}'"
            )
        if self.num_active > self.num_columns:
            raise ValueError(
                f"num_active ({self.num_active}) must be <= "
                f"num_columns ({self.num_columns})"
            )
        if self.num_active < 1:
            raise ValueError(
                f"num_active must be >= 1, got {self.num_active}"
            )
        if self.hidden_size < 1:
            raise ValueError(
                f"hidden_size must be >= 1, got {self.hidden_size}"
            )
        valid_anomaly_modes = {"overlap", "learned", "mse"}
        if self.anomaly_mode not in valid_anomaly_modes:
            raise ValueError(
                f"anomaly_mode must be one of {valid_anomaly_modes}, "
                f"got '{self.anomaly_mode}'"
            )


# ---------------------------------------------------------------------------
# Positional Encoding (for TransformerPredictor)
# ---------------------------------------------------------------------------

class PositionalEncoding(nn.Module):
    """Standard sinusoidal positional encoding.

    Adds position-dependent signals to input embeddings so the transformer
    can distinguish token order.

    Args:
        d_model: Embedding dimension.
        max_len: Maximum sequence length to pre-compute encodings for.
        dropout: Dropout applied after adding positional encoding.
    """

    def __init__(
        self,
        d_model: int,
        max_len: int = 5000,
        dropout: float = 0.1,
    ) -> None:
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)

        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float32).unsqueeze(1)
        div_term = torch.exp(
            torch.arange(0, d_model, 2, dtype=torch.float32)
            * (-math.log(10000.0) / d_model)
        )
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term[: d_model // 2 + d_model % 2])
        pe = pe.unsqueeze(0)  # (1, max_len, d_model)
        self.register_buffer("pe", pe)

    def forward(self, x: Tensor) -> Tensor:
        """Add positional encoding to input.

        Args:
            x: (B, T, D) input tensor.

        Returns:
            (B, T, D) with positional encoding added.
        """
        x = x + self.pe[:, : x.shape[1]]
        return self.dropout(x)


# ---------------------------------------------------------------------------
# Base Class
# ---------------------------------------------------------------------------

class FallbackPredictor(nn.Module, abc.ABC):
    """Base class for all fallback neural-network sequence predictors.

    Subclasses must implement :meth:`reset` and :meth:`_forward_step`.
    The base class provides the common SDR-conversion, anomaly, and
    SequenceOutput packaging logic.

    Args:
        config: A :class:`FallbackConfig` instance.
    """

    def __init__(self, config: FallbackConfig) -> None:
        super().__init__()
        self.config = config

        # Output projection: hidden_size -> num_columns logits
        self.output_proj = nn.Linear(config.hidden_size, config.num_columns)

        # Optional learned anomaly head
        if config.anomaly_mode == "learned":
            self.anomaly_head = nn.Sequential(
                nn.Linear(config.hidden_size, config.hidden_size // 4),
                nn.ReLU(),
                nn.Linear(config.hidden_size // 4, 1),
                nn.Sigmoid(),
            )

        # Anomaly likelihood tracker (rolling window)
        self._anomaly_history: deque = deque(maxlen=config.anomaly_window)

        # Previous-step SDR for anomaly comparison
        self._prev_sdr: Optional[Tensor] = None

    @abc.abstractmethod
    def reset(self, batch_size: int, device: torch.device) -> None:
        """Reset hidden state for a new sequence.

        Must be called before processing the first step of a new sequence.

        Args:
            batch_size: Number of independent sequences in the batch.
            device: Target device for state tensors.
        """

    @abc.abstractmethod
    def _forward_step(self, x: Tensor) -> Tensor:
        """Process one timestep and return hidden representation.

        Args:
            x: (B, input_size) float input for this timestep.

        Returns:
            (B, hidden_size) hidden state tensor.
        """

    def _ensure_state(self, x: Tensor) -> None:
        """Auto-initialize hidden state if not yet reset."""
        # Subclasses can override for more specific checks.
        pass

    # ----- Input conversion -----

    def _to_dense_input(self, x: Tensor) -> Tensor:
        """Convert SDR index input to dense float if needed.

        If *x* is an integer tensor with last dimension == num_active, it
        is interpreted as SDR index input and converted to a dense
        (B, input_size) float representation.

        Args:
            x: (B, D) float or (B, K) int input.

        Returns:
            (B, input_size) float tensor suitable for the network.
        """
        if x.dtype in (torch.int32, torch.int64):
            if x.shape[-1] == self.config.num_active:
                # SDR indices -> dense float
                dense = indices_to_dense(x, self.config.num_columns).float()
                # If input_size != num_columns, project via zero-padding
                if self.config.input_size != self.config.num_columns:
                    B = dense.shape[0]
                    if self.config.input_size > self.config.num_columns:
                        pad = torch.zeros(
                            B,
                            self.config.input_size - self.config.num_columns,
                            device=dense.device,
                        )
                        dense = torch.cat([dense, pad], dim=1)
                    else:
                        dense = dense[:, : self.config.input_size]
                return dense
        return x

    # ----- SDR extraction -----

    def _logits_to_sdr(self, logits: Tensor) -> Tensor:
        """Convert output logits to SDR by selecting top-K columns.

        Args:
            logits: (B, num_columns) float logits.

        Returns:
            (B, K) int64 sorted SDR indices.
        """
        K = self.config.num_active
        topk_vals, topk_idx = logits.topk(K, dim=-1)
        return topk_idx.sort(dim=-1).values  # sorted for determinism

    def _input_to_sdr(self, x: Tensor) -> Tensor:
        """Extract the current SDR from the (possibly dense) input.

        Args:
            x: Original input before dense conversion.

        Returns:
            (B, K) int64 SDR indices.
        """
        K = self.config.num_active
        N = self.config.num_columns

        if x.dtype in (torch.int32, torch.int64) and x.shape[-1] == K:
            return x.long()

        # Dense float input: threshold and convert
        if x.shape[-1] >= N:
            # Use the first num_columns elements
            dense_cols = x[:, :N]
        else:
            # Pad to num_columns
            B = x.shape[0]
            pad = torch.zeros(B, N - x.shape[-1], device=x.device)
            dense_cols = torch.cat([x, pad], dim=1)

        return dense_to_indices(dense_cols > 0, K)

    # ----- Anomaly computation -----

    def _compute_anomaly(
        self,
        actual_sdr: Tensor,
        pred_sdr: Tensor,
        hidden: Optional[Tensor] = None,
        actual_dense: Optional[Tensor] = None,
        pred_logits: Optional[Tensor] = None,
    ) -> Tensor:
        """Compute anomaly score using the configured method.

        Args:
            actual_sdr: (B, K) int64 -- current step's SDR.
            pred_sdr: (B, K) int64 -- predicted SDR (from previous step).
            hidden: (B, hidden_size) -- hidden state for learned anomaly.
            actual_dense: (B, D) float -- dense input for MSE anomaly.
            pred_logits: (B, N) float -- predicted logits for MSE anomaly.

        Returns:
            (B,) float anomaly scores clamped to [0, 1].
        """
        mode = self.config.anomaly_mode

        if mode == "overlap":
            overlap = sdr_overlap(actual_sdr, pred_sdr)  # (B,) int
            # Count valid (non-padding) entries in actual
            valid_count = (actual_sdr >= 0).sum(dim=-1).float().clamp(min=1.0)
            anomaly = 1.0 - overlap.float() / valid_count
            return anomaly.clamp(0.0, 1.0)

        elif mode == "learned":
            if hidden is None:
                # Fall back to overlap if no hidden state
                overlap = sdr_overlap(actual_sdr, pred_sdr)
                valid_count = (actual_sdr >= 0).sum(dim=-1).float().clamp(min=1.0)
                anomaly = 1.0 - overlap.float() / valid_count
                return anomaly.clamp(0.0, 1.0)
            return self.anomaly_head(hidden).squeeze(-1).clamp(0.0, 1.0)

        elif mode == "mse":
            if pred_logits is not None and actual_dense is not None:
                N = self.config.num_columns
                pred_cols = pred_logits[:, :N]
                actual_cols = actual_dense[:, :N] if actual_dense.shape[-1] >= N else actual_dense
                if actual_cols.shape[-1] < N:
                    pad = torch.zeros(
                        actual_cols.shape[0], N - actual_cols.shape[-1],
                        device=actual_cols.device,
                    )
                    actual_cols = torch.cat([actual_cols, pad], dim=1)
                mse = F.mse_loss(pred_cols, actual_cols, reduction="none").mean(dim=-1)
                return torch.sigmoid(mse).clamp(0.0, 1.0)
            # Fall back to overlap
            overlap = sdr_overlap(actual_sdr, pred_sdr)
            valid_count = (actual_sdr >= 0).sum(dim=-1).float().clamp(min=1.0)
            anomaly = 1.0 - overlap.float() / valid_count
            return anomaly.clamp(0.0, 1.0)

        else:
            # Default to overlap
            overlap = sdr_overlap(actual_sdr, pred_sdr)
            valid_count = (actual_sdr >= 0).sum(dim=-1).float().clamp(min=1.0)
            anomaly = 1.0 - overlap.float() / valid_count
            return anomaly.clamp(0.0, 1.0)

    def _compute_anomaly_likelihood(self, raw_anomaly: Tensor) -> Tensor:
        """Compute rolling anomaly likelihood (per-batch mean).

        Smooths the raw anomaly via a rolling Gaussian estimator, identical
        in spirit to HTM's anomaly likelihood computation.

        Args:
            raw_anomaly: (B,) float raw anomaly scores.

        Returns:
            (B,) float anomaly likelihood in [0, 1].
        """
        mean_val = raw_anomaly.mean().item()
        self._anomaly_history.append(mean_val)

        if len(self._anomaly_history) < 10:
            return raw_anomaly

        hist = list(self._anomaly_history)
        mu = sum(hist) / len(hist)
        var = sum((x - mu) ** 2 for x in hist) / len(hist)
        std = max(var ** 0.5, 1e-6)

        z = (mean_val - mu) / std
        likelihood = 1.0 / (1.0 + math.exp(-1.7 * z))
        likelihood = max(0.0, min(1.0, likelihood))

        return torch.full_like(raw_anomaly, likelihood)

    # ----- Main interface -----

    def step(self, x: Tensor, learn: bool = True) -> SequenceOutput:
        """Process one timestep and return a SequenceOutput.

        Args:
            x: Input for this step.  Can be:
                - (B, input_size) float -- dense feature vector.
                - (B, K) int -- SDR index input (converted to dense internally).
            learn: Whether this is a training step.  When False, hidden
                state gradients are detached to prevent backprop through
                time beyond this step.

        Returns:
            :class:`SequenceOutput` with sdr, pred_sdr, anomaly_score, aux.
        """
        # Preserve original for SDR extraction
        x_orig = x

        # Convert integer SDR indices to dense float
        x_dense = self._to_dense_input(x)

        # Auto-init state if needed
        self._ensure_state(x_dense)

        # Forward through the network
        hidden = self._forward_step(x_dense)  # (B, hidden_size)

        # Compute output logits and predicted SDR
        logits = self.output_proj(hidden)     # (B, num_columns)
        pred_sdr = self._logits_to_sdr(logits)  # (B, K)

        # Extract current input SDR
        current_sdr = self._input_to_sdr(x_orig)  # (B, K)

        # Anomaly: compare current actual vs what was predicted last step
        if self._prev_sdr is not None:
            prev_pred = self._prev_sdr
            # Align batch sizes (handle reset or batch change)
            if prev_pred.shape[0] != current_sdr.shape[0]:
                anomaly = torch.ones(
                    current_sdr.shape[0], device=current_sdr.device
                )
            else:
                anomaly = self._compute_anomaly(
                    actual_sdr=current_sdr,
                    pred_sdr=prev_pred,
                    hidden=hidden,
                    actual_dense=x_dense,
                    pred_logits=logits,
                )
        else:
            # First step: maximum anomaly (no prediction available)
            anomaly = torch.ones(current_sdr.shape[0], device=current_sdr.device)

        # Store predicted SDR for next step's anomaly computation
        self._prev_sdr = pred_sdr.detach().clone()

        # Build aux dict
        anomaly_likelihood = self._compute_anomaly_likelihood(anomaly)
        aux: Dict[str, Tensor] = {
            "logits": logits,
            "hidden": hidden,
            "anomaly_likelihood": anomaly_likelihood,
        }

        return SequenceOutput(
            sdr=current_sdr,
            pred_sdr=pred_sdr,
            anomaly_score=anomaly,
            aux=aux,
        )

    def predict(
        self,
        x_seq: Tensor,
        learn: bool = True,
    ) -> List[SequenceOutput]:
        """Process a full sequence and return per-step SequenceOutputs.

        Args:
            x_seq: (B, T, D) float or (B, T, K) int input sequence.
            learn: Whether this is a training pass.

        Returns:
            List of T :class:`SequenceOutput` instances.
        """
        T = x_seq.shape[1]
        results: List[SequenceOutput] = []
        for t in range(T):
            out = self.step(x_seq[:, t], learn=learn)
            results.append(out)
        return results

    def forward(
        self,
        x: Tensor,
        learn: bool = True,
    ) -> SequenceOutput:
        """Alias for :meth:`step` when input is (B, D).

        If input is (B, T, D), delegates to :meth:`predict` and returns
        the last step's output.

        Args:
            x: (B, D) or (B, T, D) input.
            learn: Training flag.

        Returns:
            :class:`SequenceOutput` for the (last) timestep.
        """
        if x.dim() == 3:
            results = self.predict(x, learn=learn)
            return results[-1]
        return self.step(x, learn=learn)


# ---------------------------------------------------------------------------
# LSTM Predictor
# ---------------------------------------------------------------------------

class LSTMPredictor(FallbackPredictor):
    """LSTM-based fallback sequence predictor.

    Maintains (h, c) hidden state across steps.  Each call to
    :meth:`_forward_step` runs one timestep through the LSTM and returns
    the hidden representation.

    Args:
        config: :class:`FallbackConfig` with ``backend="lstm"``.
    """

    def __init__(self, config: FallbackConfig) -> None:
        super().__init__(config)
        self.lstm = nn.LSTM(
            input_size=config.input_size,
            hidden_size=config.hidden_size,
            num_layers=config.num_layers,
            batch_first=True,
            dropout=config.dropout if config.num_layers > 1 else 0.0,
        )
        self._h: Optional[Tensor] = None
        self._c: Optional[Tensor] = None

    def reset(self, batch_size: int, device: torch.device) -> None:
        """Reset LSTM hidden state.

        Args:
            batch_size: Batch size for the new sequence.
            device: Device for state tensors.
        """
        self._h = torch.zeros(
            self.config.num_layers, batch_size, self.config.hidden_size,
            device=device,
        )
        self._c = torch.zeros(
            self.config.num_layers, batch_size, self.config.hidden_size,
            device=device,
        )
        self._prev_sdr = None
        self._anomaly_history.clear()

    def _ensure_state(self, x: Tensor) -> None:
        """Auto-initialize LSTM state if not yet reset."""
        B = x.shape[0]
        device = x.device
        if self._h is None or self._c is None:
            self.reset(B, device)
        elif self._h.shape[1] != B:
            self.reset(B, device)

    def _forward_step(self, x: Tensor) -> Tensor:
        """Run one LSTM timestep.

        Args:
            x: (B, input_size) float input.

        Returns:
            (B, hidden_size) LSTM output.
        """
        # (B, D) -> (B, 1, D) for LSTM
        out, (self._h, self._c) = self.lstm(
            x.unsqueeze(1), (self._h, self._c)
        )
        return out.squeeze(1)  # (B, hidden_size)


# ---------------------------------------------------------------------------
# GRU Predictor
# ---------------------------------------------------------------------------

class GRUPredictor(FallbackPredictor):
    """GRU-based fallback sequence predictor.

    Lighter-weight alternative to LSTM with only a single hidden state
    tensor (no cell state).

    Args:
        config: :class:`FallbackConfig` with ``backend="gru"``.
    """

    def __init__(self, config: FallbackConfig) -> None:
        super().__init__(config)
        self.gru = nn.GRU(
            input_size=config.input_size,
            hidden_size=config.hidden_size,
            num_layers=config.num_layers,
            batch_first=True,
            dropout=config.dropout if config.num_layers > 1 else 0.0,
        )
        self._h: Optional[Tensor] = None

    def reset(self, batch_size: int, device: torch.device) -> None:
        """Reset GRU hidden state.

        Args:
            batch_size: Batch size for the new sequence.
            device: Device for state tensors.
        """
        self._h = torch.zeros(
            self.config.num_layers, batch_size, self.config.hidden_size,
            device=device,
        )
        self._prev_sdr = None
        self._anomaly_history.clear()

    def _ensure_state(self, x: Tensor) -> None:
        """Auto-initialize GRU state if not yet reset."""
        B = x.shape[0]
        device = x.device
        if self._h is None:
            self.reset(B, device)
        elif self._h.shape[1] != B:
            self.reset(B, device)

    def _forward_step(self, x: Tensor) -> Tensor:
        """Run one GRU timestep.

        Args:
            x: (B, input_size) float input.

        Returns:
            (B, hidden_size) GRU output.
        """
        out, self._h = self.gru(x.unsqueeze(1), self._h)
        return out.squeeze(1)  # (B, hidden_size)


# ---------------------------------------------------------------------------
# Transformer Predictor
# ---------------------------------------------------------------------------

class TransformerPredictor(FallbackPredictor):
    """Transformer-based fallback sequence predictor.

    Maintains an internal sequence buffer and applies causal self-attention.
    Each call to :meth:`_forward_step` appends the input to the buffer
    and runs the full transformer over the buffered history up to
    ``max_seq_len`` tokens.

    Args:
        config: :class:`FallbackConfig` with ``backend="transformer"``.
    """

    def __init__(self, config: FallbackConfig) -> None:
        super().__init__(config)

        # Input projection: input_size -> hidden_size
        self.input_proj = nn.Linear(config.input_size, config.hidden_size)

        # Sinusoidal positional encoding
        self.pos_encoding = PositionalEncoding(
            d_model=config.hidden_size,
            max_len=config.max_seq_len,
            dropout=config.dropout,
        )

        # Transformer encoder with causal masking
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=config.hidden_size,
            nhead=config.num_heads,
            dim_feedforward=config.hidden_size * 4,
            dropout=config.dropout,
            batch_first=True,
        )
        self.transformer = nn.TransformerEncoder(
            encoder_layer, config.num_layers
        )

        # Buffer state
        self._buffer: Optional[Tensor] = None
        self._buffer_len: int = 0

    def reset(self, batch_size: int, device: torch.device) -> None:
        """Reset transformer buffer for a new sequence.

        Args:
            batch_size: Batch size for the new sequence.
            device: Device for state tensors.
        """
        self._buffer = torch.zeros(
            batch_size,
            self.config.max_seq_len,
            self.config.hidden_size,
            device=device,
        )
        self._buffer_len = 0
        self._prev_sdr = None
        self._anomaly_history.clear()

    def _ensure_state(self, x: Tensor) -> None:
        """Auto-initialize buffer if not yet reset."""
        B = x.shape[0]
        device = x.device
        if self._buffer is None:
            self.reset(B, device)
        elif self._buffer.shape[0] != B:
            self.reset(B, device)

    def _forward_step(self, x: Tensor) -> Tensor:
        """Run one transformer step with causal masking.

        Projects the input, appends to the internal buffer, runs the
        transformer over the buffer with a causal mask, and returns the
        last position's representation.

        Args:
            x: (B, input_size) float input.

        Returns:
            (B, hidden_size) output from the last buffer position.
        """
        # Project input to hidden dimension
        proj = self.input_proj(x)  # (B, hidden_size)

        # Append to buffer (shift left when full)
        if self._buffer_len < self.config.max_seq_len:
            self._buffer[:, self._buffer_len] = proj
            self._buffer_len += 1
        else:
            # Shift buffer left and insert at the end
            self._buffer[:, :-1] = self._buffer[:, 1:].clone()
            self._buffer[:, -1] = proj

        # Slice active portion of buffer
        seq_len = min(self._buffer_len, self.config.max_seq_len)
        buf = self._buffer[:, :seq_len]  # (B, seq_len, hidden)

        # Add positional encoding
        buf = self.pos_encoding(buf)

        # Causal mask: prevent attending to future positions
        mask = nn.Transformer.generate_square_subsequent_mask(
            seq_len, device=x.device
        )
        out = self.transformer(buf, mask=mask)  # (B, seq_len, hidden)

        return out[:, -1]  # (B, hidden_size) -- last position


# ---------------------------------------------------------------------------
# Factory Function
# ---------------------------------------------------------------------------

def create_fallback_predictor(config: FallbackConfig) -> FallbackPredictor:
    """Create a fallback predictor instance from config.

    Args:
        config: :class:`FallbackConfig` specifying the backend and
            hyperparameters.

    Returns:
        An instance of :class:`LSTMPredictor`, :class:`GRUPredictor`,
        or :class:`TransformerPredictor`.

    Raises:
        ValueError: If ``config.backend`` is not recognized.
    """
    if config.backend == "lstm":
        return LSTMPredictor(config)
    elif config.backend == "gru":
        return GRUPredictor(config)
    elif config.backend == "transformer":
        return TransformerPredictor(config)
    else:
        raise ValueError(
            f"Unknown backend: '{config.backend}'. "
            f"Expected one of: lstm, gru, transformer"
        )


# ---------------------------------------------------------------------------
# Unified Interface: TemporalPredictor
# ---------------------------------------------------------------------------

class TemporalPredictor(nn.Module):
    """Unified temporal prediction interface.

    Auto-selects HTM or a fallback neural-network predictor based on
    availability and configuration.  All backends expose the same
    ``reset`` / ``step`` / ``predict`` API returning :class:`SequenceOutput`.

    Backend selection priority for ``"auto"``:
        1. ``htm`` (htm.core library, if available)
        2. ``accelerated_htm`` (AHTM with ReflexMemory, if available)
        3. ``lstm`` (always available)

    Args:
        backend: One of ``"auto"``, ``"htm"``, ``"accelerated_htm"``,
            ``"lstm"``, ``"gru"``, ``"transformer"``.
        input_size: Input feature dimension.
        hidden_size: Hidden state size (for neural backends).
        num_columns: SDR output width (N).
        num_active: Active bits per SDR (K).
        **kwargs: Additional keyword arguments forwarded to the backend
            constructor (e.g. ``num_layers``, ``num_heads``).
    """

    def __init__(
        self,
        backend: str = "auto",
        input_size: int = 4096,
        hidden_size: int = 2048,
        num_columns: int = 2048,
        num_active: int = 41,
        **kwargs,
    ) -> None:
        super().__init__()
        self.requested_backend = backend
        self.active_backend: str = ""

        # Track config for introspection
        self._input_size = input_size
        self._hidden_size = hidden_size
        self._num_columns = num_columns
        self._num_active = num_active

        if backend == "auto":
            self._predictor = self._auto_select(
                input_size, hidden_size, num_columns, num_active, **kwargs
            )
        elif backend in ("htm", "accelerated_htm"):
            self._predictor = self._create_htm_backend(
                backend, input_size, num_columns, num_active, **kwargs
            )
        elif backend in ("lstm", "gru", "transformer"):
            cfg = FallbackConfig(
                backend=backend,
                input_size=input_size,
                hidden_size=hidden_size,
                num_columns=num_columns,
                num_active=num_active,
                **kwargs,
            )
            self._predictor = create_fallback_predictor(cfg)
            self.active_backend = backend
        else:
            raise ValueError(
                f"Unknown backend: '{backend}'. Expected one of: "
                f"auto, htm, accelerated_htm, lstm, gru, transformer"
            )

    def _auto_select(
        self,
        input_size: int,
        hidden_size: int,
        num_columns: int,
        num_active: int,
        **kwargs,
    ) -> nn.Module:
        """Try backends in priority order: htm -> accelerated_htm -> lstm."""
        # Try HTM
        try:
            predictor = self._create_htm_backend(
                "htm", input_size, num_columns, num_active, **kwargs
            )
            return predictor
        except Exception:
            pass

        # Try accelerated HTM
        try:
            predictor = self._create_htm_backend(
                "accelerated_htm", input_size, num_columns, num_active, **kwargs
            )
            return predictor
        except Exception:
            pass

        # Fall back to LSTM
        cfg = FallbackConfig(
            backend="lstm",
            input_size=input_size,
            hidden_size=hidden_size,
            num_columns=num_columns,
            num_active=num_active,
        )
        self.active_backend = "lstm"
        return create_fallback_predictor(cfg)

    def _create_htm_backend(
        self,
        backend: str,
        input_size: int,
        num_columns: int,
        num_active: int,
        **kwargs,
    ) -> nn.Module:
        """Create an HTM-based backend.

        This imports from brain_ai.temporal.htm and wraps it to return
        SequenceOutput.

        Raises:
            ImportError: If HTM modules are not available.
        """
        if backend == "htm":
            from brain_ai.temporal.htm import HTMLayer, HTMConfig
            htm_config = HTMConfig(
                input_size=input_size,
                column_count=num_columns,
                sparsity=num_active / num_columns,
                **{k: v for k, v in kwargs.items()
                   if k in HTMConfig.__dataclass_fields__},
            )
            predictor = _HTMSequenceOutputWrapper(
                HTMLayer(htm_config), num_active=num_active
            )
            self.active_backend = "htm"
            return predictor

        elif backend == "accelerated_htm":
            from brain_ai.temporal.htm import create_accelerated_htm
            ahtm = create_accelerated_htm(
                input_size=input_size,
                column_count=num_columns,
                sparsity=num_active / num_columns,
                **{k: v for k, v in kwargs.items()
                   if k not in ("hidden_size",)},
            )
            predictor = _HTMSequenceOutputWrapper(
                ahtm, num_active=num_active
            )
            self.active_backend = "accelerated_htm"
            return predictor

        raise ValueError(f"Unknown HTM backend: {backend}")

    def reset(self, batch_size: int = 1, device: Optional[torch.device] = None) -> None:
        """Reset state for a new sequence.

        Args:
            batch_size: Number of sequences in the batch.
            device: Target device.
        """
        if device is None:
            # Infer device from model parameters or default to CPU
            params = list(self.parameters())
            if params:
                device = params[0].device
            else:
                device = torch.device("cpu")

        if isinstance(self._predictor, FallbackPredictor):
            self._predictor.reset(batch_size, device)
        elif hasattr(self._predictor, "reset"):
            self._predictor.reset(batch_size, device)

    def step(self, x: Tensor, learn: bool = True) -> SequenceOutput:
        """Process one timestep.

        Args:
            x: (B, D) float or (B, K) int input.
            learn: Whether to learn from this step.

        Returns:
            :class:`SequenceOutput`.
        """
        if isinstance(self._predictor, FallbackPredictor):
            return self._predictor.step(x, learn=learn)
        elif isinstance(self._predictor, _HTMSequenceOutputWrapper):
            return self._predictor.step(x, learn=learn)
        else:
            # Generic fallback for unknown wrapper types
            result = self._predictor(x, learn=learn)
            return result

    def predict(
        self, x_seq: Tensor, learn: bool = True
    ) -> List[SequenceOutput]:
        """Process a full sequence.

        Args:
            x_seq: (B, T, D) input sequence.
            learn: Whether to learn.

        Returns:
            List of T :class:`SequenceOutput`.
        """
        if isinstance(self._predictor, FallbackPredictor):
            return self._predictor.predict(x_seq, learn=learn)
        else:
            T = x_seq.shape[1]
            results = []
            for t in range(T):
                out = self.step(x_seq[:, t], learn=learn)
                results.append(out)
            return results

    def forward(self, x: Tensor, learn: bool = True) -> SequenceOutput:
        """Forward pass -- dispatches to step or predict.

        Args:
            x: (B, D) or (B, T, D) input.
            learn: Training flag.

        Returns:
            :class:`SequenceOutput`.
        """
        if x.dim() == 3:
            results = self.predict(x, learn=learn)
            return results[-1]
        return self.step(x, learn=learn)


# ---------------------------------------------------------------------------
# HTM Wrapper (adapts old dict-return HTM to SequenceOutput)
# ---------------------------------------------------------------------------

class _HTMSequenceOutputWrapper(nn.Module):
    """Wraps an HTM module to return SequenceOutput instead of dicts.

    This adapter translates the legacy ``Dict[str, Tensor]`` return
    format from ``HTMLayer`` / ``AcceleratedHTM`` into the standardized
    :class:`SequenceOutput` contract.

    Args:
        htm_module: An ``HTMLayer`` or ``AcceleratedHTM`` instance.
        num_active: K for output SDR width.
    """

    def __init__(self, htm_module: nn.Module, num_active: int = 41) -> None:
        super().__init__()
        self.htm = htm_module
        self.num_active = num_active

    def reset(self, batch_size: int = 1, device: Optional[torch.device] = None) -> None:
        """Reset the wrapped HTM module."""
        if hasattr(self.htm, "reset"):
            self.htm.reset()

    def step(self, x: Tensor, learn: bool = True) -> SequenceOutput:
        """Process one step through HTM and return SequenceOutput.

        Args:
            x: (B, D) or (D,) input.
            learn: Whether to learn.

        Returns:
            :class:`SequenceOutput`.
        """
        result = self.htm(x, learn=learn)

        # Extract SDRs from dict results
        if "features" in result:
            features = result["features"]
            sdr = dense_to_indices(features > 0, self.num_active)
        elif "active_cells" in result:
            sdr = dense_to_indices(
                result["active_cells"] > 0, self.num_active
            )
        else:
            B = x.shape[0] if x.dim() == 2 else 1
            sdr = torch.full(
                (B, self.num_active), -1, dtype=torch.long, device=x.device
            )

        if "predictive_cells" in result:
            pred_sdr = dense_to_indices(
                result["predictive_cells"] > 0, self.num_active
            )
        else:
            pred_sdr = torch.full_like(sdr, -1)

        # Ensure 2D
        if sdr.dim() == 1:
            sdr = sdr.unsqueeze(0)
        if pred_sdr.dim() == 1:
            pred_sdr = pred_sdr.unsqueeze(0)

        anomaly = result.get("anomaly", torch.tensor(1.0, device=x.device))
        if anomaly.dim() == 0:
            anomaly = anomaly.unsqueeze(0)

        aux = {
            k: v for k, v in result.items()
            if k not in ("features", "active_cells", "predictive_cells", "anomaly")
        }

        return SequenceOutput(
            sdr=sdr,
            pred_sdr=pred_sdr,
            anomaly_score=anomaly,
            aux=aux,
        )

    def forward(self, x: Tensor, learn: bool = True) -> SequenceOutput:
        """Forward pass."""
        return self.step(x, learn=learn)


# ---------------------------------------------------------------------------
# Self-Test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys
    import traceback

    _pass = 0
    _fail = 0

    def _test(name: str, fn) -> None:
        global _pass, _fail
        try:
            fn()
            print(f"  [PASS] {name}")
            _pass += 1
        except Exception as e:
            print(f"  [FAIL] {name}: {e}")
            traceback.print_exc()
            _fail += 1

    print("=" * 60)
    print("Fallback Predictors -- Self-Test Suite")
    print("=" * 60)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}\n")

    # Common test dimensions (small for fast tests)
    B, D, H, N, K = 4, 128, 64, 128, 10

    # ---- Group 1: FallbackConfig validation ----
    print("--- 1. FallbackConfig validation ---")

    def test_config_defaults():
        cfg = FallbackConfig()
        assert cfg.backend == "lstm"
        assert cfg.input_size == 4096
        assert cfg.hidden_size == 2048
        assert cfg.num_columns == 2048
        assert cfg.num_active == 41
    _test("default values", test_config_defaults)

    def test_config_invalid_backend():
        try:
            FallbackConfig(backend="invalid")
            assert False, "Should raise ValueError"
        except ValueError:
            pass
    _test("invalid backend raises ValueError", test_config_invalid_backend)

    def test_config_num_active_gt_columns():
        try:
            FallbackConfig(num_active=3000, num_columns=2048)
            assert False, "Should raise ValueError"
        except ValueError:
            pass
    _test("num_active > num_columns raises", test_config_num_active_gt_columns)

    def test_config_invalid_anomaly_mode():
        try:
            FallbackConfig(anomaly_mode="bogus")
            assert False, "Should raise ValueError"
        except ValueError:
            pass
    _test("invalid anomaly_mode raises", test_config_invalid_anomaly_mode)

    # ---- Group 2: LSTMPredictor: reset clears state ----
    print("\n--- 2. LSTMPredictor reset ---")

    def test_lstm_reset_clears_state():
        cfg = FallbackConfig(backend="lstm", input_size=D, hidden_size=H,
                             num_columns=N, num_active=K)
        model = LSTMPredictor(cfg).to(device)
        model.reset(B, device)
        assert model._h is not None
        assert model._c is not None
        assert model._h.shape == (cfg.num_layers, B, H)
        assert model._c.shape == (cfg.num_layers, B, H)
        assert model._prev_sdr is None
    _test("reset initializes h, c to zeros", test_lstm_reset_clears_state)

    # ---- Group 3: LSTMPredictor: step returns SequenceOutput ----
    print("\n--- 3. LSTMPredictor step returns SequenceOutput ---")

    def test_lstm_step_returns_sequence_output():
        cfg = FallbackConfig(backend="lstm", input_size=D, hidden_size=H,
                             num_columns=N, num_active=K)
        model = LSTMPredictor(cfg).to(device)
        model.reset(B, device)
        x = torch.randn(B, D, device=device)
        out = model.step(x)
        assert isinstance(out, SequenceOutput)
        assert out.sdr.shape == (B, K)
        assert out.pred_sdr.shape == (B, K)
        assert out.anomaly_score.shape == (B,)
        assert "logits" in out.aux
        assert "hidden" in out.aux
    _test("step returns SequenceOutput with correct shapes",
          test_lstm_step_returns_sequence_output)

    # ---- Group 4: LSTMPredictor: predict processes sequence ----
    print("\n--- 4. LSTMPredictor predict ---")

    def test_lstm_predict_sequence():
        cfg = FallbackConfig(backend="lstm", input_size=D, hidden_size=H,
                             num_columns=N, num_active=K)
        model = LSTMPredictor(cfg).to(device)
        model.reset(B, device)
        T = 5
        x_seq = torch.randn(B, T, D, device=device)
        results = model.predict(x_seq)
        assert len(results) == T
        for r in results:
            assert isinstance(r, SequenceOutput)
            assert r.sdr.shape == (B, K)
    _test("predict returns T SequenceOutputs", test_lstm_predict_sequence)

    # ---- Group 5: LSTMPredictor: anomaly in [0, 1] ----
    print("\n--- 5. LSTMPredictor anomaly bounds ---")

    def test_lstm_anomaly_bounds():
        cfg = FallbackConfig(backend="lstm", input_size=D, hidden_size=H,
                             num_columns=N, num_active=K)
        model = LSTMPredictor(cfg).to(device)
        model.reset(B, device)
        for _ in range(10):
            x = torch.randn(B, D, device=device)
            out = model.step(x)
            assert (out.anomaly_score >= 0.0).all(), \
                f"Anomaly below 0: {out.anomaly_score}"
            assert (out.anomaly_score <= 1.0).all(), \
                f"Anomaly above 1: {out.anomaly_score}"
    _test("anomaly always in [0, 1]", test_lstm_anomaly_bounds)

    # ---- Group 6: LSTMPredictor: gradient flows through ----
    print("\n--- 6. LSTMPredictor gradient flow ---")

    def test_lstm_gradient_flow():
        cfg = FallbackConfig(backend="lstm", input_size=D, hidden_size=H,
                             num_columns=N, num_active=K)
        model = LSTMPredictor(cfg).to(device)
        model.reset(B, device)
        x = torch.randn(B, D, device=device, requires_grad=True)
        out = model.step(x)
        loss = out.aux["logits"].sum()
        loss.backward()
        assert x.grad is not None, "Gradient should flow to input"
        # Check model parameters have gradients
        has_grad = any(p.grad is not None for p in model.parameters())
        assert has_grad, "Model parameters should have gradients"
    _test("gradients flow through step", test_lstm_gradient_flow)

    # ---- Group 7: GRUPredictor: same contract as LSTM ----
    print("\n--- 7. GRUPredictor contract ---")

    def test_gru_step_returns_sequence_output():
        cfg = FallbackConfig(backend="gru", input_size=D, hidden_size=H,
                             num_columns=N, num_active=K)
        model = GRUPredictor(cfg).to(device)
        model.reset(B, device)
        x = torch.randn(B, D, device=device)
        out = model.step(x)
        assert isinstance(out, SequenceOutput)
        assert out.sdr.shape == (B, K)
        assert out.pred_sdr.shape == (B, K)
        assert out.anomaly_score.shape == (B,)
    _test("GRU step returns SequenceOutput",
          test_gru_step_returns_sequence_output)

    # ---- Group 8: GRUPredictor: step/predict shapes ----
    print("\n--- 8. GRUPredictor shapes ---")

    def test_gru_predict_shapes():
        cfg = FallbackConfig(backend="gru", input_size=D, hidden_size=H,
                             num_columns=N, num_active=K)
        model = GRUPredictor(cfg).to(device)
        model.reset(B, device)
        T = 7
        x_seq = torch.randn(B, T, D, device=device)
        results = model.predict(x_seq)
        assert len(results) == T
        for r in results:
            assert r.sdr.shape == (B, K)
            assert r.pred_sdr.shape == (B, K)
    _test("GRU predict shapes", test_gru_predict_shapes)

    def test_gru_reset_clears_state():
        cfg = FallbackConfig(backend="gru", input_size=D, hidden_size=H,
                             num_columns=N, num_active=K)
        model = GRUPredictor(cfg).to(device)
        model.reset(B, device)
        assert model._h.shape == (cfg.num_layers, B, H)
        assert model._prev_sdr is None
    _test("GRU reset clears state", test_gru_reset_clears_state)

    # ---- Group 9: TransformerPredictor: reset clears buffer ----
    print("\n--- 9. TransformerPredictor reset ---")

    def test_transformer_reset_clears_buffer():
        cfg = FallbackConfig(backend="transformer", input_size=D,
                             hidden_size=H, num_columns=N, num_active=K,
                             num_heads=4, max_seq_len=20)
        model = TransformerPredictor(cfg).to(device)
        model.reset(B, device)
        assert model._buffer is not None
        assert model._buffer.shape == (B, 20, H)
        assert model._buffer_len == 0
    _test("reset clears buffer and sets length to 0",
          test_transformer_reset_clears_buffer)

    # ---- Group 10: TransformerPredictor: step returns SequenceOutput ----
    print("\n--- 10. TransformerPredictor step ---")

    def test_transformer_step_returns_sequence_output():
        cfg = FallbackConfig(backend="transformer", input_size=D,
                             hidden_size=H, num_columns=N, num_active=K,
                             num_heads=4, max_seq_len=20)
        model = TransformerPredictor(cfg).to(device)
        model.reset(B, device)
        x = torch.randn(B, D, device=device)
        out = model.step(x)
        assert isinstance(out, SequenceOutput)
        assert out.sdr.shape == (B, K)
        assert out.pred_sdr.shape == (B, K)
        assert out.anomaly_score.shape == (B,)
    _test("step returns SequenceOutput",
          test_transformer_step_returns_sequence_output)

    # ---- Group 11: TransformerPredictor: causal masking ----
    print("\n--- 11. TransformerPredictor causal masking ---")

    def test_transformer_causal_masking():
        """Verify that rerunning identical steps produces identical output."""
        cfg = FallbackConfig(backend="transformer", input_size=D,
                             hidden_size=H, num_columns=N, num_active=K,
                             num_heads=4, max_seq_len=20, dropout=0.0)
        model = TransformerPredictor(cfg).to(device)
        model.train(False)

        # Run 2 steps
        model.reset(1, device)
        x1 = torch.randn(1, D, device=device)
        x2 = torch.randn(1, D, device=device)
        model.step(x1)
        out_a2 = model.step(x2)
        logits_a2 = out_a2.aux["logits"].detach().clone()

        # Run again with same inputs -- step 2 output should be identical
        model.reset(1, device)
        model.step(x1)
        out_b2 = model.step(x2)
        logits_b2 = out_b2.aux["logits"].detach().clone()

        assert torch.allclose(logits_a2, logits_b2, atol=1e-5), \
            "With same inputs, logits should match"
    _test("causal masking preserves past outputs",
          test_transformer_causal_masking)

    # ---- Group 12: TransformerPredictor: buffer wrapping ----
    print("\n--- 12. TransformerPredictor buffer wrapping ---")

    def test_transformer_buffer_wrapping():
        max_len = 5
        cfg = FallbackConfig(backend="transformer", input_size=D,
                             hidden_size=H, num_columns=N, num_active=K,
                             num_heads=4, max_seq_len=max_len)
        model = TransformerPredictor(cfg).to(device)
        model.reset(B, device)

        # Feed more steps than max_seq_len
        for i in range(max_len + 3):
            x = torch.randn(B, D, device=device)
            out = model.step(x)
            assert isinstance(out, SequenceOutput)

        # Buffer length counter keeps incrementing but buffer is capped
        assert model._buffer_len == max_len + 3
    _test("buffer handles more steps than max_seq_len",
          test_transformer_buffer_wrapping)

    # ---- Group 13: All backends: sdr shape (B, K) ----
    print("\n--- 13. All backends: sdr shape ---")

    def test_all_backends_sdr_shape():
        for backend_name in ("lstm", "gru", "transformer"):
            extra = {}
            if backend_name == "transformer":
                extra = {"num_heads": 4, "max_seq_len": 20}
            cfg = FallbackConfig(backend=backend_name, input_size=D,
                                 hidden_size=H, num_columns=N,
                                 num_active=K, **extra)
            model = create_fallback_predictor(cfg).to(device)
            model.reset(B, device)
            x = torch.randn(B, D, device=device)
            out = model.step(x)
            assert out.sdr.shape == (B, K), \
                f"{backend_name}: sdr shape {out.sdr.shape} != ({B}, {K})"
            assert out.sdr.dtype in (torch.int32, torch.int64), \
                f"{backend_name}: sdr dtype {out.sdr.dtype} is not integer"
    _test("sdr shape is (B, K) int for all backends",
          test_all_backends_sdr_shape)

    # ---- Group 14: All backends: pred_sdr shape (B, K) ----
    print("\n--- 14. All backends: pred_sdr shape ---")

    def test_all_backends_pred_sdr_shape():
        for backend_name in ("lstm", "gru", "transformer"):
            extra = {}
            if backend_name == "transformer":
                extra = {"num_heads": 4, "max_seq_len": 20}
            cfg = FallbackConfig(backend=backend_name, input_size=D,
                                 hidden_size=H, num_columns=N,
                                 num_active=K, **extra)
            model = create_fallback_predictor(cfg).to(device)
            model.reset(B, device)
            x = torch.randn(B, D, device=device)
            out = model.step(x)
            assert out.pred_sdr.shape == (B, K), \
                f"{backend_name}: pred_sdr shape {out.pred_sdr.shape}"
            assert out.pred_sdr.dtype in (torch.int32, torch.int64)
    _test("pred_sdr shape is (B, K) int for all backends",
          test_all_backends_pred_sdr_shape)

    # ---- Group 15: All backends: SDR index input (int) accepted ----
    print("\n--- 15. All backends: SDR index input ---")

    def test_all_backends_sdr_index_input():
        for backend_name in ("lstm", "gru", "transformer"):
            extra = {}
            if backend_name == "transformer":
                extra = {"num_heads": 4, "max_seq_len": 20}
            cfg = FallbackConfig(backend=backend_name, input_size=N,
                                 hidden_size=H, num_columns=N,
                                 num_active=K, **extra)
            model = create_fallback_predictor(cfg).to(device)
            model.reset(B, device)
            # Create SDR index input: (B, K) int
            sdr_input = torch.randint(0, N, (B, K), device=device,
                                      dtype=torch.long)
            out = model.step(sdr_input)
            assert isinstance(out, SequenceOutput), \
                f"{backend_name}: should accept SDR index input"
            assert out.sdr.shape == (B, K)
    _test("SDR index (int) input accepted by all backends",
          test_all_backends_sdr_index_input)

    # ---- Group 16: Factory: create_fallback_predictor ----
    print("\n--- 16. Factory function ---")

    def test_factory_lstm():
        cfg = FallbackConfig(backend="lstm", input_size=D, hidden_size=H,
                             num_columns=N, num_active=K)
        model = create_fallback_predictor(cfg)
        assert isinstance(model, LSTMPredictor)
    _test("factory creates LSTMPredictor", test_factory_lstm)

    def test_factory_gru():
        cfg = FallbackConfig(backend="gru", input_size=D, hidden_size=H,
                             num_columns=N, num_active=K)
        model = create_fallback_predictor(cfg)
        assert isinstance(model, GRUPredictor)
    _test("factory creates GRUPredictor", test_factory_gru)

    def test_factory_transformer():
        cfg = FallbackConfig(backend="transformer", input_size=D,
                             hidden_size=H, num_columns=N, num_active=K,
                             num_heads=4)
        model = create_fallback_predictor(cfg)
        assert isinstance(model, TransformerPredictor)
    _test("factory creates TransformerPredictor", test_factory_transformer)

    # ---- Group 17: TemporalPredictor: auto backend selection ----
    print("\n--- 17. TemporalPredictor auto selection ---")

    def test_temporal_predictor_auto():
        tp = TemporalPredictor(
            backend="auto", input_size=D, hidden_size=H,
            num_columns=N, num_active=K
        ).to(device)
        # In test env without htm.core, should fall back to lstm
        assert tp.active_backend in ("lstm", "htm", "accelerated_htm"), \
            f"Auto should select a valid backend, got '{tp.active_backend}'"
        tp.reset(B, device)
        x = torch.randn(B, D, device=device)
        out = tp.step(x)
        assert isinstance(out, SequenceOutput)
    _test("auto selects valid backend and returns SequenceOutput",
          test_temporal_predictor_auto)

    def test_temporal_predictor_explicit_lstm():
        tp = TemporalPredictor(
            backend="lstm", input_size=D, hidden_size=H,
            num_columns=N, num_active=K
        ).to(device)
        assert tp.active_backend == "lstm"
        tp.reset(B, device)
        x = torch.randn(B, D, device=device)
        out = tp.step(x)
        assert isinstance(out, SequenceOutput)
    _test("explicit lstm backend", test_temporal_predictor_explicit_lstm)

    # ---- Group 18: TemporalPredictor: backend switching ----
    print("\n--- 18. TemporalPredictor backend switching ---")

    def test_temporal_predictor_all_explicit_backends():
        for backend_name in ("lstm", "gru", "transformer"):
            extra = {}
            if backend_name == "transformer":
                extra = {"num_heads": 4, "max_seq_len": 20}
            tp = TemporalPredictor(
                backend=backend_name, input_size=D, hidden_size=H,
                num_columns=N, num_active=K, **extra
            ).to(device)
            assert tp.active_backend == backend_name, \
                f"Expected '{backend_name}', got '{tp.active_backend}'"
            tp.reset(B, device)
            x = torch.randn(B, D, device=device)
            out = tp.step(x)
            assert isinstance(out, SequenceOutput)
            assert out.sdr.shape == (B, K)
            assert out.pred_sdr.shape == (B, K)
            assert out.anomaly_score.shape == (B,)
    _test("all explicit backends work through TemporalPredictor",
          test_temporal_predictor_all_explicit_backends)

    def test_temporal_predictor_invalid_backend():
        try:
            TemporalPredictor(backend="invalid")
            assert False, "Should raise ValueError"
        except ValueError:
            pass
    _test("invalid backend raises ValueError",
          test_temporal_predictor_invalid_backend)

    # ---- Group 19: forward() dispatches correctly ----
    print("\n--- 19. forward() dispatch ---")

    def test_forward_2d_dispatches_to_step():
        cfg = FallbackConfig(backend="lstm", input_size=D, hidden_size=H,
                             num_columns=N, num_active=K)
        model = LSTMPredictor(cfg).to(device)
        model.reset(B, device)
        x = torch.randn(B, D, device=device)
        out = model.forward(x)
        assert isinstance(out, SequenceOutput)
    _test("forward(B, D) dispatches to step",
          test_forward_2d_dispatches_to_step)

    def test_forward_3d_dispatches_to_predict():
        cfg = FallbackConfig(backend="gru", input_size=D, hidden_size=H,
                             num_columns=N, num_active=K)
        model = GRUPredictor(cfg).to(device)
        model.reset(B, device)
        T = 3
        x_seq = torch.randn(B, T, D, device=device)
        out = model.forward(x_seq)
        assert isinstance(out, SequenceOutput)
    _test("forward(B, T, D) dispatches to predict",
          test_forward_3d_dispatches_to_predict)

    # ---- Group 20: Auto-init without explicit reset ----
    print("\n--- 20. Auto-init without explicit reset ---")

    def test_auto_init_lstm():
        cfg = FallbackConfig(backend="lstm", input_size=D, hidden_size=H,
                             num_columns=N, num_active=K)
        model = LSTMPredictor(cfg).to(device)
        # Do NOT call reset -- step should auto-init
        x = torch.randn(B, D, device=device)
        out = model.step(x)
        assert isinstance(out, SequenceOutput)
        assert model._h is not None
    _test("LSTM auto-inits state on first step", test_auto_init_lstm)

    def test_auto_init_transformer():
        cfg = FallbackConfig(backend="transformer", input_size=D,
                             hidden_size=H, num_columns=N, num_active=K,
                             num_heads=4, max_seq_len=10)
        model = TransformerPredictor(cfg).to(device)
        x = torch.randn(B, D, device=device)
        out = model.step(x)
        assert isinstance(out, SequenceOutput)
        assert model._buffer is not None
    _test("Transformer auto-inits buffer on first step",
          test_auto_init_transformer)

    # ---- Group 21: Anomaly behaviour over time ----
    print("\n--- 21. Anomaly behaviour over time ---")

    def test_first_step_anomaly_is_max():
        cfg = FallbackConfig(backend="lstm", input_size=D, hidden_size=H,
                             num_columns=N, num_active=K)
        model = LSTMPredictor(cfg).to(device)
        model.reset(B, device)
        x = torch.randn(B, D, device=device)
        out = model.step(x)
        # First step has no prediction -> anomaly should be 1.0
        assert (out.anomaly_score == 1.0).all(), \
            f"First step anomaly should be 1.0, got {out.anomaly_score}"
    _test("first step anomaly is 1.0 (no prediction)",
          test_first_step_anomaly_is_max)

    # ---- Group 22: PositionalEncoding ----
    print("\n--- 22. PositionalEncoding ---")

    def test_positional_encoding_shape():
        pe = PositionalEncoding(d_model=H, max_len=50, dropout=0.0).to(device)
        x = torch.randn(B, 10, H, device=device)
        out = pe(x)
        assert out.shape == (B, 10, H)
    _test("PositionalEncoding preserves shape",
          test_positional_encoding_shape)

    def test_positional_encoding_gradient():
        pe = PositionalEncoding(d_model=H, max_len=50, dropout=0.0).to(device)
        x = torch.randn(B, 10, H, device=device, requires_grad=True)
        out = pe(x)
        out.sum().backward()
        assert x.grad is not None
    _test("PositionalEncoding gradient flow",
          test_positional_encoding_gradient)

    # ---- Summary ----
    print("\n" + "=" * 60)
    total = _pass + _fail
    print(f"Results: {_pass}/{total} passed, {_fail} failed")
    if _fail > 0:
        print("SOME TESTS FAILED")
        sys.exit(1)
    else:
        print("ALL TESTS PASSED")
        sys.exit(0)
