"""
test_torch_compile.py
---------------------
Auto-generated by gen_compile_tests.py
DO NOT EDIT MANUALLY — regenerate with: python scripts/gen_compile_tests.py

Tests for the torch.compile integration skill:
- CompileConfig validation
- BucketConfig validation
- maybe_compile safe wrapper
- ShapeStabilizer bucketing
- CompileSmoketest
- CompileBenchmark
- Edge cases and error handling
"""

from __future__ import annotations

import json
import logging
import os
import sys
import tempfile
import traceback
import unittest.mock as mock
from functools import partial
from pathlib import Path
from typing import Any, Dict, List, Optional

import pytest
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------

_TEST_FILE = Path(__file__).resolve()
_ASSETS_DIR = _TEST_FILE.parent.parent / "assets"
if str(_ASSETS_DIR) not in sys.path:
    sys.path.insert(0, str(_ASSETS_DIR))

from compile_config_template import (
    BucketConfig,
    CompileConfig,
    VALID_BACKENDS,
    VALID_MODES,
    default_config,
    fast_dev_config,
    inference_config,
    production_config,
)
from compile_wrap_template import maybe_compile
from shape_stabilize_template import ShapeStabilizer, collate_fn_with_bucketing
from compile_smoketest_template import CompileSmoketest
from compile_benchmark_template import BenchmarkResult, CompileBenchmark

# ---------------------------------------------------------------------------
# Fixtures and helpers
# ---------------------------------------------------------------------------

logger = logging.getLogger("test_compile")
logging.basicConfig(level=logging.WARNING)

BUCKETS = [256, 512, 1024, 2048]


class SimpleModel(nn.Module):
    """Basic model used across tests."""
    def __init__(self, in_dim: int = 32, out_dim: int = 16):
        super().__init__()
        self.fc1 = nn.Linear(in_dim, 64)
        self.fc2 = nn.Linear(64, out_dim)

    def forward(self, input_ids=None, x=None, **kwargs):
        inp = input_ids if input_ids is not None else x
        if inp is None:
            raise ValueError("Need 'input_ids' or 'x'")
        return self.fc2(F.relu(self.fc1(inp.float())))


class NaNModel(nn.Module):
    """Model that always produces NaN."""
    def __init__(self):
        super().__init__()
        self.p = nn.Parameter(torch.ones(1))

    def forward(self, input_ids=None, x=None, **kwargs):
        inp = input_ids if input_ids is not None else x
        if inp is None:
            inp = torch.zeros(2, 4)
        return (torch.tensor(float("nan")) * self.p).expand(inp.shape[0], 4)


class BackwardFailModel(nn.Module):
    """Model that raises during backward."""
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(16, 4)

    def forward(self, input_ids=None, x=None, **kwargs):
        inp = (input_ids if input_ids is not None else x).float()

        class _FailGrad(torch.autograd.Function):
            @staticmethod
            def forward(ctx, t):
                return t
            @staticmethod
            def backward(ctx, g):
                raise RuntimeError("Intentional backward failure in test")

        return _FailGrad.apply(self.fc(inp))


class ModelWithSubmodules(nn.Module):
    """Model with named submodules for allowlist/blocklist testing."""
    def __init__(self):
        super().__init__()
        self.encoder = nn.Linear(16, 8)
        self.attention = nn.Linear(8, 8)
        self.mlp = nn.Linear(8, 4)
        self.sampling = nn.Linear(4, 2)  # typically blocklisted

    def forward(self, x):
        h = F.relu(self.encoder(x.float()))
        h = F.relu(self.attention(h))
        h = F.relu(self.mlp(h))
        return self.sampling(h)


@pytest.fixture
def simple_model():
    return SimpleModel()


@pytest.fixture
def simple_batch():
    return {"input_ids": torch.randn(4, 32)}


@pytest.fixture
def stabilizer():
    return ShapeStabilizer(buckets=BUCKETS, pad_token_id=0)


@pytest.fixture
def test_logger():
    return logging.getLogger("pytest_compile")




# =============================================================================
# Section 1: CompileConfig Validation (15 tests)
# =============================================================================


class TestCompileConfigValidation:
    """Tests for CompileConfig field validation."""

    def test_default_config_valid(self):
        """Default CompileConfig constructs without error."""
        cfg = CompileConfig()
        assert cfg.enabled is False
        assert cfg.mode == "default"
        assert cfg.backend == "inductor"

    def test_default_config_factory(self):
        """default_config() factory returns valid disabled config."""
        cfg = default_config()
        assert cfg.enabled is False
        assert cfg.mode == "default"

    def test_fast_dev_config_factory(self):
        """fast_dev_config() returns enabled config."""
        cfg = fast_dev_config()
        assert cfg.enabled is True
        assert cfg.mode == "default"

    def test_production_config_factory(self):
        """production_config() returns max-autotune enabled config."""
        cfg = production_config()
        assert cfg.enabled is True
        assert cfg.mode == "max-autotune"

    def test_inference_config_factory(self):
        """inference_config() returns reduce-overhead with dynamic=False."""
        cfg = inference_config()
        assert cfg.enabled is True
        assert cfg.mode == "reduce-overhead"
        assert cfg.dynamic is False

    @pytest.mark.parametrize("mode", list(VALID_MODES))
    def test_all_valid_modes_accepted(self, mode):
        """All VALID_MODES are accepted by CompileConfig."""
        cfg = CompileConfig(mode=mode)
        assert cfg.mode == mode

    def test_invalid_mode_raises_value_error(self):
        """Invalid mode raises ValueError with 'mode' in message."""
        with pytest.raises(ValueError, match="mode"):
            CompileConfig(mode="turbo-mode")

    @pytest.mark.parametrize("backend", list(VALID_BACKENDS))
    def test_all_valid_backends_accepted(self, backend):
        """All VALID_BACKENDS are accepted by CompileConfig."""
        cfg = CompileConfig(backend=backend)
        assert cfg.backend == backend

    def test_invalid_backend_raises_value_error(self):
        """Invalid backend raises ValueError with 'backend' in message."""
        with pytest.raises(ValueError, match="backend"):
            CompileConfig(backend="magic_backend")

    def test_invalid_fail_policy_raises_value_error(self):
        """Invalid fail_policy raises ValueError."""
        with pytest.raises(ValueError, match="fail_policy"):
            CompileConfig(fail_policy="silently_ignore")

    def test_smoketest_steps_zero_raises(self):
        """smoketest_steps=0 raises ValueError."""
        with pytest.raises(ValueError, match="smoketest_steps"):
            CompileConfig(smoketest_steps=0)

    def test_smoketest_steps_negative_raises(self):
        """Negative smoketest_steps raises ValueError."""
        with pytest.raises(ValueError, match="smoketest_steps"):
            CompileConfig(smoketest_steps=-1)

    def test_to_dict_from_dict_roundtrip(self):
        """Serialization roundtrip preserves all fields."""
        cfg = CompileConfig(
            enabled=True,
            mode="reduce-overhead",
            dynamic=None,
            backend="inductor",
            fullgraph=True,
            options={"shape_padding": True},
            allowlist=["attention"],
            blocklist=["sampling"],
            healthcheck=False,
            fail_policy="raise",
            smoketest_steps=5,
        )
        restored = CompileConfig.from_dict(cfg.to_dict())
        assert cfg.to_dict() == restored.to_dict()

    def test_copy_with_does_not_mutate_original(self):
        """copy_with() returns new config without modifying original."""
        cfg = CompileConfig(enabled=False, mode="default")
        cfg2 = cfg.copy_with(enabled=True, mode="max-autotune")
        assert cfg.enabled is False
        assert cfg2.enabled is True
        assert cfg2.mode == "max-autotune"

    def test_dynamic_none_true_false_all_valid(self):
        """dynamic accepts None, True, and False."""
        for val in (None, True, False):
            cfg = CompileConfig(dynamic=val)
            assert cfg.dynamic is val


# =============================================================================
# Section 2: BucketConfig Validation (8 tests)
# =============================================================================


class TestBucketConfigValidation:
    """Tests for BucketConfig field validation."""

    def test_default_bucket_config_valid(self):
        """Default BucketConfig constructs without error."""
        bc = BucketConfig()
        assert bc.buckets == [256, 512, 1024, 2048]
        assert bc.pad_token_id == 0

    def test_custom_buckets_accepted(self):
        """Custom sorted bucket list is accepted."""
        bc = BucketConfig(buckets=[128, 256, 512])
        assert bc.buckets == [128, 256, 512]

    def test_unsorted_buckets_raises(self):
        """Unsorted buckets raise ValueError."""
        with pytest.raises(ValueError):
            BucketConfig(buckets=[1024, 256, 512])

    def test_empty_buckets_raises(self):
        """Empty bucket list raises ValueError."""
        with pytest.raises(ValueError):
            BucketConfig(buckets=[])

    def test_duplicate_buckets_raises(self):
        """Duplicate bucket values raise ValueError."""
        with pytest.raises(ValueError):
            BucketConfig(buckets=[256, 256, 512])

    def test_negative_pad_token_id_raises(self):
        """Negative pad_token_id raises ValueError."""
        with pytest.raises(ValueError):
            BucketConfig(pad_token_id=-1)

    def test_to_dict_from_dict_roundtrip(self):
        """BucketConfig serialization roundtrip."""
        bc = BucketConfig(buckets=[128, 256, 512], pad_token_id=1)
        bc2 = BucketConfig.from_dict(bc.to_dict())
        assert bc.to_dict() == bc2.to_dict()

    def test_single_bucket_valid(self):
        """Single-element bucket list is valid."""
        bc = BucketConfig(buckets=[512])
        assert bc.buckets == [512]



# =============================================================================
# Section 3: maybe_compile Safe Wrapper (18 tests)
# =============================================================================


class TestMaybeCompile:
    """Tests for maybe_compile safe wrapper."""

    def test_disabled_returns_same_model(self, simple_model, test_logger):
        """Disabled config returns exact same model object."""
        cfg = CompileConfig(enabled=False)
        result = maybe_compile(simple_model, cfg, test_logger)
        assert result is simple_model

    def test_disabled_no_log_of_compile(self, simple_model, test_logger, caplog):
        """Disabled config does not log compilation activity."""
        cfg = CompileConfig(enabled=False)
        with caplog.at_level(logging.INFO, logger="compile_wrap_test"):
            maybe_compile(simple_model, cfg, test_logger)
        # Should not see "starting compilation" in logs
        assert "starting compilation" not in caplog.text

    def test_broken_model_fallback_eager(self, simple_model, test_logger):
        """Compilation failure returns original model with fail_policy=fallback_eager."""
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=False,
                           fail_policy="fallback_eager")

        with mock.patch("torch.compile", side_effect=RuntimeError("mock compile fail")):
            result = maybe_compile(simple_model, cfg, test_logger)

        assert result is simple_model

    def test_broken_model_raise_policy_propagates(self, simple_model, test_logger):
        """Compilation failure re-raises with fail_policy=raise."""
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=False,
                           fail_policy="raise")

        with pytest.raises(RuntimeError):
            with mock.patch("torch.compile", side_effect=RuntimeError("mock fail")):
                maybe_compile(simple_model, cfg, test_logger)

    def test_enabled_compiles_simple_model(self, simple_model, test_logger):
        """Enabled config compiles and forward works."""
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=False)
        result = maybe_compile(simple_model, cfg, test_logger)
        out = result(x=torch.randn(4, 32))
        assert out.shape == (4, 16)

    def test_healthcheck_true_no_sample_batch_no_crash(self, simple_model, test_logger):
        """healthcheck=True with no sample_batch logs warning but does not crash."""
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=True,
                           fail_policy="fallback_eager")
        result = maybe_compile(simple_model, cfg, test_logger, sample_batch=None)
        assert result is not None

    def test_healthcheck_passes_with_good_model(self, simple_model, simple_batch, test_logger):
        """Healthcheck passes for a well-behaved model."""
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=True,
                           smoketest_steps=2, fail_policy="fallback_eager")
        result = maybe_compile(simple_model, cfg, test_logger, sample_batch=simple_batch)
        out = result(x=torch.randn(4, 32))
        assert out.shape == (4, 16)

    def test_healthcheck_fails_on_nan_model(self, test_logger):
        """Healthcheck returns eager model when NaN loss detected."""
        nan_model = NaNModel()
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=True,
                           smoketest_steps=2, fail_policy="fallback_eager")
        sample = {"input_ids": torch.randn(2, 4)}
        result = maybe_compile(nan_model, cfg, test_logger, sample_batch=sample)
        # Should fall back to original model
        assert result is nan_model

    def test_blocklist_does_not_crash(self, test_logger):
        """Blocklist disabling runs without crashing."""
        model = ModelWithSubmodules()
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=False,
                           blocklist=["sampling"])
        result = maybe_compile(model, cfg, test_logger)
        out = result(torch.randn(4, 16))
        assert out.shape == (4, 2)

    def test_allowlist_empty_compiles_whole_model(self, simple_model, test_logger):
        """Empty allowlist compiles the full model."""
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=False,
                           allowlist=[])
        result = maybe_compile(simple_model, cfg, test_logger)
        out = result(x=torch.randn(4, 32))
        assert out.shape == (4, 16)

    def test_allowlist_matching_modules_compiled(self, test_logger):
        """Allowlist selectively compiles matching submodules."""
        model = ModelWithSubmodules()
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=False,
                           allowlist=["attention", "mlp"])
        result = maybe_compile(model, cfg, test_logger)
        out = result(torch.randn(4, 16))
        assert out.shape == (4, 2)

    def test_fail_policy_fallback_no_raise(self, test_logger):
        """fallback_eager policy never raises even on repeated failures."""
        model = SimpleModel()
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=False,
                           fail_policy="fallback_eager")

        call_count = [0]
        def mock_compile(m, **kwargs):
            call_count[0] += 1
            raise RuntimeError("always fail")

        with mock.patch("torch.compile", side_effect=mock_compile):
            for _ in range(3):
                result = maybe_compile(model, cfg, test_logger)
                assert result is model

    def test_compile_with_options_dict(self, simple_model, test_logger):
        """Options dict is passed through to torch.compile."""
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=False,
                           options={"shape_padding": True, "epilogue_fusion": True})
        compile_kwargs = {}

        def mock_compile(m, **kwargs):
            compile_kwargs.update(kwargs)
            return m  # return unchanged for test

        with mock.patch("torch.compile", side_effect=mock_compile):
            maybe_compile(simple_model, cfg, test_logger)

        assert compile_kwargs.get("options") == {"shape_padding": True, "epilogue_fusion": True}

    def test_fullgraph_passed_to_compile(self, simple_model, test_logger):
        """fullgraph=True is passed to torch.compile."""
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=False, fullgraph=True)
        compile_kwargs = {}

        def mock_compile(m, **kwargs):
            compile_kwargs.update(kwargs)
            return m

        with mock.patch("torch.compile", side_effect=mock_compile):
            maybe_compile(simple_model, cfg, test_logger)

        assert compile_kwargs.get("fullgraph") is True

    def test_backend_passed_to_compile(self, simple_model, test_logger):
        """backend is passed to torch.compile."""
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=False,
                           backend="aot_eager")
        compile_kwargs = {}

        def mock_compile(m, **kwargs):
            compile_kwargs.update(kwargs)
            return m

        with mock.patch("torch.compile", side_effect=mock_compile):
            maybe_compile(simple_model, cfg, test_logger)

        assert compile_kwargs.get("backend") == "aot_eager"

    def test_dynamic_none_not_passed_as_kwarg(self, simple_model, test_logger):
        """dynamic=None is not passed to torch.compile (uses default)."""
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=False, dynamic=None)
        compile_kwargs = {}

        def mock_compile(m, **kwargs):
            compile_kwargs.update(kwargs)
            return m

        with mock.patch("torch.compile", side_effect=mock_compile):
            maybe_compile(simple_model, cfg, test_logger)

        assert "dynamic" not in compile_kwargs

    def test_dynamic_false_passed_to_compile(self, simple_model, test_logger):
        """dynamic=False is explicitly passed to torch.compile."""
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=False, dynamic=False)
        compile_kwargs = {}

        def mock_compile(m, **kwargs):
            compile_kwargs.update(kwargs)
            return m

        with mock.patch("torch.compile", side_effect=mock_compile):
            maybe_compile(simple_model, cfg, test_logger)

        assert compile_kwargs.get("dynamic") is False

    def test_smoketest_steps_respected(self, simple_model, simple_batch, test_logger):
        """smoketest_steps config value is used in healthcheck."""
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=True,
                           smoketest_steps=5, fail_policy="fallback_eager")
        # If healthcheck runs 5 steps on a good model, it should succeed
        result = maybe_compile(simple_model, cfg, test_logger, sample_batch=simple_batch)
        out = result(x=torch.randn(4, 32))
        assert out.shape == (4, 16)



# =============================================================================
# Section 4: ShapeStabilizer (28 tests)
# =============================================================================


class TestShapeStabilizer:
    """Tests for ShapeStabilizer bucketing."""

    # --- bucket_size ---

    @pytest.mark.parametrize("seq_len,expected", [
        (1, 256), (100, 256), (256, 256),
        (257, 512), (512, 512),
        (513, 1024), (1024, 1024),
        (1025, 2048), (2048, 2048),
    ])
    def test_bucket_size_correct(self, stabilizer, seq_len, expected):
        """bucket_size returns correct ceiling bucket."""
        assert stabilizer.bucket_size(seq_len) == expected

    def test_bucket_size_exceeds_max_raises(self, stabilizer):
        """seq_len > largest bucket raises ValueError."""
        with pytest.raises(ValueError):
            stabilizer.bucket_size(3000)

    def test_bucket_size_zero_raises(self, stabilizer):
        """seq_len=0 raises ValueError."""
        with pytest.raises(ValueError):
            stabilizer.bucket_size(0)

    def test_bucket_size_negative_raises(self, stabilizer):
        """Negative seq_len raises ValueError."""
        with pytest.raises(ValueError):
            stabilizer.bucket_size(-1)

    # --- bucket_batch ---

    @pytest.mark.parametrize("seq_len,expected_bucket", [
        (50, 256), (100, 256), (256, 256),
        (400, 512), (512, 512),
        (700, 1024), (1024, 1024),
        (1200, 2048), (2048, 2048),
    ])
    def test_bucket_batch_shape(self, stabilizer, seq_len, expected_bucket):
        """bucket_batch produces correct output shape."""
        ids = torch.randint(1, 900, (4, seq_len))
        padded = stabilizer.bucket_batch(ids)
        assert padded.shape == (4, expected_bucket), (
            f"seq_len={seq_len}: expected (4, {expected_bucket}), got {padded.shape}"
        )

    def test_bucket_batch_padding_values_correct(self, stabilizer):
        """Padded positions contain pad_token_id."""
        ids = torch.ones(2, 100, dtype=torch.long)
        padded = stabilizer.bucket_batch(ids)
        assert padded[:, 100:].eq(0).all(), "Padded positions should be 0"

    def test_bucket_batch_original_content_preserved(self, stabilizer):
        """Original token IDs are unchanged after padding."""
        ids = torch.randint(1, 500, (3, 200))
        padded = stabilizer.bucket_batch(ids)
        assert padded[:, :200].equal(ids)

    def test_bucket_batch_exact_boundary_no_padding(self, stabilizer):
        """Sequence at exact boundary returns same tensor (no extra padding)."""
        ids = torch.randint(1, 500, (4, 512))
        padded = stabilizer.bucket_batch(ids)
        assert padded.shape == (4, 512)
        assert padded.equal(ids)

    def test_bucket_batch_not_2d_raises(self, stabilizer):
        """Non-2D input raises ValueError."""
        with pytest.raises(ValueError):
            stabilizer.bucket_batch(torch.randn(4, 10, 32))

    def test_bucket_batch_empty_batch_raises(self, stabilizer):
        """Empty batch (batch_size=0) raises ValueError."""
        with pytest.raises((ValueError, IndexError)):
            stabilizer.bucket_batch(torch.zeros(0, 100, dtype=torch.long))

    def test_bucket_batch_custom_pad_token(self):
        """Custom pad_token_id is used for padding."""
        s = ShapeStabilizer(buckets=[256, 512], pad_token_id=99)
        ids = torch.ones(2, 100, dtype=torch.long)
        padded = s.bucket_batch(ids)
        assert padded[:, 100:].eq(99).all(), "Padding should use pad_token_id=99"

    # --- unpad_batch ---

    def test_unpad_recovers_original(self, stabilizer):
        """unpad_batch recovers original sequences."""
        seqs = [torch.randint(1, 500, (length,)) for length in [50, 120, 80]]
        padded = torch.full((3, 256), fill_value=0, dtype=torch.long)
        for i, seq in enumerate(seqs):
            padded[i, :len(seq)] = seq
        lengths = torch.tensor([50, 120, 80])

        recovered = stabilizer.unpad_batch(padded, lengths)
        for i, orig in enumerate(seqs):
            assert recovered[i].equal(orig), f"Sequence {i} not recovered"

    def test_unpad_returns_list_of_correct_lengths(self, stabilizer):
        """unpad_batch returns list with correct per-sequence lengths."""
        padded = torch.zeros(4, 512, dtype=torch.long)
        lengths = torch.tensor([100, 200, 50, 300])
        recovered = stabilizer.unpad_batch(padded, lengths)
        assert len(recovered) == 4
        for i, expected_len in enumerate([100, 200, 50, 300]):
            assert recovered[i].shape[0] == expected_len

    def test_unpad_batch_shape_mismatch_raises(self, stabilizer):
        """Batch size mismatch between padded and lengths raises ValueError."""
        with pytest.raises(ValueError):
            stabilizer.unpad_batch(
                torch.zeros(4, 256), torch.tensor([100, 200, 50])  # 3 lengths for 4 seqs
            )

    # --- make_attention_mask ---

    def test_make_attention_mask_correct(self, stabilizer):
        """Attention mask is 1 for real tokens, 0 for padding."""
        ids = torch.tensor([[1, 2, 3, 0, 0], [4, 5, 0, 0, 0]])
        mask = stabilizer.make_attention_mask(ids)
        expected = torch.tensor([[1, 1, 1, 0, 0], [1, 1, 0, 0, 0]])
        assert mask.equal(expected)

    # --- mark_dynamic_dims ---

    def test_mark_dynamic_dims_no_crash(self, stabilizer):
        """mark_dynamic_dims runs without crashing."""
        batch = {
            "input_ids": torch.randint(0, 100, (4, 256)),
            "attention_mask": torch.ones(4, 256, dtype=torch.long),
        }
        stabilizer.mark_dynamic_dims(batch, dim=1)  # Should not raise

    def test_mark_dynamic_dims_skips_non_tensor(self, stabilizer):
        """mark_dynamic_dims ignores non-Tensor values."""
        batch = {
            "input_ids": torch.randint(0, 100, (4, 256)),
            "some_string": "hello",
            "some_int": 42,
        }
        stabilizer.mark_dynamic_dims(batch, dim=1)  # Should not raise

    # --- collate_fn_with_bucketing ---

    def test_collate_fn_shape(self):
        """collate_fn_with_bucketing pads batch to correct bucket."""
        batch_data = [
            {"input_ids": list(range(100))},
            {"input_ids": list(range(200))},
            {"input_ids": list(range(50))},
        ]
        result = collate_fn_with_bucketing(batch_data, buckets=BUCKETS)
        assert result["input_ids"].shape == (3, 256)

    def test_collate_fn_has_attention_mask(self):
        """collate_fn_with_bucketing generates attention_mask."""
        batch_data = [{"input_ids": list(range(100))} for _ in range(3)]
        result = collate_fn_with_bucketing(batch_data, buckets=BUCKETS)
        assert "attention_mask" in result
        assert result["attention_mask"].shape == (3, 256)

    def test_collate_fn_has_original_lengths(self):
        """collate_fn_with_bucketing records original_lengths."""
        batch_data = [
            {"input_ids": list(range(100))},
            {"input_ids": list(range(200))},
        ]
        result = collate_fn_with_bucketing(batch_data, buckets=BUCKETS)
        assert "original_lengths" in result
        assert result["original_lengths"].tolist() == [100, 200]

    def test_collate_fn_pad_token_correct(self):
        """collate_fn_with_bucketing uses specified pad_token_id."""
        batch_data = [{"input_ids": [5, 6, 7]}]  # 3 tokens → bucket 256
        result = collate_fn_with_bucketing(batch_data, buckets=BUCKETS, pad_token_id=99)
        assert result["input_ids"][0, 3:].eq(99).all()

    def test_collate_fn_large_bucket(self):
        """collate_fn_with_bucketing uses correct bucket for longer sequences."""
        batch_data = [
            {"input_ids": list(range(600))},  # needs 1024 bucket
            {"input_ids": list(range(300))},
        ]
        result = collate_fn_with_bucketing(batch_data, buckets=BUCKETS)
        assert result["input_ids"].shape[1] == 1024

    # --- ShapeStabilizer construction ---

    def test_unsorted_buckets_raises(self):
        """Unsorted buckets raise ValueError."""
        with pytest.raises(ValueError):
            ShapeStabilizer(buckets=[1024, 256, 512])

    def test_empty_buckets_raises(self):
        """Empty bucket list raises ValueError."""
        with pytest.raises(ValueError):
            ShapeStabilizer(buckets=[])

    def test_negative_pad_token_raises(self):
        """Negative pad_token_id raises ValueError."""
        with pytest.raises(ValueError):
            ShapeStabilizer(pad_token_id=-1)



# =============================================================================
# Section 5: CompileSmoketest (12 tests)
# =============================================================================


class TestCompileSmoketest:
    """Tests for CompileSmoketest."""

    def test_steps_zero_raises(self):
        """steps=0 raises ValueError."""
        with pytest.raises(ValueError, match="steps"):
            CompileSmoketest(steps=0)

    def test_steps_negative_raises(self):
        """Negative steps raises ValueError."""
        with pytest.raises(ValueError):
            CompileSmoketest(steps=-1)

    def test_steps_one_valid(self):
        """steps=1 is valid."""
        st = CompileSmoketest(steps=1)
        assert st.steps == 1

    def test_good_model_returns_true(self):
        """Good model returns True."""
        model = SimpleModel()
        opt = optim.SGD(model.parameters(), lr=1e-3)
        batch = {"input_ids": torch.randn(2, 32)}
        loss_fn = lambda out, _: out.mean()

        st = CompileSmoketest(steps=3, seed=42)
        result = st.run(model, batch, opt, loss_fn)
        assert result is True

    def test_nan_loss_returns_false(self):
        """NaN loss model returns False."""
        model = NaNModel()
        opt = optim.SGD(model.parameters(), lr=1e-3)
        batch = {"input_ids": torch.randn(2, 4)}
        loss_fn = lambda out, _: out.mean()

        st = CompileSmoketest(steps=3, seed=42)
        result = st.run(model, batch, opt, loss_fn)
        assert result is False

    def test_backward_failure_returns_false(self):
        """Backward failure returns False."""
        model = BackwardFailModel()
        opt = optim.SGD(model.parameters(), lr=1e-3)
        batch = {"input_ids": torch.randn(2, 16)}
        loss_fn = lambda out, _: out.mean()

        st = CompileSmoketest(steps=2, seed=42)
        result = st.run(model, batch, opt, loss_fn)
        assert result is False

    def test_step_times_recorded_after_run(self):
        """Step times are recorded after run()."""
        model = SimpleModel()
        opt = optim.SGD(model.parameters(), lr=1e-3)
        batch = {"input_ids": torch.randn(2, 32)}
        loss_fn = lambda out, _: out.mean()

        st = CompileSmoketest(steps=3)
        st.run(model, batch, opt, loss_fn)
        assert len(st.step_times) == 3
        assert all(t > 0 for t in st.step_times)

    def test_step_times_empty_before_run(self):
        """step_times is empty before run()."""
        st = CompileSmoketest(steps=3)
        assert st.step_times == []

    def test_create_sample_batch_shapes(self):
        """_create_sample_batch returns correct shapes."""
        model = SimpleModel()
        st = CompileSmoketest(seed=0)
        batch = st._create_sample_batch(model, batch_size=4, seq_len=32)
        assert batch["input_ids"].shape == (4, 32)
        assert batch["attention_mask"].shape == (4, 32)
        assert batch["labels"].shape == (4, 32)

    def test_run_with_synthetic_batch(self):
        """run_with_synthetic_batch convenience method passes for good model."""
        # Use a model whose embedding dim matches the synthetic batch seq_len
        model = SimpleModel(in_dim=128, out_dim=16)  # default seq_len=128
        opt = optim.SGD(model.parameters(), lr=1e-3)
        st = CompileSmoketest(steps=2, seed=1)
        result = st.run_with_synthetic_batch(model, opt, seq_len=128)
        assert result is True

    def test_inf_loss_returns_false(self):
        """Inf loss model returns False."""
        class InfModel(nn.Module):
            def __init__(self):
                super().__init__()
                self.p = nn.Parameter(torch.ones(1))
            def forward(self, input_ids=None, **kwargs):
                inp = input_ids if input_ids is not None else torch.zeros(2, 4)
                return (torch.tensor(float("inf")) * self.p).expand(inp.shape[0], 4)

        model = InfModel()
        opt = optim.SGD(model.parameters(), lr=1e-3)
        batch = {"input_ids": torch.randn(2, 4)}
        st = CompileSmoketest(steps=2, seed=42)
        result = st.run(model, batch, opt, lambda out, _: out.mean())
        assert result is False

    def test_multiple_runs_independent(self):
        """Multiple run() calls produce independent step_times."""
        model = SimpleModel()
        opt = optim.SGD(model.parameters(), lr=1e-3)
        batch = {"input_ids": torch.randn(2, 32)}
        loss_fn = lambda out, _: out.mean()

        st = CompileSmoketest(steps=2)
        st.run(model, batch, opt, loss_fn)
        first_times = list(st.step_times)

        opt2 = optim.SGD(model.parameters(), lr=1e-3)
        st.run(model, batch, opt2, loss_fn)
        second_times = list(st.step_times)

        assert len(second_times) == 2
        assert second_times != first_times or True  # just verify it re-ran



# =============================================================================
# Section 6: CompileBenchmark (14 tests)
# =============================================================================


class TestCompileBenchmark:
    """Tests for CompileBenchmark."""

    @pytest.fixture
    def bench(self):
        return CompileBenchmark()

    @pytest.fixture
    def model_fn(self):
        def make_model():
            return nn.Sequential(
                nn.Linear(32, 64), nn.ReLU(), nn.Linear(64, 32)
            )
        return make_model

    @pytest.fixture
    def batch_fn(self):
        def make_batch(device):
            return {"x": torch.randn(4, 32, device=device)}
        return make_batch

    def test_eager_mode_completes(self, bench, model_fn, batch_fn):
        """Eager mode benchmark completes and returns result."""
        results = bench.run_comparison(model_fn, batch_fn, steps=5, warmup=2,
                                       modes=["eager"])
        assert "eager" in results
        assert not results["eager"].failed

    def test_eager_result_required_keys(self, bench, model_fn, batch_fn):
        """Eager result contains all required keys."""
        results = bench.run_comparison(model_fn, batch_fn, steps=5, warmup=2,
                                       modes=["eager"])
        d = results["eager"].to_dict()
        required = ["mode", "compile_time_s", "step_times_s", "peak_memory_bytes",
                    "steady_state_tokens_per_sec_p50", "step_time_p50_s",
                    "step_time_p95_s", "error", "failed"]
        for key in required:
            assert key in d, f"Missing key: {key}"

    def test_eager_speedup_is_one(self, bench, model_fn, batch_fn):
        """Eager mode speedup vs itself is 1.0."""
        results = bench.run_comparison(model_fn, batch_fn, steps=5, warmup=2,
                                       modes=["eager"])
        r = results["eager"]
        assert r.speedup_vs(r) == 1.0

    def test_comparison_has_all_modes(self, bench, model_fn, batch_fn):
        """run_comparison returns all requested modes."""
        results = bench.run_comparison(model_fn, batch_fn, steps=5, warmup=2,
                                       modes=["eager", "default"])
        assert "eager" in results
        assert "default" in results

    def test_compile_mode_has_expected_keys(self, bench, model_fn, batch_fn):
        """Compiled mode result has all required keys."""
        results = bench.run_comparison(model_fn, batch_fn, steps=5, warmup=2,
                                       modes=["eager", "default"])
        if not results["default"].failed:
            d = results["default"].to_dict()
            assert "compile_time_s" in d
            assert "peak_memory_bytes" in d

    def test_speedup_in_reasonable_range(self, bench, model_fn, batch_fn):
        """Compiled mode speedup is between 0.1x and 20x."""
        results = bench.run_comparison(model_fn, batch_fn, steps=10, warmup=5,
                                       modes=["eager", "default"])
        if not results["default"].failed and not results["eager"].failed:
            su = results["default"].speedup_vs(results["eager"])
            assert 0.1 <= su <= 20.0, f"Speedup {su:.2f}x outside expected range"

    def test_format_report_nonempty(self, bench, model_fn, batch_fn):
        """format_report returns non-empty multi-line string."""
        results = bench.run_comparison(model_fn, batch_fn, steps=5, warmup=2,
                                       modes=["eager"])
        report = bench.format_report(results)
        assert isinstance(report, str)
        assert len(report) > 50
        assert "eager" in report

    def test_format_report_contains_all_modes(self, bench, model_fn, batch_fn):
        """format_report includes all benchmarked modes."""
        results = bench.run_comparison(model_fn, batch_fn, steps=5, warmup=2,
                                       modes=["eager", "default"])
        report = bench.format_report(results)
        assert "eager" in report
        # "default" should be in report even if compile failed on this machine

    def test_save_report_valid_json(self, bench, model_fn, batch_fn):
        """save_report writes valid JSON loadable by json.load."""
        results = bench.run_comparison(model_fn, batch_fn, steps=5, warmup=2,
                                       modes=["eager"])
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as f:
            tmp_path = f.name
        try:
            bench.save_report(results, tmp_path)
            with open(tmp_path) as f:
                loaded = json.load(f)
            assert "eager" in loaded
            assert "compile_time_s" in loaded["eager"]
        finally:
            os.unlink(tmp_path)

    def test_save_report_has_speedup_key(self, bench, model_fn, batch_fn):
        """save_report includes speedup_vs_eager for non-eager modes."""
        results = bench.run_comparison(model_fn, batch_fn, steps=5, warmup=2,
                                       modes=["eager", "default"])
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as f:
            tmp_path = f.name
        try:
            bench.save_report(results, tmp_path)
            with open(tmp_path) as f:
                loaded = json.load(f)
            assert "speedup_vs_eager" in loaded.get("eager", {})
        finally:
            os.unlink(tmp_path)

    def test_benchmark_result_steady_state_times(self):
        """BenchmarkResult.steady_state_times excludes first step."""
        r = BenchmarkResult("test", 1.5, [1.0, 0.01, 0.01, 0.01], 0, tokens_per_step=512)
        assert len(r.steady_state_times) == 3

    def test_benchmark_result_tokens_per_sec(self):
        """BenchmarkResult.steady_state_tokens_per_sec_p50 is positive."""
        r = BenchmarkResult("test", 0.5, [0.1, 0.05, 0.05, 0.05], 0, tokens_per_step=1024)
        assert r.steady_state_tokens_per_sec_p50 > 0

    def test_benchmark_result_failed_flag(self):
        """BenchmarkResult.failed is True when error is set."""
        r = BenchmarkResult("test", 0.0, [], 0, error="something went wrong")
        assert r.failed is True

    def test_benchmark_result_not_failed_flag(self):
        """BenchmarkResult.failed is False when no error."""
        r = BenchmarkResult("test", 0.5, [0.01], 0)
        assert r.failed is False



# =============================================================================
# Section 7: Edge Cases (12 tests)
# =============================================================================


class TestEdgeCases:
    """Edge cases and boundary conditions."""

    def test_single_token_sequence_buckets_to_smallest(self, stabilizer):
        """Single-token sequence is bucketed to smallest bucket."""
        ids = torch.randint(1, 100, (2, 1))
        padded = stabilizer.bucket_batch(ids)
        assert padded.shape == (2, 256)

    def test_max_bucket_boundary_exact(self, stabilizer):
        """Sequence at max bucket boundary doesn't change shape."""
        ids = torch.randint(1, 100, (2, 2048))
        padded = stabilizer.bucket_batch(ids)
        assert padded.shape == (2, 2048)
        assert padded.equal(ids)

    def test_sequence_exceeds_all_buckets_raises(self, stabilizer):
        """Sequence longer than all buckets raises ValueError."""
        ids = torch.randint(1, 100, (2, 3000))
        with pytest.raises(ValueError):
            stabilizer.bucket_batch(ids)

    def test_compile_config_with_none_options(self):
        """CompileConfig with options=None is valid."""
        cfg = CompileConfig(options=None)
        assert cfg.options is None

    def test_compile_config_with_empty_lists(self):
        """CompileConfig with empty allowlist and blocklist is valid."""
        cfg = CompileConfig(allowlist=[], blocklist=[])
        assert cfg.allowlist == []
        assert cfg.blocklist == []

    def test_compile_config_from_dict_ignores_unknown_keys(self):
        """from_dict ignores unknown keys without raising."""
        d = {"enabled": True, "mode": "default", "unknown_future_field": "value"}
        cfg = CompileConfig.from_dict(d)
        assert cfg.enabled is True

    def test_bucket_batch_single_sequence_batch(self, stabilizer):
        """Batch size 1 works correctly."""
        ids = torch.randint(1, 100, (1, 300))
        padded = stabilizer.bucket_batch(ids)
        assert padded.shape == (1, 512)

    def test_smoketest_with_single_step(self):
        """CompileSmoketest with steps=1 works."""
        model = SimpleModel()
        opt = optim.SGD(model.parameters(), lr=1e-3)
        batch = {"input_ids": torch.randn(2, 32)}
        st = CompileSmoketest(steps=1)
        result = st.run(model, batch, opt, lambda out, _: out.mean())
        assert result is True

    def test_bucket_config_single_bucket(self):
        """BucketConfig with a single bucket works."""
        bc = BucketConfig(buckets=[512])
        s = ShapeStabilizer(buckets=[512])
        ids = torch.randint(1, 100, (2, 100))
        padded = s.bucket_batch(ids)
        assert padded.shape == (2, 512)

    def test_maybe_compile_disabled_multiple_calls_consistent(self, test_logger):
        """Calling maybe_compile multiple times with disabled config is idempotent."""
        model = SimpleModel()
        cfg = CompileConfig(enabled=False)
        for _ in range(5):
            result = maybe_compile(model, cfg, test_logger)
            assert result is model

    def test_unpad_batch_single_sequence(self, stabilizer):
        """unpad_batch works with batch_size=1."""
        padded = torch.zeros(1, 256, dtype=torch.long)
        padded[0, :50] = torch.arange(1, 51)
        lengths = torch.tensor([50])
        recovered = stabilizer.unpad_batch(padded, lengths)
        assert len(recovered) == 1
        assert recovered[0].shape == (50,)

    def test_collate_fn_with_labels(self):
        """collate_fn_with_bucketing handles label field correctly."""
        batch_data = [
            {"input_ids": list(range(100)), "labels": list(range(100, 200))},
            {"input_ids": list(range(200)), "labels": list(range(200, 400))},
        ]
        result = collate_fn_with_bucketing(batch_data, buckets=BUCKETS)
        assert "labels" in result
        assert result["labels"].shape[1] == 256  # padded to bucket



# =============================================================================
# Section 8: Mode Switching and Config (8 tests)
# =============================================================================


class TestModeSwitching:
    """Tests for mode switching behavior."""

    def test_default_mode_produces_correct_output(self):
        """default mode forward output has correct shape."""
        model = SimpleModel()
        cfg = CompileConfig(enabled=True, mode="default", healthcheck=False)
        compiled = maybe_compile(model, cfg, logger)
        out = compiled(x=torch.randn(4, 32))
        assert out.shape == (4, 16)

    def test_aot_eager_backend_runs(self):
        """aot_eager backend completes without error."""
        model = SimpleModel()
        cfg = CompileConfig(enabled=True, mode="default", backend="aot_eager",
                           healthcheck=False)
        try:
            compiled = maybe_compile(model, cfg, logger)
            out = compiled(x=torch.randn(4, 32))
            assert out.shape == (4, 16)
        except Exception:
            # aot_eager might not be available in all PyTorch versions
            pytest.skip("aot_eager backend not available")

    @pytest.mark.parametrize("mode", ["default", "reduce-overhead"])
    def test_compiled_output_close_to_eager(self, mode):
        """Compiled output is numerically close to eager for basic modes."""
        torch.manual_seed(42)
        model_eager = SimpleModel()
        x = torch.randn(4, 32)

        eager_out = model_eager(x=x).detach()

        torch.manual_seed(42)
        model_compiled = SimpleModel()
        # Copy weights to ensure same initialization
        model_compiled.load_state_dict(model_eager.state_dict())

        cfg = CompileConfig(enabled=True, mode=mode, healthcheck=False)
        compiled = maybe_compile(model_compiled, cfg, logger)
        compiled_out = compiled(x=x).detach()

        assert torch.allclose(eager_out, compiled_out, atol=1e-3, rtol=1e-3), (
            f"Max diff: {(eager_out - compiled_out).abs().max()}"
        )

    def test_config_to_dict_json_serializable(self):
        """CompileConfig.to_dict() produces JSON-serializable output."""
        cfg = CompileConfig(enabled=True, mode="default",
                           options={"shape_padding": True})
        d = cfg.to_dict()
        # Should not raise
        json_str = json.dumps(d)
        assert len(json_str) > 0

    def test_mode_default_is_valid_compile_mode_string(self):
        """mode="default" is a valid torch.compile mode string."""
        assert "default" in VALID_MODES

    def test_all_compile_modes_in_valid_modes_set(self):
        """VALID_MODES contains all expected modes."""
        expected = {"default", "reduce-overhead", "max-autotune",
                   "max-autotune-no-cudagraphs"}
        assert expected == VALID_MODES

    def test_all_compile_backends_in_valid_backends_set(self):
        """VALID_BACKENDS contains all expected backends."""
        expected = {"inductor", "aot_eager", "cudagraphs"}
        assert expected == VALID_BACKENDS

    def test_compile_config_repr_contains_mode(self):
        """CompileConfig repr includes mode."""
        cfg = CompileConfig(mode="reduce-overhead")
        r = repr(cfg)
        assert "reduce-overhead" in r



# =============================================================================
# Section 9: Integration (4 tests)
# =============================================================================


class TestIntegration:
    """End-to-end integration tests."""

    def test_full_compile_and_smoketest_pipeline(self):
        """Full pipeline: compile → smoketest → inference works."""
        model = SimpleModel()
        opt = optim.AdamW(model.parameters(), lr=1e-4)
        batch = {"input_ids": torch.randn(2, 32)}

        cfg = CompileConfig(enabled=True, mode="default", healthcheck=True,
                           smoketest_steps=2, fail_policy="fallback_eager")
        compiled = maybe_compile(model, cfg, logger, sample_batch=batch)

        # Whether compiled or fallback, forward should work
        out = compiled(x=torch.randn(4, 32))
        assert out.shape == (4, 16)

    def test_stabilizer_with_model_forward(self):
        """ShapeStabilizer + model forward across all bucket sizes."""
        stabilizer = ShapeStabilizer(buckets=BUCKETS, pad_token_id=0)
        model = nn.Embedding(1000, 32)

        for seq_len in [100, 256, 300, 512, 600, 1024]:
            ids = torch.randint(1, 900, (2, seq_len))
            padded = stabilizer.bucket_batch(ids)
            out = model(padded)
            expected_bucket = stabilizer.bucket_size(seq_len)
            assert out.shape == (2, expected_bucket, 32)

    def test_benchmark_then_report_pipeline(self):
        """run_comparison → format_report → save_report full pipeline."""
        def model_fn():
            return nn.Sequential(nn.Linear(16, 32), nn.ReLU(), nn.Linear(32, 16))

        def batch_fn(device):
            return {"x": torch.randn(4, 16, device=device)}

        bench = CompileBenchmark()
        results = bench.run_comparison(model_fn, batch_fn, steps=5, warmup=2,
                                       modes=["eager"])
        report = bench.format_report(results)

        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as f:
            tmp_path = f.name
        try:
            bench.save_report(results, tmp_path)
            with open(tmp_path) as f:
                loaded = json.load(f)
            assert "eager" in loaded
        finally:
            os.unlink(tmp_path)

        assert isinstance(report, str) and len(report) > 20

    def test_config_validation_guards_training_setup(self):
        """Invalid configs are caught before reaching training setup."""
        invalid_configs = [
            {"mode": "super-fast"},
            {"backend": "custom_magic"},
            {"fail_policy": "ignore_silently"},
            {"smoketest_steps": -5},
        ]
        for bad_kwargs in invalid_configs:
            with pytest.raises(ValueError):
                CompileConfig(**bad_kwargs)
